### ISSUE TITLE
Do liftunder in pipeline, not at runtime

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr#1010]
For hg38 variants, we should do liftunder to hg19 in hail while running the pipeline, not in seqr with PyLiftover

**Comment by mike-w-wilson** [comment]
Added to loading pipeline. https://github.com/macarthur-lab/hail-elasticsearch-pipelines/pull/204

**Comment by hanars** [comment]
seqr will now use the pipeline's liftunder where present. Once all the indices have been reloaded we can deprecate the code to do liftunder in python, so leaving this open to track that work
