### ISSUE TITLE
Variant page - allow sorting by date of tag/note

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#1092]
**Is your feature request related to a problem? Please describe.**
We have a collaborator who goes through cases and adds review tags but doesn't keep track of what families he recently analyzed - so we were trying to identify the newer tags he'd added by date. On the old page, we could do a find on the page for his name but the new page doesn't let us do that. 

**Describe the solution you'd like**
One thing that would help is to be able to sort the tagged variants by how recently they were tagged (though I don't know how you handle various tags on a variant)
![image](https://user-images.githubusercontent.com/10407888/69737245-0e8dc400-1102-11ea-9f46-6c03677d0c1f.png)

**Describe alternatives you've considered**
Continuing to print the persons name on the page to allow find on the page. 
Or adding some type of view of see variants tagged by me (though still would be a lot of variants to look through).

**Comment by hanars** [comment]
This makes sense to me, if there are multiple tags on a variant we will probably just take the most recently tagged unless you have a better suggestion

**Comment by hanars** [comment]
There is now a "Last Tagged" sort that puts the most recently tagged variants at the top
