### ISSUE TITLE
In silico tool ranges

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#1140]
**Is your feature request related to a problem? Please describe.**
We sometimes get asked what scores correlate with a yellow or red notation in seqr for CADD or Primate AI for example. I'm actually not sure if this info is available in seqr but it would be handy if it could be. Figured I'd try filling this out and if it's already there, my mistake. 

**Describe the solution you'd like**
I think it would be too noisy to have as hover over info. I'd put it in some kind of FAQ menu somewhere.

**Comment by hanars** [comment]
added the range if you hover over the name of the score
