### ISSUE TITLE
Link to all saved variants on the search variants page

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1147]
Would it be possible to have a quick link on the search page, to go to all the saved variants? Currently, after performing our searches and saving them bu using tags, we click on the family ID and go to the main page. From there we then click on the colored bar on the right, to see all variants we recently tagged. It would be super handy to have a 1-step option to go directly to the saved variants page. 

Perhaps by adding a 'saved variants' link next to the Sort By feature on the top and also at the bottom by the 'Scroll to top'. 
<img width="1358" alt="Screen Shot 2020-01-23 at 3 01 24 PM" src="https://user-images.githubusercontent.com/37872186/73019347-6cccdf80-3df1-11ea-8e89-1784a25bfea4.png">

**Comment by hanars** [comment]
Would it be easier just to have the link to the family page go to the saved variant page instead?

**Comment by hanars** [comment]
I have changed the family name on the search page to link directly to the saved variants page
