### ISSUE TITLE
move gunicorn and postgres log output to peristent disks 

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#1190]
On the border between bug/feature .. but since we're not using stackdriver, we should move log files to persistent disks - at least for postgres and seqr.
Existing persistent disks (/seqr_static_files and postgres data) don't really make sense for this (and it would be very bad if logs used up all disk space), so I vote for adding dedicated persistent disks for logs.

**Comment by hanars** [comment]
logs actually do go to stackdriver:
seqr - https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22seqr-project%22%0Aresource.labels.location%3D%22us-central1-b%22%0Aresource.labels.cluster_name%3D%22seqr-cluster-prod%22%0Aresource.labels.namespace_name%3D%22default%22%0Aresource.labels.container_name%3D%22seqr-pod%22;timeRange=P7D?project=seqr-project

postgres - https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22seqr-project%22%0Aresource.labels.location%3D%22us-central1-b%22%0Aresource.labels.cluster_name%3D%22seqr-cluster-prod%22%0Aresource.labels.namespace_name%3D%22default%22%0Aresource.labels.container_name%3D%22postgres-pod%22;timeRange=P7D?project=seqr-project
