### ISSUE TITLE
Missing ClinVar info

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1416]
**Describe the bug**
This variant has been been reported in ClinVar, but there's no indication of it in seqr. 

**Link to page(s) where bug is occurring**
ClinVar page - https://www.ncbi.nlm.nih.gov/clinvar/RCV000971223/
The variant in seqr- https://seqr.broadinstitute.org/project/R0405_cmg_vcgs_genomes/saved_variants/variant/SV0077214_8142344461_f029968_v

**Scope of the bug**
Family/ variant specific.

**Screenshots**
<img width="1190" alt="Screen Shot 2020-08-06 at 3 20 22 PM" src="https://user-images.githubusercontent.com/37872186/89573283-61bf2700-d7f8-11ea-910a-99c62679decf.png">

**Comment by hanars** [comment]
@mike-w-wilson do you know the last time we updated our clinvar reference? The data for this was loaded in March 2020 but it looks like that clinvar annotation is from June 2018

**Comment by mike-w-wilson** [comment]
We updated on April 6th, 2020 and before that it looks like possibly May 2019. I know Ben has recently made some updates but  determining an appropriate update schedule would be useful. I think it would be best to update the loading pipeline to run the clinvar update if the file is X weeks/months old.

**Comment by mike-w-wilson** [comment]
The annotation is not in our current file either. I'm guessing the locus is not entered in a hail-friendly way and we use hail's import_vcf's `skip_invalid_loci` to prevent downstream errors. https://github.com/macarthur-lab/hail-elasticsearch-pipelines/blob/9996cbb643b1749c83ec850bd845004b1583b0ec/hail_scripts/v02/utils/clinvar.py#L42 . We do not filter clinvar at all besides this built in filter.

**Comment by hanars** [comment]
Yeah, I also know Larry's team on the Clinvar side is working on having some sort of subscribable updates, and I've offered us up as guniea pigs for those to see if we can do some sort of automated updating, but idk what heir timeline is for that

**Comment by hanars** [comment]
https://github.com/broadinstitute/hail-elasticsearch-pipelines/issues/238 for tracking future work to more regularly updating clinvar. Leaving this issue open to track reloading this specific project

**Comment by hanars** [comment]
clinvar has been updated for this project and this variant is now displaying correctly
