### ISSUE TITLE
Bug while adding Project on Variant Search

### ISSUE THREAD

**Issue by NLSVTN** [broadinstitute/seqr#1450]
Hi, 

Could you check whether your program crashes when you follow the steps:

1. Reload the initial dashboard with projects
2. Select a project and go to variant search page directly
3. Add another project to variant search

Basically we faced the need to introduce additional check here:

https://github.com/macarthur-lab/seqr/blob/master/ui/pages/Search/selectors.js#L137

Because when we navigate from the dashboard to variant search the projects in 'projectsByGuids' variable are not deleted and so the added project will be present in 'projectsByGuids' without the 'locusListGuids' key causing the program to crash. We needed to introduce additional check - 'locusListGuids' in projectsByGuid[projectGuid]:

```
    const projectGuidsSet = new Set((projectGuids || []).reduce((acc, projectGuid) => (
      (projectsByGuid[projectGuid] && ('locusListGuids' in projectsByGuid[projectGuid])) ?
        [...acc, ...projectsByGuid[projectGuid].locusListGuids] : acc), [], 
    )) 
```

If it does not happen for you, then just close the ticket but would be interesting to know.

**Comment by hanars** [comment]
We have that big too, so I will keep this open. If you reload the search page and then add the projects it does work, so at least there is a workaround

**Comment by hanars** [comment]
we no longer get this bug as seqr checks if the project is fully loaded before deciding whether it needs to fetch:
https://github.com/broadinstitute/seqr/blame/master/ui/pages/Search/reducers.js#L32
