### ISSUE TITLE
pubmed and google search return no match results

### ISSUE THREAD

**Issue by WendyZhang05** [broadinstitute/seqr#1451]
**Describe the bug**
In variant search results, there are links under each variant for google and pubmed search. However, google search does not have any matching results if there are multiple gene names. All pubmed search returns no matching results. I think the query terms pass to google and pubmed need to be updated. 

**Link to page(s) where bug is occurring**
https://github.com/macarthur-lab/seqr/blob/master/ui/shared/components/panel/variants/Annotations.jsx#L146
https://github.com/macarthur-lab/seqr/blob/master/ui/shared/components/panel/variants/Annotations.jsx#L154

**Comment by hanars** [comment]
We have tweaked the google and pubmed links so they should return better results. If you are still experiencing this issue, please feel free to re-open this ticket. If you do, please include 
1) Details of the variant(s) where the links are not returning search results 
2) Examples of the google and/or pubmed results that you would expect to be returned but aren't
