### ISSUE TITLE
Monarch connection lost

### ISSUE THREAD

**Issue by Jenniferneil** [broadinstitute/seqr#1465]
Hello,
I seem to be getting a 503 Service Unavailable message when clicking on the monarch link on gene pages, in all cases.  The Monarch site seems to be working independently. 

![image](https://user-images.githubusercontent.com/72513151/95352955-b9c5e880-0890-11eb-855e-cfda1f6d9bbb.png)

Thanks 
Jen

**Comment by bnouyou** [comment]
Hello,
Is it because of the 'beta' on the URL ?
If you take it off, it's working.

**Comment by Jenniferneil** [comment]
Good morning,

Yes, taking the beta off does work, however this was not needed before - the link from within a seqr gene page always went directly to the gene page in Monarch:


[cid:c94ec836-7d21-4bb5-b72a-3859068b399a]



Please note my new email: jennifer.neil@childrens.harvard.edu
(previously jennifer.partlow_at_childrens.harvard.edu)
________________________________________________
Jennifer E. Neil, MS, CGC
Licensed Genetic Counselor and Research Coordinator
The Walsh Lab, Boston Children's Hospital and HHMI
jennifer.neil@childrens.harvard.edu
T: 617-919-2865 F: 617-919-2300
www.walshlab.org

SUPPORT HEALTH EQUITY END RACISM
________________________________

**Comment by hanars** [comment]
Taking out the beta in the URL will work for now, and I will update seqr to not include it in the first place

**Comment by Jenniferneil** [comment]
Thanks!

All the best

Jen


?
________________________________

**Comment by hanars** [comment]
The link is fixed now
