### ISSUE TITLE
Log out issues

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1472]
**Describe the bug**
Frequently being logged out, approx. ~10 times a day, while using seqr. Happening to many other users as well. 

**Link to page(s) where bug is occurring**
I do not have a link atm

**Scope of the bug**
NA

**Screenshots**
Not pic at the moment

**Comment by lynnpais** [comment]
<img width="1311" alt="Screen Shot 2020-10-16 at 11 49 19 AM" src="https://user-images.githubusercontent.com/37872186/96280173-a825c480-0fa5-11eb-97f4-f2b6b99b6e8c.png">
 Just got logged out again, so took a pic this time.

**Comment by stephditroia** [comment]
Came to make this ticket but found Lynn's. I'm also having this issue. It seems random and happens 5+ times an hour.

**Comment by ch-kr** [comment]
I've also seen this today

**Comment by lynnpais** [comment]
Hi Hana,

Any update on this issue? All the analysts continue to be logged out. We lose our notes each time it happens.

**Comment by hanars** [comment]
sorry I am still working on it

**Comment by hanars** [comment]
@stephditroia @lynnpais @ch-kr I tried something yesterday which I think fixed the issue, but its hard to know for sure. Is it any better yesterday afternoon/ today?

**Comment by hanars** [comment]
@stephditroia @lynnpais @ch-kr any updates?

**Comment by ch-kr** [comment]
sorry, I haven't been on seqr this week

**Comment by stephditroia** [comment]
Same. ASHG.

**Comment by lynnpais** [comment]
I used it for ~30 minutes yesterday and it seemed fine. I'll be using seqr
tomorrow - will let you know if the issue persists.

**Comment by lynnpais** [comment]
Hi Hana,

Unfortunately the issue still persists...

**Comment by stephditroia** [comment]
To add to the timeline of this issue, I am still being logged out while using seqr and have been contacted by collaborators that they are being logged out also.

**Comment by ch-kr** [comment]
I also just got emailed by a collaborator asking about log out issues

**Comment by hanars** [comment]
is this still an issue?

**Comment by stephditroia** [comment]
I wasn't logged out during my normal seqr analysis all day yesterday.

**Comment by lynnpais** [comment]
Been doing analysis late Dec - now, no issues!

>

**Comment by JakeHagen** [comment]
I seem to be having this issue on our local install. Is there anything I can try?

**Comment by hanars** [comment]
Try making sure you are on the latest docker image with the latest python packages. You can also try restarting the server 
```
docker-compose exec seqr /usr/local/bin/stop_server.sh
docker-compose exec seqr /usr/local/bin/start_server.sh
```

**Comment by JakeHagen** [comment]
Great, that seemed to do the trick
