### ISSUE TITLE
SV tag

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1473]
**Describe the bug**
There appear to be two SVs in ROCK1, in the mother and proband. Technically, they shoud appear in one row, since it is one SV, inherited from the mother. 
I am unable to tag the variant in the proband. If I choose saved variants, the variant in the proband appears with my saved notes. However in the pic attached, my notes are for the SV in the mother.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/faa04b1338290e73d9530f006f76eb84?page=1&sort=in_omim

**Scope of the bug**
Case specific

**Screenshots**
<img width="1213" alt="Screen Shot 2020-10-16 at 11 52 55 AM" src="https://user-images.githubusercontent.com/37872186/96280685-4580f880-0fa6-11eb-887e-9c2d2cb4e69e.png">

**Comment by hanars** [comment]
This is unfortunately an issue with how data was loaded last time: https://the-tgg.slack.com/archives/C027LHMPP/p1602878710007400

**Comment by lynnpais** [comment]
The bug is to do with tagging. I cannot tag both the variants. I understand the data was loaded differently, and hence appears in two rows. Since both rows are relevant, it would be good to tag both.

**Comment by hanars** [comment]
As I explained in the linked post, this data is improperly added so seqr is not able to handle it properly. Until the data is reloaded properly, tags are not going to work right

**Comment by hanars** [comment]
Okay the data for this project has been reloaded, and now that search is returning one variant present in both the mother and proband. Tagging it should work now, let me know if you have any issues/ still experience any weird behavior

**Comment by hanars** [comment]
Data for all projects is reloaded so this should be fixed
