### ISSUE TITLE
update mgi error

### ISSUE THREAD

**Issue by SimonLi5601** [broadinstitute/seqr#1476]
To replicate the issue, just run update_mgi command 
-bash-4.2$ manage.py update_mgi
2020-10-20 15:37:08,132 INFO:  Downloading http://www.informatics.jax.org/downloads/reports/HMD_HumanPhenotype.rpt to /tmp/HMD_HumanPhenotype.rpt
18790 lines [00:01, 15450.01 lines/s]
2020-10-20 15:37:09,377 INFO:  Deleting 0 existing MGI records
2020-10-20 15:37:09,379 INFO:  Parsing file
18790 records [00:00, 41659.10 records/s]
2020-10-20 15:37:09,831 INFO:  Creating 18790 MGI records
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
...
django.db.utils.IntegrityError: duplicate key value violates unique constraint "reference_data_mgi_gene_id_marker_id_220a3b30_uniq"
DETAIL:  Key (gene_id, marker_id)=(55866, ) already exists

It seems can't get the marker_id from downloaded data.
It's also interesting to see MGI has a ForeignKey to GeneInfo which the gene_id is in different format

**Comment by hanars** [comment]
It appears that MGI changed the file format of the download, but didn't update their documentation. You can see in the index the following 2 different conflicting expected file headers for the download we were using
http://www.informatics.jax.org/downloads/reports/index.html

Vertebrate Homology
4. Mouse/Human Orthology with Phenotype Annotations (tab-delimited)
Human Marker Symbol | Human Entrez Gene ID | HomoloGene ID | Mouse Marker Symbol | MGI Marker Accession ID | High-level Mammalian Phenotype ID(space-delimited)
HMD_HumanPhenotype.rpt


Alleles and Phenotypes
2. Mouse/Human Orthology with Phenotype Annotations (tab-delimited)
Human Marker Symbol | Human Entrez Gene ID | HomoloGene ID | HGNC Association? | Mouse Marker Symbol | MGI Marker Accession ID | High-level Mammalian Phenotype ID(space-delimited)
HMD_HumanPhenotype.rpt

However when you look at the actual download, it doesn't seem to meet either format, as "MGI Marker Accession ID" is in the form "MGI:####" and that sort of value is completely absent from the download http://www.informatics.jax.org/downloads/reports/HMD_HumanPhenotype.rpt

I'm going to wait to update the code to see if they update either the file or the documentation in the next few days

**Comment by SimonLi5601** [comment]
The format issue has been fixed by The Jackson Lab and the command works well now. Thanks for your response!
