### ISSUE TITLE
SpliceAI scores not shown for saved variant

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#1480]
[This saved variant](https://seqr.broadinstitute.org/project/R0293_inmr_neuromuscular_disea/saved_variants/variant/SV0068118_119221619_f030572_hx) doesn't show a spliceAI score:
![image](https://user-images.githubusercontent.com/6240170/97255575-4fe19480-17e7-11eb-9c59-b7bdd178b071.png)

even though the variant exists in the spliceAI hail table:
```
In [1]:  ht = hl.read_table("gs://seqr-reference-data/GRCh38/spliceai/spliceai_scores.ht")
In [2]: ht.filter((ht.locus==hl.parse_locus("chr1:19221619", reference_genome="GRCh38")) & (ht.alleles == ["G", "C"])).collect()
[Stage 3:>                                                          (0 + 1) / 1]
Out[2]: [Struct(locus=Locus(contig=chr1, position=19221619, reference_genome=GRCh38), alleles=['G', 'C'], rsid=None, qual=-10.0, filters=None, info=Struct(SpliceAI=[0.10000000149011612, 0.0, 0.0, 0.0], max_DS=0.10000000149011612, splice_consequence='Acceptor gain'))]
```

and the scores in the hail table match the masked scores reported by spliceailookup.broadinstitue.org ([link](https://spliceailookup.broadinstitute.org/#variant=1%3A19221619%3AG%3AC)):

![image](https://user-images.githubusercontent.com/6240170/97255510-304a6c00-17e7-11eb-80c6-a415d7bd740b.png)

The question is why are the scores not shown in the UI?

**Comment by hanars** [comment]
It looks like when this was tagged we didn't have splice AI loaded for the variant and this project didn't properly refresh the saved variants when the data was reloaded. I triggered a manual refresh and splice AI is now showing

**Comment by bw2** [comment]
Awesome, thanks. Not sure if this is straight-forward, but it would be nice if saved variant caches were updated every time a new callset is loaded.

**Comment by hanars** [comment]
so they actually are! But the issue is it takes too long to do it synchronously for large projects (i.e not show the data loading is successful until the reload finishes), so it happens async so when it fails nothing shows up in the browser. I'm working on improving seqr logging and monitoring, so one thing I can add is an alert whenever the update fails so i can manually go in and trigger it

**Comment by bw2** [comment]
Cool!
