### ISSUE TITLE
Readviz not loading in Project I

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#1491]
**Describe the bug**
For Gabrielle and myself, show read does not appear to be working. I got a 500 error. 
**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/d51c5560e1ab8039f32a99ac928e0efd?page=1&sort=xpos

**Scope of the bug**
I've only checked Project I

**Screenshots**

**Comment by hanars** [comment]
Is there a timeline on getting this fixed? I.e. do we have any planed demos that rely on these working, or is this more a general "this should get fixed sometime soon"

**Comment by anneodonnell** [comment]
We are using it to train Gabrielle in analysis at the moment so it would have been handy for her to be able to see read data but it’s not urgent. She will presumably move on to real cases in the next week anyway.


On Nov 4, 2020, at 10:56 AM, hanars <notifications@github.com<mailto:notifications@github.com>> wrote:

* External Email - Caution *




Is there a timeline on getting this fixed? I.e. do we have any planed demos that rely on these working, or is this more a general "this should get fixed sometime soon"

**Comment by hanars** [comment]
IGV appears to be working again
