### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1493]
Search seems to be down in FAM225 only

Link - https://seqr.broadinstitute.org/variant_search/results/63b5c75a4342c9c2fe05fdf8043235fa?page=1&sort=exac

<img width="1257" alt="Screen Shot 2020-11-04 at 7 33 21 PM" src="https://user-images.githubusercontent.com/37872186/98182862-c9a70b80-1ed4-11eb-82c0-f4e4834b7570.png">

**Comment by hanars** [comment]
this is working again
