### ISSUE TITLE
No read data

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1507]
**Describe the bug**
IGV data not displayed

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/...https://seqr.broadinstitute.org/variant_search/results/491a1379c6388916a5758d612305714c?page=1&sort=xpos
Affecting multiple cases including GAZ_429 and GAZ_498

**Scope of the bug**
Appears to be project-wide

**Screenshots**
<img width="1256" alt="Screen Shot 2020-11-18 at 7 33 10 PM" src="https://user-images.githubusercontent.com/37872186/99605128-0b57ac00-29d5-11eb-96e7-7af8cca36a01.png">

**Comment by hanars** [comment]
@ch-kr @mike-w-wilson

**Comment by ch-kr** [comment]
21 samples in this project aren't in [https://app.terra.bio/#workspaces/anvil-datastorage/AnVIL_CMG_Broad_Blood_Gazda_WES/data](https://app.terra.bio/#workspaces/anvil-datastorage/AnVIL_CMG_Broad_Blood_Gazda_WES/data) -- they're in [https://app.terra.bio/#workspaces/broad-genomics-data/dba_Sankaran_PI_diseasestudied_exome_subgroupname/data](https://app.terra.bio/#workspaces/broad-genomics-data/dba_Sankaran_PI_diseasestudied_exome_subgroupname/data). this should be fixed now
