### ISSUE TITLE
loading on prem

### ISSUE THREAD

**Issue by dmcgoldrick** [broadinstitute/seqr#1518]
**Describe the bug**
I am not able to load a valid vcf dataset into ES on our docker instance of Seqr on prem. 

steps completed  are 
1) validated Auth
gcloud auth application-default login  

2) made input directory

3) Start and execute pipeline-runner

What I ran:
python3 -m seqr_loading SeqrMTToESTask --local-scheduler \
    --reference-ht-path ${REFERENCE_HT_PATH} \
    --clinvar-ht-path ${CLINVAR_HT_PATH}\
    --vep-config-json-path ${VEP_CONFIG_JSON_PATH} \
    --es-host elasticsearch \
    --es-index-min-num-shards 3 \
    --sample-type WES \
    --es-index ${ES_INDEX} \
    --genome-version ${GENOME_VERSION} \
    --source-paths ${SOURCE_PATHS} \   # a local accessible path
    --dest-path ${DEST_PATH} \ # a local accessible path

the error:
Hail version: 0.2.39-ef87446bd1c7
Error summary: HailException: MatrixTable and Table files are directories; path 'gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht' is not a directory
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   SeqrVCFToMTTask__vep_data_clinva_VARIANTS__input_vcfs_pete_9c8eb72214   has status   FAILED
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: There are 2 pending tasks possibly being run by other workers
DEBUG: There are 2 pending tasks unique to this worker
DEBUG: There are 2 pending tasks last scheduled by this worker
INFO: Worker Worker(salt=386575296, workers=1, host=b9ece43b21a0, username=root, pid=16507) was stopped. Shutting down Keep-Alive thread
INFO: 
===== Luigi Execution Summary =====

Scheduled 3 tasks of which:
* 1 complete ones were encountered:
    - 1 VcfFile(filename=/input_vcfs/peter_uwcmg_cas_1.vcf.gz)
* 1 failed:
    - 1 SeqrVCFToMTTask(...)
* 1 were left pending, among these:
    * 1 had failed dependencies:
        - 1 SeqrMTToESTask(...)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

BUG? It seems that the code is looking for a bucket file 
 'gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht' 

can I load that locally or in general is there way to download a complete set of hail datasets and files in one go?

**Link to page(s) where bug is occurring**
https://github.com/broadinstitute/seqr/blob/master/deploy/LOCAL_INSTALL.md

**Scope of the bug**
Every input vcf being converted to ES with an index for seqr

Can you help me get past his remote file? Is it needed?

Thanks for looking at this!

Daniel McGoldrick UWCMG

**Comment by hanars** [comment]
I see that directory exists for me and is a public bucket, which means any authenticated google user has access, so I am not quite sure what is happening there. If you run `docker-compose exec pipeline-runner gsutil ls gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht` what happens?

At @bw2 any thoughts?

**Comment by dmcgoldrick** [comment]
Ok -- here it is :-)
[mcgold@rainier docker-shares]$ docker-compose exec pipeline-runner gsutil ls gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht
gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht/
gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht/README.txt
gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht/_SUCCESS
gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht/metadata.json.gz
gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht/globals/
gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht/references/
gs://seqr-reference-data/GRCh37/validate_ht/common_noncoding_variants.grch37.ht/rows/

seems to work!

also within the container bash is working...

I ran this again without the environment variables as inputs and checking the paths to make sure they exist:

python3 -m seqr_loading SeqrMTToESTask --local-scheduler --reference-ht-path '/vep_data/seqr-reference-data/GRCH37/all_reference_data/combined_reference_data_grch37.ht/' --clinvar-ht-path '/vep_data/clinvar.GRCh37.2020-06-15.ht/' --vep-config-json-path '/vep-GRCh37.json' --es-host elasticsearch --es-index-min-num-shards 3 --sample-type WES --es-index XXX --genome-version 37 --source-paths '/input_vcfs/XXX.HF.final.vcf.gz' --dest-path '/input_vcfs/XXX.mt'


DEBUG: Pending tasks: 2
INFO: [pid 20824] Worker Worker(salt=641882396, workers=1, host=b9ece43b21a0, username=root, pid=20824) running   SeqrVCFToMTTask(source_paths=/input_vcfs/XXX.HF.final.vcf.gz, dest_path=/input_vcfs/XXX.mt, genome_version=37, vep_runner=VEP, reference_ht_path=/vep_data/seqr-reference-data/GRCH37/all_reference_data/combined_reference_data_grch37.ht/, clinvar_ht_path=/vep_data/clinvar.GRCh37.2020-06-15.ht/, hgmd_ht_path=None, sample_type=WES, dont_validate=False, dataset_type=VARIANTS, remap_path=, subset_path=, vep_config_json_path=/vep-GRCh37.json)
ERROR: [pid 20824] Worker Worker(salt=641882396, workers=1, host=b9ece43b21a0, username=root, pid=20824) failed    SeqrVCFToMTTask(source_paths=/input_vcfs/XXX.HF.final.vcf.gz, dest_path=/input_vcfs/XXX.mt, genome_version=37, vep_runner=VEP, reference_ht_path=/vep_data/seqr-reference-data/GRCH37/all_reference_data/combined_reference_data_grch37.ht/, clinvar_ht_path=/vep_data/clinvar.GRCh37.2020-06-15.ht/, hgmd_ht_path=None, sample_type=WES, dont_validate=False, dataset_type=VARIANTS, remap_path=, subset_path=, vep_config_json_path=/vep-GRCh37.json)

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 184, in run
    raise RuntimeError('Unfulfilled %s at run time: %s' % (deps, ', '.join(missing)))

RuntimeError: Unfulfilled dependency at run time: VcfFile__input_vcfs_pete_3e77876288

===== Luigi Execution Summary =====

Scheduled 3 tasks of which:
* 1 ran successfully:
    - 1 VcfFile(filename=/input_vcfs/peter_uwcmg_cas_1.HF.final.vcf.gz)
* 1 failed:
    - 1 SeqrVCFToMTTask(...)
* 1 were left pending, among these:
    * 1 had failed dependencies:
        - 1 SeqrMTToESTask(...)

This progress looks :( because there were failed tasks

===== Luigi Execution Summary =====

Now it seems that something is not present at run time for the second task :/ - not sure what "dependency" is Unfulfilled. The error is hard for me to interpret.

**Comment by hanars** [comment]
The dependency that is missing is the output of the SeqrVCFToMTTask which failed, so thats expected. The issue at hand here is why that task is failing. Is this the full output of the pipeline that you are getting? You may also want to clean up any intermediate files in the volume mount and running the pipeline again and see what happens

**Comment by dmcgoldrick** [comment]
Thanks I'll try a fresh install and cleanup working with our IT team here :-)

**Comment by JakeHagen** [comment]
Hi I am having the same issue with a local install. I can get around the validation with the option `--dont-validate` but then I get `Error summary: HailException: Chain file 'gs://hail-common/references/grch38_to_grch37.over.chain.gz' does not exist.`

Using `gsutil ls gs://hail-common/references/grch38_to_grch37.over.chain.gz` lists the file no problem.

**Comment by JakeHagen** [comment]
I was able to solve this by re-authenticating from within the pipeline docker container (`gcloud auth application-default login`)

Does the gcloud only work per user? So when we copy mount our config into the docker container, we need to re-auth for the now root user?

**Comment by hanars** [comment]
@bw2 any ideas why users keep needing to re-authenticate?

**Comment by bw2** [comment]
I just tried this again, but am not able to reproduce the issue. 
docker-compose mounts google auth credentials into the pipeline runner bucket: https://github.com/broadinstitute/seqr/blob/master/docker-compose.yml#L95

If the user is able to run 
`gsutil ls gs://hail-common/references/grch38_to_grch37.over.chain.gz`
on their machine (outside docker), then they should be able to run it inside the 
docker-compose exec pipeline-runner /bin/bash  
shell.

**Comment by dmcgoldrick** [comment]
So -- and thanks to others here - I have been able to load vcf on prem in the two step protocol with a directory/permissions cleanup and container upgrade. Seqr finds the same variants we had in our GEMINI test.   I authenticated like JakeHagen from within the pipeline container and could not authenticate outside the pipeline container on the server when using a windows ubuntu subsystem ssh to a seqr-docker enabled server. I have to run --dont-validate for our WES target or else it seems to not recognize our target correctly. Loading/spoofing a WES experiment with validation as WGS works - oddly enough - WES does not work with validation - WES dont-validate does work. So I think it is overlap of alternative exome targets that is the issue? 

I get an issue about quotas that is not well discussed in the manual:
Credentials saved to file: [/root/.config/gcloud/application_default_credentials.json]

These credentials will be used by any library that requests Application Default Credentials (ADC).
WARNING:
Cannot find a quota project to add to ADC. You might receive a "quota exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.

This on-prem issue seems solved for me at least and thanks Jake - but I think there is need to elaborate these credential and quota issues?

Daniel

**Comment by hanars** [comment]
@bw2 you originally set up the google account for local installations. Any idea if theres something wrong with its current settings? Is this something we need to fix on our end, or should we ad instructions for how to fix these issues locally? 

I also think this might be the same issue as https://github.com/broadinstitute/seqr/issues/1594

**Comment by dmcgoldrick** [comment]
I think the referenced issue #1594 and my comment is a new thing that we can work on locally :-). This original issue seems to be resolved now.

 I will submit issue one if we run into any setbacks

Thank you very much and others for your help!
