### ISSUE TITLE
Error when starting up the seqr docker image 

### ISSUE THREAD

**Issue by mgabere** [broadinstitute/seqr#1521]
Hi SEQR team,

When I ran the following command from the tutorial: https://github.com/broadinstitute/seqr/blob/master/deploy/LOCAL_INSTALL.md

   `sudo docker-compose up -d seqr`

I get the error:
`ERROR: for seqr Container "cefd09c308fe" is unhealthy`

There was a similar problem in the link below:
https://github.com/broadinstitute/seqr/issues/1248

But it seems like it was not resolved. Please assist me in solving this error.

Thanks,
musa

**Comment by mgabere** [comment]
Hi SEQR team. By increasing, health check timeout & interval value in the file (docker-compose.yml), this issue was resolved. Specifically, change all timeout and interval in the .yml file to 1200s. Thanks. musa

**Comment by hanars** [comment]
I'm glad it worked for you. Would you be interested in putting up a pull request with the changes you made to the docker compose file? I'd be happy to get that merged to our master to help this issue in the future
