### ISSUE TITLE
KeyError properties

### ISSUE THREAD

**Issue by veioenza** [broadinstitute/seqr#1523]
When  performing a Variant search I get the following error message.

File \"/seqr/seqr/utils/elasticsearch/utils.py\" line 54, in get_index_metadata\n    field: field_props.get('type') for field, field_props in variant_mapping['properties'].items()\nKeyError: 'properties'\n"

And indeed it looks like variant_mapping only as the "variant" key. Should this be variant_mapping['variant']['properties'] ?

**Comment by hanars** [comment]
we have updated elasticsearch from v6 to v7. If you updated your seqr version without updating your elasticsearch instance, you would see this issue

**Comment by veioenza** [comment]
Ah that got it. I updated the docker-compose and it updated ES. We do seem to have some session/login issues now. It is almost as if it forgets the session data but if I return to the dashboard it starts working fine again. This behavior has been confirmed by another user and I and restarted both the containers and the server.

seqr_1             | 152.78.0.67 - - [26/Nov/2020:12:49:12 +0000] "GET /static/app.003c0c43.css HTTP/1.1" 304 0 "http://seqr.soton.ac.uk/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36"
seqr_1             | 152.78.0.67 - - [26/Nov/2020:12:49:12 +0000] "GET /static/app-2f4e6a79.js HTTP/1.1" 304 0 "http://seqr.soton.ac.uk/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36"
seqr_1             | {"timestamp": "2020-11-26 12:49:12,271", "severity": "WARNING", "message": "Session data corrupted"}
seqr_1             | {"timestamp": "2020-11-26 12:49:12,271", "severity": "WARNING", "message": "Session data corrupted"}
seqr_1             | {"timestamp": "2020-11-26 12:49:12,271", "severity": "INFO", "httpRequest": {"requestMethod": "GET", "requestUrl": "http://seqr.soton.ac.uk/api/dashboard", "status": 302, "responseSize": 0, "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36", "remoteIp": "152.78.0.67", "referer": "http://seqr.soton.ac.uk/", "protocol": "HTTP/1.1"}}

**Comment by hanars** [comment]
We have also been seeing a spike in the "session data corrupted" errors in our production seqr recently. I haven't been able to figure out why yet. We've found that this causes users to be logged out and need to log back in again, but while its been annoying it hasn't been too too disruptive for our users
