### ISSUE TITLE
Seqr search error

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1529]
**Describe the bug**
Seqr search seems to be returning zero or far fewer variants than typical. An example is FAM182 (link below) where a de novo/ dominant permissive search returns zero variants even with parents set to ? which  essentially makes it proband only, returns zero variants. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/9f8f6ca14010d00492c5089ddf02a5fc?page=1&sort=xpos

**Scope of the bug**
Right now I have noticed it in multiple families in the VCGS exomes project. I cannot rule out other projects. I noticed this yesterday.

**Screenshots**
<img width="1180" alt="Screen Shot 2020-12-02 at 6 44 56 PM" src="https://user-images.githubusercontent.com/37872186/100945051-7e314e80-34ce-11eb-8803-75d5582e3144.png">

**Comment by hanars** [comment]
This is fixed now
