### ISSUE TITLE
No pedigrees for newly uploaded families

### ISSUE THREAD

**Issue by gvannoy** [broadinstitute/seqr#1530]
When uploading new individuals, a pedigree is not being automatically drawn on the family page the way it typically is. An error message pops up when the new individuals are added, but it does allow them to be added to the project (see below). 

Example family: RGP_1655 https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F031490_rgp_1655

This appears to be affecting all newly created families in the Rare Genomes Project_Genomes project. 

![image](https://user-images.githubusercontent.com/40441144/100952766-fba49100-34c5-11eb-8187-3c670ca7db14.png)

**Comment by gvannoy** [comment]
Similarly, when editing an individual's name that is part of an existing pedigree (from a family added pre-this issue), the name change is not incorporated into the pedigree even though it is changed everywhere else. An error message also pops up when changing and individual name (see below).

Example family: RGP_1305
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F030421_rgp_1305

This appears to be affecting all name edits made to existing RGP individuals. 

![image](https://user-images.githubusercontent.com/40441144/100953492-8f2a9180-34c7-11eb-91b7-953427f26aa8.png)

**Comment by hanars** [comment]
Pedigree image generation is working again, and I fixed the images in the examples you gave in the ticket. If you notice anywhere else that this happened, you can edit an individual in the family and then change it back and it will create a correct image
