### ISSUE TITLE
Add 'Analysis Summary' field to Case Review view

### ISSUE THREAD

**Issue by gvannoy** [broadinstitute/seqr#1531]
During case review we sometimes need to suggest analysis strategies that will be used in the future when data is loaded. We add that info to the Analysis Summary field for the analysts to see, but toggling between Case Review view and the family page to do this is a nuisance. 

I'd like to see the existing Analysis Summary field as an editable field in the Case Review view for each family. It would be best to have it just above the Internal Notes field. 

The current work-around is opening each family page separately to edit there, but this extra step can cause it to get forgotten. 

Let me know if you have questions. Thanks!

**Comment by hanars** [comment]
added!
