### ISSUE TITLE
MAX_COMPOUND_HET_GENES

### ISSUE THREAD

**Issue by SimonLi5601** [broadinstitute/seqr#1540]
**Describe the bug**
When there is larger cohort (e.g. more than 10 families ), MAX_COMPOUND_HET_GENES will affect the performance  a lot

**Scope of the bug**
Recessive or compound het search 
[](url)
The interface is frozen or throws an error (it depends on platform)

Do you have any mitigation for this query?

<img width="1321" alt="Screen Shot 2020-12-07 at 5 55 01 PM" src="https://user-images.githubusercontent.com/18488136/101415801-83b7db80-38b6-11eb-810f-082f6fbefc89.png">

**Comment by hanars** [comment]
We currently can't do inheritance-based cohort wide searches for large cohorts, its just not performant enough. In general, we use cohort search for searches limited to gene lists  or variants of interest. The "any affected" inheritance search is the most performant of the inheritance searches, so our analysts often use that, and then do follow up searches in families of interest that come up using more detailed inheritance. Also, filtering on genotype quality slows down search in large cohorts, so you can try not applying quality filters on those searches as well

**Comment by SimonLi5601** [comment]
Thanks for your suggestion, Hana! I will close this ticket.
