### ISSUE TITLE
list of variants as "location" for family variant search

### ISSUE THREAD

**Issue by sannagudmundsson** [broadinstitute/seqr#1541]
**Describe the bug**
In the variant search under "Location" I tried adding a list of variants. I tried different formats to search for several variants at once but the search returned 0 results (but in this example I know the first variant exists)

14-105146689-C-T, 14-105075673-A-AG

14-105146689-C-T 14-105075673-A-AG

14-105146689-C-T,
14-105075673-A-AG

14-105146689-C-T
14-105075673-A-AG

**Link to page(s) where bug is occurring**
I does not work for this family: https://seqr.broadinstitute.org/variant_search/results/02093570d0445bf00dc194019a1ec306?page=1&sort=xpos

But it works with this family:
https://seqr.broadinstitute.org/variant_search/results/40b816a4e4518d168852e9e94da46564?page=1&sort=xpos

**Scope of the bug**
For specific family, see link above

**Screenshots**
Works fine for family BON_B16-48

But for family MWAR011
Works for one variant

not for two

Thanks in advance!

All the best,
Sanna

**Comment by hanars** [comment]
This is fixed now. Search will work for a full list of IDs now
