### ISSUE TITLE
Search 502 error

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1553]
**Describe the bug**
Search across multiple projects won't go through

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/f27c098f672d5929af6de26581a2d73d?page=1&sort=xpos
https://seqr.broadinstitute.org/variant_search/results/30a577441388ed753b925c3bf0234ecc?page=1&sort=xpos

**Scope of the bug**
Multiple projects. I checked Kang_LGMD, VCGS_exomes and the recent Aicardi projects. 

**Screenshots**
<img width="1205" alt="Screen Shot 2020-12-10 at 11 12 19 AM" src="https://user-images.githubusercontent.com/37872186/101798040-a6c1d580-3ad8-11eb-96f8-3511d8b0f08e.png">

**Comment by hanars** [comment]
search is working again. Sorry for the delay on this
