### ISSUE TITLE
Internal Notes and Internal Summary Fields Not Saving

### ISSUE THREAD

**Issue by gvannoy** [broadinstitute/seqr#1563]
Any new edits in the Internal Notes and Internal Summary fields are not being saved.

https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/case_review

Appears to be impacting any RGP family in Case Review (the only view where these fields are visible)

No relevant screenshot to provide. No error pops up, but the edits aren't saving after submit is clicked.

**Comment by hanars** [comment]
this is fixed
