### ISSUE TITLE
Download CGRh38 data

### ISSUE THREAD

**Issue by bnouyou** [broadinstitute/seqr#1594]
Hello,

I would like to download data for GRCh38. But it doesn't work and I don't know why.
If I run `gsutil -m cp -r gs://seqr-reference-data/GRCh38/all_reference_data/combined_reference_data_grch38.ht . `, I have this message: 
```
invalid_grant: Bad Request
CommandException: 1 file/object could not be transferred.
```

Thank you in advance for your help.

**Comment by hanars** [comment]
Can you re-run `gcloud auth application-default login` to confirm you are logged in

**Comment by bnouyou** [comment]
I have done that and I have this message:
```
These credentials will be used by any library that requests Application Default Credentials (ADC).
WARNING:
Cannot find a quota project to add to ADC. You might receive a "quota exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.
```

**Comment by hanars** [comment]
@bw2 have you ever seen this before?

**Comment by bw2** [comment]
sorry no I haven't seen this before.

**Comment by hanars** [comment]
This seems to be a similar tissue to the most recent comment in https://github.com/broadinstitute/seqr/issues/1518

**Comment by hanars** [comment]
@bnouyou are you still experiencing this issue?

**Comment by bnouyou** [comment]
Hello,
Yes I still have the issue. I haven't change anything since the last time. I have downloaded Seqr few months ago with only GRCh37 and it's working well. Now I would like to add the GRCh38 and I have this message (see below) when I do the `gcloud auth application-default login  ` command.
```
These credentials will be used by any library that requests Application Default Credentials (ADC).
WARNING:
Cannot find a quota project to add to ADC. You might receive a "quota exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project.
```

Do you know what I can do ?

**Comment by bw2** [comment]
I just tried this and have no problem running 
```
gsutil -m cp -r gs://seqr-reference-data/GRCh38/all_reference_data/combined_reference_data_grch38.ht .
```
To check whether it's specific to gs://seqr-reference-data, can you check if you're able to download files from 
```
gs://genomics-public-data/resources/broad/hg38/v0/
```
for example 
```
gs://genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.dict
```
?
Also, are you running gsutil on your laptop or inside one of the seqr-associated docker containers?

**Comment by bnouyou** [comment]
I think it's good. I was doing this on a VM and it seems that the IT has close the internet connection on it. I am trying on another VM and this time it seems working.
I will update the issue when everything will be downloaded.

Thank you for your help.

**Comment by bnouyou** [comment]
Hello,
It worked  this time. Thank you.
