### ISSUE TITLE
IGV down

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1602]
**Describe the bug**
Reads not showing in VCGS_EXT_FAM3

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0358_cmg_vcgs_exomes/saved_variants/variant/SV0077983_1249185141_f030967_v

**Scope of the bug**
case specific

**Screenshots**
<img width="1240" alt="Screen Shot 2021-01-12 at 6 01 33 PM" src="https://user-images.githubusercontent.com/37872186/104384867-399ec700-5500-11eb-80ea-20afb7ae7166.png">

**Comment by hanars** [comment]
@ch-kr @mike-w-wilson

**Comment by ch-kr** [comment]
this is fixed now
