### ISSUE TITLE
re-enable linkerd

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr#1606]
We deployed linkerd on production, but had to roll back the redis connection due to issues with how it handles the traffic and the postgres connection because it was breaking the pg_dump required for seqr backups. It appears the next linkerd release should resolve these issues, and will probably also allow us to use linkerd for elasticsearch as well

**Comment by sjahl** [comment]
Just to record some state on this... I deployed an edge release of linkerd to test the opaque ports setting.

- **Elasticsearch**: I have not yet tested this. The devs claimed that using opaque-ports on port 9300 might help fix some errors related to getting the cluster established (masters elected, nodes joined, etc). It's not clear to me that this is what our problem was, but several people have been complaining about it, and it just needs some testing.

- **Redis**: I tested it a bit, I don't see any redis timeouts in the logs, however, the seqr app tells me (while doing a variant search) that no data is loaded, so I'm dubious that I've been able to test this sufficiently.

- **pg_dumps**: sadly, I see the same stalling behavior when opaque ports are used for postgres traffic. I'm able to dump smaller databases, but not the seqr database. I've gotten packet captures done on a working and failing case, and am talking with the linkerd developers to see if they have any ideas. My two additional thoughts on this are:
  - This concerns me a bit on linkerd's performance. I don't know if this is a data size, or a query wall clock/timeout issue. But it makes me wonder whether longer running queries in general will be a problem with the mesh.
  - Backing up the database in a cron job running in the seqr container isn't a particularly great practice. We may want to rethink how we're doing this. If all other app traffic is fine when proxied, maybe we don't need to worry about linkerd performance if pg_dump is a pathological case that can be done differently.

**Comment by hanars** [comment]
re: pg_dump I agree that having it run in the seqr container is not really ideal. The reason we do it that way now is because the seqr container has the gsutil cli installed so you can easily copy the dumped file to a google bucket, whereas the postgres pod does not. But I feel like there should be a better way to do this

**Comment by sjahl** [comment]
As an update here, the linkerd devs asked me to try a new edge release that they thought would fix the pg_dump issues. I spent a few hours today debugging with that in a testing cluster, but the new edge release (edge-21.2.2) still exhibits the problem. I provided the logs from the debugging; we'll see what they say.

**Comment by larrybabb** [comment]
still have not heard back from linkerd support/dev staff.

**Comment by wmorgan** [comment]
@larrybabb @sjahl do you have a Linkerd issue tracking this?

**Comment by larrybabb** [comment]
I'll defer to @sjahl since he's been maintaining the communications with linkerd.

**Comment by sjahl** [comment]
@wmorgan yes -- being tracked at https://github.com/linkerd/linkerd2/issues/5539, thanks for checking in!

**Comment by wmorgan** [comment]
Appreciate your patience. This is a weird one.

**Comment by sjahl** [comment]
linkerd 2.10 just went out to prod.

**Comment by wmorgan** [comment]
Please add yourselves to [ADOPTERS.md](https://github.com/linkerd/linkerd2/blob/main/ADOPTERS.md) when you get a moment! Can ship you swag as an incentive if you like :) 

Also, if there is anything COVID-19-related you are tackling with seqr, I'd love to hear about it. I will be talking about the intersection of Linkerd and the pandemic at Kubecon EU.
