### ISSUE TITLE
Show IGV for SVs

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr#1607]
@hanars todo add details and data file examples.

**Comment by hanars** [comment]
https://github.com/broadinstitute/seqr/pull/1636 includes all the code to theoretically show the new track types. However, that version of IGV works locally (slowly) but not on dev server, and breaks reads for crams so more investigation needed

**Comment by hanars** [comment]
In theory, once the IGV version is bumped SV tracks in IGV should just work. You add them usinng the "Edit Datasets" option on the project page in seqr, and then ypu select the "edit IGV Paths" tab and upload a file.  In the first column you put the ID for the individual in the project, and for the second column you have a gs:// file path that points to an SV file, which will end in the file path `dcr.bed.gz`. Once you have done that, yu should see anoption on the variants in that individaul to show SV reads, and if you click that it should work. If it does't you need to fix it. I will update shortly with some sample files you can use

**Comment by hanars** [comment]
Okay, so a file you can use is `gs://seqr-datasets-gcnv/GRCh/RDG_WES_Broad_Internal/v1/beds/cc_1_1.dcr.bed.gz`
The thing I left out is you upload the file, you need to add a third column to the file that specifies which sample ID in the "batch" to highlight. In real life this will be related to the seqr sample ID but for the purposes of testing you should use RP-1314_OUN_HK127-001_D1_v1_Exome_GCP

You can see an example of what the track should look like here: https://tgg-viewer.broadinstitute.org/#locus=chr15:92835700-93031800&show=~(~'gcnv_bed~'coverage~'bed)&selectedRows=~(gCNV*20Batches~(~'cc_1_1))&selectedSamples=~(gCNV*20Batches~(selectedSamples~(cc_1_1~(~'RP-1314_OUN_HK127-001_D1_v1_Exome_GCP))~sampleSettings~()))&order=~(~)&sjOptions=~(trackHeight~170~colorBy~'strand~colorByNumReadsThreshold~5~thicknessBasedOn~'numUniqueReads~bounceHeightBasedOn~'random~labelUniqueReadCount~true~labelMultiMappedReadCount~false~labelTotalReadCount~false~labelMotif~false~labelAnnotatedJunction~false~labelAnnotatedJunctionValue~'*20*5bA*5d~showOnlyPlusStrand~false~showOnlyMinusStrand~false~hideAnnotated~false~hideUnannotated~false~minUniquelyMappedReads~0~minTotalReads~1~maxFractionMultiMappedReads~1~minSplicedAlignmentOverhang~0)&vcfOptions=~(displayMode~'EXPANDED)&bamOptions=~(trackHeight~200~viewAsPairs~false~showSoftClips~true~alignmentShading~'strand)&gcnvOptions=~(trackHeight~200~trackMin~0~trackMax~5~autoscale~false~onlyHandleClicksForHighlightedSamples~true)&settingsUrl=~'https*3a*2f*2fraw.githubusercontent.com*2fbroadinstitute*2ftgg_methods*2fmaster*2fgcnv_viewer*2fgcnv_settings.json 

Don't worry that the reference tracks look different, we want to keep them the way they currently are in seqr

**Comment by ShifaSZ** [comment]
After I uploaded an igv path file containing one line `GLE_4111_4_5	gs://seqr-datasets-gcnv/GRCh38/RDG_WES_Broad_Internal/v1/beds/cc_1_1.dcr.bed.gz	RP-1314_OUN_HK127-001_D1_v1_Exome_GCP`, a variant of the sample is shown below.
![image](https://user-images.githubusercontent.com/33550059/125486990-0e129668-cf01-4043-843a-2545436674dc.png)
It shows `SHOW gCNV` which is good. But after clicking on it and waiting for data downloaded, no figure is shown. And I found some warnings on the browser console.
```
chr1:169602929-169603309 row contains 130 sample columns instead of the expected 169 columns. Skipping...
chr2:1237791-1238115 row contains 3 sample columns instead of the expected 169 columns. Skipping...
chr1:169602929-169603309 row contains 130 sample columns instead of the expected 169 columns. Skipping...
chr2:1237791-1238115 row contains 3 sample columns instead of the expected 169 columns. Skipping...
```
Those warnings are all from igv.js.
I'm still working on that. If you have any idea about it, please let me know.

**Comment by hanars** [comment]
@bw2 have you ever seen an error like that?

**Comment by ShifaSZ** [comment]
It seems that the warnings just indicate that there are some bad lines in the data. But there are many other valid lines. So, it shouldn't matter.

**Comment by hanars** [comment]
yeah, I just checked those coordinates in the TGG viewer, and I also don't see anything at those coordinates so my guess is there just isn't anything at this location in this particular file (which is fine, since this file isn't actually associated with the sample you are testing it on). If you copy-paste different coordinates into the search box, do you see anything in the track? Try chr15:92835700-93031800

**Comment by ShifaSZ** [comment]
It DOES so something!
![image](https://user-images.githubusercontent.com/33550059/125506921-3a56b6ad-7ba3-4930-a614-cd2786872e70.png)

**Comment by hanars** [comment]
so thats good, but the one issue is it *should* be highlighting one of the rows: https://tgg-viewer.broadinstitute.org/#locus=chr15:92835700-93031800&show=~(~'gcnv_bed~'coverage~'bed)&selectedRows=~(gCNV*20Batches~(~'cc_1_1))&selectedSamples=~(gCNV*20Batches~(selectedSamples~(cc_1_1~(~'RP-1314_OUN_HK127-001_D1_v1_Exome_GCP))~sampleSettings~()))&order=~(~)&sjOptions=~(trackHeight~170~colorBy~'strand~colorByNumReadsThreshold~5~thicknessBasedOn~'numUniqueReads~bounceHeightBasedOn~'random~labelUniqueReadCount~true~labelMultiMappedReadCount~false~labelTotalReadCount~false~labelMotif~false~labelAnnotatedJunction~false~labelAnnotatedJunctionValue~'*20*5bA*5d~showOnlyPlusStrand~false~showOnlyMinusStrand~false~hideAnnotated~false~hideUnannotated~false~minUniquelyMappedReads~0~minTotalReads~1~maxFractionMultiMappedReads~1~minSplicedAlignmentOverhang~0)&vcfOptions=~(displayMode~'EXPANDED)&bamOptions=~(trackHeight~200~viewAsPairs~false~showSoftClips~true~alignmentShading~'strand)&gcnvOptions=~(trackHeight~200~trackMin~0~trackMax~5~autoscale~false~onlyHandleClicksForHighlightedSamples~true)&settingsUrl=~'https*3a*2f*2fraw.githubusercontent.com*2fbroadinstitute*2ftgg_methods*2fmaster*2fgcnv_viewer*2fgcnv_settings.json

**Comment by hanars** [comment]
The code that determines which rows should be highlighted is here: https://github.com/broadinstitute/seqr/blob/master/ui/shared/components/panel/FamilyReads.jsx#L229

**Comment by ShifaSZ** [comment]
Now, it looks like:
![image](https://user-images.githubusercontent.com/33550059/125520859-a5831ff2-d598-4ba7-a23d-1d0d697d00ae.png)
The loading speed is slower than the tgg-viewer website. Maybe, there are some rooms to improve for the data loading proxies.

**Comment by hanars** [comment]
agreed that speed is pretty bad here. If you have time to look into that next, that would be great
