### ISSUE TITLE
flattenCompoundHet: which branch (or not implemented yet?)

### ISSUE THREAD

**Issue by NLSVTN** [broadinstitute/seqr#1624]
**Describe the bug**
Master branch seems to have the **flattenCompoundHet** (**variant search page**. After we do the search it appears) toggle but it does not seem to flatten the compound hets, I see no code that does it and the toggle seems to be just isolated ui that does nothing.

Are there any branches/commits that have the feature developed or partially developed that I could integrate into my code and proceed from that? As I understand the toggle should convert compound het pairs into a list of variants, remove duplicates and redraw the page perhaps in the meantime showing loading screen to avoid UI to be stuck for long.

**Comment by hanars** [comment]
There is no special branch you should be on, the compound het functionality has been live for well over a year. 

"After we do the search it appears) toggle but it does not seem to flatten the compound hets," is not a great description of what you are experiencing. Can you please describe in more detail what you are seeing and show screenshots of the bug? Can you show an image of search results with paired compound hets before and after the toggle? Or is the toggle not showing for you at all?

**Comment by NLSVTN** [comment]
Sorry, turns out my mistake, just needed to pull different code. But still long waiting times when we hit the toggle seems to be an issue.

**Comment by hanars** [comment]
yes, thats a known issue
