### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by NLSVTN** [broadinstitute/seqr#1632]
**Describe the bug**
Memory leak found here: https://github.com/broadinstitute/seqr/blob/master/seqr/utils/elasticsearch/es_search.py#L816

**get()** dictionary method gets a reference for the **list**, not copying it, and as a result **variant_1['gene_consequences']** **gene_id list** significantly increases in size wrongly. We were able to discover that getting memory issues on that line. We fixed it using **numpy** arrays in the following way:

```
consequences = np.array(variant_1['gene_consequences'].get(gene_id, []))
consequences = np.concatenate((consequences, np.array(variant_2['gene_consequences'].get(gene_id, []))))
```

Perhaps you can just use **copy** if sticking to python lists. Also, we may investigate possible performance improvements by switching completely from python lists to **numpy** soon.

**Comment by hanars** [comment]
Thanks for letting me know!

**Comment by hanars** [comment]
Also, if you do investigate numpy and find it provides any real performance boost, please let me know, or even feel free to PR your change so we can make it available for everyone

**Comment by NLSVTN** [comment]
Sure

**Comment by hanars** [comment]
Put up our own fix using regular python lists
