### ISSUE TITLE
Genotype not displaying

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1634]
**Describe the bug**
Alt genotype does not show for the pair of variants. I checked the reads, they seemed fine, so the variants are likely to be of good quality/ are real.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/variant/SV0086672_5138325911_f028471_r,SV0086673_5138328527_f028471_r

**Scope of the bug**
Case specific

**Screenshots**
<img width="1174" alt="Screen Shot 2021-01-25 at 7 26 56 PM" src="https://user-images.githubusercontent.com/37872186/105782933-52b56800-5f43-11eb-8173-d1cc3986c262.png">

**Comment by hanars** [comment]
This is so weird, because I am seeing the genotype when I went to the link you provided
<img width="1463" alt="Screen Shot 2021-01-26 at 10 37 14 AM" src="https://user-images.githubusercontent.com/24598672/105866965-8be0ed00-5fc2-11eb-988a-01f70ae360f2.png">
