### ISSUE TITLE
IGV down for a specific case

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1637]
**Describe the bug**
IGV reads not loading. We have a collaborator meeting at 5pm today. Would be great to have this data before then. If not, that's understandable. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0358_cmg_vcgs_exomes/saved_variants/variant/SV0086840_1114358834_f024813_v

**Scope of the bug**
Case specific 

**Screenshots**
<img width="1170" alt="Screen Shot 2021-01-26 at 3 32 19 PM" src="https://user-images.githubusercontent.com/37872186/105901747-cb6fff00-5feb-11eb-8641-53429586a9ce.png">

**Comment by hanars** [comment]
@mike-w-wilson @ch-kr

**Comment by ch-kr** [comment]
sorry, just got to this. readviz is loaded now
