### ISSUE TITLE
Can't reset password

### ISSUE THREAD

**Issue by ldgauthier** [broadinstitute/seqr#1644]
**Describe the bug**
I forgot my seqr password, but when I try to reset from the email link, I get the error "You have multiple authentication backends configured and therefore must provide the `backend` argument or set the `backend` attribute on the user."

It looks like you're using Oauth now, but before that I had an account with my Broad email that had a password different from my Google account (though I can't remember what it was).

**Link to page(s) where bug is occurring**
<password reset link>

**Scope of the bug**
Prevents login

**Screenshots**
![image](https://user-images.githubusercontent.com/6578548/106154610-c9be4c80-614d-11eb-8002-463f1755bdc9.png)

**Comment by hanars** [comment]
I will get this fixed, but it may not be available until early next week. In the meantime, you should be able to log in without resetting your password by logging in using google oauth instead. On the main login screen there is a "log in with google" link which will allow you to log in to your existing account without requiring you to enter the old seqr-specific password

**Comment by ldgauthier** [comment]
This isn't high priority for me, I was just trying to check out something Steph had shared.

I tried "log in with Google" and it just brought me back to the sign in page again.

**Comment by hanars** [comment]
oh actually it looks like you account was marked as inactive. I've reactivated you so you should be able to either reset the password or log in with google now

**Comment by ldgauthier** [comment]
That's fair -- I was pretty inactive.

Looks good now, thanks!
