### ISSUE TITLE
Splice AI sort bug

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr#1654]
The following error occurs when sorting by splice AI, the search succeeds when searching by xpos 

https://console.cloud.google.com/logs/query;query=error_group%2528%22COTVhMnmhbbYhAE%22%2529%0AlogName:%22stdout%22%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22seqr-cluster-prod%22%0Aresource.labels.namespace_name%3D%22default%22%0Aresource.labels.container_name%3D%22seqr-pod%22;timeRange=2021-01-29T20:24:09.382Z%2F2021-01-29T21:24:09.382Z?project=seqr-project

**Comment by hanars** [comment]
This issue is due to the fact that there are 2 active Walsh PMG indices due to the partial loading we did (1/24/2020 and 12/2/2020). The mappings for these 2 indices have different types for the `splice_ai_delta_score` field, one has float and one has double. Since this is an edge case we don't intent to support we will not make any code changes to fix the bug. Leaving this ticket open as the issue is not resolved, but it will be fixed by reloading the full project

**Comment by hanars** [comment]
@mike-w-wilson @ch-kr can we reload `CMG_Walsh_Exomes_PMG` at some point soon? We did a partial load back in December when we were struggling with loading, but theres a weird edge case bug we keep running into that would be resolved if there was only one variant index for the project

**Comment by ch-kr** [comment]
this project is reloaded now

**Comment by hanars** [comment]
confirmed that reloading fixed splice AI sort :)
