### ISSUE TITLE
not authorized to edit the internal field proband_relationship

### ISSUE THREAD

**Issue by JakeHagen** [broadinstitute/seqr#1659]
When trying to bulk edit individuals/families I get the message
`User jh3845 is not authorized to edit the internal field proband_relationship`

I also tried with a brand new install with all migrations applied.

**Comment by JakeHagen** [comment]
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/8237552/106522350-982ae580-64ad-11eb-8990-aa970273b3f1.png">

**Comment by hanars** [comment]
If you delete the "proband relationship" column from the file you are uploading it shouldl work. I will update the code so it doesn't include that in the first place

**Comment by JakeHagen** [comment]
That works. Thank you for the quick response

**Comment by hanars** [comment]
Code has been updated so this shouldn't be an issue in the future
