### ISSUE TITLE
Adding desktop IGV screenshots to Seqr

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#1669]
**Is your feature request related to a problem? Please describe.**
Browser IGV lacks some features of desktop IGV that are useful in SV analysis - namely coloring of reads based on abnormal insert size and pair orientation. 

**Describe the solution you'd like**
Ideally we'd like browser IGV to have the same read coloring features as the desktop version. In the meantime, a potential workaround: It is possible to run a script in desktop IGV to generate screenshots of defined regions. Maybe we could do this for CNVs/SVs and link to these screenshots from Seqr so it is possible to visualize SV calls to evaluate if the calls are accurate.

**Describe alternatives you've considered**
Ben has requested the changes to browser IGV

**Additional context**
This idea proposed at 2/11/21 RDG analysis meeting - Alba Sanchis Juan raised the possibility of generating the IGV screenshots, so she may have more detail on how that's done if you need it. Anne thought it might be a good idea to add the screenshots to Seqr.

**Comment by hanars** [comment]
This might be a way to show RnaSeq gene outliers (@bw2 )

**Comment by lynnpais** [comment]
IGV.js now can color by insert size. Will discuss with Hana about updating it in seqr at some point. 

@Caustint if we can view it in seqr, would you still want to add the ability to add screenshots?

**Comment by Caustint** [comment]
No, I don't think we'd need screenshots if we can color by insert size (and hopefully also pair orientation?) in seqr.

**Comment by lynnpais** [comment]
<img width="1053" alt="Screenshot 2024-04-30 at 2 32 43 PM" src="https://github.com/broadinstitute/seqr/assets/37872186/e916fdcc-c7f9-427b-bd01-e1f67b8e3774">

 It looks like IGV.js has these features. Will check with Hana about the feasibility of updating.

**Comment by hanars** [comment]
This is already an option in seqr if you click on the gear next to the IGV track you can choose what you color by, including insert size, pair orientation, or pair orientation & insert size. Will close this ticket out then!

<img width="1289" alt="Screenshot 2024-05-01 at 12 52 39 PM" src="https://github.com/broadinstitute/seqr/assets/24598672/54c6f115-6834-464d-a722-84c88684861b">
