### ISSUE TITLE
IGV error loading track data

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1672]
Reads not loading for family: OGR_SSH_T  - https://seqr.broadinstitute.org/project/R0379_ogrady_wes/saved_variants/variant/SV0087896_561521314_f026797_og

<img width="1245" alt="Screen Shot 2021-02-15 at 7 47 39 PM" src="https://user-images.githubusercontent.com/37872186/108005426-b2dd7e00-6fc6-11eb-87ae-a2b364d88e02.png">

**Comment by hanars** [comment]
@ch-kr @mike-w-wilson

**Comment by ch-kr** [comment]
this is fixed now
