### ISSUE TITLE
requirement clarification for loading genome SVs

### ISSUE THREAD

**Issue by ShifaSZ** [broadinstitute/seqr#1685]
This is associated with [#1608](https://app.zenhub.com/workspaces/seqr-workspace-5c07900a4b5806bc2bfab701/issues/broadinstitute/seqr/1608)

The requirements of the data loading are analyzed in [this document](https://docs.google.com/document/d/19jkCrvByI-Z5BAHpYCTl9doP9jrPS-OL2DOoFlBLf_0/edit).
There are some open issues for the data field mapping from genome SVs input to ElasticSearch indices:

1. The data source for `sc`, `sf`, and `sn`. See [discussions](https://docs.google.com/document/d/19jkCrvByI-Z5BAHpYCTl9doP9jrPS-OL2DOoFlBLf_0/edit?disco=AAAAH5iNkow).
For the exome SV file, they provided us SC and SF for "site count" and "site frequency", which they felt were more accurate than AF and AC as there aren't really alleles here. I'm assuming that the AC and AF in the VCF are the same as that but just wanted to confirm.
2. How many `svType`'s should we support? We support `DEL` and `DUP` for exome SVs. We found there are some other types in the genome SV sample data. Should we also support these SV types? See [discussions](https://docs.google.com/document/d/19jkCrvByI-Z5BAHpYCTl9doP9jrPS-OL2DOoFlBLf_0/edit?disco=AAAAH5iNkpI)
For exomes, all the SVs we have are DELs or DUPs. It appears with the genomes we also have translocations, insertions, and complex SVs. Do we want to bring those into seqr, or do we want to keep it to the simple DELs/DUPs? If we do bring in these other types, do we want to show the details about them (i.e. what type of complex variant or insertion something is)?
3. How to get the `geneIds` from genome SV data? See [discussions](https://docs.google.com/document/d/19jkCrvByI-Z5BAHpYCTl9doP9jrPS-OL2DOoFlBLf_0/edit?disco=AAAAH5iNkno)
In seqr we show all the genes that overlap an SV. In the file, it appears there are a lot of PROTEIN_CODING__xyz fields that list the genes with a particular predicted consequence (i.e. PROTEIN_CODING__COPY_GAIN lists the genes predicted to have a copy gain effect).  If we look at the genes in all of these lists, will that give us all genes in any way overlapped by the SV? Or could there be genes that somehow fall into none of those categories and therefore are left out? Do the NONCODING_xyz fields ever include genes? 
Relatedly, do we want to show the predicted effects of the sv on specific genes in seqr, or no?
4. Do we still need the fields of `start` and `end` for each sample in the `genotypes` records? See [discussions](https://docs.google.com/document/d/19jkCrvByI-Z5BAHpYCTl9doP9jrPS-OL2DOoFlBLf_0/edit?disco=AAAAH5iNkqM)
The way SVs are called for exomes, we can actually get slightly different coordinates for different samples on the same SV call (for example, the “same” deletion might have a start coordinate in one sample that is 4bps). I just want to confirm that this is the information we do not have for the genome calls, and not that I'm missing something.
I'm also a bit confused as to what genotype means in the context of SVs
5. About `num_exon`. For the exome calls, we have the number of exons overlapped by a given SV. Is this something we have available for genomes or no? See more [discussions](https://docs.google.com/document/d/19jkCrvByI-Z5BAHpYCTl9doP9jrPS-OL2DOoFlBLf_0/edit?disco=AAAAH5iNkn4)
6. Is the `qs` in each `genotypes` record corresponding to `CNQ` or `GQ` of each sample, or other quality scores? See [discussions](https://docs.google.com/document/d/19jkCrvByI-Z5BAHpYCTl9doP9jrPS-OL2DOoFlBLf_0/edit?disco=AAAAH5iNknw)
For exome SVs, the quailty metric we have is named QS. It appears  that for genomes we have the following quality scores: CNQ, GQ, GQ, PE_GQ, RD_GQ, and SR_GQ. Do any of these correspond to the QS score we were using? Do we want to include all or some of these in seqr, either for dispaly or filtering?
7. Do we still need the `defragged` for the `genotypes` records? See [discussions](https://docs.google.com/document/d/19jkCrvByI-Z5BAHpYCTl9doP9jrPS-OL2DOoFlBLf_0/edit?disco=AAAAH5iNkn0)
In our exome SV callset, some variants are "defragged" which is the information we display. Is this a thing that can happen with genome calls, or is there anything else similar we should know about?
8. I'm a bit confused by the relationship between the CN fields. Will there only ever be one of CN and RD_CN ? Will there always be at least one of these or not for complex variants?
9. Please suggest any required fields which are extra from those of the Exome SVs. See [discussions](https://docs.google.com/document/d/19jkCrvByI-Z5BAHpYCTl9doP9jrPS-OL2DOoFlBLf_0/edit?disco=AAAAH5iNkq0)

**Comment by ShifaSZ** [comment]
Last week for this task:
1. Met with Hana and got most of the data fields clarified. 
2. Create a [Hail notebook](https://github.com/broadinstitute/hail-elasticsearch-pipelines/blob/genome_svs_tests/genome_sv_pipeline/inspect_sv_data.ipynb) for SV data analysis. Analyzed the values of `RD_CN` for each genotype and SV type.

**Comment by larrybabb** [comment]
Waiting on Anne and Harrison for feedback.
- we can close this since we have completed our ask and if necessary open up new tickets going forward if needed.

**Comment by ShifaSZ** [comment]
All feedbacks from Anne and Harrison have been included in the [requirement document](https://docs.google.com/document/d/19jkCrvByI-Z5BAHpYCTl9doP9jrPS-OL2DOoFlBLf_0/edit#heading=h.gavh7cgcwda4).  We don't need this tick to track the requirement analysis task from now.
