### ISSUE TITLE
Project-wide search error

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1693]
**Describe the bug**
Likely a bug, affecting project wide search in the VCGS cohort

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/951afe49f8d410e0b90e723266f33a26?page=1&sort=xpos

**Scope of the bug**
Seems to be VCGS specific

**Screenshots**
<img width="1230" alt="Screen Shot 2021-03-02 at 11 25 31 AM" src="https://user-images.githubusercontent.com/37872186/109680102-2a281b80-7b4a-11eb-9c17-e56797189604.png">

**Comment by lynnpais** [comment]
I tried a similar search in the Neurodev_WES project and got another error - https://seqr.broadinstitute.org/variant_search/results/1e5d4c7b007723fc95dc69500b73a24d?page=1&sort=xpos

<img width="1235" alt="Screen Shot 2021-03-02 at 11 33 35 AM" src="https://user-images.githubusercontent.com/37872186/109681211-3f517a00-7b4b-11eb-91f3-a54a489cb067.png">

**Comment by hanars** [comment]
Hi Lynn, recessive search does not work across whole projects. You can try using the "any affected" inheritance mode, but that is the only inheritance mode available for the whole project search. 

Also, in the future, its helpful if screen shots include the full set of search criteria, not just the bottom half
