### ISSUE TITLE
Anvil download is giving an error

### ISSUE THREAD

**Issue by msingerb** [broadinstitute/seqr#1695]
**Describe the bug**
When I try and download the file from the Anvil report page for any project I am getting a ""error": "Error: To access airtable user must login with Google authentication."" error.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/api/report/anvil/R0384_rare_genomes_project_gen?loadedBefore=

**Scope of the bug**
I have tried with multiple projects and experience the same bug. 

**Screenshots**
<img width="953" alt="seqr_bug" src="https://user-images.githubusercontent.com/47390031/109705935-56519580-7b66-11eb-9e94-5fd06e76ae01.PNG">

**Comment by hanars** [comment]
This is fixed now
