### ISSUE TITLE
AppSec: Content Security Policy (CSP) Header Not Set (Due Date: May 31, 2021)

### ISSUE THREAD

**Issue by ssyms** [broadinstitute/seqr#1698]
**Describe the bug**
Content Security Policy (CSP) is an added layer of security that helps to detect and mitigate certain types of attacks, including Cross Site Scripting (XSS) and data injection attacks. These attacks are used for everything from data theft to site defacement or distribution of malware. CSP provides a set of standard HTTP headers that allow website owners to declare approved sources of content that browsers should be allowed to load on that page — covered types are JavaScript, CSS, HTML frames, fonts, images and embeddable objects such as Java applets, ActiveX, audio and video files.

Solution:
Ensure that your web server, application server, load balancer, etc. is configured to set the Content-Security-Policy header, to achieve optimal browser support: "Content-Security-Policy" for Chrome 25+, Firefox 23+ and Safari 7+, "X-Content-Security-Policy" for Firefox 4.0+ and Internet Explorer 10+, and "X-WebKit-CSP" for Chrome 14+ and Safari 6+.

References:
https://developer.mozilla.org/en-US/docs/Web/Security/CSP/Introducing_Content_Security_Policy

**Link to page(s) where bug is occurring**
https://seqr-dev.broadinstitute.org/

**Scope of the bug**
Sitewide

**Screenshots**
<img width="1234" alt="Screen Shot 2021-03-03 at 3 25 11 PM" src="https://user-images.githubusercontent.com/10914901/109886373-cf1f2300-7c34-11eb-907f-2aa7f72cf2fb.png">

**Comment by hanars** [comment]
This is live, and waiting for validation from AppSec

**Comment by ssyms** [comment]
Hi Hana, I can verify this has been fixed. Generally, we trust developers to push any fixes, and then our scanners can automatically detect when an issue has been fixed next time they run (we'll only bug you if we see an older issue that isn't being fixed within a deadline), so no need to wait for verification on bug fixes.
<img width="1244" alt="Screen Shot 2021-05-13 at 9 49 28 AM" src="https://user-images.githubusercontent.com/10914901/118158451-a2c01980-b3d0-11eb-9420-f727f9ec9e81.png">
