### ISSUE TITLE
AppSec: Cookie set without HttpOnly flag (Due Date: August 31, 2021)

### ISSUE THREAD

**Issue by ssyms** [broadinstitute/seqr#1699]
**Describe the bug**
A cookie has been set without the HttpOnly flag, which means that the cookie can be accessed by JavaScript. If a malicious script can be run on this page then the cookie will be accessible and can be transmitted to another site. If this is a session cookie then session hijacking may be possible.

Solution:
Ensure that the HttpOnly flag is set for all cookies.

References:
https://owasp.org/www-community/HttpOnly

**Link to page(s) where bug is occurring**
https://seqr-dev.broadinstitute.org/...

**Scope of the bug**
Sitewide.

**Screenshots**
<img width="1241" alt="Screen Shot 2021-03-03 at 3 29 20 PM" src="https://user-images.githubusercontent.com/10914901/109886715-61bfc200-7c35-11eb-9871-81dbb4623e57.png">

**Comment by hanars** [comment]
@ssyms this cookie is intentionally not set the HttpOnly, as it is actually used by the javascript. From the django documentation around setting this cookie to http only:
```
Designating the CSRF cookie as HttpOnly doesn’t offer any practical protection because CSRF is only to protect against cross-domain attacks. If an attacker can read the cookie via JavaScript, they’re already on the same domain as far as the browser knows, so they can do anything they like anyway. (XSS is a much bigger hole than CSRF.)

Although the setting offers little practical benefit, it’s sometimes required by security auditors.
```
https://docs.djangoproject.com/en/3.2/ref/settings/#csrf-cookie-httponly

If we change this cookie's settings, we will need to also add the csrf token to a hidden form element in the DOM or in response headers, which is not going to be any more secure than the cookie and will be more prone to errors. 

We would strongly prefer not to make this unwieldy change that would ultimately hurt our ability to follow best practices for CSRF protection in django

**Comment by hanars** [comment]
Discussed with AppSec team, and have added this issue to seqr's Plan of Action and Milestones, with the designation that we will seek ongoing risk acceptance for this vulnerability and not remediate it, as the added risk to CSRF protection that changing this cookie would entail is not worth the added security we would get
