### ISSUE TITLE
DECIPHER link update

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#1709]
**Describe the bug**
DECIPHER changed the address for the page we like to look at so clicking DECIPHER on the gene page is now taking us to a page that is a click away from the page we want. 

The link should now be (for a random gene as an example): https://decipher.sanger.ac.uk/gene/ENSG00000117394/overview/protein-genomic-info
[I think the current link goes to **protein-info** rather than **protein-genomic-info**]

**Comment by hanars** [comment]
updated!
