### ISSUE TITLE
seqr privileged access

### ISSUE THREAD

**Issue by ch-kr** [broadinstitute/seqr#1711]
I'd like to request priviledged access as I will be involved in loading data to seqr.

- I completed the IR/CP training on 3/8/21 
- I have completed a CORI check (Broad HR approved on 3/10/21)
- I have attached my signed copy of the Rules of Behavior

[seqr Rules of Behavior for Internal Users v1.0.pdf](https://github.com/broadinstitute/seqr/files/6118376/seqr.Rules.of.Behavior.for.Internal.Users.v1.0.pdf)

**Comment by hanars** [comment]
approved
