### ISSUE TITLE
Seqr privileged access

### ISSUE THREAD

**Issue by williamphu** [broadinstitute/seqr#1717]
I'd like to request privileged  access to seqr as I will be involved in loading data to seqr.

- I completed the IR/CP training on 3/8/21
- I have completed a CORI check (Broad HR approved on 3/10/21)
- I have attached my signed copy of the Rules of Behavior

[seqr Rules of Behavior for Internal Users v1.0 signed.pdf](https://github.com/broadinstitute/seqr/files/6125348/seqr.Rules.of.Behavior.for.Internal.Users.v1.0.signed.pdf)

Thanks.

**Comment by williamphu** [comment]
Sorry, not a bug

**Comment by hanars** [comment]
accepted
