### ISSUE TITLE
Privileged access to seqr

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/seqr#1718]
I'd like to request privileged access as I will be involved in loading data to seqr.

- I completed the IR/CP training on 3/8/21
- I've signed the Rules of Behavior (see attached)
- I requested a CORI check on 3/11/21
- I have attached my signed copy of the Rules of Behavior
[seqr Rules of Behavior for Internal Users v1.0_signed_michaelwilson.pdf](https://github.com/broadinstitute/seqr/files/6125888/seqr.Rules.of.Behavior.for.Internal.Users.v1.0_signed_michaelwilson.pdf)

**Comment by hanars** [comment]
approved
