### ISSUE TITLE
Edit Datasets Permission for PM team

### ISSUE THREAD

**Issue by KaylaDelano** [broadinstitute/seqr#1719]
Hi, 

I was wondering if the PM team (Myself, Stacy Mano, and Stacey Hall) could have permission to use the "Edit datasets" button on Seqr Project Pages, so that we could process IGV update/CRAM update requests. 

Thank you,
Kayla Delano

**Comment by hanars** [comment]
PMs should now be able to see an "Edit Datasets" button under the list of datasets on the project page, which will allow you to update IGV
