### ISSUE TITLE
Can't log in after AnVIL migration

### ISSUE THREAD

**Issue by MCOLeary** [broadinstitute/seqr#1723]
I am able to successfully log into seqr, but no projects are accessible to me:

![image](https://user-images.githubusercontent.com/39252949/111314966-4cd12e80-8638-11eb-9cc8-1264ad83de50.png)

**Comment by MCOLeary** [comment]
It happens only when I log in using my Google credentials. When I log in using my user name and password, it works fine.

**Comment by hanars** [comment]
@MCOLeary can you try again? It should be working now

**Comment by MCOLeary** [comment]
Yup!  Confirmed works both ways to login. Thank you!
