### ISSUE TITLE
tableName is not supplied to the FamilyTable component

### ISSUE THREAD

**Issue by NLSVTN** [broadinstitute/seqr#1732]
**Describe the bug**
There is no property `tableName` passed to the `FamilyTable` here:

https://github.com/broadinstitute/seqr/blob/master/ui/pages/Project/components/ProjectPageUI.jsx#L127

And since you generate name of the form here:

https://github.com/broadinstitute/seqr/blob/master/ui/pages/Project/components/FamilyTable/header/TableHeaderRow.jsx#L112

Form name is always **editundefinedFamiliesTable**. Minor issue, but decided to report. If you add the name in the first link, then you might need to fix the selectors:

https://github.com/broadinstitute/seqr/blob/master/ui/pages/Project/selectors.js#L152,L167

E.g. `familyTableState.familiesSearch -> (familyTableState || {}).familiesSearch`

Since `familyTableState` is going to be `undefined`

**Comment by NLSVTN** [comment]
Search on the front end may be broken though due to `familyTableState` `undefined` perhaps because there is smth wrong with the selector:

https://github.com/broadinstitute/seqr/blob/master/ui/pages/Project/selectors.js#L149

**Comment by hanars** [comment]
this has been fixed
