### ISSUE TITLE
[DUE 9/1 (target 7/6)] Deprecate username/password login for AnVIL-integrated seqr

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr#1735]
google login should be the only available login option for the Broad seqr deployment. This includes fully deprecating the login page, password management, and all project level permission management (i.e adding collaborators or managers)

Continue to support username/password option for local installs

**Comment by tommyli** [comment]
Can we please get more details on what this change means?  Some questions we have are:

* The list of deprecating items seems quite intrusive but you also mention "Continue to support username/password option for local installs".  Do local installs have much to worry?
* How will the auth table models look?  Will the `auth_group` like `<project_guid>_can_view` and `<project_guid>_can_edit` still be used?  Or will it be even more fine grained such as `<project_guid>_project_managers` `<project_guid>_analysts`, etc.?
* Will the "Collaborator" and "Manager" Access Level go?  (referring to Edit Collaborator popup).
* We have plans to integrate Seqr with our internal Okta.  How does Broad instance manage user authorisation and user roles when using OAuth2/Google Login?  OAuth2 scopes?

**Comment by hanars** [comment]
sorry for the confusion, this will only be for the Broad's seqr instance which is integrated with the AnVIL and is using that for authentication and authorization. We will continue to support local installations as they work now with no changes

**Comment by hanars** [comment]
regarding oauth2, currently what we do is create and manage users the same way we do with all other users, and when a user logs in with google oauth we check if they already have an existing seqr account and only allow them to log in if they do, and then their access permissions are controlled the same as if they had logged in with a username and password. If you set `SOCIAL_AUTH_GOOGLE_OAUTH2_CLIENT_ID` and `SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET` in your docker compose environment for seqr, that should just work
