### ISSUE TITLE
Readviz not working for HPC install

### ISSUE THREAD

**Issue by lecb** [broadinstitute/seqr#1751]
Hi Hana,

I've got seqr working, but we have an issue with readviz. I have added the .bam and .bai files to a directory on our HPC install :

![image](https://user-images.githubusercontent.com/23638585/111835799-5505c400-88ed-11eb-91ac-63a6592c4196.png)

....and successfully uploaded the mapping file (on the front end).

Individual IDs and location match up fine. I received no errors when processing the mapping file. When I try to view the reads of a variant in seqr, I see "error loading track data". 

![image](https://user-images.githubusercontent.com/23638585/111836138-bded3c00-88ed-11eb-995a-71443b2608f2.png)

I have checked the same .bam files are good by loading into IGV locally - no issues are found. Bams are aligned to the correct reference sequence.

Not sure what could be going on! 
-Ellie (Seaby)

**Comment by hanars** [comment]
Assuming you are using the docker image method of installation, you need to make sure all your readviz data is in the mounted volume. What we provide by default in the docker compose is `./data/readviz:/readviz` which means anything in a folder `./data/readviz` relative to your seqr code will be available in the app at the path `/readviz`.  You can change this to any other directory you prefer

I would start by updating the file paths in seqr via the UI, from the "add dataset" option on the project page. If it shows you an error that the file does not exist, it means you are referencing them improperly relative to where they are mounted in the docker image. If it succeeds in adding them, it means its a valid file path and IGV can show it

**Comment by eseaby** [comment]
Thanks Hana. I've tried that and I'm still getting the same issue. All bams and bai files are in the readviz directory and are correctly mapped. No issues processing mapping file.
E

**Comment by hanars** [comment]
if you shell into the seqr docker container and run the following, does it succeed:
```
python
import os
os.path.isfile(file_path) # file_path should be the exact value you used
```

**Comment by veioenza** [comment]
I believe seqr should be able to see the files now. We moved them over to the expected directory.

[root@srv03068 (PROD) dev]# **docker-compose exec seqr bash -c "ls -ld /readviz/AD022.bam"**
_-rwxr-xr-x. 1 root root 7803879891 Mar 23 09:37 /readviz/AD022.bam_

[root@srv03068 (PROD) dev]# **docker-compose exec seqr python -c "import os; print(os.path.isfile('/readviz/AD022.bam'))"**
_True_

**Comment by eseaby** [comment]
Unfortunately, the tracks still won't load. Mapping file I'm using is:

```
AD001	/readviz/AD001.bam
AD002	/readviz/AD002.bam
AD003	/readviz/AD003.bam
AD004	/readviz/AD004.bam
AD005	/readviz/AD005.bam
AD006	/readviz/AD006.bam
AD007	/readviz/AD007.bam
AD008	/readviz/AD008.bam
AD009	/readviz/AD009.bam
AD010	/readviz/AD010.bam
AD011	/readviz/AD011.bam
AD012	/readviz/AD012.bam
AD013	/readviz/AD013.bam
AD014	/readviz/AD014.bam
AD015	/readviz/AD015.bam
AD016	/readviz/AD016.bam
AD017	/readviz/AD017.bam
AD018	/readviz/AD018.bam
AD019	/readviz/AD019.bam
AD020	/readviz/AD020.bam
AD021	/readviz/AD021.bam
AD022	/readviz/AD022.bam
AD023	/readviz/AD023.bam
AD024	/readviz/AD024.bam
AD025	/readviz/AD025.bam
AD026	/readviz/AD026.bam
AD027	/readviz/AD027.bam
AD028	/readviz/AD028.bam
```

**Comment by hanars** [comment]
do you have index files? I know we use those in seqr so maybe not having them could be an issue?

**Comment by eseaby** [comment]
Yes I do, they're in the same directory.

I also noticed I can't view reads for the Hirschorn cohort in Broad seqr. I wonder if it could be an internet loading issue my end?

**Comment by hanars** [comment]
hmm maybe. Can you open up developer tools in your browser and take a screenshot of the "network" tab when you try to load IGV?

**Comment by eseaby** [comment]
Does this help?
![image](https://user-images.githubusercontent.com/78421847/112515770-7bfd4380-8d8e-11eb-939c-1cf0c0ece4f7.png)

**Comment by hanars** [comment]
could you click on each row so it shows details and take a screenshot of each? Thanks so much

**Comment by eseaby** [comment]
![image](https://user-images.githubusercontent.com/78421847/112516478-3b51fa00-8d8f-11eb-8e99-f7e4ed5ad24d.png)
![image](https://user-images.githubusercontent.com/78421847/112516542-4b69d980-8d8f-11eb-8455-67c099a01dda.png)
![image](https://user-images.githubusercontent.com/78421847/112516612-5a508c00-8d8f-11eb-9c5b-84ef753cc6af.png)
![image](https://user-images.githubusercontent.com/78421847/112516650-650b2100-8d8f-11eb-8fe9-c4307e99a452.png)

**Comment by eseaby** [comment]
Also found this... 
![image](https://user-images.githubusercontent.com/78421847/112520050-e87a4180-8d92-11eb-8417-15a4604dcc20.png)

**Comment by hanars** [comment]
hmm okay, so can you do another screenshot of the network tab showing all the requests, but this time adjust the column sizes so I can see the whole "size" value and as much of the "name" as possible

**Comment by eseaby** [comment]
![image](https://user-images.githubusercontent.com/78421847/112527286-cdabcb00-8d9a-11eb-8be4-8d80ffb82195.png)
There's only one Name this time...

**Comment by hanars** [comment]
oh sorry, I need the summary view like you did here, but also the detail view of the request/s

**Comment by eseaby** [comment]
Like this? 
![image](https://user-images.githubusercontent.com/78421847/112529386-1e242800-8d9d-11eb-8e01-f99bfa9e1531.png)

**Comment by eseaby** [comment]
or this? 
![image](https://user-images.githubusercontent.com/78421847/112529573-54fa3e00-8d9d-11eb-9b3e-a0f6acc271c8.png)

**Comment by hanars** [comment]
okay yeah this shows me what I need. So if you look in the request header, we are requesting the byte range 0-105487 and are in the response header it says the received content length is 105487 bytes, which is what you would expect. However, the size in the summary says 104kb which is a bit smaller than that, and ERR_CONTENT_LENGTH_MISMATCH is the error status you get when the actual response size and the stated size in the header don't line up, which is not supposed to happen. seqr checks the requested byte size and then reads that number of btyes from the specified file and returns a response header based on the requested bytes. I've seen this sort of thing before when we are un-gzipping content that is supposed to be gzipped - is there any chance thats whats happening here? Or maybe there is a bug for reading local igv files and seqr is not returning the correct number of bytes? I think I need to work with someone more technical on your end to help debug this

also, as a heads up, I'll be out through next Tuesday so I won't be very responsive until then

**Comment by eseaby** [comment]
Thanks Hana for all your efforts. I'll get David Hempston (my colleague) to have a read through the github. Have a good break!

**Comment by veioenza** [comment]
I tried a standard gzip of AD001.bam but that just lead to a could not find error. The requested API call does return the .bam file, 
http://seqr.soton.ac.uk/api/project/R0001_test/igv_track/%2Freadviz%2FAD001.bam

**Comment by hanars** [comment]
well gzipping doesn't work at all for bams as far as I know so I'm not sure what you are trying to do here?

**Comment by veioenza** [comment]
Any ideas on things to try?

**Comment by hanars** [comment]
do you have any crams? the first thing I'd like to try is figuring out if its a bam-specific issue. The other sanity check is to make sure the bam does open correctly in IGV desktop

**Comment by eseaby** [comment]
FYI I tried naming the index files .bam.bai and .bai and neither worked for me... 
E

**Comment by hanars** [comment]
what are they currently named and whats their directory structure?

**Comment by eseaby** [comment]
They're in the readviz directory (same one as the .bam files). For example:

`AD001.bam AD001.bai` and so on...

**Comment by bw2** [comment]
@hanars have you confirmed that local paths work (for any bam/cram)?
If yes, I add log statements to the server-side handler to make sure requests are being received & processed as expected.
These 2 lines seem questionable - doesn't a for loop still work for binary files? 
https://github.com/broadinstitute/seqr/blob/117d5ec75d1968b1cbf2b07219c4817c1deb800a/seqr/utils/file_utils.py#L48-L49

**Comment by hanars** [comment]
if someone has a small bam file they could send me that would be really helpful. I will take a look next week and confirm I can get it working for me locally

**Comment by bw2** [comment]
This is a GRCh38 bam for chr22
gs://seqr-bw/temp/CHM1_CHM13_2.chr22.bam
gs://seqr-bw/temp/CHM1_CHM13_2.chr22.bam.bai

**Comment by hanars** [comment]
heys guys, I haven't; been able to work through this yet but just wanted to update to let you know I haven't forgotten. Sorry for the delay

**Comment by hanars** [comment]
Alright, I figured out the issue. I'll get the code merged up to master sometime this week, but if you just want to introduce the fix without having to update the rest of your code to the latest version, the commit you need is here: https://github.com/broadinstitute/seqr/pull/1827/commits/9b7ecf3e4ccc1a6a805a73b16d09abbb6cdf0c71

**Comment by hanars** [comment]
for the record the fix is now in master. Let me know if you are still having issues

**Comment by eseaby** [comment]
Awesome! Thanks for fixing. I’ll ask David to load in the master and hopefully all will work beautifully 😊. Thanks so much.

**Comment by veioenza** [comment]
After updating seqr and all images, the following error appears when we try to do a variant search. The ref data hasn't been changed by us.

`relation "reference_data_genecopynumbersensitivity" does not exist LINE 1: ...erence_data_genecopynumbersensitivity"."pTS" FROM "reference... ^`

**Comment by veioenza** [comment]
The only other errors I'm seeing in the seqr logs are,

`RequestsDependencyWarning: urllib3 (1.26.4) or chardet (3.0.4) doesn't match a supported version!`

`UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.`

**Comment by hanars** [comment]
whenever you update the seqr code and see errors like that, you need to run `./manage.py migrate` and `./manage.py migrate --database=reference_data` to make sure that your database schema mat ches seqrs updates schema

**Comment by eseaby** [comment]
Thanks Hana. We've implemented the migration, but sadly we still can't view reads. We just get a blank box that doesn't expand. 

![image](https://user-images.githubusercontent.com/78421847/119111965-7ed98500-ba1b-11eb-80e8-7e2249a9aadc.png)

**Comment by hanars** [comment]
ah, yes this is sadly an unrelated bug that is also affecting our production seqr for about a week:
https://github.com/broadinstitute/seqr/issues/1849

I should have this fix for this merged today

**Comment by hanars** [comment]
okay the fix for IGV has been merged to master

**Comment by eseaby** [comment]
Everything works beautifully! Thanks so much.
