### ISSUE TITLE
Compound het search - which variant should be more restrictive? and documentation

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#1754]
**Is your feature request related to a problem? Please describe.**
I can't remember how I'm supposed to set up a compound het search where I want to make one variant very deleterious (likely SV or pLoF) and the other variant less restrictive. Is it the first or second variant that should have restrictive features? 

**Describe the solution you'd like**
And can you add some kind of direction in seqr so it's clear how users should be doing this (and so I can look there to remind me when I forget again).

**Comment by hanars** [comment]
So if you are doing a compound het only search, order does not matter. The difference is if you are doing a recessive search which will return hom alt variants and compound hets, the first "annotations" filter will be applied to the hom alt search so you probably want to use the more restrictive filter for that

Leaving this issue open to track the work for adding a better description text

**Comment by hanars** [comment]
I've added a detailed description to the "annotation secondary" panel
