### ISSUE TITLE
Feature request: Bulk Edit Individual function should be able to edit all Individual level data fields

### ISSUE THREAD

**Issue by jxchong** [broadinstitute/seqr#1759]
Currently the "Bulk Edit Individual" function only works with a limited set of fields. The rest of the fields in seqr have to be entered manually, even if they would otherwise be stored/entered from the same input csv file.

Ideally the function would be able to edit all individual-level data fields/properties and be able to edit the individual-level case review status.

**Comment by hanars** [comment]
"all individual-level data fields/properties" is a little to vague to implement. Please add an explicit list of which fields you would like to be supported

**Comment by ctmarvin** [comment]
Hi Hana, 

Here's a list of current individual level data fields that don't function with the "Bulk Edit Individual" tool. Adding functionality to bulk import these would significantly cut down on manual data entry time.

- Age
- Age of onset
- Consanguinity
- Other Affected Relatives
- Expected Mode of Inheritance
- Assisted Reproduction
- Maternal Ancestry
- Paternal Ancestry
- Pre-discovery OMIM disorders
- Previously Tested Genes
- Candidate Genes
- Case Review Status

Also see suggested fields in #1758 as these would be individual level and preferably capable of being bulk edited as well.

Ideally, if custom fields are implemented this could be expanded to allow for bulk editing of any data field linked to an individual using the "Bulk Edit Individual" function.

Colby

**Comment by hanars** [comment]
this actually overlaps an existing ticket we have (https://github.com/broadinstitute/seqr/issues/673#issuecomment-768506870) so I will update that tivcket to include these fields as well and am going to close this ticket out to avoid duplication

**Comment by hanars** [comment]
Just updating here that all of these fields are now supported through the bulk upload option
