### ISSUE TITLE
Log Out Warning 

### ISSUE THREAD

**Issue by gvannoy** [broadinstitute/seqr#1764]
A log out warning would be appreciated with the updated frequency of being automatically logged out. This would avoid losing notes that are in free text fields when the auto log out coincides with saving new notes. 

A pop-up warning that indicated "You will be logged out in ___ (5/10/15) minutes" would allow in process work to be saved. This warning would need to be visible when working in any of the case review or analysis Notes fields.

**Comment by hanars** [comment]
@gvannoy is this still an issue?

**Comment by gvannoy** [comment]
Hi Hana, nope I haven't encountered this in a while! Thank you for checking
