### ISSUE TITLE
Privileged access to seqr

### ISSUE THREAD

**Issue by larrybabb** [broadinstitute/seqr#1767]
I'd like to request privileged access as I will be involved in managing and working with seqr development.

I completed the IR/CP training on 3/8/21
I've signed the Rules of Behavior (see attached)
I completed a CORI check on 3/10/21
I have attached my signed copy of the Rules of Behavior (url
[seqr Rules of Behavior for Internal Users v1.0-signed-lbabb.pdf](https://github.com/broadinstitute/seqr/files/6223897/seqr.Rules.of.Behavior.for.Internal.Users.v1.0-signed-lbabb.pdf)

**Comment by hanars** [comment]
approved
