### ISSUE TITLE
Update gnomAD links

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#1771]
**Is your feature request related to a problem? Please describe.**
I think we should make it more clear where the gnomAD data comes from for seqr

![image](https://user-images.githubusercontent.com/10407888/113068108-a46caf80-918b-11eb-827a-a11cddc79d16.png)

What about relabeling the gnomAD part as:
gnomAD v2 exomes
gnomAD v3 genomes

I also wondered about making gnomAD v2 the hyperlink to the gnomAD v2 gene page and the gnomAD v3 term the hyperlink to the v3 gene page. And removing the gnomAD link by the gene name. Even though it's a gene level search, I often am looking at it around thinking of the population frequency data. 

If you wanted to add a link in the gnomAD gene link place, I'd love to have the DECIPHER link that is on the gene page be on the variant page. I and the analysts look at this page a lot. 

If you want me to separate these into multiple tickets, I can do that. It's just something I've been thinking about.

**Comment by hanars** [comment]
one ticket for this is fine. Can you just add examples of the gnomad v2 and gnomad v2 links you are talking about?

**Comment by anneodonnell** [comment]
This is different from the screenshot about as I don't remember what variant that is. 

Now looking at this variant: https://seqr.broadinstitute.org/variant_search/variant/15-85693356-A-G/family/F018297_199

![image](https://user-images.githubusercontent.com/10407888/113196762-d9334200-9231-11eb-8f26-14c0780cb071.png)

gnomAD exomes [0.000013](https://gnomad.broadinstitute.org/variant/15-86236587-A-G) Hom=0

Should become: 
[gnomAD v2](https://gnomad.broadinstitute.org/gene/ENSG00000170776) exomes [0.000013](https://gnomad.broadinstitute.org/variant/15-86236587-A-G) Hom=0

gnomAD genomes 0.0000318 Hom=0
Should become: 
[gnomAD v3](https://gnomad.broadinstitute.org/gene/ENSG00000170776?dataset=gnomad_r3) genomes [0.0000318](https://gnomad.broadinstitute.org/variant/15-85693356-A-G?dataset=gnomad_r3) Hom=0

I think I got those right.

**Comment by hanars** [comment]
@anneodonnell just want to confirm that you like how it looks with the links
<img width="278" alt="Screen Shot 2021-04-09 at 5 18 22 PM" src="https://user-images.githubusercontent.com/24598672/114241737-adae0700-9957-11eb-82f3-8fa23083904e.png">

**Comment by anneodonnell** [comment]
Because the link goes to gnomAD v2 and not just gnomAD v2 exomes, I’d only have the “gnomAD v2” part be the link and have exomes not link. Same for “gnomAD v3”.

**Comment by hanars** [comment]
this has been implemented
