### ISSUE TITLE
Ensure demo projects keep working

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#1777]
**Is your feature request related to a problem? Please describe.**
Maintain access to demo projects

**Describe the solution you'd like**
I discussed with Heidi and a few others - sharing thoughts/suggestions. 

We understand the need to register emails to add to demo projects for a course. We would like to keep the multiple demo projects as they are with a plan to add people to projects after they register their email with AnVIL. 

But we did like your suggestion of having one demo project viewable to all seqr users. This should be one of the genome demo genome projects with RGP samples but we would like to have the samples renamed/relabeled something more generic - probably easier to make a new project for this. I haven't asked anyone to do this but Sam and Stacy are aware of this general plan.

**Comment by hanars** [comment]
to clarify about the project that is viewable to all users, should that be all users who do not have any other projects, or truly ALL users?

**Comment by anneodonnell** [comment]
I checked with @sambaxter and we both agree that we think it would be good to have on every project, whether people have data or not. It would be a place collaborators could train new team members. But we still want to rename the samples for more data protection. And it would only be one of the genome demo projects.

**Comment by hanars** [comment]
blocked on having a test project set up and ready

**Comment by anneodonnell** [comment]
OK, we picked families for the demo project that everyone will have access to. We'd like to rename these, maybe DEMO_1, etc (unless Sam has a different suggestion for the name). I'd like them in this order. 
DEMO_1 - RGP_683
DEMO_2 - RGP_692
DEMO_3 - RGP_426
DEMO_4 - RGP_48
DEMO_5 - RGP_664

**Comment by sambaxter** [comment]
These names look good to me

**Comment by hanars** [comment]
Awesome! getting the samples renamed and the data loaded are jobs for the PM team and data loading team, who I don
t think use github to track their work, so you should probably reach out directly to them

**Comment by hanars** [comment]
@anneodonnell just pinging to see where we are on this - we were planning on deprecating all non-google access login on July 6, which would mean that the demo project accounts would lose access. We would still be able to add specific user accounts to those projects, but I haven't started working on making the globally available project described in this ticket. Are we 
a) ready for me to start working on that project this week 
b) okay with losing the demo project logins before the new project is ready 
c) need to push back the date for removing google login switchover
