### ISSUE TITLE
Adding "analyst high priority" to saved search 

### ISSUE THREAD

**Issue by sambaxter** [broadinstitute/seqr#1783]
**Is your feature request related to a problem? Please describe.**
I need to capture a list (and will in the future) of all the analyst high priority tagged variants in seqr but the "analyst high priority" tag is not one of the options in the saved variants search

**Describe the solution you'd like**
Please add the "analyst high priority" tag to the saved variant search https://seqr.broadinstitute.org/summary_data/saved_variants

**Additional context**
Anne needs this list for a publication relatively soon

**Comment by anneodonnell** [comment]
It not super urgent but it would be handy to have it by the end of April so there is time to analyze the data while we still have Emily E around. But if there are more urgent things, we can wait.

**Comment by hanars** [comment]
this option has been added
