### ISSUE TITLE
Handle 404 errors for missing images

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr#1785]
Recent changes to the exception handling middleware are causing missing images to return as 500 errors in seqr. These should be 404 warnings

**Comment by ShifaSZ** [comment]
Missing what kind of images? I tried missing pedigree images. They still look okay.

**Comment by hanars** [comment]
most of them yes but there are occasionally broken ones that don't exist. These used to and should return 404 errors, but right now are returning 500 errors which alert me as an error every time
