### ISSUE TITLE
Add new family-level tag

### ISSUE THREAD

**Issue by MCOLeary** [broadinstitute/seqr#1794]
Discussed with Anne and would like to add a new family-level tag across projects to be called "External Solve".

**Comment by hanars** [comment]
duplicated by https://github.com/broadinstitute/seqr-private/issues/990 so will track the work on that issue

**Comment by MCOLeary** [comment]
@Hana Snow ***@***.***> Grace V pointed out to me today that
we need a family level analysis status option of "External Solve" and not a
"tag".

I can't open the other ticket you linked to, so I wanted to make sure I
clarified the ask.
----------------------------------------
Melanie O'Leary, MS, CGC®
Rare Genomes Project
Broad Institute of Harvard and MIT
Project Phone: 617-714-7395
Direct Phone: 617-714-7502

**Comment by hanars** [comment]
yes, that is reflected in the other ticket

**Comment by MCOLeary** [comment]
Great, thanks!

**Comment by hanars** [comment]
since you can't see the other ticket, I figured I'd update here that its done

**Comment by MCOLeary** [comment]
Awesome, thanks!

>
