### ISSUE TITLE
Pulling incorrect gene name for autogenerated matchmaker emails

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#1798]
**Describe the bug**
If you email a match that has multiple gene submissions, the automated email sometimes pulls the wrong gene name for the subject line. The example below is interesting because it pulls the correct gene name for the body text but the incorrect gene for the subject. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F031029_rgp_1532/matchmaker_exchange - automated email for MAN_1768-01_D1 

**Scope of the bug**
Only happens if generating an email for a match with multiple genes submitted. Can be fixed manually if caught in time. 

**Screenshots**
![image](https://user-images.githubusercontent.com/44381119/115059753-f82e0700-9eb4-11eb-861f-8a1535cb6dbd.png)

**Comment by hanars** [comment]
this has been fixed
