### ISSUE TITLE
Error when trying to edit RGP project contact info

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#1799]
**Describe the bug**
Every matchmaker submission autogenerates contact info for the project. For RGP, this is bloated with older users and email addresses no longer active. When I try to edit the project I receive the error below. We would like to be able to edit this freely when needed, and the current contact emails for RGP should be matchmaker@broadinstitute.org and caustint@broadinstitute.org. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/project_page

**Scope of the bug**
I have not noticed it with other projects. 

**Screenshots**
What it looks like now: 
![image](https://user-images.githubusercontent.com/44381119/115067202-91155000-9ebe-11eb-99c7-c920f64b86c2.png)
Error when I try to edit it: 
![image](https://user-images.githubusercontent.com/44381119/115065417-1cd9ad00-9ebc-11eb-9962-f714d47a3838.png)

**Comment by hanars** [comment]
this is fixed now
