### ISSUE TITLE
Duplicates appearing when using multiple indices: issue with sort

### ISSUE THREAD

**Issue by NLSVTN** [broadinstitute/seqr#1802]
(We asked previously about the issue we identified in the email)

I investigated it deeper and figured out that there might be really an issue with the way variants are merged and duplicates eliminated when we have multiple indices that can contain the same variants. What happens is the following: 

Elasticsearch returns 'raw_hit.meta.sort' for each hit and it is based upon position only, not allelle, e.g.: 2178686113. Then sorted() python function sorts it based upon this number:

https://github.com/broadinstitute/seqr/blob/master/seqr/utils/elasticsearch/es_search.py#L540

So, for instance, 2-178686113-ATTTTTTTTTTTT-A' and  '2-178686113-A-ATT' have the same sort number - 2178686113. 
 
Since the results of different indices are just concatenated and then sorted by 'raw_hit.meta.sort' number, the order (allele part) gets lost which leads to variants not being adjacent and so duplicates remain.

Now, we could have tried using some function from pandas/numpy to do deduplication instead but unfortunately it might not be possible due to pagination of the results when, the same variant can come out, say, in 1-100 and in 101-200 results, but deduplication would work only for a single page of results. Or do you think its fine?

**Comment by hanars** [comment]
The solution to this will be to add a secondary/ tertiary sort on the variant ID itself to keep variants grouped. So instead of sorting with `[<freq/pathpogentcity/ec>, xpos]` we should sort on `[<freq/pathpogentcity/ec>, xpos, variantId]`

**Comment by NLSVTN** [comment]
Ok, got it.

**Comment by NLSVTN** [comment]
So, we changed the following line:

https://github.com/broadinstitute/seqr/blob/master/seqr/utils/elasticsearch/es_search.py#L540

to:

`new_results = sorted(new_results, key=lambda variant: (variant['_sort'], variant['variantId']))`

It seems to be working fine, but we just want to make sure thats enough.

**Comment by hanars** [comment]
I've added a tertiary "variant id" sort to the latest seqr release which should fix this issue
