### ISSUE TITLE
Authentication issues

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1803]
**Describe the bug**
Being logged out and requiring to log back in every 10-15 minutes. 

**Link to page(s) where bug is occurring**
Any page in seqr, across multiple projects, for more than 1 analyst

**Scope of the bug**
Seqr-wide

**Screenshots**
NA

**Comment by hanars** [comment]
@lynnpais @stephditroia @gvannoy have any of you noticed if this has gotten better since Tuesday? Or is it still an issue?

**Comment by lynnpais** [comment]
I used seqr on Thursday and it seemed to be good. Thank you!

Lynn

**Comment by stephditroia** [comment]
I spent 3-4hrs in seqr Wednesday with no problems. Today I've been on seqr since 9:30am (~3.5hrs) and was logged out once. I would say it's fixed or significantly better. :)

**Comment by gvannoy** [comment]
Same - it hasn't been an issue for me yesterday or today. Thanks!

**Comment by hanars** [comment]
awesome! I'm going to consider this ticket resolved then, and if this becomes a problem again we can always create a new ticket to track that
