### ISSUE TITLE
better support for mulit-index projects - Switching pages changes the number of variants on variant search page

### ISSUE THREAD

**Issue by NLSVTN** [broadinstitute/seqr#1808]
On variant search page when we navigate from first page to the second, then to third, and so on the number of variants changes. We have multiple indices in the project. We feel like it might confuse users. Is there any ideas on how it could be improved?

**Comment by hanars** [comment]
multiple indices in the project is not well supported in seqr. The best way to fix this is to reload the whole project into a single index. I will leave this open as a feature request

**Comment by lynnpais** [comment]
Resolved by Hail backend
