### ISSUE TITLE
Add searching and displaying for genome structural variants

### ISSUE THREAD

**Issue by ShifaSZ** [broadinstitute/seqr#1811]
Add genome SV supports for more searching options and data displaying as below:

New variant search options:
1. Annotations: under structural variants, add other sv_types
2. Frequency: add gnomAD SV

New SV data displays:
1. saved variant: gnomAD ID and link
2. sorted transcripts: show SV consequences
3. show CPX intervals, sv_type_details
4. show/hide prediction

**Comment by ShifaSZ** [comment]
Some thoughts about the development approach: the task can be done with multiple PRs. Each PR includes one search option or displaying feature. And, I will create a container branch and all the PRs will be merged into that branch after being reviewed. After all these PRs are merged, I will create a final PR to merge the container branch to `dev`.

**Comment by hanars** [comment]
that approach makes sense to me. In that case, you should create subtasks for this issue to correspond to each PR. Then you will move this issue with that final PR

**Comment by ShifaSZ** [comment]
Last week:
1. Created a PR for annotation search filters.
2. Set up a local Elasticsearch by cloning (_reindex) an SNP index from the prod Elasticsearch server to the local one.

This week:
1. Continue on updating the frequency search filters

**Comment by ShifaSZ** [comment]
Last week:
1. Closed the PRs for annotation and frequency search filter UI
2. Started updating the searching backend for genome SV data fields

This week:
1. Update the variant UI to display the genome SV data

**Comment by ShifaSZ** [comment]
Last week:
1. Was resolving the review issues for the variant display PR

This week:
1. Update the gnomAD link generation from gnomAD_SV_ID
