### ISSUE TITLE
Add genome SV annotation filters to the variant search

### ISSUE THREAD

**Issue by ShifaSZ** [broadinstitute/seqr#1832]
### Pre-conditions:
1. Load genome SVs into the ElasticSearch DB
2. Add the new ElasticSearch index to the project by `Edit Dataset` on the project page

### UI updates:
Existing annotation filters:
![image.png](https://images.zenhubusercontent.com/5ffdb04378d44f83fbbca86f/09e9409d-636b-48b9-9af5-661af8cb9e31)

Add new structural variant types under `VEP_GROUP_SV`. The new sv_types include BND (Translocation), CNV (Copy Number Polymorphism), CPX (Complex SV), CTX (Reciprocal chromosomal translocation), INS (Insertion), INV (Inversion). There are two existing sy_types: DEL(Deletion) and DUP (Duplication).

Expected annotation filters for the project with genome SV samples:
![image.png](https://images.zenhubusercontent.com/5ffdb04378d44f83fbbca86f/25138cf0-bbd9-41b9-ad16-bf03db374c84)

### Search updates with new SV annotation filters:
Update the ElasticSearch backend to support the new filters

**Comment by hanars** [comment]
as an FYI, this should require no backend changes, providing you correctly map the values on the front end to the values on the backend (i.e. Complex should have a value of CPX etc)
