### ISSUE TITLE
Add structural variant frequency filters for variant search

### ISSUE THREAD

**Issue by ShifaSZ** [broadinstitute/seqr#1833]
Add one scrollbar for setting gnomAD SV frequency.

Current frequency filters:
![image.png](https://images.zenhubusercontent.com/5ffdb04378d44f83fbbca86f/57d50437-fa69-4947-b0b5-e6defe9e6ef2)

Expected frequency filters (preliminary):
![image](https://user-images.githubusercontent.com/33550059/117045690-ca7ef580-acdd-11eb-9b2c-7624efcce5c3.png)

**Comment by hanars** [comment]
you should put the gnomad SV frequency on the top line and move the "this callset" and "Sv callset" filters to the second line.

**Comment by ShifaSZ** [comment]
I updated the layout for the frequency filters. Another question: Does the gnomAD SV frequency also need the `AC` and `H/H` under it?

**Comment by hanars** [comment]
looks good. I might center or right align the filters on the second row, but you can play with that while you are implementing it and see what looks best/ what is easiest to do

And thats a good question but no, for gnomad SVs we don't have the AC or H/H data so we can't filter on it and therefore don't want to add those options.
