### ISSUE TITLE
New staff user

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#1838]
Need to set up our new analyst, Ikeoluwa Osei-Owusu (ioseiowu@broadinstitute.org), as a staff user. Saw a mention on Slack that the new method for this was to open a ticket, sorry if that's no longer the case!

**Comment by hanars** [comment]
I have added her as an analyst to seqr. In the future, new analysts should register with terra and log in to seqr first, and then I will grant them analyst permissions.
