### ISSUE TITLE
Incorrect X chromosome deletion in males from several families 

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#1844]
A deletion involving almost the whole X chromosome is being called by seqr in a male in this family: 
https://seqr.broadinstitute.org/project/R0408_cmg_perth_wes/saved_variants/family/F029313_uwa_lai16137

![image](https://user-images.githubusercontent.com/84086816/117996182-ee5ebe80-b30f-11eb-82ee-d21cd688e73b.png)

This has been discussed with Anne O'Donnell and we think that most likely there has been a sex mix up and this sample has somewhat been analyzed as a female hence looking like a X was missing. The 2MB on Xp that is not reported to be included in the deletion by Seqr might be an artefact/a region difficult to sequence in the genome. 

The same deletion is called in males from several other families (example: https://seqr.broadinstitute.org/project/R0528_cmg_engle_wes/saved_variants/family/F029149_eng_tf)

**Comment by hanars** [comment]
This is not bug in the seqr software, but rather an issue with a sample mixup or a caller error. Please reach out to the project management or analysis teams for help resolving this issue
