### ISSUE TITLE
NO CALL showing for all SVs

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#1847]
**Describe the bug**
All exome gCNV calls are being displayed as NO CALL. This is happening in both saved variants and new searches and across multiple projects. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/d4dd7fb3c82265968b890600cba29e03?page=1&sort=xpos

**Screenshots**
![image](https://user-images.githubusercontent.com/44381119/118169708-40c6da80-b3f7-11eb-8c6f-aef003403c1f.png)

**Comment by hanars** [comment]
gentotypes are showing again for all Svs
