### ISSUE TITLE
GTEx expression not displaying on gene page

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#1848]
**Describe the bug**
The gene page is no longer displaying GTEx data. 

**Link to page(s) where bug is occurring**
Example search:
https://seqr.broadinstitute.org/variant_search/results/577b2fe25e5e8cb0b283b896c1eb1a8e?page=1&sort=xpos

**Scope of the bug**
Seen in both the Walsh project and RGP project. Haven't checked others. 

**Screenshots**
![image](https://user-images.githubusercontent.com/44381119/118170832-951e8a00-b3f8-11eb-94c0-ca711032893f.png)

**Comment by hanars** [comment]
gtex is working again
