### ISSUE TITLE
Unexpected EOF homo_sapiens_vep_99_GRCh37.tar.gz 

### ISSUE THREAD

**Issue by veioenza** [broadinstitute/seqr#1855]
When trying to download the homo sapiens ref data I get an EOF error. 

Using the command as given in the local install documentation.
`curl -L http://ftp.ensembl.org/pub/release-99/variation/indexed_vep_cache/homo_sapiens_vep_99_GRCh37.tar.gz | tar xzf - & `

Command
```
gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

kind regards,
David H

**Comment by hanars** [comment]
hmm thats odd @bw2 have you ever encountered this sort of error before?

**Comment by bw2** [comment]
To rule out transient Ensembl server or network issues, I would try this again, maybe using wget instead of curl.

**Comment by veioenza** [comment]
It looks like a network issue somewhere. It is back again now so I will start the downloads.
