### ISSUE TITLE
'tagGuids' error

### ISSUE THREAD

**Issue by JenPartlow** [broadinstitute/seqr#1856]
Good Afternoon, 
We receive this error: " type object got multiple values for keyword argument 'tagGuids' " when doing a variant search or just clicking on saved variants bar in MC-700 in Walsh Lab Exomes.

Thanks in advance for your help
Jen

**Comment by Jenniferneil** [comment]
Commenting here to link my current Github account to this .... I didn't realize I had a new one with my new name :) 
Jen Neil 

(previously JenPartlow)

**Comment by hanars** [comment]
this is fixed now

**Comment by Jenniferneil** [comment]
Thanks!!
