### ISSUE TITLE
seqr search fails with splice_ai sort

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1857]
**Describe the bug**
Unable to retrieve variant in the callset

**Link to page(s) where bug is occurring**
Variant I am trying to look up: https://seqr.broadinstitute.org/project/R0358_cmg_vcgs_exomes/saved_variants/variant/SV0091472_2034927140_f030723_v 
Error: 
https://seqr.broadinstitute.org/variant_search/results/796b05d0c4071f1d14a4d2996a033111?page=1&sort=splice_ai

**Scope of the bug**
Case specific 

**Screenshots**
<img width="1244" alt="Screen Shot 2021-05-18 at 10 23 09 AM" src="https://user-images.githubusercontent.com/37872186/118668777-29a33680-b7c3-11eb-9d63-25b2ae64d3b3.png">

**Comment by hanars** [comment]
This appears to be a re-emergence of this issue related to sorting across project by splice AI: https://github.com/broadinstitute/seqr/issues/1654

As a workaround, changing the sort to anything else (xpos is easiest probably) fixes the search:
https://seqr.broadinstitute.org/variant_search/results/796b05d0c4071f1d14a4d2996a033111?page=1&sort=xpos

Keeping the issue open to track work to fix

**Comment by hanars** [comment]
splice ai sort is fixed now
