### ISSUE TITLE
[DUE 6/25] Adding "discovery notes" section to AnVIL metadata and to seqr

### ISSUE THREAD

**Issue by sambaxter** [broadinstitute/seqr#1864]
**Is your feature request related to a problem? Please describe.**
We need a place in seqr and in the anvil reports and sample metadata reports to add notes on discoveries. The seqr field should only be accessible by CMG staff members but some tasks available to everyone, like making an MNV or complex SV could trigger structured notes being added to this section.

**Describe the solution you'd like**
Add a "Discovery notes" field in seqr, which is only accessible to staff.  Any notes in this field will be exported a new column in the AnVIL discovery report at the end of the report ([see new data model here](https://docs.google.com/spreadsheets/d/1GAaFWimwZHRzOE2st9YSI7oDIW6rfpAfc07JzJR4pb8/edit#gid=1620774226)) and to the sample metadata report ([see new data model here](https://docs.google.com/spreadsheets/d/1kmb7N9x_ElDfo03O4XHGfWnbD8scTigm6321urV8Nfw/edit#gid=1794279131)) 

**Describe alternatives you've considered**
If adding a new field is not possible we can start with just adding the columns to the reports and create logic for how variously other actions in seqr could trigger notes being added.  If there are multiple notes being added you can just concatenate them.

**Additional context**
Update should be added to https://seqr.broadinstitute.org/report/anvil and  https://seqr.broadinstitute.org/report/sample_metadata. If it is possible to have this completed by the last week of June that would allow us to use this for our "final" CMG submissions

**Comment by hanars** [comment]
for first pass will be doing the alternative approach of 
> adding the columns to the reports and create logic for how variously other actions in seqr could trigger notes being added. If there are multiple notes being added you can just concatenate them.

**Comment by hanars** [comment]
to add the column to the sample metatdata UI, add "discovery_notes" to the VARIANT_ANVIL_COLUMNS constant

**Comment by hanars** [comment]
discovery notes have been added for MNVs and complex SVs. Considering this work done for now, if in the future we need other triggers for additional discovery notes those should be requested in a separate ticket
