### ISSUE TITLE
[DUE 6/25] Logic generating "discovery note" for MNV and SV

### ISSUE THREAD

**Issue by sambaxter** [broadinstitute/seqr#1865]
**Is your feature request related to a problem? Please describe.**
We need to indicate in the AnVIL reports and sample metadata reports when a set of variants are part of a MNV or complex SV.  

**Describe the solution you'd like**
When someone uses the [MNV or complex SV functionality](https://github.com/broadinstitute/seqr-private/issues/971) in seqr we would like it to trigger a note being generated to the discovery notes field requested in [this ticket](https://github.com/broadinstitute/seqr/issues/1864). The message would ideally say "The following variants are part of the multinucleotide variant, [INSERT MANUAL MNV NAME] _(or complex structural variant - depending on which was added)_: [LIST LINKED VARIANTS] " And then list the variants separated by a comma. We can use the genomic coordinates for both MNVs and SVs. 

**Describe alternatives you've considered**
We had originally reported only the MNV or SV variant name in reports and had a complaint that computationally that was useless. 

**Additional context**
If it is possible to have this completed by the last week of June that would allow us to use this for our "final" CMG submissions

**Comment by hanars** [comment]
For example, for RGP_312 https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F021070_rgp_312/Multi-Nucleotide%20Variant

All the variants in this family in the discovery page would have the following discovery_note:
"The following variants are part of the multinucleotide variant 19-1912632-GC-TT: 19-1912633-G-T, 19-1912634-C-T"

MNVs/ complex SVs are rep[resented in the database as having more than 2 variants that are tagged together in the same genes. For variants with more than 2 variants tagged together, if any of them have svType they are Complex SVs, otherwise they are MNVs

**Comment by hanars** [comment]
In _process_saved_variants in report_api.py, if the length of comp_het_variants is > 2, then do not change the inheritance_models but do add a discovery_note to the variant. For all other variants, discovery_notes is blank. Then in _parse_anvil_family_saved_variant make sure to add discovery_note to the parsed variant as well.

**Comment by hanars** [comment]
Note that we are going with the alternative solution of generating this in the report and not storing it as a separate field

**Comment by hanars** [comment]
Example complex SV: https://seqr.broadinstitute.org/project/R0474_cmg_sherr_exomes/saved_variants/family/F024890_she_2810/Multi-Nucleotide%20Variant

discovery_note should say "The following variants are part of the complex structural variant CNV[DUP:chr6:157148527-160158816+DUP:chr6:148519450-152369712+DEL:chr6:160991630-169781698]: DUP:6:157148527-160158816, DUP:6:148519450-152369712, DEL:6:160991630-169781698"
Use the svName field for the name of the parent complex SV, and then the svName if it exists or <type>:<chrom>:<start>-<end> for the name of the nested complex variants

**Comment by ShifaSZ** [comment]
> In _process_saved_variants in report_api.py, if the length of comp_het_variants is > 2, then do not change the inheritance_models but do add a discovery_note to the variant. For all other variants, discovery_notes is blank. Then in _parse_anvil_family_saved_variant make sure to add discovery_note to the parsed variant as well.

Regarding the logic for generating the discovery_note, I still have a question:
When `comp_het_variants > 2`, no change to the `inheritance_models` and add a `discovery_note`. In this case, do we still need to update the `gene_ids` using the IDs from `main_transcript` or `transcripts`?

**Comment by hanars** [comment]
> When `comp_het_variants > 2`, no change to the `inheritance_models` and add a `discovery_note`. In this case, do we still need to update the `gene_ids` using the IDs from `main_transcript` or `transcripts`?

yes

**Comment by ShifaSZ** [comment]
> discovery_note should say "The following variants are part of the complex structural variant CNV[DUP:chr6:157148527-160158816+DUP:chr6:148519450-152369712+DEL:chr6:160991630-169781698]: DUP:6:157148527-160158816, DUP:6:148519450-152369712, DEL:6:160991630-169781698"
> Use the svName field for the name of the parent complex SV, and then the svName if it exists or ::- for the name of the nested complex variants

How can I get the nested complex variants? It seems that I can them from the name of the parent complex SV. But I not sure if it is the right way to get those names.

**Comment by hanars** [comment]
> > discovery_note should say "The following variants are part of the complex structural variant CNV[DUP:chr6:157148527-160158816+DUP:chr6:148519450-152369712+DEL:chr6:160991630-169781698]: DUP:6:157148527-160158816, DUP:6:148519450-152369712, DEL:6:160991630-169781698"
> > Use the svName field for the name of the parent complex SV, and then the svName if it exists or ::- for the name of the nested complex variants
> 
> How can I get the names of nested complex variants? It seems that I can them from the names of the parent complex SV. But I'm not sure if it is the right way to get those names.

No, you cannot get the from the name of the parent. The parent name is user-generated text which in this case happens to include the nested variants but you can't rely on that. You get the names from the svType, chrom, pos, and end from the nested variant themselves. For MNVs you get the names from the chrom, pos, ref, and alt of the nested variants

**Comment by larrybabb** [comment]
@hanars and @ShifaSZ to check in wednesday June 23 to assure that we can get this done by 6/25. Don't stress out.

**Comment by hanars** [comment]
These discovery notes have been added to the anvil metadata download and the sample metadata page
