### ISSUE TITLE
[DUE 6/25] Update to AnVIL metadata format

### ISSUE THREAD

**Issue by sambaxter** [broadinstitute/seqr#1866]
**Is your feature request related to a problem? Please describe.**
Need to remove a column from the AnVIL subject table due to another change in the metadata data model.  

**Describe the solution you'd like**
The AnVIL team has asked us to  remove the column "dbgap_submission" from our subject tables ([see new datamodel with column removed in row six](https://docs.google.com/spreadsheets/d/1GAaFWimwZHRzOE2st9YSI7oDIW6rfpAfc07JzJR4pb8/edit#gid=1620774226)).  Will also need to renumber headers of the subsequent column headers. 

**Describe alternatives you've considered**
We can manually remove the column for now and just ignore the fact it skips a number in the header columns since they still show up in the right order, but I am sure someone will eventually ask why our column headers skip a number so it will be easier to do this programatically. 

**Additional context**
If it is possible to have this completed by the last week of June that would allow us to use this for our "final" CMG submissions.

**Comment by hanars** [comment]
this has been done
