### ISSUE TITLE
Genotype display

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1881]
**Describe the bug**
Parental data was added to the project and hence I reanalyzed the case. I removed the old Review tag on PAX7 and added a new one after performing a new search with the new parental data. However, in the saved variants page, the genotype of the parents are not being updated. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/variant/SV0089373_118634414_f030189_rg

**Scope of the bug**
Across projects, noticed in two other RGP cases. 

**Screenshots**
<img width="1203" alt="Screen Shot 2021-05-24 at 1 46 53 PM" src="https://user-images.githubusercontent.com/37872186/119387139-83f63880-bc96-11eb-93e7-364d74cfd794.png">

**Comment by hanars** [comment]
this is fixed
