### ISSUE TITLE
Add link to Family Page from Saved Variant(s) page

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#1884]
It would be great if I could jump directly to the family page from a Saved Variant page like https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F026337_rgp_677
instead of having to first click over to the Family Search page. 
This would make it easier to check the pedigree and other info.

**Comment by hanars** [comment]
the family ID is already a link to the family page. Also, hovering over the family ID shows you the pedigree image and other family details
