### ISSUE TITLE
Seqr stopped working in Safari and Firefox.  Only works in Chrome.  

### ISSUE THREAD

**Issue by therealtytanium** [broadinstitute/seqr#1888]
**Describe the bug**
Always been able to use Safari and Firefox to use Seqr.  Now unable to - 'white screen of death' instead of login page.
Resent having to download Chrome just to use Seqr.  I don't use Chrome for anything else.  Is there some setting that I can change within Safari?  Or within Seqr?

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/

**Scope of the bug**
Local instance of Seqr still works on Safari and Firefox.  I am aware that Seqr is optimised for Chrome, but it should still work in other browsers surely?

**Screenshots**

Broad CMG Seqr
![image](https://user-images.githubusercontent.com/84891380/119766734-e77fa080-bef8-11eb-9a77-2ea77b1e32d5.png)

Local instance Seqr
![image](https://user-images.githubusercontent.com/84891380/119766767-f5cdbc80-bef8-11eb-9f4d-4d79905cce4d.png)

**Comment by hanars** [comment]
Seqr is only supported in chrome, not just optimized for it. That means if there are issues in other browsers we don't fix them. We are a very small dev team and frankly do not have the bandwidth to add additional browser suppprt
