### ISSUE TITLE
Error loading data

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1889]
**Describe the bug**
IGV data not loading 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0365_cmg_scott_exomes/saved_variants/variant/SV0018429_1746878731_r0365_cmg

**Scope of the bug**
Across the project

**Screenshots**
<img width="1223" alt="Screen Shot 2021-05-27 at 9 13 54 AM" src="https://user-images.githubusercontent.com/37872186/119832383-1d5a6000-becc-11eb-8ec2-368a38844f3e.png">

**Comment by hanars** [comment]
The new protocol when IGV is not loading is to report it in the analyst_pmops slack channel, not make github issues
