### ISSUE TITLE
Unable to retrieve variants in the callset

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1890]
**Describe the bug**
Unable to retrieve variants in the CMG callset. In MTEH008, the MYH1 gene variant is also in 4 other individuals, but the seqr link seems to be down.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0294_myoseq_v20/saved_variants/variant/SV0019510_1710419542_r0294_myo

**Scope of the bug**
Case specific, but Gabriel also reported having similar issues I think.

**Screenshots**
<img width="1269" alt="Screen Shot 2021-05-27 at 12 18 47 PM" src="https://user-images.githubusercontent.com/37872186/119861781-c497c100-bee5-11eb-83d7-316d61cb3a01.png">

**Comment by hanars** [comment]
this is fixed for all project s now
