### ISSUE TITLE
Custom feature implementation to integrate with PanelApp

### ISSUE THREAD

**Issue by tommyli** [broadinstitute/seqr#1891]
We are planning to implement integration with [PanelApp AU](https://panelapp.agha.umccr.org/), a custom feature for
Seqr.  PanelApp is a service allowing researchers and experts curate and share Gene Lists.  These gene lists are
accessible via a REST API.

We've listed a few things to consider:

* Should implementation be full client side logic since PanelApp already provide an API?  It seems overkill otherwise,
  especially for the simple use case of browsing panels and importing genes from panels.
* However, more sophisticated use cases would require server side integration.  E.g. searching for panels by gene names.
* Server side integration is also more extensible.  E.g. a researcher have already asked for exclusion of incidental
  finding genes (presumably some list like [Incidentalome](https://panelapp.agha.umccr.org/panels/126/) from PanelApp AU
  or from [ACMG Recommendations for Reporting of Incidental Findings in Clinical Exome and Genome
  Sequencing](https://www.ncbi.nlm.nih.gov/clinvar/docs/acmg/)) when doing Location search.
* Server side implementation is also feasible because:
  * PanelApp provides APIs to download all genes per sample
  * Data is not that large, only hundreds of panels (257 as of writing)
  * Data growth rate is not that large
  * Data staleness is not an issue because these lists are **manually curated** and maintained by community in the first
    place
* There should be some Django config setting to feature toggle this (e.g. setting values are `None`, `PanelAppAustralia`,
  `PanelAppGenomicsEngland`).
* The obvious page to show this feature is in the [Gene Lists
  page](https://seqr.broadinstitute.org/summary_data/gene_lists).
* Is your team going to implement something similar?

We would also like to use this as an opportunity for us to collaborate closely with your team.  Implementing this as a
feature toggle that's off by default should be low risk but it is our plan to have this feature eventually submitted for
PR.  Would your team consider accepting a feature like this?

**Comment by hanars** [comment]
Overall, sounds very interesting. I would have to reach out to our team to see if this is something we would be interested in taking live here at the Broad, but I think either way we would be open to taking this in to our main branch as a feature that is off by default, as I agree there is little harm there. And even if the Broad doesn't plan to use it, it could certainly be valuable to other groups with their own installations. 

We currently have no plans to work on anything like this, so you should feel free to go ahead without worrying about duplicating efforts. 

I think thats fine to do a fully client-side integration, just be aware we've added CSP headers to seqr that would need to be updated to allow any new cross domain requests on the client side. I think doing everything client side is net easier if you decide to go with a basic integration.

If you go with a more complex integration and want to do server-side code, you should look at the code we've implemented for kibana to create a passthrough proxy on the server side.

Given the data size and stability, maybe it would make more sense to add panel app as a table to the reference data database? We already create manage commands to allow periodically updating those tables via cron job, so maybe that would be a way to have all the panel app data in seqr without getting to stale but also without adding lots of API calls to the code.

Ultimately, I'm not the most clear on what an integration looks like, so its hard for me to make recommendations on implementation
