### ISSUE TITLE
Error message when doing seqr searches with revel/MPC sort

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#1892]
I have an error message (Request error, see screen shot below) when using any search option in seqr since May 27 and I am unable to view the search results. This issue happens in multiple seqr projects. Refreshing the page does not help. Logging out and back does not help either. I use google chrome and I tried to clear my cache on google chrome and it did not change anything. The other analysts do not seem to have this issue. 

https://seqr.broadinstitute.org/variant_search/results/bf7d5edae20c578686f2617d34b2db05?page=1&sort=revel

![Screen Shot 2021-05-27 at 9 52 34 AM](https://user-images.githubusercontent.com/84086816/120356238-1a97aa80-c2d2-11eb-96a4-19427a4e2533.png)

**Comment by hanars** [comment]
This appears to be a sort-specific issue - changing the sort to almost anything else works
https://seqr.broadinstitute.org/variant_search/results/bf7d5edae20c578686f2617d34b2db05?page=1&sort=xpos

The only sorts that have issues are revel and MPC

**Comment by hanars** [comment]
search is fixed for all sorts now, including the original link with revel
