### ISSUE TITLE
Error message loading IGV in some seqr projects

### ISSUE THREAD

**Issue by KaylaDelano** [broadinstitute/seqr#1900]
**Describe the bug**
When trying to load IGV into seqr, I received an error message saying "Error accessing: (CRAM filename)"; this first happened when uploading IGV from a closed workspace in the Jueppner project, and later after trying to update CRAMs from an AnVIL workspace for the Engle project. I've attached a screenshot of the first error message. Between these, I successfully uploaded IGV to the Thaker WES project. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0550_cmg_jueppner_wgs/project_page
https://seqr.broadinstitute.org/project/R0528_cmg_engle_wes/project_page

**Scope of the bug**
First happened in the Jueppner WGS project, then in Engle WES project. I was able to successfully load IGV in the Thaker WES project. 

**Screenshots**
<img width="612" alt="Screen Shot 2021-06-03 at 10 36 25 AM" src="https://user-images.githubusercontent.com/74615418/120824209-35faf380-c526-11eb-8358-b0ab4981e049.png">

This is a screenshot of the error message I received.

**Comment by hanars** [comment]
please attach or otherwise send me the file you are using

**Comment by KaylaDelano** [comment]
[CMG_Engle_WES_IGVUpdate.xlsx](https://github.com/broadinstitute/seqr/files/6599790/CMG_Engle_WES_IGVUpdate.xlsx)
[Jueppner_IGV_June2021.xlsx](https://github.com/broadinstitute/seqr/files/6599794/Jueppner_IGV_June2021.xlsx)


Here are both!

**Comment by hanars** [comment]
The seqr service account does not appear to have access to either the engle or jueppner buckets. I spot checked a couple of other projects and seqr does appear to still have access to them so this is probably an issue with the way these buckets were set up and not with seqr

**Comment by KaylaDelano** [comment]
Okay, thank you! I'll see about fixing the access in the google bucket.

**Comment by hanars** [comment]
Hi Kayla, is this still an issue?

**Comment by KaylaDelano** [comment]
Hi @hanars , yes it is, we are trying to figure out what happened with these specific buckets that access was no longer available, but this hasn't come up with any other workspaces or seqr projects.
