### ISSUE TITLE
MME match page - date view

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#1902]
**Is your feature request related to a problem? Please describe.**
On MME match page, we can't see the full date (specifically the year) so it's hard to tell which matches are new. I can make it show up if I shrink the text but then it's too small to present on Zoom calls. 
![image](https://user-images.githubusercontent.com/10407888/121224317-6dcfa700-c856-11eb-9abb-216e13027dc3.png)

**Describe the solution you'd like**
Could the date column be wider so the whole date shows up. We don't use the match ID that much so that column could be narrower. 

**Describe alternatives you've considered**
Change the format of the date to list YYYY/MM/DD to at least see which matches returned in the most recent year.

**Comment by hanars** [comment]
this has been fixed
