### ISSUE TITLE
IGV viewer slowness

### ISSUE THREAD

**Issue by SimonLi5601** [broadinstitute/seqr#1905]
I was wondering if you are experiencing IGV viewer slowness on your end in general? Comparing to the Backbone Js and Django template version, it takes much longer to show all the tracks after clicking show read. And it also takes the same amount of time if you clicks another variant. I noticed you refactored this part of codes recently for different feature, but does that help the loading speed? Or you didn't have this issue at all.
Thanks!

**Comment by hanars** [comment]
I'm not really sure what is meant by the "backbone js" version of IGV is in seqr - we switched to react back in 2018 I think so if there was a switch off of backbone then its far too removed for me to know if there is a slowdown or not all these years later. We didn't asses IGV performance in the latest changes we made since they were not intended to change performance, so I can't comment on if that helped or not other than to say I didn't notice any dramatic change

**Comment by SimonLi5601** [comment]
I just would like to give a feedback on this one in case it might be helpful. We figured out actually the default refgene track slows down the display in our environment since seqr is using a convenient way for genome reference, e.g. genome: "hg19" in igv options. We define the reference directly and changed the URL for refgene track to solve the problem.
Slow(default):
"url": "https://s3.amazonaws.com/igv.org.genomes/hg38/ncbiRefGene.txt.gz",

Fast: "url": "https://s3.amazonaws.com/igv.org.genomes/hg38/refGene.sorted.txt.gz",
         "indexURL": "https://s3.amazonaws.com/igv.org.genomes/hg38/refGene.sorted.txt.gz.tbi",
 
Related document,
https://github.com/igvteam/igv.js/wiki/Reference-Genome

**Comment by hanars** [comment]
awesome! Reopening the ticket so we can make this change on our end (unless its an easy fix for you guys to PR to us)

**Comment by SimonLi5601** [comment]
Probably you should evaluate if this is necessary in you environment. I can't reproduce this issue in a plain html or a simple React app when I was using the same reference genome. The reason why it is slow still kind of unknown to me. Probably the seqr variant search results display page is already using a lot memory that contributes to the slowness. As a side note, we found that it would speed up the page if we disable some components in the variant search results if there are a lot of families, e..g the short cut to add "Review" or "Excluded" tags.

**Comment by hanars** [comment]
we also see better performance with the sorted file, so we've updated to use it
