### ISSUE TITLE
MNV export logic not working as expected

### ISSUE THREAD

**Issue by sambaxter** [broadinstitute/seqr#1944]
**Describe the bug**
Related to ticket https://github.com/broadinstitute/seqr/issues/1865.  There are a couple behaviors that are not occurring as expected.  

- The manually created variant should not be exported as part of the variant list, only the seqr generated variants should be in the export.  So in the example below 1912634-C-T, 19-1912633-G-T should be in the AnVIL report but 19-1912632-GC-TT should not.
- The message for the MNVs (The following variants are part of the multinucleotide variant, [INSERT MANUAL MNV NAME]) the Manual name should include the c. and p. (if available) as well as the G. In this example below the message should read "The following variants are part of the multinucleotide variant 19-1912632-GC-TT (c.586_587delinsTT, p.Ala196Leu): 19-1912634-C-T, 19-1912633-G-T"

**Link to page(s) where bug is occurring**
Example: https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F021070_rgp_312
[Rare Genomes Project_Genomes_PI_Discovery.xlsx](https://github.com/broadinstitute/seqr/files/6810472/Rare.Genomes.Project_Genomes_PI_Discovery.xlsx)

**Comment by hanars** [comment]
The logic has been updated. Let me know if you have any more issues!
