### ISSUE TITLE
Allow arbitrary files to be uploaded / attached to family notes

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#195]

**Comment by anneodonnell** [comment]
I can see how this could be misused but I think if we had a warning at the time of attachment saying no names, identifiers, or PHI should be on any uploads. The types of upload I was thinking about are important PDFs for relevant papers and at the moment would be handy to be able to add screenshots from the TGG viewer for CNV and RNAseq data - though as these hopefully eventually get built into seqr, there would be less need for them. We'd probably want to put some file size limit so people don't store large in seqr. I also know you have a lot of development work going on so this isn't essential.

**Comment by hanars** [comment]
Duplicated by https://github.com/broadinstitute/seqr/issues/1760
