### ISSUE TITLE
CMG_gCNV: warning flag 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1961]
CMG_gCNV updates: Need warning flag (Yellow triangle) when CN and call type do not match up.

**Comment by ShifaSZ** [comment]
@lynnpais What does it mean by `CN and call type do not match up`? Any background information will help. Thanks.

**Comment by hanars** [comment]
Show a yellow warning triangle (where 'Defragged' and 'Potential UPD' warning is shown) if the following criteria is met:
- if svType is DUP and copy number is < 2
- if svType is DEL and copy number is > 2
