### ISSUE TITLE
IGV performance

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr#1962]
SVs and RNASeq IGV are much slower in seqr than in TGG viewer. Possible that switching that switching to API instead of cat-ing file will fix this

**Comment by ShifaSZ** [comment]
I found that most of the performance differences between the seqr IGV and TGG viewer come from the two reference tracks. The lengths of the data parsing time for the reference track data are variant with different track options. For the Refseq track, I tried the sorted data, and with/without indexURL, the timing is shown as below:
```
Unsorted, without indexURL:
igv.js:15083 Onload /api/igv_genomes/org.genomes/hg38/ncbiRefGene.txt.gz
igv.js:15384 Decompressing...
igv.js:15387 Decompressed. Time: 0.5499999523162842s
igv.js:31536 Parsing lines...
igv.js:31577 Parsed total 166923 lines. Time: 19.58300018310547s

Changed to refGene.sorted.txt.gz
igv.js:15083 Onload /api/igv_genomes/org.genomes/hg38/refGene.sorted.txt.gz
igv.js:15384 Decompressing...
igv.js:15387 Decompressed. Time: 1.1619999408721924s
igv.js:31536 Parsing lines...
igv.js:31577 Parsed total 85561 lines. Time: 9.070000171661377s

Added indexURL for Refseq:
igv.js:15083 Onload /api/igv_genomes/org.genomes/hg38/refGene.sorted.txt.gz?someRandomSeed=0.x71gii150kg
igv.js:31536 Parsing lines...
igv.js:31577 Parsed total 3600 lines. Time: 0.559999942779541s
```

The timing for the Gencode is:
```
igv.js:15083 Onload https://storage.googleapis.com/storage/v1/b/seqr-reference-data/o/GRCh38%2Fgencode%2Fgencode.v27.annotation.sorted.gtf.gz?alt=media&someRandomSeed=0.sqnpb100jib
igv.js:31536 Parsing lines...
igv.js:31577 Parsed total 116223 lines. Time: 20.7020001411438s
```
While TGG viewer only takes less than a second to parse the Gencode data. There could be problems with our Gencode data. We should re-generate the data. Without indexURL option for the Gencode track, IGV takes more than 10 minutes to decompress and parse the downloaded data. It consumes quite a lot of computation time and that's why the page becomes stuck.

**Comment by hanars** [comment]
Okay, so it seems like switching to use the sorted and indexed refseq is a great fix we should do!

For gencode, we never "generated" that track, we just copied it from somewhere. What track is the TGG viewer using?

**Comment by hanars** [comment]
It looks like theres also an IGV hosted genocde track we could try instead of our google storage one - `/api/igv_genomes/org.genomes/hg38/annotations/gencode.v28.basic.annotation.sorted.gtf.gz`

**Comment by ShifaSZ** [comment]
The Genecode reference you provided has a little better performance but not as good as TGG viewer one.
```

igv.js:15083 Onload /api/igv_genomes/org.genomes/hg38/annotations/gencode.v28.basic.annotation.sorted.gtf.gz?someRandomSeed=0.y9fgt250a9
igv.js:31536 Parsing lines...
igv.js:31577 Parsed total 75195 lines. Time: 13.045000076293945s
```
It is weird that the Gencode data that TGG viewer using doesn't work for seqr. It says some transcripts are missing.

**Comment by hanars** [comment]
@bw2 any idea why we would be struggling to use the gencode track thats in TGG viewer?

**Comment by larrybabb** [comment]
per @hanars spend no more than a day on this then move onto the pipeline update since its a high priority.

**Comment by ShifaSZ** [comment]
@hanars @bw2 I found that the file `gencode_v32_knownGene.sorted.txt.gz` which TGG viewer uses is in `refgene` format, not the `gtf` format that seqr currently use. After I changed the file and the file format option, seqr IGV works in the same way as TGG viewer.

**Comment by hanars** [comment]
One thing is, seqr uses a condensed view of the genes that takes up very minimal vertical space, similar to refseq, while TGG viewer uses this expanded view that takes up a lot of vertical space. Is this something we can toggle in seqr? Or if we use the TGG viewer's reference do we have to use the expanded view?

**Comment by bw2** [comment]
Glad you found the issue. I set default IGV track params here: 
https://github.com/broadinstitute/tgg-viewer/blob/master/src/redux/selectors.js#L323-L336

**Comment by bw2** [comment]
The viewer itself is created here:
https://github.com/broadinstitute/tgg-viewer/blob/master/src/components/IGV.jsx#L180

**Comment by ShifaSZ** [comment]
> One thing is, seqr uses a condensed view of the genes that takes up very minimal vertical space, similar to refseq, while TGG viewer uses this expanded view that takes up a lot of vertical space. Is this something we can toggle in seqr? Or if we use the TGG viewer's reference do we have to use the expanded view?

Yes, we could. There are some options for the track as two examples below:
```
      height: 350,
      displayMode: 'EXPANDED',
```
But I don't think we should expand the display for seqr.

**Comment by hanars** [comment]
> But I don't think we should expand the display for seqr.

Agreed, I just wanted to confirm that the changes we would make to using this track would not get us that expanded view by default. But it sounds like our current track options will cause this to display the way it was before, just much faster, so we should be all set to use this

**Comment by ShifaSZ** [comment]
@bw2 I could use `gencode_v32_knownGene.sorted.txt.gz`  for GCRh38 now. What's your suggestion for GCRh37? Thanks.

**Comment by hanars** [comment]
updated reference URLs, so closing this
