### ISSUE TITLE
CMG_gCNV: Replace/explain the more obscure SV type names 

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#1963]
Replace the more obscure SV types with a longer descriptive name (i.e. BND and INS:ME:ALU). 
If not enough space, can use hover-over explanations. 

![image](https://user-images.githubusercontent.com/44381119/125954759-a9d4f69b-1ef4-4a36-9f07-b9569851437f.png)

**Comment by ShifaSZ** [comment]
I'm going to update the annotation part of the variant display to something like the below figures. If there are SVTYPE_details available, then the details can be shown in the hove-over.  Let me know if you have any comments @hanars @stephditroia.
![image](https://user-images.githubusercontent.com/33550059/127691993-07284568-1a3d-44aa-ac79-d52e56cc085f.png)
![image](https://user-images.githubusercontent.com/33550059/127691401-90046cd8-5805-4a8b-ad52-a573ce683e14.png)
![image](https://user-images.githubusercontent.com/33550059/127691710-f0a59294-fd8c-454c-9c3d-b27804438bfc.png)

**Comment by stephditroia** [comment]
This looks great. Thanks, Shifa!

**Comment by stephditroia** [comment]
Will the CN# still be displayed for dups and dels or is this info being removed for all SVs?

**Comment by hanars** [comment]
> Will the CN# still be displayed for dups and dels or is this info being removed for all SVs?

CN will still be sown where it exists, this just happens to be an example with no dups/dels

**Comment by stephditroia** [comment]
Good to know about CN.  

One more comment - I ran these screenshots by the analysts and they loved the new SV type and alt/ref genotype displays but noted that the SV size display seems a little wonky. It would be ideal if we could switch units (ie 50bp instead of 0.0500kb; 1.2Mb instead of 1260kb). If that is too complicated, we could at least get rid of the unnecessary trailing zeros (0.05) and the scientific notation takes up more space than writing out 1260.

**Comment by hanars** [comment]
thats not really related to this ticket - can you make a separate ticket for it?

**Comment by stephditroia** [comment]
Sounds good. Ticket made.
