### ISSUE TITLE
Filtering on SV functional annotations 

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#1964]
As discussed in the July 15 meeting:
Add SV functional annotations section in Annotations dropdown menu in seqr so we can filter using these.
Ex: LOF, copy gain, UTR, promoters, translocations, Partial DUP, intronic, no gene association

**Comment by ShifaSZ** [comment]
The filters we are going to support include `LOF`, `DUP_LOF`, `COPY_GAIN`, `DUP_PARTIAL`, `MSV_EXON_OVR`, `INTRONIC`, `INV_SPAN`, `UTR`, `INTERGENIC`, `PROMOTER`, and `NO_GENE`. 
For `NO_GENE`, we could add an annotation to `transcriptConsequenceTerms` to indicate there is no gene associated. We could also update the variant search to get the variants with no gene. I prefer to update the loading pipeline. What do you think? @hanars

**Comment by hanars** [comment]
I think we just don't want to add a filter for NO_GENE and do not allow people to search for that explicitly
