### ISSUE TITLE
SV quality score

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#1965]
Need to hook up QS for SVs called from genome (0-1000). 
Use the same slider as exome gCNV. 

Need to update the ? hover text to say:
The quality score (QS) represents the quality of a Structural Variant call. Recommended SV-QS cutoffs for filtering:
1) on Exome data: duplication >=50, deletion>=100 and homozygous deletion>=400 
2) on Genome data, any SV > 10

**Comment by ShifaSZ** [comment]
`min_qs` is a quality filter for genome SVs only. Should we exclude it for SNP or exome search?

**Comment by hanars** [comment]
There is a qs filter for exome SVs already, we should just also show/ apply that for genome SVs. In theory, once the qs data is in the ES index there shouldn't need to be any code changes to get the filter to work. All the seqr changes for this ticket are the update for the hover text
