### ISSUE TITLE
seqr log out issue

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#1972]
**Describe the bug**
Being logged out of seqr automatically once-twice a day. Not as frequent as the last time I put in a ticket, but I do lose progress/ notes that are not saved.

**Comment by hanars** [comment]
Daily log in is required for our compliance certification, so unless it's consistently more than that theres nothing I can do. You can try explicitly logging out and then logging back in when you start your day, so you don't get a surprise log out in the middle of the day
