### ISSUE TITLE
Update topmed 

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#1980]
**Is your feature request related to a problem? Please describe.**
We determined at the 7/22/2021 analysis meeting that the topmed data in seqr is from Nov 2018. Hana and Mike suggest updating to the latest release.

**Comment by hanars** [comment]
blocked on loading pipeline https://github.com/broadinstitute/hail-elasticsearch-pipelines/issues/266

**Comment by hanars** [comment]
Updated in the latest pipeline release. All projects loaded going forward will have updated topmed
