### ISSUE TITLE
Strange error message for project-wide recessive searches

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#1981]
**Is your feature request related to a problem? Please describe.**
Project-wide or cross-project recessive and compound heterozygous searches return `TransportError: 431 - '' - no detail`. We need a more descriptive error message. 

![image](https://user-images.githubusercontent.com/44381119/126704125-a87f68da-c62e-4fa0-b0b8-4a83b4aa4733.png)

**Comment by hanars** [comment]
I'm having trouble replicating this - can you provide a link?

**Comment by stephditroia** [comment]
https://seqr.broadinstitute.org/variant_search/results/74a3c4ad72125b6bb8664262aa53ceb0?page=1&sort=position

**Comment by hanars** [comment]
this is no longer returning a weird message and is instead returning a 504 Timeout error, which is what we expect for cohort recessive searches
