### ISSUE TITLE
Support project-wide or cross-project recessive searches on single genes

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#1982]
**Is your feature request related to a problem? Please describe.**
Right now we cannot run a project-wide or cross-project compound het search. We would like to support these searches for short gene lists or a single gene. 

**Describe alternatives you've considered**
An alternative solution is to allow sorting by family in an 'any affected' project-wide search. This is already a ticket.

**Comment by hanars** [comment]
It appears that project wide/ cross project recessive search in a single gene already works! I did the standard recessive restrictive search in the whole RGP project in TTN and it completed just fine, and I also did that same search in all the "Eye" projects which is across about a dozen projects and that all worked fine.

The search does fail if I try to search across ALL the CMG projects as once, but I'm not sure how necessary that is. Is there some minimum number of projects it needs to work for as part of "cross project" search? Or are there any specific recessive single gene searches you know of that are failing?

**Comment by hanars** [comment]
Actually, it appears that its not the number of projects in a search that causes this error, but rather the number of families in a project. So a recessive search in Myoseq_v20 all by itself does not work, as it appears the current magic cutoff for inheritance based search is 1024 families that have data loaded. This should not be too hard to fix, which will allow inheritance based search to work across all cohorts (in a single gene)

**Comment by hanars** [comment]
I have fixed the issue for searching across large cohorts like Myoseq, but still have some issues with searching across many projects, so leaving this open to track that work

**Comment by hanars** [comment]
As an update, the too_long_frame_exception issue is fixed. I as able to do a recessive search in a single gene across the neuromuscular cohorts - the first time I did it it returned a 504 timeout error, but after waiting 5 minutes and trying again it worked.
When searching across the entire CMG, search is still not working - elasticsearch itself is running into timeout limits for performing that search. Leaving this ticket open to track getting that search to work

**Comment by hanars** [comment]
I am now able to perform a standard recessive search in a single gene across all the CMG projects. It did fail the first time with a 504 error and then succeeded when I refreshed the page 5 minutes later. Given that success, I am going to close out this issue. If you find specific genes/ sets of projects where search is not working, please open a new ticket with the details of that issue
