### ISSUE TITLE
Require descriptions for new gene lists

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#1983]
**Is your feature request related to a problem? Please describe.**
There are several public gene lists without descriptions. We would like to make descriptions mandatory when creating a new gene list. The hover-over can provide specific guidance on what to enter in the description if needed. 

**Additional context**
![image](https://user-images.githubusercontent.com/44381119/126708651-9c266949-ca68-4a59-b96c-b8d426c2e33d.png)

**Comment by hanars** [comment]
added
