### ISSUE TITLE
Change variant search results sort by options

### ISSUE THREAD

**Issue by Ikeoluwa-O-O** [broadinstitute/seqr#1989]
**Is your feature request related to a problem? Please describe.**
As discussed at the July 22, 2021 RDG Analysis Meeting, we would like to add "callset AF" to the “Sort By” options on the variant search page. In addition, we would like to remove the "ExAC Frequency" as a sort by option, and instead add "gnomAD Exomes Frequency".

**Comment by hanars** [comment]
sorts have been updated
