### ISSUE TITLE
Adding hom counts for callset 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2005]
**Describe the solution you'd like**
Request to add hom counts for callset, similar to hom counts for gnomAD data.

**Comment by hanars** [comment]
Blocked on loading pipeline change https://github.com/broadinstitute/hail-elasticsearch-pipelines/issues/259

**Comment by hanars** [comment]
Pipeline work completed, data in pipeline test index

**Comment by hanars** [comment]
Data in `r0652_pipeline_test__wgs__grch38__variants__v02__vcfv32__20221110`, field to use is `homozygote_count`

**Comment by ShifaSZ** [comment]
So we need to add `hom=xxx` to the `This Callset` line in the population column according to the data field `homozygote_count`. Is that right?

**Comment by ShifaSZ** [comment]
Should we also add a search condition for the new `homozygote_count` field?

**Comment by hanars** [comment]
> Should we also add a search condition for the new `homozygote_count` field?

yes, should behave like gnomad with the "H/H" input

**Comment by hanars** [comment]
Homozygote count has been added to seqr. As projects are reloaded, this will automatically be added to them
