### ISSUE TITLE
Unable to upload a pedigree file?

### ISSUE THREAD

**Issue by vdauwera** [broadinstitute/seqr#2016]
I'm trying to launch Seqr on some data from a Terra (AnVIL) workspace. I have a joint-called VCF in my workspace bucket and I made a pedigree table based on the template TSV provided. The file upload looks like it completes successfully (?) but when I submit the form I get the error "Field(s) "uploadedFileId" are required".

See screenshots.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/create_project_from_workspace/marketing-experiments/test-seqr

**Scope of the bug**
Not sure how to evaluate the scope -- I can't get past this initial page.

<img width="1111" alt="Screen Shot 2021-08-02 at 2 44 21 PM" src="https://user-images.githubusercontent.com/2748435/127909467-e78402ce-00fe-4a22-988b-e9abaaac6cd4.png">

<img width="1116" alt="Screen Shot 2021-08-02 at 2 44 34 PM" src="https://user-images.githubusercontent.com/2748435/127909464-9ac64314-d714-4ed0-ab54-8bdaa33768e6.png">

**Comment by hanars** [comment]
Can you try filling out the whole form, then uploading the file after the rest of the form is filled out, and then hitting submit?

**Comment by vdauwera** [comment]
I just tried it now, same result

**Comment by vdauwera** [comment]
This is my tsv (added the .txt extension so github would accept it)

[individuals_test.tsv.txt](https://github.com/broadinstitute/seqr/files/6919623/individuals_test.tsv.txt)

**Comment by hanars** [comment]
so the issue seems to be that you have not accepted seqr's privacy policy and terms of service. If you go to directly to seqr.broadinstitute.org  and log in it will redirect you to the page where you can accept those terms, and then once you have done that you can go back and Leaving this ticket open to track the work to fix this so in the future there will be a better user experience for this case

**Comment by vdauwera** [comment]
Ohhh that makes sense -- I thought the Terra login somehow transferred (like with Single Cell Portal). Thanks so much for getting this figured out so quickly! I look forward to actually trying the Seqr functionality.

**Comment by hanars** [comment]
I've fixed the underlying issue so this shouldn't happen in the future
