### ISSUE TITLE
Request to update in silico tool - FATHMM

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2027]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
Update to FATHMM_MKL which includes annotations for noncoding variants - http://fathmm.biocompute.org.uk/fathmmMKL.htm

**Describe alternatives you've considered**
NA

**Additional context**
Discussed with Mike and the analysis team and thought it best to update.

**Comment by hanars** [comment]
Created https://github.com/broadinstitute/hail-elasticsearch-pipelines/issues/264 to track the work to get the data into the pipeline. Showing in seqr is blocked on the pipeline work

**Comment by hanars** [comment]
@lynnpais just to clarify we should replace the current fathmm with the new fathmm MKL, or we should show both?

**Comment by lynnpais** [comment]
Yes, replace the current fathmm with the new fathmm MKL which is more
comprehensive.

**Comment by hanars** [comment]
Note to self: possible values have changed, from ['D', 'T'] to ['D', 'N']

**Comment by hanars** [comment]
We also get VEST4 and MutPred as part of the corresponding dbnsfp update, so we will ad those to the UI as well as part of this work. These are all available in ES as well as the v3 pipeline, so add support for both. In the v2 pipeline MutPred is in the form `"0.387"` and  VEST4 is `".;0.015;0.015;.;0.014"` or `"0.491"`. In v3 these are single floats, for vest is parsed by `field.split(';').find(lambda p: p != '.')`

**Comment by lynnpais** [comment]
Analysts would like to discuss this further. Will try to share an update later this week.

**Comment by hanars** [comment]
FATHMM's source has been updated and vest and MutPred added
