### ISSUE TITLE
Improve SV size display for gCNV data 

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#2028]
When reviewing the gCNV SV type and alt/ref genotype displays, the analysts noticed that the SV size display seems a little wonky for variant interpretation. It would be ideal if we could switch units where appropriate (ie 50bp instead of 0.0500kb; 1.2Mb instead of 1260kb). 

If switching units is too complicated, could we clean up the display by removing unnecessary trailing zeros (0.05kb instead of 0.0500kb) and removing scientific notation when the notation takes up more space than writing it out (1260kb instead of 1.26e+3kb)?

50bp instead of 0.0500kb example:
![image](https://user-images.githubusercontent.com/44381119/128231489-7aaddabd-084c-43d6-a829-54e430f29b9a.png)

1.2Mb instead of 1.26e+3kb
![image](https://user-images.githubusercontent.com/44381119/128231466-a17f5d82-44c3-480a-aca4-82eef344345b.png)

241Mb instead of 2.41e+5kb
![image](https://user-images.githubusercontent.com/44381119/128231627-8fc73917-35db-4fa5-9a34-0a2424622f4d.png)

**Comment by hanars** [comment]
implemented the first approach, changing units based on size
