### ISSUE TITLE
seqr IGV "color by insert size" feature 

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2039]
Is it possible to add the option of "Color alignments by insert size and pair orientation" in browser seqr IGV to show reads with discordant insert sizes in red (see attached picture as an example). 
This is a default IGV feature (that is available in desktop version of IGV but is not functional in seqr IGV):  https://software.broadinstitute.org/software/igv/interpreting_insert_size

![3386_splitReads](https://user-images.githubusercontent.com/84086816/128767789-d86afe7e-c1fe-4e4e-ab65-3710ca2cedc2.png)

**Comment by hanars** [comment]
@bw2 do you happen to know if thats supported in browser IGV?

**Comment by Glemiret** [comment]
Thanks!
