### ISSUE TITLE
Issue Loading Alias ES Index 

### ISSUE THREAD

**Issue by williamphu** [broadinstitute/seqr#2045]
**Describe the bug**
I have created an alias `r0555_seqr_demo__wgs__grch38__variants__v02__combined` for the two ES indices: `r0555_seqr_demo__wgs__grch38__variants__v02__vcfv1__20210811` and `r0555_seqr_demo__wgs__grch38__variants__v02__vcfv18__20210706`. When I go to load this alias in the project [https://seqr.broadinstitute.org/project/R0555_seqr_demo/project_page](https://seqr.broadinstitute.org/project/R0555_seqr_demo/project_page), I get a NoneType error:

<img width="775" alt="Screen Shot 2021-08-13 at 1 22 32 PM" src="https://user-images.githubusercontent.com/17106856/129577110-6dace970-5bc6-442a-af26-4804585f1924.png">

**Comment by hanars** [comment]
This is fixed! To test it, I actually aded this alias to this project on prod, so thats been done, although you might want to validate you are seeing the variants you expect

**Comment by williamphu** [comment]
Thanks Hana!
