### ISSUE TITLE
discrepancy between  tvs and online list

### ISSUE THREAD

**Issue by sannagudmundsson** [broadinstitute/seqr#2047]
When I download lists from seqR for example [here](https://seqr.broadinstitute.org/summary_data/saved_variants/Tier%201%20-%20Phenotype%20not%20delineated). It states 16 variants are listed,17 are, one variant listed twice (assume 16 refers to unique variants?). Downloading a csv also lists 17 variants, again (14-64767808-A-C) is listed twice. However, when I download list as tsv, it is 18 variants: the duplicated variant listed twice (ok) but then an additional variant "X-15331689-C-T " that is not found online or in the csv, only the tsv.

Also, when looking at all RGP Review tagged variants. Writes that it list of 2372 (I assume unique). Cvs and tsv (now concordant?) have 2556 variants of which 2537 are unique.

**Comment by hanars** [comment]
The number displayed on the page is wrong - it says "Showing 16" but if you actually count the variants on the page its 17. 

Variants are not unique in the "Review" download for a single project, it is one variant per family

In general, when you submit issues please be clear if you are reporting a bug, asking for a feature enhancement, or asking a question. If you are asking a question, please be explicit about what you want to know. In this ticket you sort of describe a situation that to me is not a problem and don't ask anything about it so I'm not sure how to respond

**Comment by sannagudmundsson** [comment]
Yes. All the above is clear to me.

I am reporting a bug.

**Title: discrepancy between tvs and online list.**

Bug: "when I download list as tsv, it is **18 variants:** the duplicated variant listed twice (ok) but then **an additional variant "X-15331689-C-T " that is not found online or in the csv, only the tsv.**

-> variants listed online is not the same variants listed in the tsv.

**Comment by hanars** [comment]
When I run the download for tsv I do not see that extra "X" variant you describe, I get the exact same results for csv and tsv. Can you try refreshing the page and re-downloading and see if you still get it?

**Comment by sannagudmundsson** [comment]
File from yesterday file from now. The one from yesterday has the X-chrom
variant.

*---My*
*Sanna Gudmundsson, Ph.D., Wallenberg Postdoctoral fellow, O'Donnell-Luria
Lab*
Program in Medical and Population Genetics, Broad Institute of
Massachusetts Institute of Technology and Harvard, Cambridge, MA, USA
Division of Genetics and Genomics, Boston Children's Hospital, Harvard
Medical School, Boston, MA, USA
Analytic and Translational Genetics Unit, Massachusetts General Hospital,
Boston, MA, USA
***@***.***
***@***.***

**Comment by hanars** [comment]
So that sounds like someone added a tag by accident and immediately removed it and you just had unlucky timing. Since the files are now the same, this should be resolved

**Comment by sannagudmundsson** [comment]
Yes, thank you for helping me look at that. I did not realize that these
lists can differ between times of download since analysts are constantly
adding/removing tags.

Sanna
*---*
*Sanna Gudmundsson, Ph.D., Wallenberg Postdoctoral fellow, O'Donnell-Luria
Lab*
Program in Medical and Population Genetics, Broad Institute of
Massachusetts Institute of Technology and Harvard, Cambridge, MA, USA
Division of Genetics and Genomics, Boston Children's Hospital, Harvard
Medical School, Boston, MA, USA
Analytic and Translational Genetics Unit, Massachusetts General Hospital,
Boston, MA, USA
***@***.***
***@***.***
