### ISSUE TITLE
Project page not loading - CMG_Walsh_Exomes_PMG

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#2049]
**Describe the bug**
I cannot get the Walsh PMG project page to load but can load individual families. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0532_cmg_walsh_exomes_pmg/project_page

**Scope of the bug**
Other CMG exome project pages are loading fine for me, including other Walsh projects.

**Comment by hanars** [comment]
The project page is loading again. Someone set WAL_PMG13100_PMG13102_D1 as her own mother and it broke the pedigree drawing. I've created https://github.com/broadinstitute/seqr/issues/2050 to prevent this from happening in the future
