### ISSUE TITLE
CMG_gCNV project: odd 0 symbol appearing after CNV size

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#2074]
**Describe the bug**
An odd symbol is appearing after the CNV size where number of exons is usually reported. We think this bug is where exon=0 or is a partial exon. 
If no exons are affected, this should read '0 exons' or remain blank. 
If we can identify partial exon CNVs it would be nice to put '<1 exon' or 'partial exon'. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/variant/prefix_5489_DEL/family/F028037_beg_146

**Scope of the bug**
All CNV/SV data

**Screenshots**
![image](https://user-images.githubusercontent.com/44381119/131025705-d555531a-a03d-47f2-9648-38d4cacf3645.png)

**Comment by hanars** [comment]
this is fixed
