### ISSUE TITLE
Change mb to Mb for megabases

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#2075]
**Describe the bug**
For the size of a CNV in megabases, change mb to Mb

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/variant/CMG.phase1_CMG_BND_chr1_9/family/F025854_3386

**Scope of the bug**
All CNV/SV data

**Screenshots**
![image](https://user-images.githubusercontent.com/44381119/131027019-7fdefeab-12d8-4d3d-b912-1f36eb3faae9.png)

**Comment by hanars** [comment]
fixed
