### ISSUE TITLE
Colored line legend in seqr gCNV viewer

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2076]
Feature on gCNV viewer in seqr 
Add a legend that explains if the color of the line belongs to affected or unaffected status on the side of the gCNV track image. Add a hover hover text next to the legend that says “clicking on the colored line will show the sample name associated with this copy number".
- The analysts have decided to keep the following as default: Red line: affected individuals. Blue line: unaffected individuals
- If possible, add the feature of customizable colors as in TGG viewer (see pictures below)

![Screen Shot 2021-08-26 at 4 55 11 PM](https://user-images.githubusercontent.com/84086816/131034931-bf5fc778-c4c4-4b88-bc3f-ac415c8f66f0.png)
![Screen Shot 2021-08-26 at 4 57 24 PM](https://user-images.githubusercontent.com/84086816/131034996-3b985d72-35d2-4dcd-b0b4-d9283e42fc50.png)

**Comment by hanars** [comment]
We have added a legend for the colors
