### ISSUE TITLE
Hover over text next to number of exons in a CNV

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2080]
On SV called by gCNV pipeline on exome data, add the following hover over text next to the CNV size and number of exons (see red rectangle on attached screen shot): “CNV size and exon number are estimated from exome data and should be confirmed by an alternative method”.
![Screen Shot 2021-08-19 at 3 44 38 PM](https://user-images.githubusercontent.com/84086816/131182242-aa16fd45-afa4-420e-ae9a-c866bd19ebcd.png)

**Comment by hanars** [comment]
added
