### ISSUE TITLE
RGP Bulk Individual Upload Issue

### ISSUE THREAD

**Issue by jgserran** [broadinstitute/seqr#2083]
Spreadsheet with new individuals to create in RGP genomes project failed to upload with error "max() arg is an empty sequence" 

<img width="977" alt="Screen Shot 2021-08-30 at 10 24 33 AM" src="https://user-images.githubusercontent.com/89798273/131372782-08115e43-ee0f-4011-a3d6-7ce729ec9582.png">

Spreadsheet attached here: 
[Outstanding seqr_upload sibs .xlsx](https://github.com/broadinstitute/seqr/files/7078123/Outstanding.seqr_upload.sibs.xlsx)

**Comment by hanars** [comment]
It appears that file got messed up somehow and has over 1 million rows with some invalid values near the end. I would copy/ paste the rows you care about into a new excel file and upload that
