### ISSUE TITLE
Deletions and duplications called by gCNV on exome data 

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2085]
As discussed on the meeting on August 31, deletions and duplications called by the gCNV pipeline on exome data should be named “exome deletion” and “exome duplication” in seqr. The options of “exome deletion” and “exome duplication” should also appear in the annotations section (under structural) in seqr searches. The words “deletion” and “duplication” should be kept and applied to CNVs identified from genome data.

**Comment by hanars** [comment]
we will wait to work on this until the next exome gCNV callset is available for loading

**Comment by hanars** [comment]
Rethinking this - we will do the backend work that will allow us to support data loaded either the way it currently is or the way it will need to be for this functionality to work. Then, we will reload all the data, and after that we will implement the front end changes to take advantage of the backend changes, and deprecate the bridge functionality

**Comment by hanars** [comment]
Bridge functionality has been added to seqr, and the loading pipeline had been updated accordingly. we are now blocked on reloading all gcnv data using the updated pipeline

**Comment by Glemiret** [comment]
Hi Hana, is it now possible to apply the changes in this ticket?

**Comment by hanars** [comment]
this has been implemented. There are now separate annotations for "gCNV Deletion" and "gCNV Duplication" that will work separately from the genome SV "Deletion" and "duplication"
