### ISSUE TITLE
Recessive search 504 error

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2091]
**Describe the bug**
Anything apart from a standard recessive search is resulting in a 504 error. Merely changing to show all variants is resulting in an error. This is the same issue I had last week (#2069 and 2068). It seemed to be working for you, but not me. Two other analysts checked as well and had similar issues as I did. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/02d05001e7c0ab1a8937180905c735bb?page=1&sort=in_omim

**Scope of the bug**
Case specific

**Screenshots**
<img width="1272" alt="Screen Shot 2021-09-02 at 7 35 11 AM" src="https://user-images.githubusercontent.com/37872186/131836843-8d42d61b-8eda-4c88-bdf8-f3c6019763a9.png">

**Comment by hanars** [comment]
This is now succeeding. I've noticed you seem to be putting in a bunch of tickets for 504 errors that all work when I try them. In the future, can you wait like 15 minutes and try again before submitting the issue?

**Comment by hanars** [comment]
okay thats so weird! Its working on my end, does that link still not work on your end? Either way I'll re open the ticket as this seems to be an issue of things workign for me but not for you which means its a bug and not just a blip in elasticsearch performance

**Comment by hanars** [comment]
one thing to try as a workaround in the meantime is changing your sort. I looked at https://seqr.broadinstitute.org/variant_search/results/032950526f21777973cf4f0663327ecc?page=1&sort=in_omim which is a different search of yours that timed out recently that you didn't submit a ticket for and I am seeing a 504 for that, but if I change the sort to position it succeeds: https://seqr.broadinstitute.org/variant_search/results/032950526f21777973cf4f0663327ecc?page=1&sort=xpos

**Comment by hanars** [comment]
@lynnpais to clarify, the links that I say are working, do they work for you?

**Comment by lynnpais** [comment]
Yes, if the sort is set to position in the link you sent, it does work. I
can use this in the meantime until sort by in OMIM is fixed which is
essential when viewing >200 variants.

Thanks!

**Comment by hanars** [comment]
I have made some improvements to the performance of OMIM sort and I am now seeing the searches complete with omim sort applied (instead of timing out). Closing this issue out for now, but let me know if you continue to experience the issue

**Comment by jxchong** [comment]
@hanars I am doing some analysis in our instance and also getting a 504 error when I sort by OMIM. It works fine if I sort by position or by CADD score (it should be displaying from a list of 2431 filtered variants). We are up to date with the Broad repository as of a week ago.

**Comment by hanars** [comment]
So OMIM sort is probably not going to work on our instance for really big searches either. This fix was to get it working for smaller searches. For large cohort searches we would really recommend using gene lists if you want to prioritize specific genes rather than using the sort. 

You could try adding more resources/memory to your elasticsearch cluster, which might allow it to work on these large searches.

**Comment by jxchong** [comment]
Thanks Hana. This was just a single proband search (for all rare coding variants). We don't have a candidate gene in mind but we're using the OMIM sort in case the underlying gene was already known (in OMIM), so I think it wouldn't make sense to put a gene list consisting of all OMIM genes in there?
