### ISSUE TITLE
Individual ID text in automatically generated pedigrees

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2092]
**Is your feature request related to a problem? Please describe.**
The text representing the individual IDs in the automatically generated pedigrees in seqr overlaps the pedigree symbols and is often cut off in the pedigree image shown on the family page. 

**Describe the solution you'd like**
Move the text so it does not overlap the symbols (having the label for each individual centered below their pedigree symbol would be ideal)

**Describe alternatives you've considered**
Text wrapping could be implemented if needed

**Additional context**
Example of text overlap issue can be seen here: https://seqr.broadinstitute.org/project/R0555_seqr_demo/family_page/F031959_demofamily1

**Comment by hanars** [comment]
This is resolved
