### ISSUE TITLE
Make saved searches more prominent on the variant search page

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2093]
**Is your feature request related to a problem? Please describe.**
Saved searches are currently stored in a small drop down menu that can be missed by novice users (who are the ones most likely to benefit from saved searches)

**Describe the solution you'd like**
Add a title above the existing filter categories (Inheritance, pathogenicity, annotations, etc) that reads "Customize Search". Then add a new section above Customize Search that says "Select a Saved Search (Recommended):". This section should contain a single grey box (similar to the one of the filter categories) labeled "Saved Search" and then the dropdown menu with the saved searches can appear at the right of the box. Mock-up of this proposal provided below. 

**Describe alternatives you've considered**
We workshopped this amongst the analysts, but are open to other designs/wording if you have ideas! 

**Additional context**
Mockup: https://docs.google.com/presentation/d/1GEBbi64N1iA9o1NjJWwTfY9LAGi50XTMKxKrpfdjt6U/edit#slide=id.ge8dd146fdd_2_75

**Comment by hanars** [comment]
this has been implemented
