### ISSUE TITLE
OMIM links missing

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#2105]
**Describe the bug**
OMIM flags, links, and disease associations on the gene page are all missing. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/9213ed9d165a50187351bfced2ee1c16?page=1&sort=xpos

**Scope of the bug**
I noticed when running a known gene list search in the link above. Spot checking RGP makes me think it is seqr-wide. Screenshots of the RGP case below. 

**Screenshots**
![image](https://user-images.githubusercontent.com/44381119/132274002-1a9833c1-be49-4850-b52c-9df3dc46b6e2.png)
![image](https://user-images.githubusercontent.com/44381119/132274023-517a5381-26cd-4069-8ea5-403c333c19bb.png)
![image](https://user-images.githubusercontent.com/44381119/132274049-3ba17571-fea7-4c48-a7b8-127e8ed2cd50.png)

**Comment by lynnpais** [comment]
Also noticed the same across all projects

**Comment by hanars** [comment]
OMIM entries are back. Leaving this ticket open to track work to make sure this cannot happen again

**Comment by hanars** [comment]
we have fixed the underlying issues that caused this
