### ISSUE TITLE
Take Seqr_Demo project live

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2135]
**Is your feature request related to a problem? Please describe.**
The [Seqr_Demo](https://seqr.broadinstitute.org/project/R0555_seqr_demo/project_page) project was newly created with the intention that it would be a project that ALL seqr users have access to so users can test out seqr functionality even if they don't have any of their own data loaded.

**Describe the solution you'd like**
We'd like to grant all seqr users access to this project

**Describe alternatives you've considered**

**Additional context**
We'd like to have the project live by the time the ASHG conference starts (10/18) to coincide with Lynn's presentation, which may attract some new users. Readviz is not yet available but will hopefully be added soon.

**Comment by hanars** [comment]
This project has been taken live for all users
