### ISSUE TITLE
seqr access

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2146]
Collaborators from the Bonneman cohort are having trouble accessing the data in seqr. Might be related to which accounts they registered on AnVIL. The two individuals are Svetlana Gorokhova (svetlana.gorokhova@univ-amu.fr) and Dimah Saade (dimah.saade@nih.gov).

**Comment by hanars** [comment]
Yes, this appears to be that they are trying to access seqr using an email address that is not the same as the one that has been granted access to their projects. For Svetlana, I see svetlana.gorokhova@nih.gov which has been added to all the cohorts but does not appear to have been used recently, and I also see the email you sent me svetlana.GOROKHOVA@univ-amu.fr which was used earlier this week but has not been added to all the cohorts. For Dimah I see the email you sent me dimah.saade@nih.gov added to all the cohorts but it does not appear to have been used recently, and I see dimah.saade@gmail.com logged in more recently but with no projects added. 

The easiest thing would be to have them register and use their nih.gov accounts in AnVIL, but if they can't do that then someone needs to go into each project they needs access to and add their new accounts. This should be done by whoever on their team is generally responsible for adding new members to seqr. There is nothing I can do on my end to make this process smoother - in general, users need to log in with the same email address that has always been associated with their seqr account or they need to reach out to whoever on their end does user management to add new accounts

**Comment by lynnpais** [comment]
Okay, I'll follow-up with them. Thanks for taking a look!

Happy Friday!
