### ISSUE TITLE
The Google Storage access token is expiring sooner than expected (which is 1 hour).

### ISSUE THREAD

**Issue by ShifaSZ** [broadinstitute/seqr#2149]
The IGV API provides a proxy for downloading data from Google Storage. We use Redis to cache the Google access token with a fixed expiration time of 1 hour. But the token actually expires sooner because it could be generated earlier than the time when it is being fetched.

The consequence of the issue is that the Google storage accesses will fail during the time between the token expires and the cache expires.

We need to get the expiration time for the token before we cache the token.

**Comment by hanars** [comment]
we also need to create a fallback to regenerate the token if the cache fails. Redis is not a primary dependent service for seqr so the app has to work fully if redis is completely down/unavailable. While IGV will obviously be very slow with no redis, it needs to at least function
