### ISSUE TITLE
Adding a Gene list

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2163]
**Describe the bug**
The add Gene List on the Project Page seems to be loading a random list when you first load it. It is also taking very long to load - not sure what can be done about it. 

**Scope of the bug**
Across all projects

**Comment by hanars** [comment]
I'm not sure I understand the bug you are reporting. I am seeing it take a long time to load, but I am not seeing it loading the random list you are describing - can you show a screenshot?

**Comment by lynnpais** [comment]
Emily and I ran into this issue earlier, but it seems to have been
resolved.

Thanks,
Lynn
