### ISSUE TITLE
Options to choose a Gene List

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2164]
**Is your feature request related to a problem? Please describe.**
As the number of Gene Lists are now 400+ it would nice to be able to select a list from 'Add Gene List' and hit enter after checking a box(es), rather than have to scroll all the way down to do so. 

**Describe the solution you'd like**
Described above

**Comment by hanars** [comment]
hitting "tab" and then "enter" will now trigger the submit button without needing to scroll
