### ISSUE TITLE
Add SV calling algorithms to quality metrics on SV calls in seqr

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2166]
**Is your feature request related to a problem? Please describe.**
The number of algorithms supporting an SV call provides some information on the quality of the call - if the variant was called by multiple algorithms it is more likely to be real. Currently there is no way to see which algorithms contributed to each SV call in seqr. 

**Describe the solution you'd like**
Source algorithms are listed in the info column of the vcf. We would like to list all algorithms that called each variant in the popup that appears when hovering over CN on the call. It should appear under the quality score. Mock-up below. 

**Describe alternatives you've considered**
Open to other locations this could be displayed, but think it makes most sense for it to be displayed with other quality metrics

**Additional context**
![image](https://user-images.githubusercontent.com/67653781/136573360-09cb011f-d2e5-452c-ad45-3186a6c29c53.png)

**Comment by ShifaSZ** [comment]
Sorry for skipping the message in the email last week. There is no information about the algorithms used for calling the SVs in a genome SV VCF file. We probably need to ask Harrison for the algorithms used.

**Comment by hanars** [comment]
okay we will reach out to Harrison and Alba then

**Comment by ShifaSZ** [comment]
Good points for the "algorithms" field. I can check the values in the field.

**Comment by hanars** [comment]
I think we should do the per-variant "algorithms" and not worry about the per-sample
