### ISSUE TITLE
PanelApp integration - seqr tags

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2167]
**Is your feature request related to a problem? Please describe.**
Currently, PanelApp gene lists that are manually added to a project are colored blue in the variant search results. This makes it hard to prioritize, and to differentiate between levels of evidence requiring the user to go to the site to get more information. 

**Describe the solution you'd like**
- Match the color of the tag to the PanelApp confidence level for a given gene - Green (strong), amber (moderate), Red (limited evidence) genes can show up in a dull, light red so as not to conflict with built-in constraint tags. Skip fourth PanelApp category - No List, which is also grey. 
-Text displayed on the tag should correspond to the name of the panel. If the gene is part of more than one panel, display additional tags. Depending on the number of gene lists added to a project, there can be many tags. 

<img width="929" alt="Screen Shot 2021-10-08 at 11 08 50 AM" src="https://user-images.githubusercontent.com/37872186/136580779-388a27ef-0d02-43e6-aded-34df88e013c6.png">

**Comment by hanars** [comment]
@tommyli just an FYI that we will be implementing this change on our end, if you want to use that/ if you had something similar planned

**Comment by hanars** [comment]
this has been implemented
