### ISSUE TITLE
PanelApp integration - gene lists

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2168]
**Is your feature request related to a problem? Please describe.**
From the dropdown menu in the Gene List section, it is not clear which list is a PanelApp one and which isn't.

**Describe the solution you'd like**
Add the word ‘PanelApp’ to the gene list name, so it populated accordingly in the dropdown menu. Example: Amyloidosis - PanelApp.

<img width="326" alt="Screen Shot 2021-10-08 at 11 14 12 AM" src="https://user-images.githubusercontent.com/37872186/136581389-f426f385-50a5-4505-b4a8-4f3447d45e67.png">

**Comment by tommyli** [comment]
All good.  In practice, I'm curious how Broad users will use these lists.  E.g. how many users will continue to curate/maintain their own public lists now that PanelApp lists are there?  What about curate/maintain their own private lists?  We had some discussions on our end and private lists may continue to be used if users want a "stable" list that does not change.  For this latter use case, a "duplicate a public list into my private list" may be something we're looking at so any thoughts/ideas welcome.
