### ISSUE TITLE
Gene list tag layout in seqr

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2169]
**Is your feature request related to a problem? Please describe.**
As we are expanding the list of tags in seqr, we would like to revise the layout to help differentiate between in-built gene lists (LoF, HI, etc) from user-added lists (PanelApp)

**Describe the solution you'd like**
Add a grey line as shown below to separate these categories.

<img width="1023" alt="Screen Shot 2021-10-08 at 11 19 58 AM" src="https://user-images.githubusercontent.com/37872186/136582856-3ac0a12f-aa43-4a95-b65d-bc0f49690215.png">

**Comment by hanars** [comment]
added
