### ISSUE TITLE
RNAseq viewer menu suggestions

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#2183]
**Describe the bug**

![image](https://user-images.githubusercontent.com/10407888/137597916-457586c3-d224-490e-8d9f-e8d4506c8e37.png)

Rename GTEx Muscle to Agg. GTEx Muscle (and same for other ones). 
Put normalized tracks above aggregate tracks as we recommend people use the normalized track

Add a ? by RNA-seq reference tracks that says something like: 
Normalized GTEx tracks are more comparable to patient RNA-seq data. If you want to explore if a splice junction is seen in any sample, aggregate GTEx tracks show all data. The y-axis range is expected to differ between a single patient sample and normalized or aggregate GTEx data.

**Comment by hanars** [comment]
this has been updated
