### ISSUE TITLE
RNAseq viewer gene view

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#2185]
**Is your feature request related to a problem? Please describe.**
When show RNASeq is selected (which we are inconsistent in how we spell this within the tool versus the launch button - would make both RNA-seq), it shows near the variant, which does make sense. But an analyst would also want to look at the entire gene locus. 

**Describe the solution you'd like**
It would be nice to be able to click a button somewhere and also view the RNA-seq data for the entire gene locus (to avoid having to zoom out over and over). 

**Describe alternatives you've considered**
I tried entering the gene name in the IGV search bar as another option but that didn't work. I also don't think it's a great option because the average seqr user probably wouldn't think to do this. 

**Additional context**
Add any other context, links to relevant seqr pages, or screenshots about the feature request here.

**Comment by anneodonnell** [comment]
There are many things one would want to do: 

From an SNV/indel, one may want to: 
- Look at the RNAseq data for the region around the variant (and then may end up zooming out some)
- Look at the RNAseq data for the entire gene (though if it's a big gene, they will still probably end up zooming in)
- Look at the gCNV data for the entire gene to see if there is any hint of a deletion in trans (that was missed in the calling so not in the vcf/seqr)

For a CNV/SV, common uses: 
- Look at the gCNV data for the entire CNV/SV event (may zoom out or zoom in from there)
- For small CNV/SV, maybe look at the RNAseq data for the CNV/SV event (but probably less for events that include multiple genes)

I'm not sure the best way to offer this - I think maybe the default selection opens to a window a bit bigger than the variant (for CNV/SV, 3x the size centered on the event, and for SNV/indel, 50-100 bp range - seems fine how it currently opens). And then within the menu there is somewhere you can click to change the coordinates to show the entire gene (with some padding, ~10% of gene length on each side).

I'm not sure how feasible something like that would be. 

A concern is having too many new links on each variant which is visually distracting. 
The goal is to avoid having to click zoom our or zoom in tens of times to view what is needed.

**Comment by hanars** [comment]
It would be feasible to add an option to show the whole gene's coordinates on the side menu - would something like this work? I added a "range" section with the options for "Show Variant" and "Show Gene"

![image](https://user-images.githubusercontent.com/24598672/139699245-33adc47c-85b7-468f-8f01-0a94d5d29f54.png)

**Comment by anneodonnell** [comment]
yes, I think that would work - when selecting show variant, we'd still want some padding on it (like you show a 200bp window for an SNV now). But generally, yes, I think this would work well. I'd default to the variant view but like to be able to easily jump to a gene level view. It would be good to work whether one is looking at DNA or RNA data.

**Comment by hanars** [comment]
So to summarize: 
We will be adding a "Range" option to the control bar as shown above that will allow users to toggle between viewing the variant and viewing the gene. This option will be available for all data types. It will default to viewing the variant when opened (current behavior). In the "variant" view it will show with a 200bp range (current behavior). 
In the "gene" view, do we want to show it with a similar 200bp range on either side, or do we want to have it similar to an SV where we show 1/3 of the size of the gene as padding on either side?

**Comment by anneodonnell** [comment]
Let's do it like SV with 1/3 size of the gene as padding on either side

**Comment by hanars** [comment]
and option to select "variant" or "gene" is now available for all sample types
