### ISSUE TITLE
SpliceAI optimizing filtering/ in silico search improvements

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#2186]
**Is your feature request related to a problem? Please describe.**
SpliceAI is an in silico score that denotes variants that may impact splicing. It's different than the other scores which we largely use to prioritizing coding variants. There are a relatively manageable number of variants with high SpliceAI per genome. It would be really helpful to be able to have this filter of SpliceAI score > X (specified by user) overrule the annotation field and return any variant with high SpliceAI score PLUS whatever else is requested in the search. 

The other in silico tools should not behave this way as they either wouldn't be relevant (for missense variants only) or would return too many results to be helpful. 

**Describe the solution you'd like**
Have SpliceAI filtering overrule the annotation field the same way that ClinVar does

**Describe alternatives you've considered**
Open to other ideas

**Additional context**
Blocked until filtering by in silico added to seqr

**Comment by hanars** [comment]
The splice Ai and in silico filtering has been updated as discussed
