### ISSUE TITLE
Define linkerd policies for seqr pod resources

### ISSUE THREAD

**Issue by sjahl** [broadinstitute/seqr#2192]
Putting this one on the backburner for later….

A new feature in linker 2.11 allows for policies to be specified. This allows us to define which pods/services can talk to one another, providing a layer of security. E.g. We could specify that the seqr pod is allowed to communicate with postgres and elasticsearch -- and also specify that postgres is not allowed to talk to elasticsearch.

Not a required feature for us, but seems like it might be nice down the road from from a compliance/security perspective.

**Comment by hanars** [comment]
It does nto use linkerd specifically, but this PR adds a kubernetes NetworkPolicy that effectively enforces pop-too-pod communication rules
