### ISSUE TITLE
Unable to download table

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2200]
**Describe the bug**
The download table link on the saved variants page is not working

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/summary_data/saved_variants/Known%20gene%20for%20phenotype

**Scope of the bug**
Not case specific

**Screenshots**
<img width="1310" alt="Screen Shot 2021-10-21 at 7 56 31 AM" src="https://user-images.githubusercontent.com/37872186/138272413-2711e62f-7c61-4d35-b07a-cb248879c042.png">

**Comment by hanars** [comment]
Duplicates https://github.com/broadinstitute/seqr/issues/2191

**Comment by hanars** [comment]
the issue is fixed now
