### ISSUE TITLE
Update Seqr dataset extensions to support .vcf

### ISSUE THREAD

**Issue by williamphu** [broadinstitute/seqr#2218]
**Is your feature request related to a problem? Please describe.**
Currently when loading a VCF to seqr, it expects the .vcf to be zipped (.gz, or .bgz), so seqr complains about .vcf.

**Describe the solution you'd like**
The loading pipeline can handle .vcf unzipped, so it'd be nice to be able to link .vcf if a user provides that, instead of having to recommunicate and upload a .gz/.bgz. This would be expanding the list of supported extensions to add _.vcf_.

**Describe alternatives you've considered**
I can currently go into kibana to remap the ES index path, but that takes time and some troubleshooting.

**Additional context**
This is similar to the previous request for .bgz support: https://github.com/broadinstitute/seqr/issues/1914

**Comment by hanars** [comment]
this has been updated
