### ISSUE TITLE
Increased support for uploading metadata

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#2220]
**Is your feature request related to a problem? Please describe.**
For GREGoR we really need to encourage and make as easy as possible for people to share as much sample metadata as we can get. Also helpful for the Bahrain genome project. 

**Describe the solution you'd like**
Create an template file that includes all the metadata that can be uploaded in a project, where the header has the right name to allow bulk upload. Also create an example file that has mock data and also information on format requirements for each field. 

Could ask for someone on the project management team to help with this. 

**Describe alternatives you've considered**

**Additional context**
What we have now has some information on the page but want to make it as easy as possible for people to upload without asking us a lot of questions.

**Comment by hanars** [comment]
Updated according to the suggestion in the comments
