### ISSUE TITLE
Link to MME page for a family from the saved variant page

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#2223]
**Is your feature request related to a problem? Please describe.**
The workflow for submitting a gene to MME is typically to review the saved variants, add a Matchbox tag, then go to the family page and then to the MME link to create a submission. 

**Describe the solution you'd like**
Be able to link to the MME page directly from the Saved variants page (but also keep the link on the family page). 

**Describe alternatives you've considered**
Would be cool if the Matchbox tag linked directly to the MME page when you clicked on it. 
Also, the Matchbox (MME) tag should probably be renamed to seqr MME. 

**Additional context**
This is what I mean by the MME page https://seqr.broadinstitute.org/project/R0312_cmg_bonnemann_genomes/family_page/F015978_b13_52/matchmaker_exchange

**Comment by hanars** [comment]
The tag name has been updated to "seqr MME", and clicking on the tag will now take you to the matchmaker page
