### ISSUE TITLE
Bulk upload of assigned analyst field

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#2230]
**Is your feature request related to a problem? Please describe.**
Be able to assign cases in a bulk upload

**Describe the solution you'd like**
Add assign analyst as an option for bulk upload. It would often be uploaded at a separate time from the other metadata but should have the option to also upload with the other metadata.

**Comment by hanars** [comment]
@Causint this is now available in seqr. In the "Update Individual Metadata" you can upload a file which has an "Assigned Analyst" column that contains the email addresses of the analysts you want to assign

**Comment by Caustint** [comment]
Got it. It might be nice to indicate somewhere on the bulk edit pages that
this is an available optional column (I couldn't see it there, forgive me
if I missed it)?

Some troubleshooting: I was able to get this to work nicely in the
Proband-only Pathways project but the table doesn't upload when I try to go
through the same process for RGP. Can you advise if there is any specific
formatting I need to adhere to in projects with family structures (like
RGP)? I.e. should I choose one individual in each family to add info within
the Assigned Analyst column? Does it matter which individual?

For what it's worth, for the table that wouldn't upload I had the Assigned
Analyst column filled in for every family member:
[image: image.png]

Related question: Can I upload a file containing just the
families/individuals I want to update? Would that leave all the other
families as they are? I am a little nervous about somehow messing up the
entire project!

*Christina Austin-Tse, PhD, FACMG*
Analysis Team Lead, Center for Mendelian Genomics, Broad Institute of MIT
and Harvard
Clinical Molecular Geneticist, Center for Genomic Medicine, Massachusetts
General Hospital
Instructor in Pathology, Harvard Medical School
Pronouns: She/her

**Comment by hanars** [comment]
> Got it. It might be nice to indicate somewhere on the bulk edit pages that this is an available optional column (I couldn't see it there, forgive me if I missed it)? 

Its not shown, feel free to submit a new gtihub issue if you would like me to add it

> Some troubleshooting: I was able to get this to work nicely in the Proband-only Pathways project but the table doesn't upload when I try to go through the same process for RGP. Can you advise if there is any specific formatting I need to adhere to in projects with family structures (like RGP)? I.e. should I choose one individual in each family to add info within the Assigned Analyst column? Does it matter which individual? For what it's worth, for the table that wouldn't upload I had the Assigned Analyst column filled in for every family member: [image: image.png] 

I think it shouldn't matter whether you choose one individual in each family, or whether you set all of them to the same analyst, but one is sufficient and it shouldn't matter which one. Just make sure both the family ID and individual ID are correctly set. Also, note that when you reply to emails in github it won't attach anything, you need to go to the github website for that

> Related question: Can I upload a file containing just the families/individuals I want to update? Would that leave all the other families as they are? I am a little nervous about somehow messing up the entire project! 

Yes I would in fact strongly recommend you ONLY include families you want to change, as families that are left out will remain unchanged and families that you include  but don't want to change you might accidentally mess up
