### ISSUE TITLE
Visualization of "exome datasets" list in Project Page

### ISSUE THREAD

**Issue by bnouyou** [broadinstitute/seqr#2244]
**Is your feature request related to a problem? Please describe.**
It's not a functionality issue, it's a visualization issue. I am using a local seqr instance, I have added several datasets in my projects, and in the web interface, on the project page, the "exome datasets" are listed, and the list is very long. See an example:
![image](https://user-images.githubusercontent.com/22322228/139274873-d021912d-06b3-4003-a0ac-6d24c093d29d.png)

It's not very convenient, as I need to scroll down to see the families below. And the more samples I add, the longer the list.

**Describe the solution you'd like**
Maybe it would be possible to show only the beginning of the list and have a "show more" link. It's just an idea.

Thank you.

**Comment by hanars** [comment]
A "show more" link has been added to limit the number of displayed datasets
