### ISSUE TITLE
Update of saved searches

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2245]
Please update the saved searches using searches currently saved in Gabrielle Lemire seqr account. 

Replace the following existing saved searches 
1. De novo/Dominant Permissive -> De novo/Dominant Permissive new (name this saved search: De novo/Dominant Permissive)
2. De novo/Dominant Restrictive -> De novo/Dominant Restrictive new (name this saved search: De novo/Dominant Restrictive)
3. De novo/Dominant-SV only -> De novo/Dominant-SV only Trio (name this saved search: De novo/Dominant-SV only Trio)
4.  Recessive restrictive-> Recessive restrictive new (name this saved search: Recessive restrictive)
5.  Recessive SV-> Recessive SV new (name this saved search: Recessive SV)

Add these new saved searches: 
1. De novo/Dominant-SV only-Proband/duo (name this saved search: De novo/Dominant-SV only-Proband/duo)
2. Recessive permissive new (name this saved search: Recessive permissive)

**Comment by Glemiret** [comment]
I put in parentheses: "name this saved search: De novo/Dominant Permissive". That is how I suggest the search should be named in seqr. There is no "new" in that suggested name, so I am not sure I understand your comment

**Comment by hanars** [comment]
I was confused about the syntax in your request. I thought it was formatted as:
`existing name -> new name (name this is saved for for me)`

But it looks like the way you actually named these is `existing name -> name this is saved for for me (new name)`

**Comment by Glemiret** [comment]
Yes I could not save the new searches with the name that they should have in my seqr account (as some names were already used)

Yes I meant:
replace this existing seqr search with -> this search in my seqr account (and in () this is the final name the search should have for all users). 
Does that work?

**Comment by hanars** [comment]
These have all been updated
