### ISSUE TITLE
Can't show reads under the family panel

### ISSUE THREAD

**Issue by ShifaSZ** [broadinstitute/seqr#2247]
**Describe the bug**
When opening a project and scrolling down to a family panel in it, click on the "SHOW gCNV" or "SHOW READS" buttons as in the picture below. 
![image](https://user-images.githubusercontent.com/33550059/139305854-d8e54cb9-a81b-46d2-85b0-300e53c2e87b.png)
The page goes blank and there are error messages in the debugger as in the figure below.
![image](https://user-images.githubusercontent.com/33550059/139306576-7e73acde-9b31-4167-8239-f4240cc126b2.png)

**Link to page(s) where the bug is occurring**
https://seqr-dev.broadinstitute.org/project/R0486_cmg_gcnv/project_page

It looks like that the code fails to check the undefined `variant` in the statement below.
```
  const size = variant.end && variant.end - variant.pos
```

**Comment by hanars** [comment]
this is fixed
