### ISSUE TITLE
List manuscript in seqr

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2248]
**Is your feature request related to a problem? Please describe.**
Share the new seqr manuscript with the community

**Describe the solution you'd like**
Link the paper to the pre-login page. "_seqr_ preprint now available on medRxiv" with a hyperlink to https://www.medrxiv.org/content/10.1101/2021.10.27.21265326v1

**Comment by lynnpais** [comment]
Link the paper to the pre-login page under the About section- "View the _seqr_ preprint" with a hyperlink to https://www.medrxiv.org/content/10.1101/2021.10.27.21265326v
<img width="890" alt="Screen Shot 2021-10-29 at 2 37 36 PM" src="https://user-images.githubusercontent.com/37872186/139485715-c4051045-d6d9-4b63-8ddb-6a6ccb6b6f19.png">
1

**Comment by hanars** [comment]
this has been added
