### ISSUE TITLE
Cite seqr feature

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2249]
Add a "Cite _seqr_" feature to the bottom of the seqr browser. This link should direct people to a page with the following information: For discoveries made using seqr, please cite - 
Pais, L., Snow, H., Weisburd, B., Zhang, S., Baxter, S., DiTroia, S., O’Heir, E., England, E., Chao, K., Lemire, G., Osei-Owusu, I., VanNoy, G., Wilson, M., Nguyen, K., Arachchi, H., Phu, W., Solomson, M., Mano, S., O’Leary, M., … O’Donnell-Luria, A. seqr: a web-based analysis and collaboration tool for rare disease genomics. medRxiv (2021). https://doi.org/10.1101/2021.10.27.21265326

<img width="699" alt="Screen Shot 2021-10-29 at 2 39 47 PM" src="https://user-images.githubusercontent.com/37872186/139486044-dba495ee-d36c-4063-9d99-9e28065c6860.png">

**Comment by hanars** [comment]
added
