### ISSUE TITLE
gnomAD SV link in seqr 

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2263]
Clicking on the gnomAD SV allele frequency link in seqr for a given CNV brings you to the gnomAD SV website but with the wrong genomic coordinates. It seems like the seqr Hg38 coordinates (part of actually) are used but in the gnomAD browser which uses Hg19. 

Here are 2 examples from the CMG_gCNV project.  https://seqr.broadinstitute.org/project/R0486_cmg_gcnv/saved_variants/family/F025811_mpau036 https://seqr.broadinstitute.org/project/R0486_cmg_gcnv/saved_variants/family/F025854_3386

Screenshots show examples of a deletion involving DES gene with gnomAD SV link leading to the gnomAD SV webpage with wrong genomic coordinates (involves another gene (USP37)). 
![Screen Shot 2021-11-03 at 1 50 07 PM](https://user-images.githubusercontent.com/84086816/140328690-a17eef00-4de3-41ee-993f-3c0e9059fdb3.png)

![Screen Shot 2021-11-03 at 1 50 19 PM](https://user-images.githubusercontent.com/84086816/140328708-aec95755-8fd5-47be-b1a1-28aa00bcf42e.png)

**Comment by hanars** [comment]
Note that this is only an issue where the gnomad Sv frequency is 0 - for  SVs that are present in gnomad the link works fine

**Comment by hanars** [comment]
oh yes! The note was mostly for myself, making sure I understood the full scope of the issue

**Comment by hanars** [comment]
this is fixed now
