### ISSUE TITLE
New gCNV field to identify new variants in old samples

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#2269]
**Is your feature request related to a problem? Please describe.**
Several new fields in the new dataset: 
36 id - id of the variant, formed by sample_type_chr_start_end
37 sample_in_round1 - TRUE if the sample is present in the round 1 callset
38 identical_in_round1 - TRUE if the variant has an identical call in the round 1 callset, with the exact same coordinates, for the same sample and type
39 partial_ovl_in_round1 - TRUE if the variant has at least a 30% reciprocal overlapped call in the round 1 callset, for the same sample and type
40 any_ovl_in_round1 - TRUE if the variant has at least 1 bp overlapped call in the round 1 callset, for the same sample and type
41 no_ovl_in_round1 - TRUE if the variant has no overlapped call in the round 1 callset, for the same sample and type

**Describe the solution you'd like**
Gabrielle and analyst team is going to come up with an initial proposal for discussion with seqr team. Wanted to add this to the planning board. My goal is to empower project level reanalysis to identify cases that need family based re-analysis as there is too much data to reanalyze everything.

**Comment by hanars** [comment]
Considering this blocked until we have details of how we want to show this data

**Comment by hanars** [comment]
https://github.com/broadinstitute/seqr/issues/2360 tracks the specific changes we want to make, so closing this ticket out and will that one to track the work
