### ISSUE TITLE
Inclusion of mitochondrial variants to seqr

### ISSUE THREAD

**Issue by slstenton** [broadinstitute/seqr#2270]
**Is your feature request related to a problem? Please describe.**
Inclusion of mitochondrial variant calls from GS in seqr

**Describe the solution you'd like.**
Map created of features which would be helpful to include for the analysis of mtDNA variants in seqr, including sample level annotation, variant level annotation, and helpful links: https://docs.google.com/document/d/1q1cwvbal9fWPI5sgyIWcjX86kJ-x0irD/edit?usp=sharing&ouid=105984679363104309787&rtpof=true&sd=true (for discussion with the seqr team).

**Comment by hanars** [comment]
Hey Sarah thanks so much for putting the document together! One thing we will need before we go forward is a mapping between the fields you list that we want in seqr, and the fields in the actual VCF. If this is something you know and can add to the document that would be great If its not something you know, we can reverse engineer it ourselves, but wanted to check with you first.

It would also be helpful if you could clarify in the document which field correspond to things already shown in seqr (for instance VEP variant function) and things which are not currently shown in seqr  ( for example, anything to do with MITOMAP). It would also be helpful to know what we need to support for display, and what needs to be supported in search. For instance, do we need to be able to filter variant by heteroplasmic AF, or do we just want to show what the AF is

This may be more productive to do as a meeting - if you think so I'd be happy to set up some time to talk this through

**Comment by sstentonbroad** [comment]
Hi Hana,

All great points, I’ll start working on these updates, and we can go from there? Maybe arrange to meet afterwards? (I think it sometimes does take a discussion or two for me to realize exactly what information is needed).

In terms of fields in the VCF, I don’t I have access to the VCF files themselves, but I’ve tried to indicate in the comments as {xxx} the row name / column name from the Hail MatrixTable where I was able to already find certain information (e.g., major_haplogroup, mito_cn...), is this useful?

**Comment by hanars** [comment]
Sounds like a plan, let me know whenever you think you are ready to meet

**Comment by sstentonbroad** [comment]
@ShifaSZ I've added the links to the location of downloadable data (e.g., the know MITOMAP pathogenic variants).

**Comment by sstentonbroad** [comment]
Here's the path to the matrixtable: gs://seqr-datasets/cmg_mito/test_ten_cmg_mito_combined.mt
