### ISSUE TITLE
Recessive searches across multiple projects

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2271]
**Describe the bug**
504 error when trying to run a recessive search across multiple projects. Not sure if this is a bug or something we do not have the ability to do yet (search across many projects). 

For context, Nicky Whiffin is interested in recessive variants in a particular region, so I tried to search across our neuromuscular cohorts. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/c17561b4202553660e678ae59cc932c3?page=1&sort=in_omim

**Screenshots**
<img width="1270" alt="Screen Shot 2021-11-05 at 2 50 05 PM" src="https://user-images.githubusercontent.com/37872186/140563360-0f0b1379-a582-422e-be4f-6772f181a047.png">

**Comment by hanars** [comment]
Multi-project inheritance based search is only available within a single gene and is not supported for genomic regions
