### ISSUE TITLE
5'UTR variants VEP plug in UTR annotator to seqr loading

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#2274]
**Is your feature request related to a problem? Please describe.**
Add 5'UTR variants using the VEP plugins - useful for analyzing non-coding-but-genic variantshttps://github.com/ImperialCardioGenetics/UTRannotator

**Describe the solution you'd like**
I think this would be something to add to the loading pipeline. We would also want this to be added as an annotation that we could filter on in seqr (in the new section where Splice AI score filtering will go). 

**Describe alternatives you've considered**
Mike said this ties in with updating the gnomAD v4 pipeline maybe

**Comment by hanars** [comment]
Blocked in seqr on related pipeline work: https://github.com/broadinstitute/hail-elasticsearch-pipelines/issues/282

**Comment by ImraanDixon** [comment]
The last mention of this plugin is as a one off use.  I was wondering if there are still plans to implement this feature permanently in seqr? Excuse me if this has already been done.

**Comment by hanars** [comment]
this is an open feature request, it has not been done yet

**Comment by lynnpais** [comment]
Closing in favor of #282 and #4124
