### ISSUE TITLE
Add SliceRegion VEP plug in to seqr loading pipeline and filtering

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#2275]
**Is your feature request related to a problem? Please describe.**
Add another splice variant predictor using the VEP plugins - useful for analyzing non-coding-but-genic variants https://github.com/Ensembl/VEP_plugins/blob/release/104/SpliceRegion.pm 

**Describe the solution you'd like**
I think this would be something to add to the loading pipeline. We would also want this to be added as an annotation that we could filter on in seqr (in the new section where Splice AI score filtering will go). 

**Describe alternatives you've considered**
Mike said this ties in with updating the gnomAD v4 pipeline maybe

**Additional context**

**Comment by hanars** [comment]
Blocked in seqr on https://github.com/broadinstitute/hail-elasticsearch-pipelines/issues/283
