### ISSUE TITLE
ClinVar override for frequency filters

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2282]
**Is your feature request related to a problem? Please describe.**
We are concerned that well-established pathogenic variants might be missed in our standard filtrations if they are above our typical frequency cutoffs.

**Describe the solution you'd like**
We'd like to guard against this by setting ClinVar Pathogenic (P)/Likely Pathogenic (LP) filtrations to have a limited override of gnomAD frequency filters. Basically, when ClinVar P and/or LP is selected, we'd like any variant classified as P and/or LP **that has a popmax AF <5%** to be returned, regardless of the allele frequency cutoff selected for that filtration (often 1% or lower). We do not want this override to apply to HGMD classifications. To clarify this behavior to users we could modify the existing text in the filtration section to say "Filter by reported pathogenicity. Note this filter will override any annotations filter (i.e. variants will be returned if they have either the specified pathogenicity OR transcript consequence). Additionally, ClinVar Pathogenic or Likely Pathogenic filters will override gnomAD frequency filters up to a popmax AF of 5%."

**Describe alternatives you've considered**
Open to edits to the wording above, I struggled to find a concise way to make it clearer.

**Additional context**
This request stems from Anne - she and I have discussed and Emily tested it out to show it would only add a few extra variants to the search result for a typical case.

**Comment by hanars** [comment]
This has been implemented
