### ISSUE TITLE
GQ filter bug

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2284]
**Describe the bug**
Variants with no GQ are being returned despite filter set to >40. Likely because it dislays as - rather than a numeric value. These are poor quality and should not be returned. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/variant/19-7596017-G-T/family/F029148_eng_sw

**Scope of the bug**
All projects

**Screenshots**
<img width="1194" alt="Screen Shot 2021-11-10 at 8 01 18 AM" src="https://user-images.githubusercontent.com/37872186/141118122-1e93ccdf-8160-45c8-be6c-2d165668e320.png">

**Comment by hanars** [comment]
Hi Lynn, in the future can you make sure to also link to the search page where the bug actually occurred (as in, the search page with the gq filter applied) and not just the single variant

**Comment by hanars** [comment]
This is actually an issue with how we handle missing gq at pipeline loading time. I've put up a fix in the pipeline, but the behavior will unfortunately not be fixed in seqr until we are able to reload the data

**Comment by lynnpais** [comment]
Data not yet re-loaded.

**Comment by lynnpais** [comment]
Will this be no longer be an issue when we move to the Hail backend?

**Comment by hanars** [comment]
this will be fixed whenever data is reloaded. All data will be reloaded for the hail backend, but it may also happen sooner

**Comment by lynnpais** [comment]
As there is a fix in the pipeline and this cohort is not active, closing the ticket.
