### ISSUE TITLE
CMG Walsh Microcephaly Cohort Show reads

### ISSUE THREAD

**Issue by Jenniferneil** [broadinstitute/seqr#2285]
The show reads function in the CMG_Walsh_Exomes_Microcephaly cohort has not been working for a while.  Is there an issue with this cohort and/or can this be re-enabled?

https://seqr.broadinstitute.org/project/R0451_cmg_walsh_exomes_microce/project_page

Thanks!
Jen

**Comment by hanars** [comment]
This has been fixed
