### ISSUE TITLE
For each variant in search results, show all the gene names whose VEP-annotated consequence matches one of the consequences selected by the user in variant filters.

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#229]
Currently, all coding genes are shown. Instead, select gene names to show based on whether the variant effect for that gene is among those selected by the user.

**Comment by hanars** [comment]
Showing all the genes will be resolved by https://github.com/macarthur-lab/seqr/issues/646 

Leaving this open because we would want to highlight all the genes whose consequence was filtered on, and currently we only highlight the gene for the worst annotation

**Comment by hanars** [comment]
Should consider this while working on https://github.com/macarthur-lab/seqr-private/issues/421

**Comment by hanars** [comment]
also, within a gene should show a consequence that was sorted on and not neccessarily the main transcript

**Comment by hanars** [comment]
RNU4ATAC is a good example of this - its always the secondary gene because its non-coding even though the main gene is always intronic
