### ISSUE TITLE
Annotate variants in seqr with popmax AF

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2295]
**Is your feature request related to a problem? Please describe.**
seqr currently annotates variants with overall FAF, and overall FAF is used in searches. This leads to the return of many variants with high popmax AFs, which we do not want to waste time on in analysis.

**Describe the solution you'd like**
We'd like variants to instead be annotated with continental popmax AF (ie popmax AF in one of these 5 subpopulations: AFR, AMR, EAS, NFE, SAS). We'd also like popmax AF to be the values used in searches.

**Describe alternatives you've considered**
We considered whether we wanted to use popmax filtering AF (FAF) but ultimately decided against using FAF (partly because it may not be available for low frequency variants).

**Additional context**
This change was discussed with Anne and she asked me to submit the ticket.

**Comment by hanars** [comment]
This has been implemented and is now live for all projects
