### ISSUE TITLE
Document data model for mitochondrial indices

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr#2296]
Create a document clearly showing which fields exist in the provided mitochondrial matrix table and what fields we will be mapping them to in elasticsearch. Should also document any fields not included in the matrix table that we need to add in order to export to elasticsearch

Input MT: gs://seqr-datasets/cmg_mito/test_ten_cmg_mito_combined.mt

Documentation for fields for display/ search: https://docs.google.com/document/d/1q1cwvbal9fWPI5sgyIWcjX86kJ-x0irD/edit#

Data Model: https://docs.google.com/document/d/1AeBJIhzMWlhBhuJJOnqrUMHcAkRQlSub1kKrq_JLRfM/edit#heading=h.8lvj89xk368q

**Comment by ShifaSZ** [comment]
@hanars I finished the first round of the fields of the Elasticsearch indices. Please review it. You can find it in the chapter https://docs.google.com/document/d/1AeBJIhzMWlhBhuJJOnqrUMHcAkRQlSub1kKrq_JLRfM/edit#heading=h.e8uw4gr93cfj

**Comment by larrybabb** [comment]
@ShifaSZ check in with @hanars by Wednesday if this is still unfinished by then so we can review.

**Comment by ShifaSZ** [comment]
@hanars Data models are ready to review. I have some questions (in red color) especially in the [reference data](https://docs.google.com/document/d/1AeBJIhzMWlhBhuJJOnqrUMHcAkRQlSub1kKrq_JLRfM/edit?pli=1#heading=h.nop2hwwr9tt8) and [ES Index Record and Data Mapping ](https://docs.google.com/document/d/1AeBJIhzMWlhBhuJJOnqrUMHcAkRQlSub1kKrq_JLRfM/edit?pli=1#heading=h.471gen7yndgj)sections.

**Comment by hanars** [comment]
I left many other comments during my last review that still have not been addressed, and I was completely unable to review the UI requirements section because they way you suggested edits instead of actually editing the document made that section impossible to read (which was one of my review comments that has not yet been addfressed). gnomad was the biggest issue but all my comments were blocking

**Comment by hanars** [comment]
At this point we can say the documentation step is done
