### ISSUE TITLE
Create mitochnodrial loading pipeline

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr#2297]
Implement the loading pipeline for mitochondrial data. Output should conform to the data model specified by https://github.com/broadinstitute/seqr/issues/2296

Input MT: gs://seqr-datasets/cmg_mito/test_ten_cmg_mito_combined.mt

**Comment by ShifaSZ** [comment]
@hanars, I described the mito pipeline files and folders in [this document](https://docs.google.com/document/d/1AeBJIhzMWlhBhuJJOnqrUMHcAkRQlSub1kKrq_JLRfM/edit#heading=h.k55pd1ktism9). Please comment if they are appropriate.

**Comment by ShifaSZ** [comment]
Created a [PR](https://github.com/broadinstitute/hail-elasticsearch-pipelines/pull/306) for loading the mito reference data.
Continue on creating the mito schema.

**Comment by hanars** [comment]
closing this out as the main pipeline code has been merged. At this point, any changes to the mito pipeline will be captured in more specific tickets
