### ISSUE TITLE
Support mitochondrial indices in seqr search

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr#2298]
Add support for a mitochondrial dataset type for indices in seqr so mitochondrial indices can be loaded in addition to "regular" variants. 
Update search UI and backend to support the additional filters requested in the "Search" section in https://docs.google.com/document/d/1q1cwvbal9fWPI5sgyIWcjX86kJ-x0irD/edit#

**Comment by tommyli** [comment]
Hey @hanars, our group worked on Mitochondrial variants before (see [mitoreport](https://github.com/bioinfomethods/mitoreport)) so we're curious on the upcoming features on this.  I've submitted request for accessing the Google Doc link but if it contains anything sensitive then please reject.
