### ISSUE TITLE
Add RNA-seq expression outlier analysis results

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#2316]
We currently run [OUTRIDER](https://github.com/gagneurlab/OUTRIDER) to compute expression outliers in batches of RNA-seq  samples. The pipeline produces one output .tsv for all samples from a given tissue, across seqr projects. We currently have samples from 3 tissues: fibroblasts, muscle, whole blood. The format is:

```
sampleID        geneID  symbol  biotype pValue  padjust zScore  rawcounts       normcounts      meanCorrected   description     chr     start   end     strand  q
sampleId1  ENSG00000163349 HIPK1   protein_coding  7.77091714514281e-06    0.646659054220143       4.16    15512   6153.27 4093.3  homeodomain interacting protein kinase 1 [Source:HGNC Symbol;Acc:HGNC:19006]    1       113929192       113977869       1
       34
sampleId1  ENSG00000168675 LDLRAD4 protein_coding  4.14570542419572e-06    0.646659054220143       3.99    9425    3772.55 1545.16 low density lipoprotein receptor class A domain containing 4 [Source:HGNC Symbol;Acc:HGNC:1224] 18      13217498        136527
55        1       34
sampleId1  ENSG00000248923 MTND5P11        processed_pseudogene    1.50622263106982e-05    0.835604930417935       3.36    6796    821.07  216.12  mitochondrially encoded NADH:ubiquinone oxidoreductase core subunit 5 pseudogene 11 [Source:HGNC Symbol;Acc:HG
NC:42273] 5       134924648       134926459       -1      34
sampleId2 ENSG00000000003 TSPAN6  protein_coding  0.660373966825563       1       -0.41   664     681.82  717.62  tetraspanin 6 [Source:HGNC Symbol;Acc:HGNC:11858]       X       100627109       100639991       -1      34
sampleId2  ENSG00000000005 TNMD    protein_coding  0.871360793071309       1       0.32    100     284.46  326.49  tenomodulin [Source:HGNC Symbol;Acc:HGNC:17757] X       100584802       100599885       1       34
sampleId2  ENSG00000000419 DPM1    protein_coding  0.454123468249556       1       -0.73   3223    2438.06 2614.07 dolichyl-phosphate mannosyltransferase subunit 1, catalytic [Source:HGNC Symbol;Acc:HGNC:3005]  20      50934867        50958555        -1
      34
```

Here's the same table, verticalized:

```
>>> 2
$1        sampleID : SampleId1
$2          geneID : ENSG00000163349
$3          symbol : HIPK1
$4         biotype : protein_coding
$5          pValue : 7.77091714514281e-06
$6         padjust : 0.646659054220143
$7          zScore : 4.16
$8       rawcounts : 15512
$9      normcounts : 6153.27
$10  meanCorrected : 4093.3
$11    description : homeodomain interacting protein kinase 1 [Source:HGNC Symbol;Acc:HGNC:19006]
$12            chr : 1
$13          start : 113929192
$14            end : 113977869
$15         strand : 1
$16              q : 34
<<< 2

>>> 3
$1        sampleID : SampleId1
$2          geneID : ENSG00000168675
$3          symbol : LDLRAD4
$4         biotype : protein_coding
$5          pValue : 4.14570542419572e-06
$6         padjust : 0.646659054220143
$7          zScore : 3.99
$8       rawcounts : 9425
$9      normcounts : 3772.55
$10  meanCorrected : 1545.16
$11    description : low density lipoprotein receptor class A domain containing 4 [Source:HGNC Symbol;Acc:HGNC:1224]
$12            chr : 18
$13          start : 13217498
$14            end : 13652755
$15         strand : 1
$16              q : 34
<<< 3
```
This table has ~17,000 records per sample (approximately = the number of genes). 
I think the design should support overall RNA-seq sample counts in the low thousands (we current data we are in the low to mid hundreds), so on the order of ~20 million records. 

From previous discussions, the plan was to store this in a postgres table. The columns should probably be:  `sampleId, geneId, zScore,  pValue, padjust`  to allow dynamic volcano plots and other features.

Each volcano plot represents outlier in a given sample. Each dot is a gene. The x-axis is `zScore`, and the y-axis is `-log10(pValue)` , with labels shown by default for genes that have `padjust < 0.05`:

![image](https://user-images.githubusercontent.com/6240170/142923204-5c45be61-7da4-497d-9380-92dc07c731f0.png)

Potential features include
- showing the volcano plot(s) on the family page
- letting users adjust the 0.05 threshold, mouse-over genes below the threshold, and/or see where genes of interest are in the plot
- in addition to volcano plots, maybe showing a table of top genes in a sample, along with gene annotations from OMIM, etc.
- pre-populating variant search filters with outlier gene ids 
- highlighting gene expression outliers in variant search results

**Comment by hanars** [comment]
Note that whenever we get new sample we will want to reload all the existing data, so the data loading mechanism should be built to make that easy
