### ISSUE TITLE
Add RNAseq gene expression data

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#2319]
A basic output of the RNA-seq pipeline is the normalized expression for each gene in each sample. This number is just the count of RNA-seq reads that aligned to each gene, normalized by the gene's length and the total number of reads in the sample. The normalized units are transcripts-per-million (TPMs). 

This data could be provided as a gene x sampleId matrix (gzipped .tsv) for all RNA-seq samples, or as 1 file per sample. We discussed having this uploaded manually through an admin page. 

For users who may forget or not know the sample's tissue-of-origin, seqr should also ingest and show sample-level RNA-seq metadata such as the imputed tissue. Later we could add sample-level QC info like total number of RNA-seq reads, sequencing date, etc.

A typical use case is to compare the expression of a gene-of-interest in a given individual (or family - in the rare cases where we have RNA-seq for more than one family member) vs. other rare-disease samples in the same tissue vs. GTEx controls in relevant tissue(s). This can be done with box plots (or violin plots) where each dot is a sample - similar to the GTEx violin plots in the Gene Info window.

Here's an example of a plot showing 3 fibroblast samples from 1 family vs. all other fibroblast rare disease samples & 100 GTEx fibroblast samples:

![image](https://user-images.githubusercontent.com/6240170/142958996-a9abc4c2-3585-406d-a4ef-8e1a4cf01238.png)

Features could include:
- having a plot on the family page where a user could select the gene, and see TPMs plotted for the sample(s) from this family vs. other rare disease samples from the same tissue vs. GTEx samples from the same tissue.
- we discussed showing expression of samples from other projects without labeling the points (similar to gCNV background).
- showing this plot by clicking a variant search result.
- it can sometimes be useful to show other GTEx tissues beyond the one that exactly matches the tissue of origin (worth double-checking with users).

**Comment by hanars** [comment]
@anneodonnel my thought is for the first pass of this, we should have an option to view these plots in the variant search results (so you can see for the specific gene) but showing it on the family page is better as a future feature (since the UI for choosing a gene seems a bit unwieldy). But wanted to confirm that with you, we could add to the family page as part of the first pass if that seems important

**Comment by anneodonnell** [comment]
I agree that it should eventually be on the family page too but fine to just have in the variant results initially. 

Generally the plan sounds good - I worry about the 4th bullet point - showing other tissues. While it could be useful in some cases, it probably isn't generally useful and will be information overload. 

Also, we need to incorporate tissue type for DNA and RNA samples in GREGoR moving forward so you may want to incorporate that as a more general feature (though RNAseq could have 2 tissue types - reported and inferred). I'm going to make a separate GitHub ticket to track tissue type in seqr.
