### ISSUE TITLE
gCNV viewer CNV initial coordinates view

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2327]
gCNV viewer in seqr  
Change the default coordinates of the gCNV view when it first loads in seqr to encompass entire CNV +buffer on either side (100% of event size on each side so the SV takes up the middle third) to have a better visualization of the CNV (a more zoomed out view than what is currently displayed).

**Comment by Glemiret** [comment]
I played with gCNV viewer on seqr some more and it is faster to use (to zoom in and out), thanks! 
Can you actually change this: 
Change the default coordinates of the gCNV view when it first loads in seqr to encompass entire CNV +buffer on either side (**50**% of event size on each side so the SV takes up approximately the middle third) to have a better visualization of the CNV (a more zoomed out view than what is currently displayed).

**Comment by hanars** [comment]
this has been updated
