### ISSUE TITLE
GnomAD SV allele frequency hover over text 

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2328]
Add more detailed info about gnomAD SV frequency for CNVs in seqr as a hover over text (attached screen shot) so that users know how the allele count is determined for SV in seqr.
Change the hover over text to: "Filter by locus frequency (AF) among gnomAD SVs. The following criteria need to be met for a SV in gnomAD to be counted as an allele: 1) same SV type (deletion, duplication, etc) 2) For large SV >5Kb, a SV in gnomAD has to have a 50% reciprocal overlap or 3) for small SV< 5Kb, a SV in gnomAD has to have a 10% reciprocal overlap or 4) Insertion breakpoints within 100bp"
![Screen Shot 2021-11-18 at 3 44 32 PM](https://user-images.githubusercontent.com/84086816/143927425-b29c42b1-348f-451b-bf84-0fbb47a19933.png)
.

**Comment by hanars** [comment]
this has been updated
