### ISSUE TITLE
Project variant search - blank

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2330]
**Describe the bug**
Selecting Project variant search on the Family Page first leads to a blank page. Refreshing it works. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/project/R0285_cmg_gleeson_exomes

**Scope of the bug**
Across many projects 

**Screenshots**
<img width="1323" alt="Screen Shot 2021-12-01 at 9 51 03 AM" src="https://user-images.githubusercontent.com/37872186/144256628-020b8284-ea89-4b19-a347-a6820218a8ee.png">

**Comment by hanars** [comment]
this is fixed
