### ISSUE TITLE
Update MME contacts for 2 projects

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2341]
Can I request you to update the MME contacts for the Kang_v11 and CMG_Kang_LGMD_WES projects to include matchmaker@broadinstitute.org, pkang@umn.edu, ccbruels@umn.edu, Elicia.Estrella@childrens.harvard.edu, stafk006@umn.edu

Thanks,
Lynn

**Comment by lynnpais** [comment]
If you think the new feature can be implemented in the next week or so, there's no need to do this. We can just wait. If you think it might take you longer to get to it, we would appreciate it if you could update the contact for the two projects. Thanks.

**Comment by hanars** [comment]
this will take me the same amount of time as just implementing https://github.com/broadinstitute/seqr/issues/2342 so I will not be doing this a s a separate request
