### ISSUE TITLE
Update Estonian External Exomes project to hg38 

### ISSUE THREAD

**Issue by KaylaDelano** [broadinstitute/seqr#2353]
Please lift the Estonian External Exomes project: https://seqr.broadinstitute.org/project/R0322_estonian_external_exomes/project_page 

from hg37 to hg38. 

The index on elasticsearch is: r0322_estonian_external_exomes__wes__grch38__variants__v02__vcfv13__20211215

Please let me know if you need any other information. Thank you! 

-Kayla

**Comment by hanars** [comment]
@williamphu I'm seeing the following error with the index: 
"The following families are included in the callset but are missing some family members: HK043 (HK043_0106, HK043_0107, HK043_0108)"

That family previously had data for all 4 individuals but no appears to only have data for 1. Do we intentionally want to remove data from the other 3? Or was there an error with the callset generation or sample subsetting?

**Comment by williamphu** [comment]
I'll take a look at the callset for those individuals.

**Comment by williamphu** [comment]
A look at the v13 WES callset indicates that there are no individuals that start with HK043. Upon looking at the family, I noticed that the only individual that is in the callset for this family is HK064_0164, who is in the callset. Unsure about why the numbering is different for this individual.

**Comment by williamphu** [comment]
@KaylaDelano would you be able to check up on the family when you have time?

**Comment by williamphu** [comment]
Asked Kayla to follow up and it looks like there's not a lot of information on these samples - they're external samples without a lot of historical information. @KaylaDelano asked Anne, and her response was not to spend too much time investigating the family if there's not a lot of info. Kayla is wondering if we could exclude the HK043 samples (HK043_0106, HK043_0107, HK043_0108). What would that entail? If we remove data from these three, can we load HK064_0164 without the other three?

**Comment by hanars** [comment]
If we want to keep the one sample we have data for and exclude the other 3 I can do that. I can also exclude the entire family. Just let me know what we want to do in the end. Either way its something I can do myself as long as Anne/ the PM team says its okay

**Comment by KaylaDelano** [comment]
@hanars given that the samples included in the callset came from what CRAMs we have available (and that these are pretty old external samples), I think it makes most sense to exclude the 3 and keep the 1 included in the family. I will make a note to the analyst that the ID does not match up with the rest of the family, and that the rest of the family is not available. Thanks!

**Comment by hanars** [comment]
okay so I was able to "unload" the 3 samples, but I am now seeing another error:
```
The following families have saved variants but are missing from the callset: HK015, HK020, HK017, HK049, HK021, HK006, HK044, HK002, HK009, HK010, HK022, HK024, HK028, HK035, HK036, HK051, HK007, HK047, HK012, HK029, HK032, HK011, HK048.
```
That is a lot of families to be entirely missing from the index - can we confirm that we actually have hg38 data for everything in this project? Should we be splitting this project in 2 instead of trying to lift the whole thing?

**Comment by KaylaDelano** [comment]
Hi @hanars , we should split the project - sorry for the confusion- we only have data for a subset of samples, the list is attached ("Estonian External- CRAMs to load"). I'm not sure what I would need to do to split this (do I need to make a new seqr project?) but that is the route we should go. I've also attached the list of what is missing data, if that is helpful. 


[Estonian External- CRAMs to load.xlsx](https://github.com/broadinstitute/seqr/files/7864654/Estonian.External-.CRAMs.to.load.xlsx)
[Estonian External- Missing Data.xlsx](https://github.com/broadinstitute/seqr/files/7864656/Estonian.External-.Missing.Data.xlsx)

**Comment by hanars** [comment]
To split the project, create a new seqr project named whatever you think the 38 project should be named but make sure to create the project as build 37. Then provide me with a list of the families you want moved from the old project to the new one. This should ideally be all the projects we have 38 data for. I will then move those families form the old project to the new project and lift them to 38. What will be left is a new project on 38 with all the families we have 38 data for, and an old project with all the families we don;t. Tags, notes, etc will all stay with the appropriate families

**Comment by KaylaDelano** [comment]
Hi @hanars , I created the seqr project: https://seqr.broadinstitute.org/project/R0599_estonian_external_jan202/project_page for samples to be moved to hg38. Attached is a spreadsheet of families to load. 
Thanks! 
[~$Estonian-External_Families to load.xlsx](https://github.com/broadinstitute/seqr/files/7873381/Estonian-External_Families.to.load.xlsx)

**Comment by hanars** [comment]
families have been moved to the new project and lifted to hg38. Everything should be set now
