### ISSUE TITLE
frequency sub-fields too narrow to see values

### ISSUE THREAD

**Issue by jxchong** [broadinstitute/seqr#2356]
**Describe the bug**
If I expand the Frequency customization section in the Variant Search page, I see a horizontal list of control frequency datasets and a slider/text field where I can enter a custom value. The problem is that the text fields are so narrow that you can't actually see the number you are typing in. In the screenshot attached (Chrome, Mac), I entered "1" into all of the AC and H/H fields but it actually looks like the AC fields are empty (which then is confusing because the slider for AF switches to 1, while the actual value for AC is much more stringent.

**Link to page(s) where bug is occurring**
N/A own instance

**Scope of the bug**
all projects

**Screenshots**
<img width="1454" alt="Screen Shot 2021-12-16 at 2 58 28 PM" src="https://user-images.githubusercontent.com/1133838/146461267-4d52efae-f9d6-418f-a343-50c9105ddf77.png">

**Comment by hanars** [comment]
Converting to a feature request, as what this is actually asking for is support for seqr on a smaller screen

**Comment by jxchong** [comment]
Got it thanks. For what it's worth, it's not *that* small a screen (16" MBP)😉

**Comment by hanars** [comment]
This is fixed now, thanks for reporting the issue!
