### ISSUE TITLE
Position of Classify feature

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2357]
**Is your feature request related to a problem? Please describe.**
The Classify feature can be better placed and less distracting as it currently is.

**Describe the solution you'd like**
We propose to move the classify feature to where the other tags are listed, adjacent to the edit tags feature. Also, we would like for the color to be changed to a grey outline, but not filled in. 

**Describe alternatives you've considered**
This is what we discussed at the analyst meeting yesterday. If there are any issues with this proposal, we can reconsider. 

**Additional context**
Below is a mock up for heterozygous and compd hets
<img width="1006" alt="Screen Shot 2021-12-17 at 11 03 39 AM" src="https://user-images.githubusercontent.com/37872186/146573340-3afe6a77-dbe5-488f-9461-72ef6a7148d1.png">

<img width="1029" alt="Screen Shot 2021-12-17 at 11 03 51 AM" src="https://user-images.githubusercontent.com/37872186/146573347-a2f64e53-641e-4fef-bc38-fa0d774e47ec.png">

**Comment by hanars** [comment]
I ended up moving this to the same row as the tags like you asked, but on the right of the variant next to the variant-specific link instead of next to the edit tag button as it looked a little neater this way
