### ISSUE TITLE
Position of variants in alternate transcripts

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2358]
**Is your feature request related to a problem? Please describe.**
The current position of variants in alternate transcripts can be confusing to the user. 

**Describe the solution you'd like**
We propose to move it to the variant information column, between the HGVS.P info and the chr location. 

**Describe alternatives you've considered**
This was discussed at the analyst meeting yesterday. 

**Additional context**
Here's an example
<img width="953" alt="Screen Shot 2021-12-17 at 11 12 34 AM" src="https://user-images.githubusercontent.com/37872186/146574467-d49e6168-bc37-4217-9c0b-8bbbc2e9782d.png">

**Comment by hanars** [comment]
this has been updated
