### ISSUE TITLE
Add STRVCTVRE scores to seqr for genome SV data

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#2368]
**Is your feature request related to a problem? Please describe.**
Add STRVCTVRE scores to seqr for genome SV data

**Comment by hanars** [comment]
Blocked on William generating the file

**Comment by ShifaSZ** [comment]
Updated the code to add the STRVCTVRE score field. Waiting for William to fix a VCF file issue.

**Comment by ShifaSZ** [comment]
The VCF file issue has been fixed. I created a [PR](https://github.com/broadinstitute/hail-elasticsearch-pipelines/pull/295) to update the loading pipeline.

**Comment by ShifaSZ** [comment]
@anneodonnell How do you like the STRVCTVRE scores to be used in search and displayed?

**Comment by hanars** [comment]
@anneodonnell please disregard

**Comment by hanars** [comment]
These scores have need added
