### ISSUE TITLE
Add an AF cutoff to Gene Search feature

### ISSUE THREAD

**Issue by eoheir** [broadinstitute/seqr#2373]
**Is your feature request related to a problem? Please describe.**
Currently, the 'Gene Search' link used to find additional hits in a gene searches for **all** variants in that gene in any affected individual. This often returns a large number of very common variants that are not relevant, so the analysts typically end up adjusting the allele frequency filter to eliminate these variants. 

**Describe the solution you'd like**
We would like the allele frequency filter to be set to 10% as default for Gene Searches, in order to ignore the very common variants. 

The hover-over text for the Gene Search link will also need to be modified to: "Search this gene for variants with an allele frequency <10% present in any affected individual."

**Describe alternatives you've considered**
This was discussed at our most recent analyst meeting. 

**Additional context**
Example:
<img width="928" alt="Screen Shot 2022-01-07 at 10 00 10 AM" src="https://user-images.githubusercontent.com/57765157/148563595-ed17a9c1-2563-4f66-9dd9-dba38f68a87a.png">

**Comment by hanars** [comment]
For the AF filter, would you like it applied to all populations or just some of them (i.e. gnomad), and do you want it to apply to "this callset"

**Comment by eoheir** [comment]
Let's apply it to all populations. Applying it to the callset doesn't appear to make much of a difference, so I think that can just be left as is. Thank you!

**Comment by hanars** [comment]
this has been updated
