### ISSUE TITLE
Unusual variant search results in CMG_NeuroDev_WES

### ISSUE THREAD

**Issue by eoheir** [broadinstitute/seqr#2375]
**Describe the bug**
I've been noticing some strange variant search behavior in several of the new NeuroDev cases that were loaded on 12/16/2021. When I run our standard de novo/dominant permissive or recessive restrictive and permissive searches, several variants are being returned in which none of the family members (including the proband) appear to have any alt alleles. Do you have any idea why this might be happening? 

**Link to page(s) where bug is occurring**
I've noticed this in several cases so far, but here are just a few examples:
https://seqr.broadinstitute.org/variant_search/results/6de3e7681befe287ad34e9b9393dc54d?page=1&sort=protein_consequence
https://seqr.broadinstitute.org/variant_search/results/2d07263ef26f30e150ecc0ffa24012f2?page=1&sort=protein_consequence
https://seqr.broadinstitute.org/variant_search/results/6861abf8e4f3978b329bb0040ee22557?page=1&sort=protein_consequence

**Scope of the bug**
I checked a few other projects and have not seen this issue come up anywhere else. It also only seems to be happening with the latest batch of NeuroDev cases (not every single case, but the majority that I've checked). 

**Screenshots**
Example of search results from a de novo permissive search:
![Screen Shot 2022-01-07 at 3 17 17 PM](https://user-images.githubusercontent.com/57765157/148601951-44ab9ca5-a42a-4a22-afcc-dd8df9e9a8ff.png)

Taking a closer look into one of these variants, it appears that this issue is only occurring in the NeuroDev case, and that the variant behaves normally in all other projects:
<img width="900" alt="Screen Shot 2022-01-07 at 3 21 51 PM" src="https://user-images.githubusercontent.com/57765157/148602693-cfb29356-f8d6-490e-8f29-1c9481186cb2.png">

**Comment by hanars** [comment]
@mike-w-wilson @williamphu this appears to be a pipeline bug where the same sample id is being added to the genotypes list twice - for example in elasticsearch for one of these variants I am seeing
```
"variantId" : "1-17750-G-A",
"genotypes" : [
...
            {
              "num_alt" : 1,
              "ab" : 0.1071428582072258,
              "sample_id" : "859-55379524-01",
              "gq" : 54,
              "dp" : 84.0
            },
...
            {
              "num_alt" : 0,
              "ab" : null,
              "sample_id" : "859-55379524-01",
              "gq" : 40,
              "dp" : 28.0
            },
...
]
```

Not sure if this is an issue with duplicate sample IDs, or a sample remap issue, or if its actually a non-sample specific bug. This was loaded on 12/15 off of `v12` of the `RDG_WES_Broad_Internal` callset, although a couple days later we loaded a couple of other projects off of `v13`. I spot checked those projects and they look fine

**Comment by williamphu** [comment]
@hanars is this limited to the R0526_cmg_neurodev_wes project? If so, I believe I fond the issue - there are duplicate sample IDs in the sample ID file, which looks to be the result of duplicate sample ids being listed in the rollup in Airtable for remapping VCF ID's to Seqr ID's. I will follow up with the PM team.

**Comment by hanars** [comment]
We have only seen the issue in the one project, so thats probably it

**Comment by hanars** [comment]
These families have been removed form seqr, and the issue should be fixed for all other families
