### ISSUE TITLE
Case Review page not functioning correctly

### ISSUE THREAD

**Issue by gvannoy** [broadinstitute/seqr#2377]
The Case Review page for the RGP Genomes project is not working correctly. It only loads if the user scrolls down while on the page. When loaded, a few actions cause the entire page (not just the family results) to 'crash' and go completely blank. These actions include using the search bar, editing the 'Assigned analyst' field. When I click the back arrow on the browser to get out of the blank page, it prompts me to log in again every time.  

https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/case_review

This is impacting RGP Genomes project, but we have not been in any other projects. I think that we are the only group that uses Case Review, so others may not have noticed if there is an issue in other projects.

**Comment by hanars** [comment]
@caustint this is probably related to a cached search you did. Please either clear your local storage (https://www.leadshook.com/help/how-to-clear-local-storage-in-google-chrome-browser/)  or use a different browser (i.e. safarai)until this bug is fixed

**Comment by hanars** [comment]
this should all be fixed now
