### ISSUE TITLE
Test users credentials

### ISSUE THREAD

**Issue by zbedo** [broadinstitute/seqr#2378]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Provide test user's credentials.

**Additional context**
Please provide at least two test user's credentials for every permission level in this service.

**Comment by hanars** [comment]
seqr has upped its security since we set up testing accounts for Albano. Please provide me with 3 valid google email accounts that have been registered in anvil and I will set them up for you
