### ISSUE TITLE
Reorganize saved search menu

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2385]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
We'd like to reorder the default searches in the saved search menu as follows:
None
De novo/dominant restrictive
Recessive restrictive
De novo/dominant permissive
Recessive permissive
De novo/dominant - SV - Proband/duo
De novo/dominant - SV - Trio
Recessive SV

**Describe alternatives you've considered**
Happy to discuss if there are any issues

**Additional context**

**Comment by hanars** [comment]
this is doable, but currently everything is just sorted alphabetically so this is a bit more work than you would expect. Noting that here so I don't get confused and think I can do this too quickly

**Comment by ShifaSZ** [comment]
Is it about the order of the variants in the search results or just the order of the items in the saved search menu?

**Comment by hanars** [comment]
order has been updated
