### ISSUE TITLE
Unexpected formatting for Slack notifications for sample loading

### ISSUE THREAD

**Issue by williamphu** [broadinstitute/seqr#2391]
This is a super minor bug.

**Describe the bug**
The message for notifying new samples loaded in slack for this project https://seqr.broadinstitute.org/project/R0554_tgg_shimamura_wes/project_page was malformed.

Not sure if one of the characters in the sample ids broke formatting, or if it's a slack API character limit (which we couldn't fix).

**Link to page(s) where bug is occurring**
https://the-tgg.slack.com/archives/CA620K989/p1642183928000100

**Scope of the bug**
Limited to slack notifications.

**Comment by hanars** [comment]
Its a slack character limit 😢 If we keep running into this issue we could break the message apart ourselves, but I'm not sure that much beter than whats happening here, so for now I will leave this as is. Thanks for reporting it though!
