### ISSUE TITLE
Customizations to new Rare Genomes Project_Genomes_GRU project needed

### ISSUE THREAD

**Issue by gvannoy** [broadinstitute/seqr#2392]
The new project page for RGP genomes (Rare Genomes Project_Genomes_GRU) needs the same customizations as the prior project page (Rare Genomes Project_Genomes_HMB) including:

1. 'Bulk Edit Metadata' changed to 'Edit Families and Individuals' with the accompanying 5 tabs of options (as pictured in figure below)
2. Ability to bulk upload new families from the same export sheet that the Rare Genomes Project_Genomes_HMB project uses and have this information display correctly in the case review view. 
3. Add case review permission for all users who have this level of access in the Rare Genomes Project_Genomes_HMB project.

![image](https://user-images.githubusercontent.com/40441144/149581626-1865476b-f62d-406c-9a59-80fcb9a9f5ac.png)

**Comment by hanars** [comment]
done!

**Comment by gvannoy** [comment]
So fast!! Amazing, thank you :)
