### ISSUE TITLE
seqr hyperlink hover over text 

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2394]
Add the following text in the existing hover over text on the seqr hyperlink under the variant annotation: “Search for this variant across all your seqr projects. For CNVs: Any variant with ≥20% reciprocal overlap will be returned.
![Screen Shot 2022-01-13 at 4 49 57 PM](https://user-images.githubusercontent.com/84086816/149960152-d7097201-2e43-4725-bc20-88ab30aa5268.png)
”

**Comment by hanars** [comment]
do we want this to say SVs instead of CNVs, as I'm pretty sure thats also the case for SVs?

**Comment by Glemiret** [comment]
Yes great idea. And let's avoid acronyms. 
"Search for this variant across all your seqr projects. For structural variants: Any variant with ≥20% reciprocal overlap will be returned"

**Comment by hanars** [comment]
Oh I was going to just make the text conditional on whether or not the variant was an SV. So show "Search for this variant across all your seqr projects. Any variant with ≥20% reciprocal overlap will be returned" on SVs, and leave the text as-is for SNPs

**Comment by Glemiret** [comment]
Sounds good. 
For SV only can we add the word structural in the hover over text: ""Search for this variant across all your seqr projects. Any **structural** variant with ≥20% reciprocal overlap will be returned"
Thanks!

**Comment by hanars** [comment]
this has been added

**Comment by Glemiret** [comment]
Thanks! 
Can you just correct the typo, strictural--> structural
Thanks!

**Comment by hanars** [comment]
fixed
