### ISSUE TITLE
Hover over text on gnomAD SV link

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2395]
Add a hover over text over the gnomAD SV link (red arrow on attached screenshot) that says: “The following criteria need to be met for an SV in gnomAD to be counted as an allele: Has the same SV type (deletion, duplication etc) and either has sufficient reciprocal overlap (SVs>5Kb need 50%, SVs<5 kb need 10%) or has insertion breakpoints within 100bp.
![Screen Shot 2022-01-13 at 5 02 28 PM](https://user-images.githubusercontent.com/84086816/149961262-30276d44-ed05-4145-9ac2-90a3ccc28d78.png)
”

**Comment by hanars** [comment]
this has been added
