### ISSUE TITLE
gnomAD SV link malfunction 

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2396]
Clicking on the gnomAD SV hyperlink in different families in the CMG_gCNV project lead to a gnomAD page saying "variant not found" when there were reported allele counts in gnomAD SV. The gnomAD SV link works in other families in this project. 
Examples of families where the link does not work: 4778 and 3386. 
https://seqr.broadinstitute.org/variant_search/results/5ea0c8de66c7c815ff3037a2a971606c?page=1&sort=xpos
https://seqr.broadinstitute.org/variant_search/results/3be19138923fd54b4198bac683445d2f?page=1&sort=xpos

![Screen Shot 2022-01-18 at 11 06 09 AM](https://user-images.githubusercontent.com/84086816/149974749-9ce21db5-38aa-45db-96c1-d596ec997ab6.png)
![Screen Shot 2022-01-18 at 11 06 22 AM](https://user-images.githubusercontent.com/84086816/149974765-10cac855-3f20-4bc2-a3ee-fa35e8fa6657.png)

**Comment by hanars** [comment]
@ShifaSZ it appears many variants are missing the `gnomad_svs_ID` field in the elasticsearch index. We expect this value for all variants that have `gnomad_svs_AF` so this is probably either a bug in the pipeline or in the data we were delivered

**Comment by hanars** [comment]
gnomad_sv_ID field missing from the delivered VCF. This is blocked on receiving updated data
