### ISSUE TITLE
Missing Copy Number (CN) in some CNV calls

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2398]
Some CNVs lack the Copy Number (CN) calls in some families from the CMG_gCNV project. 
For example, family 3386, MCAI054
https://seqr.broadinstitute.org/variant_search/results/3be19138923fd54b4198bac683445d2f?page=1&sort=xpo
https://seqr.broadinstitute.org/variant_search/results/92b4303dbe3c71124fb01f8e610e9eef?page=1&sort=xpos
![Screen Shot 2022-01-19 at 12 55 41 PM](https://user-images.githubusercontent.com/84086816/150187524-c4b68074-cfa7-4c06-b0a3-4fbc9b0c3726.png)
![Screen Shot 2022-01-19 at 12 59 10 PM](https://user-images.githubusercontent.com/84086816/150187583-9fa066dc-e05f-479e-8062-94b6b63bf4dd.png)
![Screen Shot 2022-01-19 at 1 01 18 PM](https://user-images.githubusercontent.com/84086816/150187934-d0cba4de-d228-45b6-af37-463ddbc5f3e4.png)
![Screen Shot 2022-01-19 at 1 01 02 PM](https://user-images.githubusercontent.com/84086816/150187948-05bd904c-6fee-4531-9b6c-b555aecef0d5.png)

**Comment by hanars** [comment]
apparently, seqr will not show a "ref" CN for alt variants. So it isn't showing a CN of 2 (or CN of 1 for the X variants in males). Thats a bug, we should be showing those. I think its kind of weird that there are deletions called as "alt" that have a CN of 2, but :shrug:

**Comment by Glemiret** [comment]
Thanks for looking into this. Why would a deletion have a CN of 2?

**Comment by hanars** [comment]
I have no idea, its really more a question for Alba or Harrison. I did have Shifa double check the VCF for the CEP112 deletion because I thought it was so weird to call a deletion as hom alt with a CN of 2, but that is what was in the VCF we received

**Comment by Glemiret** [comment]
Yes that does not make sense. It should be CN:0. This will be confusing to analyze.

**Comment by hanars** [comment]
so seqr can not be in the business of QCing the data in the application and seqr can't just invent a CN because its the value people expect to see. Essentially, our options here are:
1. Don't show the CN at all (current behavior, confusing)
2. Show the CN of 2 with a warning triangle indicating the call type does not match the CN (the current behavior in the cases where this already happens i.e. a DEL with CN 3)
3. Push back on the Talkowski group to resolve all of these calls in their pipeline before they deliver data to us, and hold off on loading all data to seqr until they do so

**Comment by Glemiret** [comment]
But "CN:2" usually appear in seqr under the sample name, so why is it not appearing here if that is what is in the vcf? 

I just chatted with Anne. We might need to do Option 2 to not delay SV data upload. But she wanted us to ask Harrison and Alba first their thoughts on this bug and how easy it would be to fix. 

Here is a suggested post on the cmg_sv channel; Do you agree with the phrasing (or can you make it clearer)?

I noticed some discrepancies in copy number calls in some families from the CMG_gCNV project in seqr (genomes). Some CNVs lack the Copy Number (CN) calls, examples in screenshots below. Hana and Shifa verified the vcf for the CEP112 homozygous deletion and the copy number is 2 (and it should be CN:0). What do you think is the source of these bugs in the vcf?

**Comment by hanars** [comment]
> But "CN:2" usually appear in seqr under the sample name, so why is it not appearing here if that is what is in the vcf?

Per my earlier response "apparently, seqr will not show a "ref" CN for alt variants. So it isn't showing a CN of 2 (or CN of 1 for the X variants in males). Thats a bug, we should be showing those.". This is only a bug for WGS SVs, not WES gCNV calls

I'll post in the channel, I think linking the VCF will make more sense to them than the screenshots

**Comment by Glemiret** [comment]
Oh I understand now, thank you. 

Thank you for posting on the channel. I think we'll go with Option 2 with a warning.

**Comment by hanars** [comment]
per discussion in slack, the warning displayed will be  "Copy number does not match genotype. Copy number calling may be unreliable for small events, however genotype call is likely accurate"

**Comment by hanars** [comment]
copy numbers are now showing with a warning

**Comment by Glemiret** [comment]
thank you!
