### ISSUE TITLE
Bug in genotype display on project-wide search

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2410]
For project-wide search, the genotypes are not shown on each family (for both CNVs and SNVs). They are shown if the page is refreshed. This has been discussed with Hana. 

https://seqr.broadinstitute.org/variant_search/results/474adf0206d301bb2560d3159fc231d7?page=1&sort=xpos

![image](https://user-images.githubusercontent.com/84086816/150589175-3a173236-e153-486c-9bba-fda9d9329573.png)

**Comment by hanars** [comment]
this is fixed
