### ISSUE TITLE
Add hover over text for the gCNV tags 

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2411]
Add a hover over text for the current gCNV tags to clarify for the casual user the meaning of these tags
For the "Identical call" tag, add hover over text: "Identical call in previous callset" 
For the "Overlapping call" tag, add hover over text: "Overlapping call in previous callset" 
For the "new call" tag, add hover over text: "No overlap in previous callset" 

Thanks!

**Comment by hanars** [comment]
these have been added
