### ISSUE TITLE
Annotations selection result in no variants 

### ISSUE THREAD

**Issue by Ikeoluwa-O-O** [broadinstitute/seqr#2413]
A collaborator for the [CMG_Muntoni_External_Genome](https://seqr.broadinstitute.org/project/R0536_cmg_muntoni_external_gen/project_page) project discovered that no variants are returned when `TF binding site variant` or `regulatory region variant` is selected in the Annotations section of a customized search. No other search criteria is selected. 

When I performed this same search, I also found no variants. 
![Screen Shot 2022-01-24 at 12 28 40 PM](https://user-images.githubusercontent.com/84587859/150833795-faf8a687-c5ce-46e5-a9bb-f874919ef6a2.png)

![Screen Shot 2022-01-24 at 11 53 58 AM](https://user-images.githubusercontent.com/84587859/150827943-63860c5d-c19c-403b-b277-13bece5ff373.png)

I tried this with other genome cases in seqr (RGP and a non-external Manton project). I ran into the same issue. Given that we at least expect some variants in these genomic regions, could this be a bug?

**Comment by hanars** [comment]
Hey thanks for reporting the issue! In the future, please try to submit all your github requests using an issue template. You can start [here](https://github.com/broadinstitute/seqr/issues/new/choose) and select either "bug report" or "feature request" (in this case it would be a bug report) and it will prompt you for the information I need from you and will automatically add tags that help me triage issues. 
The important thing that it would have prompted you for in this case is links to the page where the issue is happening. While the link to the project page is nice, I usually need links to the search pages themselves where you are seeing issues. 

I was able to replicate the error on my own so I don't need anything else from you at this time, just wanted to let you know for the future!

**Comment by hanars** [comment]
Digging in to the actual issue more, this is an issue for all seqr projects, and actually there are a few more annotations that are entirely missing, in total the following 10 consequences are completely absent from seqr
```
feature_elongation
feature_truncation
initiator_codon_variant
regulatory_region_ablation
regulatory_region_amplification
regulatory_region_variant
TF_binding_site_variant
TFBS_ablation
TFBS_amplification
transcript_amplification
```

@mike-w-wilson could we be misconfiguring VEP somehow in the pipeline? It seems incredibly unlikely to me that there is not a single variant in any project at all in seqr where at least one transcript would have any of those consequences...

`nc_transcript_variant` and `non_coding_exon_variant` also are not in the seqr data but those appear to be holdovers from a previous version of VEP and  have been replaced with other values in the UI so we should actually just remove those as options

while looking into it I also noticed there are `start_retained_variant` in the data but no UI filter for them so we should also probably add that as an option. But I digress

**Comment by mike-w-wilson** [comment]
I reviewed the raw vep output in the pipeline. Here are the consequence terms and their counts for the latest internal exome callset:
```
'3_prime_UTR_variant': 5278313
'5_prime_UTR_variant': 2084995
'NMD_transcript_variant': 10510720
'coding_sequence_variant': 39116
'downstream_gene_variant': 28586983
'frameshift_variant': 472047
'incomplete_terminal_codon_variant': 1842
'inframe_deletion': 131596
'inframe_insertion': 95529
'intron_variant': 64241621
'mature_miRNA_variant': 4793
'missense_variant': 6198633
'non_coding_transcript_exon_variant': 7939821
'non_coding_transcript_variant': 15974526
'protein_altering_variant': 16186
'splice_acceptor_variant': 189926
'splice_donor_variant': 114569
'splice_region_variant': 1845062
'start_lost': 24435
'start_retained_variant': 510
'stop_gained': 172118
'stop_lost': 10357
'stop_retained_variant': 4702
'synonymous_variant': 3554044
'transcript_ablation': 6
'upstream_gene_variant': 23823027
```
and the latest genome callset:
```
'3_prime_UTR_variant': 1782758
'5_prime_UTR_variant': 493871
'NMD_transcript_variant': 17914955
'coding_sequence_variant': 5660
'downstream_gene_variant': 27310368
'frameshift_variant': 47519
'incomplete_terminal_codon_variant': 277
'inframe_deletion': 23912
'inframe_insertion': 14553
'intron_variant': 179550326
'mature_miRNA_variant': 1321
'missense_variant': 1022989
'non_coding_transcript_exon_variant': 2351299
'non_coding_transcript_variant': 51451376
'protein_altering_variant': 1049
'splice_acceptor_variant': 27754
'splice_donor_variant': 22028
'splice_region_variant': 352449
'start_lost': 3027
'start_retained_variant': 81
'stop_gained': 20848
'stop_lost': 1638
'stop_retained_variant': 909
'synonymous_variant': 808976
'transcript_ablation': 2
'upstream_gene_variant': 27496351
``` 
Those terms are not present in our datasets. We do not filter this in the pipeline and it does not look like the hail vep configuration, which the pipelne utilizes, does either.

```
{"command": [
    "/vep",
    "--format", "vcf",
    "__OUTPUT_FORMAT_FLAG__",
    "--everything",
    "--allele_number",
    "--no_stats",
    "--cache", "--offline",
    "--minimal",
    "--assembly", "GRCh38",
    "--fasta", "/opt/vep/.vep/homo_sapiens/95_GRCh38/Homo_sapiens.GRCh38.dna.toplevel.fa.gz",
    "--plugin", "LoF,loftee_path:/opt/vep/Plugins/,gerp_bigwig:/opt/vep/.vep/gerp_conservation_scores.homo_sapiens.GRCh38.bw,human_ancestor_fa:/opt/vep/.vep/human_ancestor.fa.gz,conservation_file:/opt/vep/.vep/loftee.sql",
    "--dir_plugins", "/opt/vep/Plugins/",
    "-o", "STDOUT"
],
 "env": {
     "PERL5LIB": "/vep_data/loftee"
 },
 "vep_json_schema": "Struct{assembly_name:String,allele_string:String,ancestral:String,colocated_variants:Array[Struct{aa_allele:String,aa_maf:Float64,afr_allele:String,afr_maf:Float64,allele_string:String,amr_allele:String,amr_maf:Float64,clin_sig:Array[String],end:Int32,eas_allele:String,eas_maf:Float64,ea_allele:String,ea_maf:Float64,eur_allele:String,eur_maf:Float64,exac_adj_allele:String,exac_adj_maf:Float64,exac_allele:String,exac_afr_allele:String,exac_afr_maf:Float64,exac_amr_allele:String,exac_amr_maf:Float64,exac_eas_allele:String,exac_eas_maf:Float64,exac_fin_allele:String,exac_fin_maf:Float64,exac_maf:Float64,exac_nfe_allele:String,exac_nfe_maf:Float64,exac_oth_allele:String,exac_oth_maf:Float64,exac_sas_allele:String,exac_sas_maf:Float64,id:String,minor_allele:String,minor_allele_freq:Float64,phenotype_or_disease:Int32,pubmed:Array[Int32],sas_allele:String,sas_maf:Float64,somatic:Int32,start:Int32,strand:Int32}],context:String,end:Int32,id:String,input:String,intergenic_consequences:Array[Struct{allele_num:Int32,consequence_terms:Array[String],impact:String,minimised:Int32,variant_allele:String}],most_severe_consequence:String,motif_feature_consequences:Array[Struct{allele_num:Int32,consequence_terms:Array[String],high_inf_pos:String,impact:String,minimised:Int32,motif_feature_id:String,motif_name:String,motif_pos:Int32,motif_score_change:Float64,strand:Int32,variant_allele:String}],regulatory_feature_consequences:Array[Struct{allele_num:Int32,biotype:String,consequence_terms:Array[String],impact:String,minimised:Int32,regulatory_feature_id:String,variant_allele:String}],seq_region_name:String,start:Int32,strand:Int32,transcript_consequences:Array[Struct{allele_num:Int32,amino_acids:String,appris:String,biotype:String,canonical:Int32,ccds:String,cdna_start:Int32,cdna_end:Int32,cds_end:Int32,cds_start:Int32,codons:String,consequence_terms:Array[String],distance:Int32,domains:Array[Struct{db:String,name:String}],exon:String,gene_id:String,gene_pheno:Int32,gene_symbol:String,gene_symbol_source:String,hgnc_id:String,hgvsc:String,hgvsp:String,hgvs_offset:Int32,impact:String,intron:String,lof:String,lof_flags:String,lof_filter:String,lof_info:String,minimised:Int32,polyphen_prediction:String,polyphen_score:Float64,protein_end:Int32,protein_start:Int32,protein_id:String,sift_prediction:String,sift_score:Float64,strand:Int32,swissprot:String,transcript_id:String,trembl:String,tsl:Int32,uniparc:String,variant_allele:String}],variant_class:String}"
}
```

**Comment by hanars** [comment]
@anneodonnell essentially this means there are a bunch of theoretically possible but very rare consequences that in fact don't exist in any of our callsets but theoretically could in the future. Given that, should we leave seqr's behavior as is, or should we remove them as options for filtering to prevent collaborators from getting confused the way they did here

**Comment by hanars** [comment]
Discussed offline, Anne seems very skeptical that there really aren't any of these in our data, and Mike will do further investigation. We think this is an issue upstream of our pipeline

**Comment by mike-w-wilson** [comment]
Waiting until we update VEP to investigate as the fields are not really used

**Comment by mike-w-wilson** [comment]
@lynnpais, gnomAD and GTEx both went to 105. Do we want to update to 109 or sync with those two projects?

**Comment by lynnpais** [comment]
@anneodonnell gnomAD is on 105 and so will v4. Do you would want to go with the same?

**Comment by mike-w-wilson** [comment]
A little more information, VEP 109 uses GENCODE 43 while VEP 105 uses GENCODE 39.

**Comment by lynnpais** [comment]
Thanks, Mike! I thought to mention too and added it to my prior note.

**Comment by gilmorera** [comment]
So is this an issue with VEP?

**Comment by gilmorera** [comment]
Or hail?  We are having similar issue and if you've discovered something please let me know.  We're using VEP108 and `--everything`, but we're considering testing with `--regulatory` to see if things change.

**Comment by gilmorera** [comment]
@hanars Someone on our team has confirmed that using VEP (v101) by itself does annotate with the regulatory terms, when using `--regulatory` or `--everything`.

I also did a query on all of our ES indices to see if these terms were in any of our datasets:
```json
GET index1,....,index79/_search
{
  "query": {
    "terms": {
      "transcriptConsequenceTerms": [
        "feature_elongation",
        "feature_truncation",
        "initiator_codon_variant",
        "regulatory_region_ablation",
        "regulatory_region_amplification",
        "regulatory_region_variant",
        "TF_binding_site_variant",
        "TFBS_ablation",
        "TFBS_amplification",
        "transcript_amplification"
        ]
    }
  }
}
```

This query returned nothing.  I did a check with some other terms to make sure my query wasn't faulty and I received results.

I also downloaded and checked one of our hail tables.  It seems the regulatory consequence terms are stored in another struct:
```python
mt2.group_rows_by(mt2.vep.regulatory_feature_consequences.consequence_terms).aggregate(n=hl.agg.count()).show()
[Stage 255:=================================================>  (474 + 16) / 500]2023-10-03 13:09:48 Hail: INFO: Coerced sorted dataset
2023-10-03 13:09:48 Hail: INFO: Coerced dataset with out-of-order partitions.
+------------------------------------------------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+
| consequence_terms                                          |        'S1'.n        |        'S2'.n        |        'S3'.n       |        'S4'.n        |        'S5'.n        |        'S6'.n        |        'S7'.n        |
+------------------------------------------------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+
| array<str>                                                 |             int64 |             int64 |             int64 |             int64 |             int64 |             int64 |             int64 |
+------------------------------------------------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+
| ["regulatory_region_ablation","regulatory_region_variant"] |                27 |                27 |                27 |                27 |                27 |                27 |                27 |
| ["regulatory_region_variant"]                              |          20800484 |          20800484 |          20800484 |          20800484 |          20800484 |          20800484 |          20800484 |
+------------------------------------------------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+-------------------+
```
So it seems like something is potentially lost in translation when converting from the Matrix Table to the ES index.  What do you think?

**Comment by gilmorera** [comment]
Also just wanted to point out the fields:
```python
Also wanting to point this out:

In [192]: list(mt2.vep.regulatory_feature_consequences.keys())
Out[192]:
['allele_num',
'biotype',
'consequence_terms',
'impact',
'minimised',
'regulatory_feature_id',
'variant_allele']

In [191]: list(mt2.vep.transcript_consequences.keys())
Out[191]:
['existing_inframe_oorfs',
'existing_outofframe_oorfs',
'existing_uorfs',
'five_prime_utr_variant_consequence',
'five_prime_utr_variant_annotation',
'allele_num',
'amino_acids',
'appris',
'biotype',
'canonical',
'ccds',
'cdna_start',
'cdna_end',
'cds_end',
'cds_start',
'codons',
'consequence_terms',
'distance',
'domains',
'exon',
'gene_id',
'gene_pheno',
'gene_symbol',
'gene_symbol_source',
'hgnc_id',
'hgvsc',
'hgvsp',
'hgvs_offset',
'impact',
'intron',
'lof',
'lof_flags',
'lof_filter',
'lof_info',
'minimised',
'polyphen_prediction',
'polyphen_score',
'protein_end',
'protein_start',
'protein_id',
'sift_prediction',
'sift_score',
'strand',
'swissprot',
'transcript_id',
'trembl',
'tsl',
'uniparc',
'variant_allele']
```
The `mt.vep.reg_feat_conseq` struct has a unique field `regulatory_feature_id`, which is why I'm guessing it's a separate data structure.

**Comment by hanars** [comment]
thanks! This is very helpful

**Comment by gilmorera** [comment]
Hi @hanars .  I know there hasn't been much time to evaluate any of this info I posted, but I was curious if you think this is something actionable?  If so do you think there will be any headway on this in the short term?

I'm asking for a friend 😛.  If this issue is a priority for you all then we might work on something else in the meantime.

**Comment by hanars** [comment]
We are planning to do a full overhaul of how we run VEP in early 2024, with the goal of using a more updated version, better aligning with how the gnomad v4 release calls VEP, and adding some additional plugins.We will certainly make sure to address this issue as part of that overhaul,  but it is unlikely that we will address this issue until then.

If you or your friend are interested in working on this yourselves, we would be happy to accept a pull request that fixes this issue to the main seqr codebase as we would love to have it fixed sooner, we just realisticall do not hav the badwidth to address this right now

**Comment by gilmorera** [comment]
Thank you for the update @hanars.  I will bring this up in our team meeting.

**Comment by hanars** [comment]
@bpblanken just flagging to make sure this gets considered as part of the new VEP update. The TL;DR is that there are some "consequence terms" that were being annotated as part of `regulatory_feature_consequences` instead of `transcript_consequences`. As part of our VEP update we should confirm where these consequences are being annotated and ensure that either a) they have moved into `transcript_consequences` or b) that we are including `regulatory_feature_consequences` in the final VEP output (currently its dropped)

**Comment by bpblanken** [comment]
Did some snooping on this and found:

These keys present under `regulatory_feature_consequences`:
```
regulatory_region_ablation
regulatory_region_variant
```

These keys present under `motif_feature_consequences`:
```
TF_binding_site_variant
TFBS_ablation
```

But didn't find (at least within the ~2million test variants I'm using):
```
feature_elongation 
feature_truncation
regulatory_region_amplification (probably nested under  `regulatory_feature_consequences`)
TFBS_amplification (probably nested under `motif_feature_consequences`)
transcript_amplification
```

This confirms that the consequences have not moved into `transcript_consequences` and that we'll want to add new annotation fields for `regulatory_feature_consequences` and `motif_feature_consequences` (if we care about the latter).

**Comment by hanars** [comment]
We should probably have a quick meeting with @lynnpais to decide how we want to handle the `regulatory_feature_consequences` and `motif_feature_consequences` - it seems likely that these are valuable annotations to have but given that the schema for them is different we probably need to display them quite differently (i.e. they have no transcript_id, so we would still want to show a "real" transcript in addition to these consequences). 

For the ones we did not find, we should determine if they are indeed somewhere else in the VEP annotation, or if not we should remove them from the UI/ filter options entirely.

**Comment by hanars** [comment]
Update on the missing consequences with updated VEP:

- Moved to motif/regulatory features:
```
regulatory_region_ablation
regulatory_region_amplification
regulatory_region_variant
TF_binding_site_variant
TFBS_ablation
TFBS_amplification
```

- Deprecated and removed from UI:
```
initiator_codon_variant
```

The remaining 3 consequences were left in the annotations table and are in the global consequence enum, but querying the annotations table for these consequences results in no variants. @bpblanken can you investigate?
```
feature_elongation
feature_truncation
transcript_amplification
```

**Comment by bpblanken** [comment]
I don't think there's a bug here, those three consequences are legitimately not being produced.  

I sanity checked against gnomad's published VEP and looks as though they are also missing there:

```
import hail as hl
ht = hl.read_table('gs://gcp-public-data--gnomad/release/4.1/ht/genomes/gnomad.genomes.v4.1.sites.ht')
ht = ht.flatten()
ht = ht.explode('vep.transcript_consequences')
ht = ht.flatten()
ht = ht.explode('vep.transcript_consequences.consequence_terms')
ht.select('vep.transcript_consequences.consequence_terms')
consequences = ht.aggregate(hl.agg.collect_as_set(ht['vep.transcript_consequences.consequence_terms']))
consequences
```

```
{'3_prime_UTR_variant',
 '5_prime_UTR_variant',
 'NMD_transcript_variant',
 'coding_sequence_variant',
 'downstream_gene_variant',
 'frameshift_variant',
 'incomplete_terminal_codon_variant',
 'inframe_deletion',
 'inframe_insertion',
 'intergenic_variant',
 'intron_variant',
 'mature_miRNA_variant',
 'missense_variant',
 'non_coding_transcript_exon_variant',
 'non_coding_transcript_variant',
 'protein_altering_variant',
 'splice_acceptor_variant',
 'splice_donor_5th_base_variant',
 'splice_donor_region_variant',
 'splice_donor_variant',
 'splice_polypyrimidine_tract_variant',
 'splice_region_variant',
 'start_lost',
 'start_retained_variant',
 'stop_gained',
 'stop_lost',
 'stop_retained_variant',
 'synonymous_variant',
 'transcript_ablation',
 'upstream_gene_variant'}
```

**Comment by anneodonnell** [comment]
I can say that I do not think these are clinically interesting categories so I would not chase them - and seems like we should also not show them in seqr.

**Comment by bpblanken** [comment]
One potential route of investigation for a future engineer is the `--check_svs` flag.  That flag isn't an option with the current way we're running VEP (`--offline` with a local cache).  References to `feature_elongation` in [the VEP testing source](https://github.com/Ensembl/ensembl-vep/blob/31a3581b84495b617b2f3980da6c6313ca6d238f/t/OutputFactory.t#L1518-L1536) are correlated with mentions of SVs.

**Comment by hanars** [comment]
All annotation filters in seqr can now result in variants!
