### ISSUE TITLE
Another staff-level access request

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2415]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Can you also grant staff-level access to Martin Jankowiak (mjankowi@broadinstitute.org)? Sorry I didn't combine this with the request from this morning, I was worried he wasn't going to get back me and didn't want to delay access for others.

**Describe alternatives you've considered**

**Additional context**
This has also been approved by Anne/Heidi

**Comment by hanars** [comment]
no worries, this is all set now
