### ISSUE TITLE
Abnormal display of gene list tags

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2423]
**Describe the bug**
Occasionally, gene list tags are displaying as small squares with no text (screenshot below). Refreshing the page typically fixes the issue, but it eventually happens again (haven't figured out the pattern for when it happens yet).

**Link to page(s) where bug is occurring**
Screenshot is from https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F021077_rgp_320

**Scope of the bug**
All of the analysts have seen this sporadically across multiple projects

**Screenshots**
![image](https://user-images.githubusercontent.com/67653781/151248359-e673b8a4-aecb-4a94-9e85-650aac0a1bd5.png)

**Comment by hanars** [comment]
this should be fixed now
