### ISSUE TITLE
Possible race condition in gcloud auth configuration

### ISSUE THREAD

**Issue by sjahl** [broadinstitute/seqr#2437]
From the crash this weekend. Two errors of note here. I've included the Seqr stacktrace below, but I don't think it's actually what's important. The problems that we had should probably be caught prior to arriving at the seqr codepath. This occurred when the container was starting up: we failed to authenticate with `gcloud` and then (expectedly) seqr died on startup because it had no auth identity and then just stopped. We have a very long `sleep` in the seqr entrypoint, which is why we end up sitting here

1) On container startup, we failed to connect to the google authentication api . From what I can tell from other errors, we even had trouble talking to github and PyPI at startup. So, I think either the node was having network issues, or it just takes a while for the network interface to become available when the pod starts up. I don't have a great answer for why this seems to be happening more, but my suspicion is that without the GCP volume attachment for static media, the container is actually starting up faster than it used to.

```
+ gcloud auth activate-service-account --key-file /.config/service-account-key.json
ERROR: gcloud crashed (TransportError): HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6dcbc1cdf0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

2) This is the seqr stacktrace, included for completeness. I don't really think there's much to be done on the seqr side of things here since the gcloud authentication is happening outside of the app.

```
[2022-01-30 03:23:45 -0500] [161] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 586, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/seqr/wsgi.py", line 24, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/seqr/settings.py", line 397, in <module>
    raise Exception('Error starting seqr - gcloud auth is not properly configured')
Exception: Error starting seqr - gcloud auth is not properly configured
```

I think to keep this from happening, we'll want to:

- add some retry logic (or at least exit on error) in the docker entrypoint when we fail to auth
- get rid of the `sleep 1000000000000`, since that's going to trick kubernetes into thinking the pod is somewhat alive
- add a livenessProbe and/or a startupProbe. These will help kubernetes bail on dead containers. Our readinessProbe was working, since k8s didn't think the pod was ready, but there's an important distinction between broken and `NotReady`, and these other two types of probes should help there.

**Comment by hanars** [comment]
> * add some retry logic (or at least exit on error) in the docker entrypoint when we fail to auth

So we actually are setting/checking gcloud auth in 2 places when seqr starts up - once in the docker entrypoint which is the error you show, but once is in settings.py which is where the error occurs in the stacktrace you provided. seqr runs `gcloud auth list --filter=status:ACTIVE --format="value(account)"` and if that fails it justraises an exception and crashes the app. Do you think its also worth adding some logic there to try activate the service account if it hasn't been activated already?

> * get rid of the `sleep 1000000000000`, since that's going to trick kubernetes into thinking the pod is somewhat alive

we have a comment on that that "# sleep to keep image running even if gunicorn is killed / restarted". Is that not something we should worry about?

**Comment by sjahl** [comment]
> So we actually are setting/checking gcloud auth in 2 places when seqr starts up - once in the docker entrypoint which is the error you show, but once is in settings.py which is where the error occurs in the stacktrace you provided. seqr runs `gcloud auth list --filter=status:ACTIVE --format="value(account)"` and if that fails it justraises an exception and crashes the app. Do you think its also worth adding some logic there to try activate the service account if it hasn't been activated already?

Yeah, having the app try to auth if the SA isn't activated by that point might be a good idea too. That code is already gated behind a Terra config option, so it shouldn't impact anyone else.

> we have a comment on that that "# sleep to keep image running even if gunicorn is killed / restarted". Is that not something we should worry about?

In general, I think that if seqr's dead, we should let kubernetes redeploy pods automatically for us. My guess is that the sleep was added there to make it easier to exec into the container to debug problems (which is hard to do if the container keeps getting reaped 😂 ). So we don't want to lose that ability. I think the k8s Way ™️ to do this is via `kubectl debug`, where you can launch a copy of the pod outside of the replicaset that won't keep getting killed. But, we can keep the sleep in there until we figure out what a workable pattern is.
