### ISSUE TITLE
Change SC to AC for exomes and genomes SV

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2439]
As discussed on slack with Hana, we should call an SV allele count (AC) instead of site count (SC) based on Harrison's recommendation. I discussed this with Anne and we concluded to change it for both exomes and genomes SV calls. 

Can you please change "SC" to "AC" for SV in exome and genomes (screenshot below, examples on an exome and on a genome)
![Screen Shot 2022-02-02 at 2 24 37 PM](https://user-images.githubusercontent.com/84086816/152223541-77651a44-23e8-4442-9a36-58017ee97ba8.png)
![Screen Shot 2022-02-02 at 2 25 55 PM](https://user-images.githubusercontent.com/84086816/152223621-ad19248c-a6aa-4ef3-a2e2-3daca6e96ef1.png)

**Comment by hanars** [comment]
this has been updated
