### ISSUE TITLE
Change the name of gCNV deletion/duplication 

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2440]
Please change the following names in the annotations section of seqr searches 
gCNV deletion --> please call "exome deletion"
gCNV duplication--> please call "exome duplication"
![Screen Shot 2022-02-02 at 2 34 23 PM](https://user-images.githubusercontent.com/84086816/152224404-c01ee238-df2d-415b-ac4e-4f335677240f.png)
"

**Comment by hanars** [comment]
updated
