### ISSUE TITLE
Remove the word "large" on hover over text

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2441]
Please remove the word "large" in the hover over text of gCNV deletion, gCNV duplication, deletion and duplication (for both exome and genomes) in the annotations section of seqr searches. CNV and SV called by exome and genome can be actually as small as a few bp so we need to change that. Discussed with Anne and Chrissy. 
![Screen Shot 2022-02-02 at 2 42 12 PM](https://user-images.githubusercontent.com/84086816/152225379-39025ddf-be70-4ec7-92da-88986d47fa26.png)
![Screen Shot 2022-02-02 at 2 38 34 PM](https://user-images.githubusercontent.com/84086816/152225394-e73ca4db-1cd8-4cd7-8092-9120f2555289.png)

**Comment by hanars** [comment]
updated
