### ISSUE TITLE
Invalid search error on gCNV 'seqr' link

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#2448]
**Describe the bug**
When searching for overlapping SVs I get a `Invalid search hash: 380ae83b13e64d490ae45538de387444` error. Is this a bug or an error due to too many returned variants? 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/variant/suffix_1704_DUP_2/family/F012952_ogi857
https://seqr.broadinstitute.org/variant_search/results/380ae83b13e64d490ae45538de387444?page=1&sort=pathogenicity

**Screenshots**
![image](https://user-images.githubusercontent.com/44381119/152570141-51fb6745-f61d-442e-bbe4-96db5e5c85cf.png)

**Comment by hanars** [comment]
This is a bug related to the "seqr" search in gcnv, it should be affecting all projects

**Comment by hanars** [comment]
There was a bug with generating the "seqr" link, which has been fixed. Clicking the link will now take you to a successful search results page: https://seqr.broadinstitute.org/variant_search/results/d6eedc0b1ea3fa9d0c625473f8ea3be2?page=1&sort=xpos
