### ISSUE TITLE
Change the display in the frequency section of seqr search

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2451]
This has been discussed with Anne and the analysis team. 

1) Can you please remove the "1000 genomes" and "ExAC" options in the Frequency section of seqr search. (see 2 "X" in screenshot)
2) Can you move "This callset" option on the first row of this section so options pertaining to SNV/indel are on the same line and options pertaining to SV are on the line below (see red arrow in screenshot)
3) Can you change the name of "SV callset" to "This SV callset". 
Thank you! 

![Screen Shot 2022-02-04 at 1 34 49 PM](https://user-images.githubusercontent.com/84086816/152585059-6c85cedc-ad97-4fcc-a849-030f3773853c.png)

**Comment by hanars** [comment]
The current default saved searches apply 1000 genomes and exac frequency filters. Should we remove those filters from the saved searches going forward?

**Comment by Glemiret** [comment]
The threshold for 1000G and Exac is set to 1 in the saved search so we are not using them. So yes these filter options can be removed from saved search 
![Screen Shot 2022-02-04 at 1 50 00 PM](https://user-images.githubusercontent.com/84086816/152586356-a04f84bc-9021-4e21-91dc-a62a31569830.png)

**Comment by hanars** [comment]
this has been done
