### ISSUE TITLE
Update of saved searches

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2452]
Please update the saved searches using searches currently saved in Gabrielle Lemire seqr account.
This has been discussed with analysis team and Anne. The goal is to include the new "exome del" and "exome dup" options in the saved searches. We also did minor modifications on the variants included in the annotation (2nd hit) in recessive searches. 

Replace the following existing saved searches
current name in seqr-->name this is saved for in my seqr account (name to use for this search for all users)

De novo/Dominant Permissive -> De novo/Dominant Permissive new (name this saved search: De novo/Dominant Permissive)
De novo/Dominant Restrictive -> De novo/Dominant Restrictive new (name this saved search: De novo/Dominant Restrictive)
De novo/Dominant-SV only Trio-> De novo/Dominant-SV only Trio new (name this saved search: De novo/Dominant-SV only Trio)
De novo/Dominant-SV only-Proband/duo --> De novo/Dominant-SV only-Proband/duo new (name this saved search: De novo/Dominant-SV only-Proband/duo)
Recessive restrictive-> Recessive restrictive new (name this saved search: Recessive restrictive)
Recessive permissive--> Recessive permissive new (name this saved search: Recessive permissive)
Recessive SV-> Recessive SV new (name this saved search: Recessive SV)

**Comment by hanars** [comment]
these have been added. For future updates to saved searches, for small tweaks to existing searches its actually easier if you tell me what has changed, whereas for big changes/ entirely new saved searches its easier to do this approach where you create the saved search for yourself. For instance, if the only change is adding "Exome duplication" and "Exome Deletion", thats easier if you just tell me to do that, but if it is "that, plus a bunch of other tweaks to secndary annotation" its easier to do it this way

**Comment by Glemiret** [comment]
there were a few other changes in all the searches so I thought it was easier to do this approach.
