### ISSUE TITLE
[DUE 4/1/22] Disable download options on seqr training projects

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#2456]
**Is your feature request related to a problem? Please describe.**
We are working on creating a new project of samples for a workshop and it was pointed out that it's preferable to not allow any downloads of data when we give access to rare disease families for teaching purposes. 

It would be helpful to know how doable this is for planning purposes - we are planning for a workshop in early April. 
**Describe the solution you'd like**
Should not be able to download variants on the search or saved variants page, just on the teaching projects. It's ok to leave this active on the demo project (where I do think it's a helpful feature to demo). 

**Describe alternatives you've considered**

**Additional context**
This would be for things like "Exome Project A" and "Genome Project A", etc. But we will also make new training projects as the variants in these cases are in ClinVar now so we want fresher cases for teaching.

**Comment by hanars** [comment]
this has been done
