### ISSUE TITLE
Local install SeqrVCFToMTTask key not found error - bump hail version

### ISSUE THREAD

**Issue by gavinmonahan** [broadinstitute/seqr#2460]
**Describe the bug**
This is quite a benign bug and has an easy fix.
When running pipeline-runner through docker-compose on a local install of seqr, a keynotfound error is raised: `java.util.NoSuchElementException: key not found: GRCh37` (see attached log file). This seems to be related to the version of Hail (I was running hail 0.2.74), as it has been reported [here](https://github.com/hail-is/hail/issues/10722), and fixed [here](https://github.com/hail-is/hail/pull/10888). Minimum version of hail to avoid this issue is [0.2.77](https://hail.is/docs/0.2/change_log.html#version-0-2-83).
Issue fixed by opening a bash terminal inside the container and running `pip install hail==0.2.77`
Could you update the hail version in hail-elasticsearch-pipelines requirements.txt file to >=0.2.77?

**Link to page(s) where bug is occurring**

**Scope of the bug**
Are you experiencing this issue in all projects? Within specific families within one project?

**Screenshots**
[pipeline-runner hail error.txt](https://github.com/broadinstitute/seqr/files/8020706/pipeline-runner.hail.error.txt)

**Comment by hanars** [comment]
The latest docker image for the pipeline-runner component now comes with an updated version of hail. Thanks for reporting this!

**Comment by hanars** [comment]
Sorry, I built and pushed the image but forgot to push the tags properly. Should be all set now.
