### ISSUE TITLE
RNAseq OUTRIDER plots missing

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#2462]
**Describe the bug**
I'm giving a seqr demo at 3pm today and I really wanted to use https://seqr.broadinstitute.org/project/R0332_cmg_estonia_wgs/family_page/F018136_hk011 as the example because it has RNAseq and SVs contributing to the diagnosis (plus an interesting variant on de novo search that isn't the answer). OUTRIDER doesn't seem to be working (though the splicing and differential expression looks fine). 

I have a backup case for OUTRIDER so it's not urgent. I would really like seqr to be running well at 3pm as a higher priority than fixing OUTRIDER. 

![image](https://user-images.githubusercontent.com/10407888/153125239-d29ab358-94ac-4b31-af37-9317f76b63a7.png)

Spot checking a few others that are missing: 
https://seqr.broadinstitute.org/project/R0332_cmg_estonia_wgs/family_page/F020251_hk106
https://seqr.broadinstitute.org/project/R0312_cmg_bonnemann_genomes/family_page/F018397_b16_50
https://seqr.broadinstitute.org/project/R0358_cmg_vcgs_exomes/family_page/F017850_fam27

It does seem like the ones that say RNAseq loaded 2/4/22 are the ones without OUTRIDER. I spot checked 5 randomly selected from the RNAseq list from Ben and found 1 and missing 4 so probably a good number are missing. 

https://docs.google.com/spreadsheets/d/1S3l28tZqFmzqqwqi_BCzuIkaVFmZz9eGpGtqtH5eVoo/edit#gid=667067448

**Comment by hanars** [comment]
This is not a bug. The existence of the indicator that there is RNA seq data means there is OUTRIDER data and/ or expression data. All the examples you linked are ones where we have expression data but no outrider data. See here for the announcement about adding the expression data: https://the-tgg.slack.com/archives/C027LHMPP/p1644009651485649

There is a question of why I was only given outrider data for ~150 samples when I was given expression data for ~250. We had discussed in slack that many samples did not have outrider data, but as a ticket was never made I have never investigated further

**Comment by anneodonnell** [comment]
That was why I made this ticket so you had some sample IDs to look into why the data you have is incomplete. Is there something different you are looking for?

**Comment by bw2** [comment]
I think only muscle and whole-blood samples are currently loaded. 
@hanars I'll share the tables for fibroblast samples  + an updated table for whole-blood.
