### ISSUE TITLE
Adjust which SVs are considered passing quality filters 

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#2463]
**Is your feature request related to a problem? Please describe.**
Currently, only SVs that have `PASS` in the FILTER field are returned with the 'Pass Variants Only' search option. After talking with the group and Alba about our highest quality SVs and best SV candidates, about half of them have `BOTHSIDES_SUPPORT` in this field causing these high-quality candidates to be excluded from restrictive searches. 

**Describe the solution you'd like**
We would like SVs with either `PASS` or `BOTHSIDES_SUPPORT` in the FILTER field returned with the 'Pass Variants Only' option. 

**Additional context**
![image](https://user-images.githubusercontent.com/44381119/153265905-0dfbf2cd-8f23-46c9-9da9-d3a53fe4fc9c.png)
![image](https://user-images.githubusercontent.com/44381119/153265956-6b27eee4-29dd-45ea-98ca-a4507e49e1d6.png)

**Comment by hanars** [comment]
As an FYI, this is impossible to do without reloading all SV data, on a per project basis. We can do that, but its an enormous amount of manual work on our team. I'd like to confirm with @anneodonnell whether this is higher priority than mitochondrial variant loading, as we would need to pull Shifa off of that to get this implemented

Going forward, should "BOTHSIDES_SUPPORT" really be showing up as a filter on the variants at all? It seems like its not really a filter in the way we traditionally think of it, and as such probably shouldn't be displayed like one

**Comment by anneodonnell** [comment]
Let's give it a little time to see if we find more things we would want changed before triggering a reload.

**Comment by ShifaSZ** [comment]
Currently, we filter out just "PASS" from the "filter" field. We can filter our "BOTHSIDES_SUPPORT" as well. We can also add a field (e.g. "bothsides_support_filter") to keep the information. @hanars And do we need to display and search on the field?

**Comment by hanars** [comment]
We do not need to search on the field. We can display it if present next to the SV size and number of exons

**Comment by ShifaSZ** [comment]
How about we display the information in the popup as below?
![image](https://user-images.githubusercontent.com/33550059/158894810-c75f0f7b-cf8b-4d4e-a518-33c753323875.png)

**Comment by hanars** [comment]
Just say "Bothsides Support", but yeah the popup is fine

**Comment by hanars** [comment]
Variants with Both sides support are no longer filtered out by the pass filter
