### ISSUE TITLE
Staff level access to new users

### ISSUE THREAD

**Issue by ch-kr** [broadinstitute/seqr#2478]
**Is your feature request related to a problem? Please describe.**
I received an email from Areesha Salman (asalman@broadinstitute.org) and Katherine Lafferty (klaffert@broadinstitute.org), two new clinical variant analysts, requesting access to seqr. 

**Describe the solution you'd like**
Could you give these two users staff access?

**Describe alternatives you've considered**

**Additional context**

**Comment by hanars** [comment]
these should be all set
