### ISSUE TITLE
SpliceAI spelling in seqr

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2480]
**Describe the bug**
SpliceAI is currently spelled as 'Splice Ai' in seqr. It needs to be changed to 'SpliceAI'. Source: https://www.illumina.com/science/genomics-research/articles/predict-splicing-primary-sequence-deep-learning.html

**Link to page(s) where bug is occurring**
Across seqr in the variant search dropdown, sort by function, variant search results and saved variants sections.

**Scope of the bug**
Across seqr.

**Screenshots**
Here's one example
<img width="163" alt="Screen Shot 2022-02-22 at 11 55 18 AM" src="https://user-images.githubusercontent.com/37872186/155180917-52980cce-f8f6-4f63-a882-0bdfb7e0bb3e.png">

**Comment by hanars** [comment]
this has been updated
