### ISSUE TITLE
Add analysis groups to individual family pages for all RGP projects

### ISSUE THREAD

**Issue by jgserran** [broadinstitute/seqr#2497]
This feature request is not related to a problem but would provide easier access to information. When clicking on the analysis groups located on the RGP main page we are able to see which families belong to the group. However, within each of these family pages there is no indication that they are part of that analysis group. We would like for this grouping to be visible within the individual family pages by adding a tag/label. We would like this to exist for all RGP projects if possible.  

I have attached an image of the analysis groups that are shown on the top left side in the main RGP pages. 
<img width="252" alt="Screen Shot 2022-03-01 at 11 50 07 AM" src="https://user-images.githubusercontent.com/89798273/156221727-80ddc93c-3440-4abc-84df-64e4cb0c7861.png">

A suggestion would be to include it at the top of each individual family page near "family description" or "analysis status". I have attached an image of this location. 
<img width="541" alt="Screen Shot 2022-03-01 at 1 21 40 PM" src="https://user-images.githubusercontent.com/89798273/156234605-d4bbfcec-6f34-40da-ad07-e333b05bfaf0.png">

**Comment by hanars** [comment]
this has been added
