### ISSUE TITLE
Automatically clear notes/tags in seqr demo project

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2506]
**Is your feature request related to a problem? Please describe.**
The demo project (https://seqr.broadinstitute.org/project/R0555_seqr_demo/project_page) quickly gets cluttered with notes/tags from various users

**Describe the solution you'd like**
Could we set up a system to automatically clear the project on a quarterly basis?

**Describe alternatives you've considered**

**Additional context**
Requested by both Anne and Chrissy.

**Comment by hanars** [comment]
this will now happen automatically on the first of the month for each quarter (January/ April/ July/ October)
