### ISSUE TITLE
Overlapping SVdel+SNV not recognized as a compound het pair

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#2508]
**Describe the bug**
We need to think through this one, but currently SV deletions with an overlapping SNV are not recognized as a compound het pair and not returned in a recessive search.  The SNV alone will be returned because it is seen as homozygous (alt/alt) although in reality it is hemi in trans with a deletion (-/alt). For obviously damaging SNVs this has not been a problem because the homozygous call (hopefully) will alert our attention. The issue is when the SNV is not obvious (intronic or a weak missense/hypomorph) and we are unaware of the more damaging allele (SV deletion) because it is not returned as a comp het pair. 

Is there a way to customize the comp het logic to return homozygous calls only when the genomic coordinates fall within a deletion?

**Comment by hanars** [comment]
To clarify the issue, are we specifically talking about wanting hom alt SNPs to be returned, and currently we are only returning ref/alt  in compound het search? If so, would we be okay returning compound hets with 2 SNPs where one (or both) of them was hom alt in the proband? Or would we only want this behavior to apply if one of the hits is an SV?

Can you also provide links to searches/ examples of these sorts of variants

**Comment by stephditroia** [comment]
_To clarify the issue, are we specifically talking about wanting hom alt SNPs to be returned, and currently we are only returning ref/alt in compound het search?_ 
Hom alt SNPs are returned in recessive searches (i.e. our saved rec searches). I'm not sure about compound het specific searches - I honestly don't use that search on its own. For a SNP/SVdel comp het pair with overlapping genomic coordinates, the SV is not being returned in a recessive search. 

_If so, would we be okay returning compound hets with 2 SNPs where one (or both) of them was hom alt in the proband?_ 
This is a no because it would return too many pairs in families with consanguinity. 

_Or would we only want this behavior to apply if one of the hits is an SV?_
If possible, this is the best solution. 


Here is an example, I'll ask around for more if needed:
Saved variants: https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F029262_rgp_1139/Known%20gene%20for%20phenotype
Rec search: https://seqr.broadinstitute.org/variant_search/results/1c2666b4e56c83547853ccee7870a0eb?page=1&sort=xpos

**Comment by hanars** [comment]
So to clarify, the change we want is:
For compound het pairs with one SNP and one SV, we want to allow the SNP to be hom alt.

**Comment by stephditroia** [comment]
Yes, but only if the SV is a deletion AND the genomic coordinates overlap

**Comment by stephditroia** [comment]
Two more examples:
RTN4IP1
Any affected search returns both variants, one maternal one paternal:
https://seqr.broadinstitute.org/variant_search/results/21482c4e22c4cce85bf42001e51e0e45?page=1&sort=revel
Recessive search returns the hom missense only:
https://seqr.broadinstitute.org/variant_search/results/131466ef44a9ecdea9e5c39e3f26b893?page=1&sort=revel
Comp Het search returns nothing:
https://seqr.broadinstitute.org/variant_search/results/609a26665ca7991b0872ce7a2701e08e?page=1&sort=revel

JAG2
Any affected search returns 3 variants, 2 overlapping SVs and 1 hom missense:
https://seqr.broadinstitute.org/variant_search/results/2a4264c1887ceae077f0cb2094045286?page=1&sort=revel
Recessive search returns hom missense only:
https://seqr.broadinstitute.org/variant_search/results/d74a860ee4ecb64dbfe96c464617c70c?page=1&sort=revel

**Comment by hanars** [comment]
search has been updated and the expected variants are all now returning
