### ISSUE TITLE
MME integration - default email

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#2514]
**Is your feature request related to a problem? Please describe.**
For users directly collaborating with our group (where we can see the data), we require our matchmaker email is copied on all MME submissions through seqr. This should continue. 

But for AnVIL seqr users - where we cannot see the data - when they use MME within seqr, they should not have our matchmaker email copied. 

**Describe the solution you'd like**
I think this just needs to remove the autopopulated email and contact name for AnVIL seqr MME.

**Comment by hanars** [comment]
this behavior has been updated so going forward we will be left off of MME submissions from AnVIL collaborators
