### ISSUE TITLE
Add Geno2MP link to the Gene Info page

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#2520]
**Is your feature request related to a problem? Please describe.**
While I've been wanting to include links to Geno2MP at the variant level, which is a bit more work, Stephanie pointed out we could at least link the gene page to increase use of this resource. 

**Describe the solution you'd like**
I happened to be looking at POU4F3 gene tonight and the link would be https://geno2mp.gs.washington.edu/Geno2MP/#/gene/POU4F3/gene/0/0/0
So seems like it should be straightforward to link for any gene ID

**Comment by hanars** [comment]
link has been added
