### ISSUE TITLE
Add sort by size functionality for variant search results

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2524]
**Is your feature request related to a problem? Please describe.**
Larger CNVs are more likely to be disease-causing, so it may be useful to sort CNV/SV results by size

**Describe the solution you'd like**
Given that we have size estimates for all CNV/SVs, I'm wondering if it would be possible to add "Size" to the "Sort By" options for variant search results. 

**Describe alternatives you've considered**

**Additional context**
The sort would only be relevant for CNV/SVs, but if the search results contain both CNVs and SNVs, the SNVs could just be interpreted as size=1bp and sorted to the bottom.

**Comment by hanars** [comment]
using the current elasticsearch backend theres no reason to think sorting by size will be an issue for us

**Comment by jxchong** [comment]
Thanks good to know. In our Nanopore data, we get 3-5k indels (from starting point of 1 million indels) and ~500 SVs per sample if we filter for ultra-low frequency variants only.
