### ISSUE TITLE
Inappropriate formatting of "Analysis in Progress" per cent value

### ISSUE THREAD

**Issue by mathob** [broadinstitute/seqr#2527]
**Describe the bug**
A minor formatting issue: the "Analysis in Progress" is a per cent figure formatted as e.g. "1.0e+2%" whereas I think most users would prefer the usual format "100%"

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0555_seqr_demo/project_page#

**Scope of the bug**
I only have access to the demo project

**Screenshots**
![image](https://user-images.githubusercontent.com/56565998/157338712-1b4f93ce-d2a4-41cb-a5ae-45ee388ca9ea.png)

**Comment by hanars** [comment]
this has been fixed, thanks for reporting!
