### ISSUE TITLE
Update WGS SV Genotype Quality score cutoffs in saved searches

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2529]
**Is your feature request related to a problem? Please describe.**
We are losing some high quality SV calls in the current saved searches because they have a quality score of 1 (the lowest assigned value) and we previously set the cutoff to 10.

**Describe the solution you'd like**
Would like to update all 7 default saved searches to remove WGS SV Genotype Quality score cutoffs. Also need to update Recessive Restrictive to "Pass Variants Only" (I think this was changed in error at some point). I saved updated versions of all 7 default searches in my account and tagged them with today's date (eg Recessive restrictive 03.08.22) in case it's easier to update that way.

**Describe alternatives you've considered**

**Additional context**

**Comment by hanars** [comment]
these have all been updated. For changes like this it was easier for me to change the existing searches rather than using the new ones you made, so you will still see those on your account
