### ISSUE TITLE
Adding information from GenCC into seqr 

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2538]
This has been discussed with the analysis team 

**On the variant page:** 
Add a tag named **“GenCC”** for any gene that has an entry in GenCC with the option of clicking on the tag leading to the GenCC webpage for that gene. Do not add a tag for genes that have an entry in GenCC when the entry is "No known gene disease assertions". 

Add the tag below the gene name and just above the OMIM box (see red arrow). Start a new line for this tag so it is on its own line (no need to add a grey line). The color of the tag box could be dark blue (just a suggestion to differentiate it from other tags). In the example below, clicking on the tag links to this webpage: https://search.thegencc.org/genes/HGNC:9438
 
![Screen Shot 2022-03-08 at 4 37 53 PM](https://user-images.githubusercontent.com/84086816/157761368-48f402c5-4122-47b3-bb43-4d55bd1a56e4.png)

**Hovering over the GenCC tag** shows this text (the same text we suggest finding on the gene page) : 
Genomics England PanelApp (2021): strong for Dystonia 16  (AR)
[Laboratory for Molecular Medicine](https://search.thegencc.org/submitters/GENCC_000107) (2020): moderate for Dystonia 16(AR)
Orphanet (2021): supportive for Dystonia 16 (AR)

**On the gene page:** 
Under Disease Associations (see red arrow), add GenCC curation on the left side of the page below "dbNSFP Details" with a summary of the curation results in this format “curation team (year): classification for name of disease (inheritance)” on the right side of the page .

**GenCC curation**                                                         Genomics England PanelApp (2021): strong for Dystonia 16  (AR)
                                                                             [Laboratory for Molecular Medicine](https://search.thegencc.org/submitters/GENCC_000107) (2020):        moderate for Dystonia 16(AR)
                                                                         Orphanet (2021): supportive for Dystonia 16 (AR)

![Screen Shot 2022-03-09 at 9 07 27 AM](https://user-images.githubusercontent.com/84086816/157761667-852992d6-1535-4173-8aa2-34372f07ccad.png)

Let me know if anything is unclear and if you have any questions. Thanks!

**Comment by hanars** [comment]
this has been added. I did make some tweaks to the display, let me know if you want me to change any of it

**Comment by Glemiret** [comment]
Looks great!!! I already love it! 
Are you able to link to the GenCC webpage from the tag on the variant page like described above: 
"Add a tag named “GenCC” for any gene that has an entry in GenCC **with the option of clicking on the tag leading to the GenCC webpage for that gene."**

**Comment by hanars** [comment]
I added the link to the hover to be consistant with everything else in that section. No other labels are links and I think it might be too easy to accidentally trigger the link when trying to hover. But if you really feel strongly I can make the label a link

**Comment by Glemiret** [comment]
Ok I did not realize I could click on the disease name in the hover over text, that is fine with me. 
I really like the display with the colors! Thanks!
