### ISSUE TITLE
Variant tag count discrepancies

### ISSUE THREAD

**Issue by mathob** [broadinstitute/seqr#2539]
**Describe the bug**
The numbers of variant tags (Review, Excluded, etc) on the project page are not the same as the numbers on the Saved Variants page

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0555_seqr_demo/project_page
this page says there are  e.g. 13 Review variants

https://seqr.broadinstitute.org/project/R0555_seqr_demo/saved_variants/Review
but this page shows only 3 Review variants

**Scope of the bug**
I only have access to the demo project. Perhaps this is something to do with tags being regularly cleared.

**Screenshots**
![image](https://user-images.githubusercontent.com/56565998/157771660-d49723c9-c5cb-4088-afde-d8875640f3cb.png)
![image](https://user-images.githubusercontent.com/56565998/157771735-b5f8f549-b3e9-4875-b00f-18a8e0e051c3.png)

**Comment by hanars** [comment]
So when it says "1-3 or 3 Review Variants (11 total)" that means you have applied filters to the page that are filtering it to 3 variants, but there are 11 possible Review variants to show. The discrepancy between the 13 and 11 variants comes from how we count compound het variant pairs as 2 different variants on the main page but only as 1 variant on the saved variant page (an example pair: https://seqr.broadinstitute.org/project/R0555_seqr_demo/saved_variants/variant/SV0107804_1323809851_f031960_d,SV0107805_1323874908_f031960_d) 

This is confusing behavior, so I will update the project page to match the saved variants page counts

**Comment by hanars** [comment]
counts are now matching
