### ISSUE TITLE
Arrangement of genes in a SV

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2540]
**Is your feature request related to a problem? Please describe.**
How are genes currently organized if there multiple involved in a SV? It appears to be random (at least not by effect or position).

**Describe the solution you'd like**
We would like the genes in an SV to be organized by position. This would make it easier to understand why some genes are LOF/partially duplicated/ deleted (at the ends oof the SV) and others are full dups/dels (in the middle of the SV). 

**Describe alternatives you've considered**
NA

**Additional context**
Example where genes in the SV seem to be organized randomly - https://seqr.broadinstitute.org/project/R0528_cmg_engle_wes/saved_variants/variant/SV0104848_1182731904_f028943_e,SV0104850_1183171828_f028943_e
<img width="1220" alt="Screen Shot 2022-03-11 at 9 16 13 AM" src="https://user-images.githubusercontent.com/37872186/157885279-377c9c4f-75bf-471c-8628-f7a4b287bcc2.png">

**Comment by hanars** [comment]
Currently, we show them in random order, based on how they happen to come back from the database. Sorting by gene position is easy enough to do

**Comment by lynnpais** [comment]
Ok, perfect, let's go by gene position. Thanks.

**Comment by hanars** [comment]
SV genes are now sorted by position
