### ISSUE TITLE
SV display in a compound heterozygous state

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2541]
**Is your feature request related to a problem? Please describe.**
Per our previous request to update how compound heterozygous variants are displayed, the gene is in the column on the left, and the variants are to the right. For SVs with multiple genes, the one with a 2nd hit, is included on the left, and all other genes in the SV are mentioned on the right. For example, there's a compd het event involving PCF11. The SV includes PCF11 and other genes. Currently only the other genes are mentioned below the variant consequence. This is confusing to some (esp collaborators) as it only shows 7 of 8 genes involved in the SV below the variant consequence.

**Describe the solution you'd like**
If it does not complicate matters, would it be possible to show all genes in the SV under the variant consequence? In this case, include PCF11. 

**Describe alternatives you've considered**
NA

**Additional context**
Example - https://seqr.broadinstitute.org/project/R0528_cmg_engle_wes/saved_variants/variant/SV0104848_1182731904_f028943_e,SV0104850_1183171828_f028943_e
<img width="1199" alt="Screen Shot 2022-03-11 at 9 21 16 AM" src="https://user-images.githubusercontent.com/37872186/157886736-90ebcf58-5fb0-4246-b53a-b93db9ee8e2d.png">

**Comment by hanars** [comment]
this is possible. For SNPs that are annotated in multiple genes in compound hets, we currently show the compound het gene on the left and the other genes on the right. For these SNPs, would you like to show the compound het gene along with the other genes the way we will for SVs, or would you like to keep the behavior as is for SNPs

**Comment by lynnpais** [comment]
We decided to show the gene for SVs and SNPs. I expect this is what the display will look like - 
![Picture1](https://user-images.githubusercontent.com/37872186/158444420-20495e97-7954-4e45-8173-5e1fb8cdc820.png)

Also to confirm, 'Copy Gain' annotation which currently appears next to Duplication, will not show. The annotation will move besides PCF11 once we include the gene below. 

For SNPs that fall on multiple genes, the other genes would show as they are being currently.

**Comment by hanars** [comment]
genes are now shown for compound hets
