### ISSUE TITLE
Add a gene page link to primAD

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#2546]
**Is your feature request related to a problem? Please describe.**
Would like to help people start looking at this primate data resource from Illumina so would add a link to the gene page: http://primad.basespace.illumina.com/gene/IDUA?dataset=gnomad_r3

**Describe the solution you'd like**
Add a primAD gene page link to gene page
![image](https://user-images.githubusercontent.com/10407888/158102872-f2a8fa65-7e1d-4be9-866d-a17f4cd889e4.png)

**Comment by hanars** [comment]
this has been added
