### ISSUE TITLE
Inheritance filter not working on custom searches

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#2548]
**Describe the bug**
I don't think the inheritance filter is working when running seqr-wide custom searches. Any affected and dominant searches are returning multiple variants present only in unaffected individuals. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/report/custom_search/858b5d749d601f35832f754fa8b9a233?page=1&sort=xpos
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/44381119/158221614-c4200b97-c4d7-4b60-9b0d-79c44078f4ff.png">

https://seqr.broadinstitute.org/report/custom_search/e36cfbefc42eb53088a39dfc765eae27?page=1&sort=xpos
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/44381119/158221792-925b2593-f33d-4796-ab53-d7e9d2e2c481.png">

**Comment by hanars** [comment]
this is fixed now
