### ISSUE TITLE
QC tags for outlier genome SVs

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2553]
Some genome cases have numerous false positive SVs called and are outliers. 

Can you please add a QC tag on the family/project page, similarly to what was done for exome gCNV? 

Under SV QC flags, can you please add a box saying "Numerous false positive SV calls"
<img width="513" alt="Screen Shot 2022-03-15 at 2 25 23 PM" src="https://user-images.githubusercontent.com/84086816/158446497-cebe6773-f6b0-46dc-aa45-ee99244fcad9.png">

This tag needs to be added for the following CMG genome cases (this list has been prepared by Alba, please let me know if some case identifiers do not make sense): 

1-01207
1-03905
1-06728
1243
181
226
268
269
3155
3165
3822
3871
457
4778
851
A517
ABC012
B1276
B16-50
CHU_01
CHU_02
CHU_17
CHU_18
D14-1282
D97-331
DF
ENG_AHM
ENG_AJW
ENG_COJ
ENG_EU
ENG_MY
ENG_SZ
ENG_WL
EW
F1
FA
FAM1
GAZ_431
HK032
HK075
JUE_285
K1211
MWAR053
NH15-475
OGI643
P-1
P-4
RGP_1004
RGP_1065
RGP_107
RGP_1201
RGP_149
RGP_1500
RGP_1553
RGP_1608
RGP_1629
RGP_164
RGP_1684
RGP_245
RGP_283
RGP_338
RGP_430
RGP_463
RGP_655
RGP_799
RGP_889
RGP_932
ROS_014
SCO_PED082
TRI_UT-13
TRI_UT-17
TRI_UT-22
UC394
VCGS_FAM148
VCGS_FAM69

**Comment by hanars** [comment]
"Numerous false positive SV calls" is a bit long, and the SV is a bit redundant since it in the "SV QC flag" section. Is there a hard cutoff that was used to generate this list? If so, I think something like "> 10,000 Variants" is better.

**Comment by Glemiret** [comment]
That works, thanks

**Comment by hanars** [comment]
Do you know what the cutoff is? 10,000 was just an example number

**Comment by Glemiret** [comment]
Alba confirmed that a cutoff of 10,000 works. She will use a formula and make it more systematic for future releases.

**Comment by hanars** [comment]
okay but is this family list the full list for 10,000? I need to first batch we do to have the cutoff match the list

**Comment by Glemiret** [comment]
I just chatted with Alba:
She uses this formula to determine which samples are outliers 1.5*IQR + 3Q
so for the last callset, that would translate to raw calls>18,000
However, this cutoff will vary as the callset enlarges so Alba does not recommend adding a number with the QC flag. 
And Alba et al would give us the list of cases that are outliers when a new SV callset is loaded 
This could be called "outliers as defined by the GATK SV pipeline"
I think there is no space limitation on the seqr page next to QC flag so I suggest using that.

**Comment by hanars** [comment]
theres no space limit, but long labels look pretty bad. I'll do "Outlier Num. Calls"

**Comment by hanars** [comment]
this has been added
