### ISSUE TITLE
Display of SV translocations

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2557]
**Is your feature request related to a problem? Please describe.**
The SV calls marked as translocations in seqr aren't making much sense. A translocation is defined as a chromosomal abnormality in which a chromosome breaks and a portion of it reattaches to a different chromosome. In seqr, these calls sometimes have a range of coordinates on a single chromosome and sometimes have a single coordinate. When there is a range of coordinates, there is usually some sort of event evident in the reads at the position of the first coordinate, but it's unclear to me what the second coordinate is because the reads are often clear at that position (example: https://seqr.broadinstitute.org/variant_search/variant/phase2_BND_chr1_108/family/F021482_ev). Additionally, when there is a range of coordinates, clicking on show reads seems to open IGV to a random location. 

**Describe the solution you'd like**
Most (all?) translocations seemed to be flagged as unresolved so I'm not sure how they are being defined as translocations. Assuming they are all the same variant type, I do think we need to tweak how these events are being displayed to make them more consistent

**Describe alternatives you've considered**
Alternatives will really depend on where the translocation tag is coming from and what info is available in the vcf

**Additional context**
Another example "translocation" with a range of coordinates (this variant was actually resolved as an insertion of a transposable element): https://seqr.broadinstitute.org/project/R0293_inmr_neuromuscular_disea/saved_variants/variant/SV0107032_4127940857_f021482_e

Example search results showing the range of different displays for translocations:
https://seqr.broadinstitute.org/variant_search/results/654ec176465505b0120a23562aa48699?page=1&sort=gnomad

**Comment by hanars** [comment]
These are real translocations that are properly called in the data. These issues have to do with how we are handling loading the data, and are not correctly storing the information about the origin position and destination position of these variants. We will need to reload data to get these to display properly, and can do that as part of our other upcoming planned reloading work.

This will require updating the loading pipeline to store the `chrom2:start2-end2` in the sv_type_detail field and updating the seqr display to show it accordingly

**Comment by hanars** [comment]
Sorry, I misread how we are loading data. This is just an issue of how we are displaying the variants, I can update that

**Comment by hanars** [comment]
I'm sorry for going back and forth on this, but my original comment was correct. We do need to reload data in order to be able to properly show these translocations

**Comment by ShifaSZ** [comment]
After we update the `end` from END2 to END and add translocation destination information (CHR2 and END2) to cpx_intervals, we can display the dest location of a translocation SV below the variant coordination as `To: <CHRM2>:<END2>`. Do you think it'd work? @hanars

**Comment by ShifaSZ** [comment]
The existing cpx_intervals display the types as 'BND' which could be confusing. Should we map the types to some more meaningful strings?

**Comment by hanars** [comment]
> The existing cpx_intervals display the types as 'BND' which could be confusing. Should we map the types to some more meaningful strings?

Yes use the mapping we already use for mapping the main svType

**Comment by ShifaSZ** [comment]
Some of the translocation variants have a CHR2 but no END2. Should we just display `CHROM` for them?

**Comment by ShifaSZ** [comment]
The size of a translocation SV is 0 now since the END is always equal to START. Is it okay?
![image](https://user-images.githubusercontent.com/33550059/158871836-4e3b56aa-23b0-40e3-a4e3-6df4247f369e.png)

**Comment by hanars** [comment]
Why would end be equal to start? Shouldn't start be coming from `locus.position` and end becoming from `info.END`?

**Comment by ShifaSZ** [comment]
The SV dataset doesn't have a `START` field. We use the `locus.position` as the start. In the SV dataset, the `info.END` is always the same as the `locus.position` if CHR2 is different from `locus.contig`.

**Comment by hanars** [comment]
lets move this conversation to slack

**Comment by hanars** [comment]
@Caustint is something like the screenshot that Shifa shared above an okay way for us to show translocations? The data we receive doesn't have any information except for the breakpoints. From Harrison:
"For translocations we just focus on the breakpoints since they are huge events. The start or end would either the first or last bp on the chr depending on the oreintation"

Also let me know if you'd prefer to meet briefly to discuss

**Comment by hanars** [comment]
@ShifaSZ Chrissy and I discussed and we want to show translocations in the following way:
 - show the second breakpoint next to the main position, separated by a semi colon. 
   - The second breakpoint should also be a UCSC link, the same way the main position is.
   - In this example, this would be [1:821138](http://hgw1.soe.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr1%3A821088%2D821187&hgsid=1307238245_11hZsplIj3AUfdjAyzazggpl1fWT);[8:375476](http://hgw1.soe.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr8%3A375426%2D375525&hgsid=1307238245_11hZsplIj3AUfdjAyzazggpl1fWT)
 - Show hg19 coordinates for both positions, also separated by a semi colon
 - Do not show the size
 - Use the first position for determining what position IGV opens to (I think the changes to END in the pipeline will make this the default behavior already, but we should confirm) 

Given these requirements, I think we should use the `xstop` field  thats already in the pipeline for determining the end coordinates. Therefore, I think you should undo the changes to `cpx_intervals`

**Comment by hanars** [comment]
Discussed offline with Chrissy and agreed that for size sort translocations should be sorted after other SVs but before SNPs. PR for just that change is here: https://github.com/broadinstitute/seqr/pull/2572

**Comment by hanars** [comment]
Here is the full list of projects to reload. It is the same as the list in tje original loading ticket (https://github.com/broadinstitute/seqr-private/issues/1029#issuecomment-1022421032) plus `CMG_gCNV` which was left out of that list because we had already loaded it 
```
CMG_Aicardi_WGS
 CMG_Beggs_WGS
 CMG_Bonnemann_Genomes
 CMG_Engle_WGS
 CMG_Estonia_WGS
 CMG_Gleeson_WGS
 CMG_Hildebrandt_WGS
 CMG_Jueppner_WGS
 CMG_Kang_Genomes
 CMG_Laing_Ravenscroft_WGS
 CMG_Lerner-Ellis_WGS
 CMG_Manton_Genomes
 CMG_Myoseq_WGS
 CMG_PCGC_WGS
 CMG_Roscioli_WGS
 CMG_Sankaran_Genomes
 CMG_Scott_Genomes
 CMG_Seidman_WGS
 CMG_Sherr_WGS
 CMG_Southampton_WGS
 CMG_Tristani_WGS
 CMG_VCGS_Genomes
 CMG_Walsh_WGS
 CMG_Wendy Chung_Genomes
 CMG_gCNV
 INMR - WGS - PCR-Free WGS
 KNC Neuromuscular Disease CMG Genomes
 Laing_PCRFree_WGS_v5
 Laing_WGS
 Manton-PCRfree-4S
 Newcastle_Genomes_D309
 Pierce - Retinal Degeneration - CMG - Genomes and Arrays
 Rare Genome Project_External_Genomes_v2
 Rare Genomes Project_Genomes_HMB
```

**Comment by hanars** [comment]
Translocation display has been updated as discussed. Let me know if there are still any issues!
