### ISSUE TITLE
Show all variants display bug

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2558]
**Describe the bug**
The black dot does not show when you click on Show all variants. It works tho. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/9adce219d7dadc4513bdd74604619633?page=1&sort=in_omim

**Scope of the bug**
Across seqr

**Screenshots**
<img width="1158" alt="Screen Shot 2022-03-16 at 10 45 01 AM" src="https://user-images.githubusercontent.com/37872186/158617114-10c9f212-78d1-4103-bd58-c9cf945b98c0.png">

**Comment by hanars** [comment]
this is fixed
