### ISSUE TITLE
Remove 'Solved' as an analysis status option

### ISSUE THREAD

**Issue by eoheir** [broadinstitute/seqr#2571]
**Is your feature request related to a problem? Please describe.**
seqr currently has a 'Solved' option for case analysis status, but this option isn't necessary, as analysts should be specifying 'Solved - known gene for phenotype,' 'Solved - novel gene,' etc.

<img width="534" alt="Screen Shot 2022-03-21 at 9 29 20 AM" src="https://user-images.githubusercontent.com/57765157/159270954-a95a7177-78cc-4558-a0bb-2c725b79cae6.png">

**Describe the solution you'd like**
Remove the 'Solved' analysis status option from seqr.

**Additional context**
This was requested by Anne.

**Comment by hanars** [comment]
There are about 200 families in seqr with this status - what do you want to happen to them? I can automatically have all of them assigned to a different status, but I can't programmatically know if they are novel or known gene solves so I'm not sure thats a good idea. I could also get you a list of families and have someone manually set them correctly

**Comment by hanars** [comment]
Alternatively, I can remove the option from the user interface so no new families get this status, but leave those with this status as-is

**Comment by eoheir** [comment]
Yes, the families that currently have this status are fine to leave as is. We just want to remove this option so that it's no longer used in the future. Thank you!

**Comment by hanars** [comment]
this has been removed as an option. Families already classified as "Solved" remain unchanged
