### ISSUE TITLE
ACMG Calculator state update bug

### ISSUE THREAD

**Issue by drtconway** [broadinstitute/seqr#2573]
To reproduce:

1. go to an unclassified variant
2. Open the ACMG Calculation dialogue.
3. You should see
Score = 0, Classification = Unknown, Criteria Applied = No criteria applied.
4. Toggle BS1_P from N to Y.
5. You should see
Score = -1, Classification = Likely Benign, Criteria Applied = BS1_P.
6. Now toggle BS1_P back to N.
7. You should see the same as step 3 above, but instead you see 
Score = -1, Classification = Likely Benign, Criteria Applied = No criteria applied.

I am observing this behaviour on the MCRI instance, but I don't believe there are any downstream (MCRI specific) changes that could be remotely relevant.

![Appearance at step 3.](https://user-images.githubusercontent.com/22288081/159382804-b089a79e-a9f2-42c3-b18e-d0371534ee66.png)

![Appearance at step 5.](https://user-images.githubusercontent.com/22288081/159382816-80f16d86-cbc8-4766-a0ae-12467272e553.png)

![Appearance at step 7.](https://user-images.githubusercontent.com/22288081/159382827-b99b50f5-0889-4123-b3b4-a6c8950beb8c.png)

**Comment by hanars** [comment]
this is fixed in the latest seqr release
