### ISSUE TITLE
seqr search link not working

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2574]
**Describe the bug**
The seqr link on the variant page to identify other variants in the callset is not working.

**Link to page(s) where bug is occurring**
Variant page - https://seqr.broadinstitute.org/project/R0394_cmg_kang_lgmd_wes/saved_variants/family/F024865_kun_k1439/seqr%20MME
Not responsive link - https://seqr.broadinstitute.org/variant_search/results/9352da21cd62563ff1d4be85422ef6b1?page=1&sort=in_omim

**Scope of the bug**
This variant only 

**Screenshots**
NA

**Comment by hanars** [comment]
this is now fixed
