### ISSUE TITLE
New method for adding families to Analysis Groups

### ISSUE THREAD

**Issue by gvannoy** [broadinstitute/seqr#2583]
Currently, it is fairly cumbersome to regularly add small numbers of families to Analysis Groups in seqr. In the RGP_Genomes_HMB project (which contains 1539 families), it is time-consuming to scroll to check off the families being added, and sometimes it 'chokes' while scrolling through such a large list.

Ideally, we would be able to add families to different Analysis Groups from Case Review and the Family page. The solution we imagine would involve leveraging the new Analysis Groups field that displays on the Family Page. Ideally, this would be an editable field (not display only) with a dropdown of all possible analysis groups that allows for selecting more than one group. This would require that this field be visible even if the family had not yet been associated with any Analysis Groups (currently it seems to only display if the family has been added to at least one Analysis Group). We would like the same functionality for this field to be available in Case Review as well.

**Comment by hanars** [comment]
this has been added
