### ISSUE TITLE
gnomAD gene level stats

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2586]
**Describe the bug**
Stats such as LoF or missense constraint are not appearing as tags below the gene on the variant page or on the gene page for certain genes in seqr. For example, SRGAP2 is both missense and LoF constrained but this info is not visible as a usual red tag or on the gene page under stats. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F026448_rgp_682/seqr%20MME

**Scope of the bug**
Not project specific.

**Screenshots**
<img width="1205" alt="Screen Shot 2022-03-24 at 4 58 38 PM" src="https://user-images.githubusercontent.com/37872186/160009394-1d12e645-1ae3-4c00-a692-3f87afbcb45d.png">

<img width="1159" alt="Screen Shot 2022-03-24 at 4 55 59 PM" src="https://user-images.githubusercontent.com/37872186/160009161-ff2e20ee-e5ed-448a-b5f8-5fea076a1ea2.png">

**Comment by hanars** [comment]
There appear to be 2 ensembl IDs associated with the same gene symbol: 
https://seqr.broadinstitute.org/summary_data/gene_info/ENSG00000163486
https://seqr.broadinstitute.org/summary_data/gene_info/ENSG00000266028

The ensembl ID associated with the linked variant is not the ensembl ID associated with regions of high constraint. We may want to reconsider how we do gencode ensemble ID mapping in the pipeline, but I think this should be done holistically with the overall gencode and constraint score updates we have planned for the next gnomad release

**Comment by lynnpais** [comment]
This is now working as expected.
