### ISSUE TITLE
New Training Projects added to seqr for workshop April 6-8

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#2589]
Stacey Hall is making new demo seqr projects for the H3 Africa Rare Disease analysis training workshop that is happening April 6-8. These will be loaded with RGP cases but they are being double coded - as GT#. Overall Chrissy is the point person for these but I wanted to communicate the plan. 

Name: GREGoR Training Project (A-L)

A few things need to happen with these projects: 
- William will load the data - I think Stacey will communicate with him when she is ready
- Hana - can you make these show up as Demo projects
- Hana - these also need downloads deactivated - this is really important to happen before the workshop
- @bw2  is copying the cram files and renaming them so we have IGV working for the workshop. (He had another long term suggestion for this so we can avoid storing extra data copies that I'll submit a separate GitHub ticket about)
- Stacey will load cram paths for these projects

The seqr workshop is the morning of Thursday April 7th 10:30am-noon, but people may be using it through Friday. We should try to avoid big data loading or anything else that might slow seqr down during these days. 

(I can't figure out how to tag Stacey or Chrissy in this)

**Comment by hanars** [comment]
Do we want matchmaker enabled on these projects or no? Also, I can't do anything until the projects have been created - @shall48 please comment with links to all the relevant projects once they exist

**Comment by shall48** [comment]
https://seqr.broadinstitute.org/project/R0607_gregor_training_project_/project_page
https://seqr.broadinstitute.org/project/R0608_gregor_training_project_/project_page
https://seqr.broadinstitute.org/project/R0609_gregor_training_project_/project_page
https://seqr.broadinstitute.org/project/R0610_gregor_training_project_/project_page
https://seqr.broadinstitute.org/project/R0611_gregor_training_project_/project_page
https://seqr.broadinstitute.org/project/R0612_gregor_training_project_/project_page
https://seqr.broadinstitute.org/project/R0613_gregor_training_project_/project_page
https://seqr.broadinstitute.org/project/R0615_gregor_training_project_/project_page
https://seqr.broadinstitute.org/project/R0616_gregor_training_project_/project_page
https://seqr.broadinstitute.org/project/R0617_gregor_training_project_/project_page
https://seqr.broadinstitute.org/project/R0618_gregor_training_project_/project_page
https://seqr.broadinstitute.org/project/R0619_gregor_training_project_/project_page

**Comment by hanars** [comment]
All of these projects have been set as Demo projects, with downloads disabled and matchmaker disabled. Leaving this ticket open as I will update the UI so in the future projects can be set as demos when they are being created instead of needing me to change them later

**Comment by anneodonnell** [comment]
Chrissy pointed out that I may have asked for the wrong thing - I just want them to have the demo tag in seqr but not be visible to anyone who has a seqr account. Access to the projects would still be by who we add to the project. 

This is different than the Demo project - which anyone can see since we made up parts of the data.

**Comment by hanars** [comment]
that is what I did, don't worry. They are not available to anyone unless stacey grants them access

**Comment by hanars** [comment]
You can now set demo status and disable matchmaker at project creation time
