### ISSUE TITLE
Match IGV name to seqr name rather than cram name

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#2590]
**Is your feature request related to a problem? Please describe.**
For Demo projects, we need to deidentify the data so Ben was making a copy and renaming the crams, with us pointing to these deidentified crams. 

![image](https://user-images.githubusercontent.com/10407888/160213197-4b2deb76-5ac5-43fb-a03d-18401c95e94a.png)

**Describe the solution you'd like**
Ben suggested that seqr could possibly show the seqr sample ID name rather than the cram ID name, which would circumvent the need to rename the crams, allowing us to deidentify data in seqr in these special cases. Plus this should work fine for other projects to use the seqr ID as the IGV read data label. 

**Describe alternatives you've considered**
This is an issue for the workshop in ~10 days but Ben said he can do the copying trick for now to ensure everything is set for the workshop. 

**Additional context**
Ben said he would communicate with Hana directly but wanted to log the feature request.

**Comment by hanars** [comment]
The label on the cram shows the individual ID as it is displayed in seqr, not the cram ID. The cram ID itself is not shown anywhere in seqr. I think what @bw2 was talking about had to do with the URL we fetch the data from. @anneodonnell can you confirm that having the URL include the RGP ID is actually a problem? It sounds like your only concern is the display, which will not actually be an issue. The URL will not be visible to most users, but a technically savvy user could find if if they were trying really hard

**Comment by hanars** [comment]
Talked with @bw2 and confirmed that current functionality is what we need/ what he was proposing

**Comment by anneodonnell** [comment]
Great - we can confirm it looks ok once we load the data and readviz
