### ISSUE TITLE
gnomAD SV frequency

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2593]
**Describe the bug**
Currently, the hover over for gnomAD SVs shows the callset AF, not SV AC in gnomAD. Needs to show gnomAD SV AC instead. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/variant/SV0109223_1329453194_f022115_r

**Scope of the bug**
SVs across all projects

**Screenshots**
<img width="1254" alt="Screen Shot 2022-03-28 at 1 41 28 PM" src="https://user-images.githubusercontent.com/37872186/160455903-64eab147-5a72-40f9-925c-0922a02679d5.png">

**Comment by hanars** [comment]
As explained here, we do not have that information available to us from so we can;t show it. I will update that ticket to make it clear we also want to show AC once that is available to us: https://github.com/broadinstitute/seqr/issues/2507
