### ISSUE TITLE
Unable to remove 'saved by' filter

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#2594]
**Describe the bug**
I was playing with the 'saved by' filter on the saved variants page and now can't see all variants. How can I remove the filter? And can we add a 'view all' option? 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0474_cmg_sherr_exomes/saved_variants/family/F024932_she_1865/Known%20gene%20for%20phenotype

**Scope of the bug**
All projects.

**Screenshots**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/44381119/160476194-c5ea367d-8a7a-41c0-886a-6e730e4dfbd8.png">

**Comment by hanars** [comment]
If you click the "saved by" dropdown, at the top of the list of options is a blank space and if you click that it will clear the filter. But I agree that it should say "view all" so its clear what that is/ does

**Comment by hanars** [comment]
the "View All" option has been added
