### ISSUE TITLE
Load SV data to GREGoR training project A-L

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2595]
**Is your feature request related to a problem? Please describe.**
We created GREGoR training projects A-L for an H3Africa workshop we are leading on 4/6-4/9. We pulled from RGP cases for these projects, and one of the cases, RGP_925, has a compound het SNV/SV pair that is a great solve for the case. We'd like to use this case to show off how seqr handles filtering and display of SV data.

**Describe the solution you'd like**
In all 12 of the new training projects (GREGoR training project A-L) we'd like to load SV data only for case GT7, which maps to RGP_925.

**Describe alternatives you've considered**

**Additional context**
Not requesting SV loading for the other cases in the training projects since we haven't finished analysis of the primary SV data for all of these RGP cases yet (they have existing SNV/small indel candidates so are not top of our list for SV review).

**Comment by hanars** [comment]
I have loaded this for training project A: https://seqr.broadinstitute.org/project/R0607_gregor_training_project_/project_page

@Caustint can you take a look and make sure it looks right (and the variant you expect is coming back) and then I can add it to the other projects

**Comment by Caustint** [comment]
I did a quick search in the gene of interest and it looks like the same variant is showing up twice? https://seqr.broadinstitute.org/variant_search/results/4e7b8510371766fd19ea16be90aae8bf?page=1&sort=xpos

**Comment by hanars** [comment]
Good catch. That issue is fixed now, can you take another look?

**Comment by Caustint** [comment]
Looks good!
