### ISSUE TITLE
Gene List dropdown sometimes does not match a loaded Saved Search

### ISSUE THREAD

**Issue by david-ma** [broadinstitute/seqr#2601]
**Describe the bug**
If the user has started a search and set a Gene List, and then selects a Saved Search which does not have a Gene List, the Location search panel's Gene List dropdown is not cleared.

The Location search panel's genes, variants, etc. are all set/blanked correctly, it is just the dropdown component which is not receiving the correct value.

If the Saved Search has a Gene List, the dropdown is set correctly.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/

**Scope of the bug**
All projects, Broad, MCRI, Garvan.

**Screenshots**
Original reproduction instructions from @drtconway
1. Navigate to the variant search page
![Screen_Shot_2022-03-23_at_11 32 19_am](https://user-images.githubusercontent.com/3320713/161173607-10f4433f-4007-4008-9094-9e9fa77fc51e.png)

2. Select a saved search and a gene list.
![Screen_Shot_2022-03-23_at_11 32 42_am](https://user-images.githubusercontent.com/3320713/161173633-ec0098ed-365a-4823-bd4d-be0fec6e1000.png)

3. Search. In this case, you can see there is just one result.
![Screen_Shot_2022-03-23_at_11 33 20_am](https://user-images.githubusercontent.com/3320713/161173670-767bbfd7-9877-4f2e-8f3b-cbdf26cbae37.png)

4. Change the saved search, but don't touch anything else. Note the gene list box shows the gene list you used earlier.
![Screen_Shot_2022-03-23_at_11 33 35_am](https://user-images.githubusercontent.com/3320713/161173689-2e17b5f2-35c8-4dc8-b6ea-c6e1f83ce431.png)

5. Search. Notice that in this case it returns 53 results.
![Screen_Shot_2022-03-23_at_11 33 54_am](https://user-images.githubusercontent.com/3320713/161173701-51b7dfef-1211-4f89-bd01-f1c4019b2f7e.png)

6. Navigate back to the project page, then back to the variant search page.
7. Select the saved search you used in step 4, and the gene list you used, and search. Notice there are only 11 results now.
![Screen_Shot_2022-03-23_at_11 34 29_am](https://user-images.githubusercontent.com/3320713/161173712-9cc2ab00-a6ae-474e-bab0-c631608e2d52.png)

It appears that when a different saved search was selected in step 4, the gene list was cleared in the internal state, but not in the UI, and the search was performed with no gene list applied.

**Comment by hanars** [comment]
this is now fixed in production seqr
