### ISSUE TITLE
Show Created Date column on LocusListTables

### ISSUE THREAD

**Issue by david-ma** [broadinstitute/seqr#2603]
Batch updating the Public Gene Lists can make sorting by Last Updated less useful, because even if the list hasn't changed, a database operation is performed on that row, so Last Updated shows when that list has been last synced with PanelApp, not when that list was last changed.

Adding a Created Date column would help users differentiate between old & new gene lists.

This table is used on the [Summary Data](https://seqr.broadinstitute.org/summary_data/gene_lists) page and also when adding a Gene List to a project. There is enough width on both these pages to accomodate a new column.

I also think that it would also be more useful to set the default sort to Created Date, instead of Name/alphabetically, since there is a Filter/search provided to quickly reach the list you want, if you know the name*.

The new column, as implemented on my local dev env:
<img width="1680" alt="Screen Shot 2022-04-01 at 3 55 50 pm" src="https://user-images.githubusercontent.com/3320713/161197468-587e8079-ed08-4ed7-8847-0f3600f4f83e.png">

*When adding a gene list to a project, the filter is not shown. Shall I add it in this issue or make a seperate issue?
There is enough screen space, and more than 600 lists now.

**Comment by hanars** [comment]
> *When adding a gene list to a project, the filter is not shown. Shall I add it in this issue or make a seperate issue? There is enough screen space, and more than 600 lists now.

I think make it a separate issue, so that this issue can be closed once the code you already submitted goes live and it will just be easier to track what has/ has not been done.
I do agree that adding the filter to the UI for adding a list to a project is a good idea, so I encourage you to make that ticket

**Comment by hanars** [comment]
this is now live in production seqr
