### ISSUE TITLE
Spelling error in help text

### ISSUE THREAD

**Issue by david-ma** [broadinstitute/seqr#2605]
Spelling error in help text

To reproduce:

1. Navigate to the variant search page.
2. Expand the Inheritance panel.
3. Click on the help text `(described here)` link.

The text contains:

> Finds variants where all affected indivs have at least one alternate allele and all unaffected are homozygous reference.

`indivs` should read `individuals`.

**Comment by hanars** [comment]
this is now fixed in production seqr
