### ISSUE TITLE
Pedigree images are not displaying

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2610]
**Describe the bug**
Pedigree files are displaying as a little image symbol. I need to record a seqr demo this weekend and hoped to be able to show pedigrees!

**Link to page(s) where bug is occurring**
(https://seqr.broadinstitute.org/project/R0608_gregor_training_project_/family_page/F039260_gt12)

**Scope of the bug**
I've checked the new training projects and RGP, assuming all projects are impacted.

**Screenshots**
![image](https://user-images.githubusercontent.com/67653781/161326261-9fb63800-c2ff-461e-a1fb-59bf89bc44ef.png)

**Comment by hanars** [comment]
thanks for letting me know! This is fixed now
