### ISSUE TITLE
PedigreeImg shown in FamilyLayout in PopupWithModal is broken

### ISSUE THREAD

**Issue by david-ma** [broadinstitute/seqr#2620]
Original issue:

To reproduce
1. Navigate to a trio.
2. Do a search.
3. For one of the variants, hover over the family link, and pause a moment.
<img width="1681" alt="Screen Shot 2022-04-05 at 5 58 19 pm" src="https://user-images.githubusercontent.com/3320713/161706746-e6644d96-ef1f-43c2-aa43-d211dc22d649.png">
https://seqr.broadinstitute.org/variant_search/results/a4eecaa83cc728c9cff264a994eb1500?page=1&sort=xpos

---

David:

The problem is that FamilyLayout.jsx is given "leftContent" from Family.jsx, and then tries to draw it with only 3/16ths of the space, and rightContent is given 13/16ths of the space. See:
<img width="45%" alt="Screen Shot 2022-04-05 at 3 57 01 pm" src="https://user-images.githubusercontent.com/3320713/161703529-e11d0e30-c318-47b5-bab1-5693a7fe7601.png"> <img width="45%" alt="Screen Shot 2022-04-05 at 3 57 13 pm" src="https://user-images.githubusercontent.com/3320713/161703549-fd55eb8b-a39a-4a08-88c5-6e979e09e27c.png">

---

One part of the problem can be solved using `width: 100%;` CSS on PedigreeImg in LazyPedigreeImagePanel.jsx. This stops the overlapping, but makes the Pedigree Image unreadable.

**Design 1)** A better solution is to also change the width given to leftContent, to 7/16ths, and give the main "fields" part 9/16ths:
<img width="784" alt="Screen Shot 2022-04-05 at 3 43 21 pm" src="https://user-images.githubusercontent.com/3320713/161704183-04d7adbb-6228-4175-90fa-01efd351eff9.png">

**Design 2)** It would be better to put the PedigreeImg in rightContent instead of leftContent, so that users with slow internet don't experience jarring "[Pop in](https://web.dev/optimize-cls/)" when the image loads, shoving the text to the side.
<img width="806" alt="Screen Shot 2022-04-05 at 5 23 36 pm" src="https://user-images.githubusercontent.com/3320713/161704552-bc9b248b-1880-4030-bc50-ef0a5b494201.png">

**Design 3)**  Using `float: right;` would be better in this case than rightContent, because it would allow the text to wrap and wouldn't waste space. But this is a bit hacky and might have side effects on other components.
<img width="941" alt="Screen Shot 2022-04-05 at 5 25 20 pm" src="https://user-images.githubusercontent.com/3320713/161704680-9e07895d-ee74-4d47-85ec-b24fcf7be4ea.png">

**Design 4)** Stacking the PedigreeImg would be helpful for families with pedigrees larger than Trios
<img width="732" alt="Screen Shot 2022-04-05 at 5 16 05 pm" src="https://user-images.githubusercontent.com/3320713/161705079-88e3d9ce-40d4-43ee-b6af-fe269fb70d12.png">

**Design 5)** Image on bottom, to prevent "pop in" on slow internet.
<img width="1504" alt="Screen Shot 2022-04-05 at 5 21 09 pm" src="https://user-images.githubusercontent.com/3320713/161705119-1a85a81f-d944-4d51-b716-f3e8ec50ffcf.png">

**Design 6)** Just increase the size of the Pop up Modal? No example screenshot sorry.

Which approach would be best for SeqR, @hanars?

**Comment by david-ma** [comment]
Notes to self, for working on this issue:

* Important related files are: Family.jsx, PopupWithModal.jsx, FamilyLayout.jsx, LazyPedigreeImagePanel.jsx, IndividualRow.jsx, Matchmaker.jsx

* FamilyLayout is also used in IndividualRow.jsx (used in [the project page](https://seqr.broadinstitute.org/project/R0555_seqr_demo/project_page)) and Matchmaker.jsx, make sure any changes don't break those components.

* To work on the Popup Modal without it closing whenever you mouse out, comment out line 34 in PopupWithModal.jsx
`34:   //  this.setState({ isOpen: false })`

**Comment by hanars** [comment]
So none of these solutions are really the right approach. The actual issue is we are using semantic UI's Grid class which does not set minimum width based on dynamic content, and switching to instead use the Table class solves the display issues without having to refactor the display. PR is here: https://github.com/broadinstitute/seqr/pull/2623

**Comment by david-ma** [comment]
Ok, yeah that fixes the core issue. Would you like me to implement one of the layout designs, using the table system?

Also, there's a visual bug in your PR, the grey `tfoot` doesn't extend all the way across the table now.
<img width="1680" alt="Screen Shot 2022-04-06 at 3 07 09 pm" src="https://user-images.githubusercontent.com/3320713/161900288-75ebe5a5-077d-4ee4-acf8-fe24e213ce8d.png">

It is because adding [this Table Cell (line 70)](https://github.com/broadinstitute/seqr/pull/2623/commits/3b11711dae8a5a06e88c7b6efed6b4d42883f2df#diff-78d92709234a381c503b6593e37de9e18c61823493bf1572a48d9a474cc20af5R70-R73) puts 2 `td` in each `tr` in the `tbody`. But the `tfoot` still only has 1 `th`.

You can fix it by adding a `<Table.HeaderCell />` to [line 148](https://github.com/broadinstitute/seqr/pull/2623/commits/3b11711dae8a5a06e88c7b6efed6b4d42883f2df#diff-78d92709234a381c503b6593e37de9e18c61823493bf1572a48d9a474cc20af5R148).
