### ISSUE TITLE
Update seqr citation and publication info

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2625]
**Is your feature request related to a problem? Please describe.**
Need to update seqr citation and publication link (yay, it's published!)

**Describe the solution you'd like**
In the 'About seqr' section on the main page, update from preprint to - https://onlinelibrary.wiley.com/doi/10.1002/humu.24366

For the 'cite seqr' link at the bottom of the page -
Pais, L. S., Snow, H., Weisburd, B., Zhang, S., Baxter, S. M., DiTroia, S., O’Heir, E., England, E., Chao, K. R., Lemire, G., Osei-Owusu, I., VanNoy, G. E., Wilson, M., Nguyen, K., Arachchi, H., Phu, W., Solomonson, M., Mano, S., O’Leary, M., … O’Donnell-Luria, A. (2022). seqr: A web-based analysis and collaboration tool for rare disease genomics. Human Mutation. https://doi.org/10.1002/humu.24366

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hanars** [comment]
this has been updated
