### ISSUE TITLE
Migration of Families from HMB Project to GRU Project

### ISSUE THREAD

**Issue by jgserran** [broadinstitute/seqr#2627]
This feature request would prevent a future problem when loading data into Seqr. A lot of families need to be moved from the Rare Genomes Project HMB page to the Rare Genomes Project GRU page before their data is loaded. The reason we want to migrate them over is because they were consented under the GRU protocol and we would like to keep them all in the same group. When migrating over the families, it is important that everything is copied over including the notes in the Case Review page. I have added a list of all the families that need to be moved over. It would be great if you are able to transfer all of the families on the list.

[Families for migration to GRU.csv](https://github.com/broadinstitute/seqr/files/8445831/Families.for.migration.to.GRU.csv)

**Comment by hanars** [comment]
RGP_1840 and RGP_1770 do have data loaded so I did not transfer them over. Let me know if you do actually want them moved.

Also, while I am happy to do this once in a blue moon when someone makes a mistake and something needs to be moved, having me move families can not be part of the normal RGP process. If it is your teams intention that I periodically move families, we need to set up a meeting to discuss a different solution for you guys. If this just a once-or-twice thing right now as we are switching over protools than its totally fine to have me move things
