### ISSUE TITLE
Show genes in SVs with no known consequence

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr#2634]
As reported in https://github.com/broadinstitute/seqr/issues/2629 BND SVs have no genes annotated for them. This is because the current SV generation only adds genes with a known impact on `PROTEIN_CODING` regions. Because BNDs by definition are unresolved there is no way to know what impact they would have on a gene, but we still want to show that the breakpoint occurs in a gene. Per this slack thread, we will add this data in later SV callsets and should update the pipeline to seqr: https://the-tgg.slack.com/archives/CT1J8AGES/p1649435522696849

**Comment by lynnpais** [comment]
Break ends now have the gene info. Nothing further needed, so closing this out.
