### ISSUE TITLE
Tracking analysis in seqr

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2648]
**Is your feature request related to a problem? Please describe.**
As there are new data types, we need a better way of tracking what is available, and who/when it has been analyzed. 

**Describe the solution you'd like**
Add new data types for analysis (STR, mito, RNAseq) to the section, 'Analyzed By' in seqr. Old data can be left. See image below. 
For these newer fields - option for bulk checking (on the backend) to allow folks who analyze the data outside of seqr to note cohorts/samples across many projects that have been analyzed. 
We don’t need the sort by CMG/ non-CMG users going forward, it will be pretty obvious based on the email address. 

**Describe alternatives you've considered**
NA

**Additional context**
<img width="877" alt="Screen Shot 2022-04-12 at 11 06 03 AM" src="https://user-images.githubusercontent.com/37872186/162993700-370aeca3-b8e9-4fe7-9994-73e087ae0aac.png">

**Comment by hanars** [comment]
Is it okay to move the existing "analyzed by" values to the "WES/WGS" section?

**Comment by lynnpais** [comment]
Yes, I think that should be fine.

**Comment by lynnpais** [comment]
This is looking good, thank you!

**Comment by lynnpais** [comment]
Emily and I just noticed that the 'Analyzed By' option is missing in cases
where no one has previously selected it. Excuse me if you are still working
on things. Here's an example -
https://seqr.broadinstitute.org/project/R0208_kang_v11/family_page/F010641_k1089

[image: Screen Shot 2022-04-19 at 12.31.34 PM.png]
