### ISSUE TITLE
Add ClinGen to Gene info

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2649]
**Is your feature request related to a problem? Please describe.**
Add ClinGen’s dosage sensitivity scores for genes on the variant page (search results and saved variants).

**Describe the solution you'd like**
Similar to other gene annotations such as the GenCC flag, we would like to have a single tag in Purple, which reads ‘ClinGen’. 
On the hover over, it would display the scores for both haploinsufficiency and triplosensitivity. 
Colors to use for points: 
grey - 0 
blue - 1
lighter green - 2
darker green - 3
empty box with a grey border - 40 (Dosage Sensitivity Unlikely)
empty box with a grey border - 30 (Autosomal Recessive)

Clicking on the hover over should take you to the relevant gene page in ClinGen. For example, COL11A1 would go to - https://search.clinicalgenome.org/kb/genes/HGNC:2186
The same Gene link should be added to the list of links on the gene page on the top.

**Describe alternatives you've considered**
NA

**Additional context**
Here’s an example – 
<img width="576" alt="image" src="https://user-images.githubusercontent.com/37872186/162996573-ab874cf2-4c55-4740-b5ff-a14edddeb5a9.png">

**Comment by lynnpais** [comment]
The link you provided looks good, thanks.

**Comment by hanars** [comment]
> empty box with a grey border - 40 (Dosage Sensitivity Unlikely)
empty box with a grey border - 30 (Autosomal Recessive)

@lynnpais do you want these displayed the same or do you want them to be different?

**Comment by lynnpais** [comment]
Was initially thinking the same, but we can do-
empty box with a BLACK border - 40 (Dosage Sensitivity Unlikely)
empty box with a GREY border - 30 (Autosomal Recessive)

**Comment by hanars** [comment]
this has been added
