### ISSUE TITLE
Horizontal stretch of the family page 

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2658]
**Describe the bug**
The text on the family page is stretched horizontally (so we don't see the full text) and we can’t scroll to the right to access the Variant Search option

**Link to page(s) where bug is occurring**
RGP_123 and RGP_248 
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F019671_rgp_123
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F020329_rgp_248

**Scope of the bug**
Noticed in 2 projects, but there are probably more

**Screenshots**
![Screen Shot 2022-04-20 at 2 11 15 PM](https://user-images.githubusercontent.com/84086816/164295457-6edd3d39-e4d6-4b20-92ba-28c3f2fee090.png)

**Comment by hanars** [comment]
this is fixed now
