### ISSUE TITLE
Order of family members in seqr IGV 

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2667]
**Is your feature request related to a problem? Please describe.**
Proband is not always listed first when loading IGV in seqr. It seems to be a random order (mother then proband, father, mother then proband etc). 

**Describe the solution you'd like**
Use a the same order for all families: top to bottom: proband, mother and father 

**Additional context**
![Screen Shot 2022-04-21 at 5 22 55 PM](https://user-images.githubusercontent.com/84086816/164554597-2189542e-0d25-45f4-af4b-07cff845a985.png)

**Comment by hanars** [comment]
this is actually a bug, as that is supposed to be the functionality

**Comment by hanars** [comment]
this is fixed now
