### ISSUE TITLE
Searchable gene list dropdown menu

### ISSUE THREAD

**Issue by eoheir** [broadinstitute/seqr#2668]
**Is your feature request related to a problem? Please describe.**
In projects that have a large number of gene lists added to them (i.e. RGP), it can be difficult to find the specific gene list that you would like to apply to your search, since there are so many different gene lists to scroll through. 

**Describe the solution you'd like**
If possible, we would like the ‘Gene List’ dropdown menu on the variant search page to be searchable, so that it is quicker/easier to locate your gene list of interest.

**Comment by hanars** [comment]
this has been added
