### ISSUE TITLE
Analyzed by feature missing

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2670]
**Describe the bug**
Related to #2648, the analyzed by feature is missing in cases where it was not previously analyzed and selected. 

**Link to page(s) where bug is occurring**
One example - https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F032068_rgp_1434

**Scope of the bug**
All cases that do not have previous Analyzed By information. 

**Screenshots**
<img width="1269" alt="Screen Shot 2022-04-25 at 9 10 51 AM" src="https://user-images.githubusercontent.com/37872186/165096190-e2ab45e5-72b6-4e95-b52d-7d8943e97d21.png">

**Comment by hanars** [comment]
this is now fixed (FYI @Glemiret)
