### ISSUE TITLE
Sort by Family Name

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2671]
**Describe the bug**
Listing by family name should begin with RGP_1, RGP_2, etc. This is especially important as we are beginning to analyze older cases. Currently it is organized by lowest values 1 and 0, hence RGP_1000 is listed first. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/project_page

**Scope of the bug**
Across seqr

**Screenshots**
<img width="1190" alt="Screen Shot 2022-04-25 at 9 38 36 AM" src="https://user-images.githubusercontent.com/37872186/165101185-7e75e693-b03a-4de9-871b-dd829e3483d7.png">

**Comment by hanars** [comment]
family name sorts alphabetically, not numeircally. Alphabetically this is correct, the same way that  `aaac` comes alphabetically before `aab`. For analying lder cases I recommend using the "data first loaded" sort
