### ISSUE TITLE
Search for family id case-sensitive not working

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2672]
**Describe the bug**
Search for a family using the ID does not seem to be working 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/project_page

**Scope of the bug**
Haven't checked other projects yet

**Screenshots**
<img width="1284" alt="Screen Shot 2022-04-25 at 9 44 04 AM" src="https://user-images.githubusercontent.com/37872186/165101614-6d77ab9c-0b64-4e6f-a117-725df7a0348f.png">

**Comment by hanars** [comment]
this is a bug with upper vs lower case - using `rgp_1000` works

**Comment by hanars** [comment]
this is fixed now
