### ISSUE TITLE
pipeline-runner not running because of missing Bio/EnsEMBL/Registry.pm in docker image

### ISSUE THREAD

**Issue by adlab-bioinfo** [broadinstitute/seqr#2678]
**Describe the bug**
We have installed the latest docker image of SEQR pipeline last week.

```
root@vls186-seqr:/opt/seqr/data# docker images
REPOSITORY                                      TAG           IMAGE ID       CREATED         SIZE
gcr.io/seqr-project/seqr                        gcloud-prod   18237846b371   2 hours ago     2.28GB
gcr.io/seqr-project/seqr                        <none>        8a95d454e45c   5 days ago      2.28GB
gcr.io/seqr-project/pipeline-runner             gcloud-prod   24b0cc0a5772   12 days ago     3.79GB
elasticdump/elasticsearch-dump                  latest        a5057a00907a   3 weeks ago     278MB
docker.elastic.co/elasticsearch/elasticsearch   7.16.3        3a5e93284781   3 months ago    611MB
docker.elastic.co/kibana/kibana                 7.16.3        df64a680d590   3 months ago    1.3GB
gcr.io/seqr-project/redis                       gcloud-prod   98d2caf140c6   5 months ago    113MB
postgres                                        12.6          145bb83bd157   11 months ago   314MB
```
When running the pipeline-runner using this command :

```
root@vls186-seqr:/opt/seqr# cat fam126.sh 
BUILD_VERSION=37
SAMPLE_TYPE=WES
INDEX_NAME=fam126
 
INPUT_FILE_PATH=INPUT/FAM126.vcf
 
docker-compose exec pipeline-runner load_data.sh $BUILD_VERSION $SAMPLE_TYPE $INDEX_NAME $INPUT_FILE_PAT
```

 after a few minutes we have this error message :

`Can't locate Bio/EnsEMBL/Registry.pm in @INC (you may need to install the Bio::EnsEMBL::Registry module) (@INC contains: /ensembl-vep-release-99/modules /ensembl-vep-release-99 /etc/perl /usr/local`
 

**Scope of the bug**

When running pipeline-runner with an VCF file for input the processing stop with  error messages.

**Screenshots**

I have uploaded a few screenshot of the problem and the log messages file.

[seqr_log_adlab.txt](https://github.com/broadinstitute/seqr/files/8557643/seqr_log_adlab.txt)
<img width="1419" alt="Capture d’écran, le 2022-04-25 à 16 10 16" src="https://user-images.githubusercontent.com/104390385/165166956-99e6c51d-c0a0-4855-8714-b368d723958f.png">
<img width="1422" alt="Capture d’écran, le 2022-04-25 à 16 09 48" src="https://user-images.githubusercontent.com/104390385/165166959-fab77f2d-120a-4375-87b0-7fe70620f725.png">
.

**Comment by adlab-bioinfo** [comment]
Within the docker image there is the ./ensembl-vep-release-99/modules/Bio/EnsEMBL folder with perl package but no trace of Registry.pm

# find . | grep EnsEMBL
./ensembl-vep-release-99/modules/Bio/EnsEMBL
./ensembl-vep-release-99/modules/Bio/EnsEMBL/VEP

**Comment by hanars** [comment]
can you confirm that you ran the necessary set up steps for the pipeline runner image? Per the [instructions](https://github.com/broadinstitute/seqr/blob/master/deploy/LOCAL_INSTALL.md#option-2-annotate-and-load-on-prem) you should have run 
```
docker-compose exec pipeline-runner download_reference_data.sh $BUILD_VERSION
```

**Comment by adlab-bioinfo** [comment]
yes I did.

Here is the content of my data folder.

***@***.***:/opt/seqr/data# ls -al
total 28
drwxrwxrwx  7 root             root 4096 Apr 11 20:30 .
drwxr-xr-x  4 root             root 4096 Apr 26 18:16 ..
drwxrwxrwx  2 root             root 4096 Apr 25 20:39 elasticsearch
drwxrwxrwx  5 root             root 4096 Apr 25 19:23 input_vcfs
drwxrwxrwx 19 systemd-coredump root 4096 Apr 20 18:27 postgres
drwxrwxrwx  3 root             root 4096 Apr 12 20:18 seqr-reference-data
drwxrwxrwx  4 root             root 4096 Apr 13 20:43 vep_data
***@***.***:/opt/seqr/data# du -h --max-depth=1
4.0K ./elasticsearch
1.3G ./input_vcfs
40M ./postgres
312G ./seqr-reference-data
25G ./vep_data
338G .

But I had trouble with my Internet connection so I had to download files
manually.

Is the missing Perl package installed during this step ?

**Comment by adlab-bioinfo** [comment]
I doing the complete  download_reference_data step again, 

docker-compose exec pipeline-runner download_reference_data.sh 37

**Comment by adlab-bioinfo** [comment]
This is the data folder after the downlaoding:

root@vls186-seqr:/opt/seqr/data# du -h --max-depth=2
4.0K	./elasticsearch
4.0K	./input_vcfs
312G	./seqr-reference-data/GRCh37
312G	./seqr-reference-data
13G	./vep_data/homo_sapiens
13G	./vep_data/loftee_data
25G	./vep_data
337G	.

**Comment by adlab-bioinfo** [comment]
Same error with a new docker image :

```
Hail version: 0.2.90-ef50e56cae11
Error summary: HailException: VEP command '/vep --format vcf --json --everything --allele_number --no_stats --cache --offline --minimal --assembly GRCh37 --dir_cache /vep_data --plugin LoF,human_ancestor_fa:/vep_data/loftee_data/GRCh37/human_ancestor.fa.gz,filter_position:0.05,min_intron_size:15,conservation_file:/vep_data/loftee_data/GRCh37/phylocsf_gerp.sql,gerp_file:/vep_data/loftee_data/GRCh37/GERP_scores.final.sorted.txt.gz -o STDOUT' failed with non-zero exit status 2
  VEP Error output:
Can't locate Bio/EnsEMBL/Registry.pm in @INC (you may need to install the Bio::EnsEMBL::Registry module) (@INC contains: /ensembl-vep-release-99/modules /ensembl-vep-release-99 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.2
DEBUG: 1 running tasks, waiting for next task to finish
INFO: Informed scheduler that task   SeqrVCFToMTTask__seqr_reference__VARIANTS__input_vcfs_FAM1_2343bbfe14   has status   FAILED
DEBUG: Asking scheduler for work...
DEBUG: Done
DEBUG: There are no more tasks to run at this time
DEBUG: There are 2 pending tasks possibly being run by other workers
DEBUG: There are 2 pending tasks unique to this worker
DEBUG: There are 2 pending tasks last scheduled by this worker
INFO: Worker Worker(salt=962358823, workers=1, host=5132187de51d, username=root, pid=5691) was stopped. Shutting down Keep-Alive thread
INFO: 
===== Luigi Execution Summary =====

Scheduled 3 tasks of which:
* 1 complete ones were encountered:
    - 1 VcfFile(filename=/input_vcfs/FAM126.vcf)
* 1 failed:
    - 1 SeqrVCFToMTTask(...)
* 1 were left pending, among these:
    * 1 had failed dependencies:
        - 1 SeqrMTToESTask(...)

This progress looks :( because there were failed tasks

```
===== Luigi Execution Summary =====

**Comment by adlab-bioinfo** [comment]
I have been able to process a VCF file. Seems to be fixed.

Can we upload json index of this version into our previous SEQR Elasticsearch index ?

**Comment by hanars** [comment]
I'm not really sure what that means. The way seqr uses elasticsearch, each index is created once and never updated so you should never be adding anything to a previous index. You should update seqr to use the new index
