### ISSUE TITLE
Add 'Project' column to saved variant data

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2681]
**Is your feature request related to a problem? Please describe.**
I would like to generate aggregate stats across all our solved cases such as average GQ, AB, SpliceAi score, etc. Some projects have misleading discovery tags and it would be helpful to filter these out. 

**Describe the solution you'd like**
As you suggested, it would be helpful to have a 'Project' column for the downloadable variant metadata. 

**Describe alternatives you've considered**
NA

**Additional context**
Referring to the data on this page - https://seqr.broadinstitute.org/summary_data/saved_variants

**Comment by hanars** [comment]
this has been added
