### ISSUE TITLE
GTex data missing for certain genes

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2683]
**Describe the bug**
GTex data missing on the Gene Page for certain genes

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/variant/SV0111289_4154240785_f019820_r

**Scope of the bug**
Across seqr for certain genes

**Screenshots**
<img width="1213" alt="Screen Shot 2022-04-27 at 11 29 10 AM" src="https://user-images.githubusercontent.com/37872186/165555295-f5de333c-e3a0-412d-9df9-f6a1edc354ef.png">

**Comment by hanars** [comment]
gtex was actually having an outage earlier, but they seem to have fixed it and this is now working again
