### ISSUE TITLE
Missing "analyzed by" option on family page 

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2685]
**Describe the bug**
Option of adding a stamp with analyst name and date to say that case has been analyzed on family page is not there anymore. ("analyzed by"). 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F031937_rgp_1822

**Scope of the bug**
Noticed in several projects, RGP_ 1822, RGP_1738, RGP_2036

**Screenshots**
![Screen Shot 2022-04-27 at 1 50 15 PM](https://user-images.githubusercontent.com/84086816/165589313-6589c9d0-9df7-432f-b221-65bd5b704bfe.png)

**Comment by hanars** [comment]
duplicates https://github.com/broadinstitute/seqr/issues/2670

**Comment by Glemiret** [comment]
@hanars Sorry for the duplicate! Is it supposed to be resolved? I don't see it in the projects I mentioned above.

**Comment by hanars** [comment]
Its not resolved, that is an open ticket. I will update that ticket once it is resolved. It is too difficult for me to track my work on multiple tickets, so when people open tickets for issues that already have tickets I close the duplicate tickets and figure they can follow the original tickets for updates on when something is fixed

**Comment by Glemiret** [comment]
Oh I misread and saw that Lynn's ticket was closed. Sounds good.
