### ISSUE TITLE
Issue with displaying Gene Lists

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2703]
**Describe the bug**
Gene Lists are not displaying as expected in the 'Add Gene List' view on a Project Page. 

**Link to page(s) where bug is occurring**
One example - https://seqr.broadinstitute.org/project/R0588_tgg_thaker_wgs/project_page > Add Gene List

**Scope of the bug**
All projects 

**Screenshots**
<img width="1159" alt="Screen Shot 2022-05-04 at 2 00 27 PM" src="https://user-images.githubusercontent.com/37872186/166766436-6ada407f-5bf8-4f87-a4f0-6c5cea22a3e6.png">

**Comment by hanars** [comment]
this is fixed now
