### ISSUE TITLE
Provide dropdown for files to load to AnVIL

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr#2719]
Populate a dropdown with all the possible files a user can load, rather than having a free text field where thye type it in

**Comment by ShifaSZ** [comment]
I'm considering creating a new `AnvilFileSelector` component and using it in DATA_BUCK_FIELD for the second page of the data loading Wizard. The new component is similar to the `LocusListSelector`. It can load options from the backend. Is it the right way to do it? @hanars

**Comment by hanars** [comment]
So we proabbly need a new component for this, but it shouldn't fetch the data. We should have the list of files come back from the `grant_access` step so they will be available to the form as part of the form's values. You can wrap the new `AnvilFileSelector` in a `FormSpy` to give it access to all the form's values

**Comment by ShifaSZ** [comment]
It sounds great to get the file list in the `grant_access` step. Can the `asyncValues` in the FormWizard state be accessible from the form? If not, should we pass these values in through initialValues? As an alternative solution, can we save these values to the redux store so that `AnvilFileSelector` can get them?

**Comment by hanars** [comment]
Good catch, right now the `asyncValues` would only be accessible on form submit, not in the form itself. Both the solutions you propose are possible, we could either make the `asyncValues` accessible to the form field, or we could pass them through in `initialValues`.  I would rather we did not add them to the redux store. If we wanted to make them available on the field, we could add a function that would bind asyncValues to a field if the field wanted, something like
```
const getConfiguredPageFields = fields =>  {
  const { asyncValues } = this.state
  return fields.map(field => field.addAsyncValues ? { ...field, asyncValues } : field)
}
```

If we wanted to make them available on the form, we would pass them as `initialValues` but we would want to make sure not to skip adding the real `initialValues` so we would want to change the initial state for that field to be null instead of an empty dict and then we would do something like `initialValues={asyncValues || initialValues}`. The `AnvilFileSelector` would be able to get the values from a FormSpy this way. If we go with this approach we can also could get rid of the custom `onFormSubmit` behavior as the values will already be submitted by the form. 

 Either approach works, its up to you which you think is cleaner.

**Comment by hanars** [comment]
Alternatively, since this is a more complex approach than I originally thought, you could go with your initial idea of making the `AnvilFileSelector` have its own DataLoader and have it fetch the files as a separate endpoint, instead of having it retrurned from `grant_access`

**Comment by ShifaSZ** [comment]
> If we wanted to make them available on the field, we could add a function that would bind asyncValues to a field if the field wanted, something like
> 
> ```
> const getConfiguredPageFields = fields =>  {
>   const { asyncValues } = this.state
>   return fields.map(field => field.addAsyncValues ? { ...field, asyncValues } : field)
> }
> ```

Similar to your idea, how about we add a field decorator callback to the page field for the `ForWizard` to update the fields according to asyncValues? The `ForWizard` does below for each page
```
const fields = pages[pageIndex].fields.map( ({fieldDecorator, ...field}) => fieldDecorator ? { ...field, ...fieldDecorator(this.state.asyncValues) } : field)
```
Then, we use the `Select` component for the `DATA_BUCK_FIELD` and add the `fieldDecorator` to it like
```
{
...,
fieldDecorator: ({ fileList }) => fileList ? {options: fileList.map( file => ({value:file, name:file}))} : {},
...,
}

**Comment by hanars** [comment]
I don't see an advantage to this approach though? Compared to my proposal, its just as much complexity in the wizard component itself but much more complexity for the field component. Why add complexity in 2 places instead of one?

**Comment by ShifaSZ** [comment]
Okay, I'll create a new AnvilFileSelector component and call a new API to load the file list while the component is created.
