### ISSUE TITLE
Add UI for adding new data to existing AnVIL project

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr#2721]
Add a button on the project page where user can provide new samples and new file in the existing workspace and ask for loading from the new file to the project:

- The "Edit Datasets" button is currently shown to data managers/ PMs. In non-cmg projects with AnVIl workspaces, users with edit access to the project will be shown a "Request Additional Data" button in the same spot. 
  -  This will be available for projects which are not contained in the `ANALYST_PROJECT_CATEGORY` only. We will need to update the data returned from the server to add an `isAnalystProject` field for projects to do this properly
- Clicking the button will open a modal for users to request adding additional data
  -  a form with a subset of the fields from the main loading form: DATA_PATH_FIELD, UPLOAD_PEDIGREE_FIELD, AGREE_CHECKBOX
  - an info box informing users that the joint called VCF must include all previously loaded samples in that project, and must be in the same workspace as before
  - update the text shown in the pedigree upload field to say that they only need to include newly added individuals
- Submitting the form will hit a new api endpoint, `project/(?P<project_guid>[^/]+)/add_workspace_data`
  - This will  be in the existing `anvil_workspace_api.py` file, and will share a lot of code with the current `create_project_from_workspace` endpoint, we will want to make helper methods  
  - The endpoint will do the following:
    - Check the user has edit access on the underlying AnVIL workspace
    - Check that the agree checkbox was checked and then run the `add_service_account` function for the underlying workspace. Although this was run when the users initially requested data loading, we want to run it again in case they went into the workspace in the meantime and removed seqr's access.
    - Run the same data path validation as we do in the create api. However, also validate that all samples in the project that currently have data loaded plus all the new samples in the pedigree table are in the VCF, not just the new samples. 
    - Add the new individuals to the project
    - upload a sample id file to google bucket that overwrites the existing one. This needs to have the full sample id list, with both the old and new samples
    - Trigger the DAG the same as in the create API. Use the same sample type as was used originally (i.e the sample type all the loaded samples have)
    - Send all the same alerting as in the create api. For the slack message, update the body to say that the user equested to load additional data

**Comment by larrybabb** [comment]
@hanars add some more info to description so that Shifa can begin working on this when he's done his current task.

**Comment by hanars** [comment]
Added more detail to the description

**Comment by hanars** [comment]
Updated details based on moving to a wizard layout for AnVIl loading (https://github.com/broadinstitute/seqr/pull/2817):

This should also use a wizard as well, sharing code as much as possible. There will be the same 3 steps in this workflow as in the initial data request workflow, with the following changes:

1. The grant access step is identical
2. The validate VCF step is the same endpoint, but the UI leaves out the sample type and genome version fields
3. The final step has the pedigree upload but no project description field. The endpoint for this step is different, and will be the `project/(?P<project_guid>[^/]+)/add_workspace_data` step described in theticket description, minus the parts that are done in the grant access and VCF validation steps

**Comment by ShifaSZ** [comment]
> * Run the same data path validation as we do in the create api. However, also validate that all samples in the project that currently have data loaded plus all the new samples in the pedigree table are in the VCF, not just the new samples.

I assume that we get the previously loaded samples from the previous VCF files. Is that right? If yes, how can we get the loaded VCF file names?

**Comment by hanars** [comment]
> I assume that we get the previously loaded samples from the previous VCF files. Is that right? If yes, how can we get the loaded VCF file names?

Absolutely not. We require ALL samples, both those that are previously loaded and the new ones, to be joint called together and be made available in a single VCF. Our validation here must check that ALL samples are in the single VCF specified in the new loading request

**Comment by hanars** [comment]
> Do we need to support removing some of the existing individuals?

No. To be as clear as I can, in order to use this form and add new data to seqr users must provide a new joint called VCF that contains ALL the samples that were previously loaded as well as any new samples. If any samples are missing from the VCF, we fail validation, tell the user the samples are missing, and do not let them proceed with loading. This is non-negotiable. We do not go looking for other VCFs. We do not remove individuals form the project. We do not do anything other than fail validation and refuse to let users proceed.

**Comment by ShifaSZ** [comment]
> 3\. The final step has the pedigree upload

Can the user upload an empty pedigree file or even not upload any file when there are no additional individuals?

**Comment by hanars** [comment]
> > 3. The final step has the pedigree upload
> 
> Can the user upload an empty pedigree file or even not upload any file when there are no additional individuals?

No, there is no reason for us to waste our time and money loading a file with no new samples

**Comment by ShifaSZ** [comment]
> 2\. The validate VCF step is the same endpoint, but the UI leaves out the sample type and genome version fields

We may still need the sample type field because the data to be loaded can be different type.

**Comment by hanars** [comment]
> We may still need the sample type field because the data to be loaded can be different type.

No it cant, we do not support this. Use the same sample type as all the previously loaded samples
