### ISSUE TITLE
Request to add SpliceAI field when downloading search results

### ISSUE THREAD

**Issue by melnel000** [broadinstitute/seqr#2722]
**Is your feature request related to a problem? Please describe.**
When downloading variant search results, the SpliceAI score is missing from the output text file.

**Describe the solution you'd like**
It would be great if the downloaded results could include the SpliceAI score.

**Describe alternatives you've considered**
I have not tried any alternatives.

**Additional context**
None

Thanks!

**Comment by hanars** [comment]
the download has been updated and now includes splice AI

**Comment by melnel000** [comment]
Thanks very much for adding this feature.

Would it be possible to also include polyphen, sift, muttaster, fathmm and rsid fields in the downloaded results as well?

**Comment by hanars** [comment]
they are already included
