### ISSUE TITLE
Minor bug in RGP_248 display

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2724]
**Describe the bug**
Bug when hovering over RGP_248 (see screenshot), a pop window appears and it is not possible to click on RGP_248.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F020329_rgp_248/Known%20gene%20for%20phenotype

**Scope of the bug**
Just this project

**Screenshots**
If applicable, add screenshots to help explain y
![Screen Shot 2022-05-19 at 6 18 07 PM](https://user-images.githubusercontent.com/84086816/169413910-e256726a-459c-423b-b1d3-b9f94044133e.png)
our problem.

**Comment by hanars** [comment]
this is fixed
