### ISSUE TITLE
Gene list display bug

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2726]
**Describe the bug**
On the project page, if the gene list name extends to the tags column on the right, the delete or ? function does not work.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/project_page

**Scope of the bug**
Across seqr

**Screenshots**
<img width="1397" alt="Screen Shot 2022-05-20 at 2 14 23 PM" src="https://user-images.githubusercontent.com/37872186/169589357-86ab5c3c-1e2e-4d17-9adf-a1ffad7c372b.png">

**Comment by hanars** [comment]
this is fixed now
