### ISSUE TITLE
Limit amount of space for user-added Gene Lists

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2727]
**Is your feature request related to a problem? Please describe.**
User-added gene list tags are taking up a significant amount of real estate without adding much value.

**Describe the solution you'd like**
Limit the space for user-added tags (excludes GenCC, ClinGen, constraint metrics) to 3 rows. Add scroll functionality if the tags exceed the allotted space. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hanars** [comment]
Right now the order the list is shown is pretty random (or maybe alphabetical) but if we do this we probably want to think about that more carefully. Thoughts on putting the panel app lists above the other lists? Would we want consider the confidence of the list as part of that ordering?

**Comment by lynnpais** [comment]
Can we keep user-added gene list tags to 5 rows for now? For most projects, that should show all the tags without needing to scroll. I'll discuss with the other analysts about ordering and put in a new ticket when we have made a decision. Thanks.

**Comment by hanars** [comment]
this is done
