### ISSUE TITLE
Expand OMIM box

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2728]
**Is your feature request related to a problem? Please describe.**
Would be nice to be able to see all conditions a gene is associated with per OMIM in one view. This is especially useful to take screenshots for presentation purposes. Currently, you can scroll, but not expand the box.

**Describe the solution you'd like**
Add functionality to allow a user to click and drag the bottom right corner of the box to expand it vertically.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hanars** [comment]
dragging the lower right corner will resize the omim container
