### ISSUE TITLE
Saved variants page bug

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2733]
**Describe the bug**
The saved variants bar not loading - resulting in a blank page  

**Link to page(s) where bug is occurring**
Link to saved variants bar on the project page - https://seqr.broadinstitute.org/project/R0351_cmg_bonnemann_exomes/family_page/F027487_bon_b16_99
Blank page - https://seqr.broadinstitute.org/project/R0351_cmg_bonnemann_exomes/family_page/F027487_bon_b16_99

**Scope of the bug**
At least  3 projects affected

**Screenshots**
NA

**Comment by hanars** [comment]
this is fixed now, sorry for the disruption
