### ISSUE TITLE
Default transcript keeps resetting to CLASP1 in RGP_248

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#2749]
**Describe the bug**
I have changed the 'user chosen transcript' to RNU4ATAC several times for RGP_248 and it keeps switching back to CLASP1. 

**Link to page(s) where bug is occurring**
Family page: https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F020329_rgp_248
Saved variants page: https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F020329_rgp_248/Known%20gene%20for%20phenotype

**Scope of the bug**
I tried to change the transcript of another variant in this family (not compound het) and it also revertted when refreshing the page. 

**Screenshots**
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/44381119/170311008-e882bf9e-b772-404c-bd84-83994e94ed30.png">

**Comment by stephditroia** [comment]
Another example: Trying to change UPF1 variant to MANE transcript [ENST00000262803]
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F031947_rgp_1840/Tier%201%20-%20Novel%20gene%20and%20phenotype

**Comment by hanars** [comment]
I fixed these on a case-by-case basis, leaving this ticket open to fix the underlying issue and prevent this from happening again
