### ISSUE TITLE
Use the WES/WGS date for the last analyzed feature 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2754]
**Is your feature request related to a problem? Please describe.**
The 'last analyzed' feature is currently using dates for any data types such as gCNV or STR or WES on the project page.

**Describe the solution you'd like**
The last analyzed feature must use the WES/WGS date, and not dates for other data types such as gCNV or STR.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hanars** [comment]
I'm sorry, but can you describe what you mean by the "last analyzed feature"?

**Comment by lynnpais** [comment]
<img width="1211" alt="Screen Shot 2022-05-26 at 11 52 18 AM" src="https://user-images.githubusercontent.com/37872186/170525508-3a3d6bdb-fb94-4cad-940c-4140aaead405.png">
<img width="1211" alt="Screen Shot 2022-05-26 at 11 52 18 AM" src="https://user-images.githubusercontent.com/37872186/170525525-8dd793f9-119c-4a29-a88f-4f63f673a4be.png">

On the project page, the option to filter cases by the date it was last analyzed. We would like this feature to use the WES/WGS analyzed date found on the family page.

**Comment by hanars** [comment]
this has been done
