### ISSUE TITLE
Disclaimer for pedigree file uploads

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2758]
**Is your feature request related to a problem? Please describe.**
Include a disclaimer for pedigree file uploads in seqr.

**Describe the solution you'd like**
Have a pop up which needs to be cleared before uploading with the following text, "seqr is not a HIPAA-compliant platform. By proceeding, I affirm this image does not contain any protected health information (PHI)"

**Comment by hanars** [comment]
this has been added
