### ISSUE TITLE
Ordering Gene Lists

### ISSUE THREAD

**Issue by KaitlynSparks** [broadinstitute/seqr#2766]
Would it be possible to order the display of the gene lists? We are using multiple gene lists in our research group and it is frustrating to sift through everything searching for a specific gene list. 

First prize for us would be groups and subgroups of gene lists so that we can organise things a bit more. It would also be great if we could search for variants in a specific gene list group (see feature request #2765 ). 

If this is not possible or not easily implementable, would it be possible to organise the gene lists alphabetically?

Thank you for your time and your effort.

**Comment by KaitlynSparks** [comment]
Thank you for your response. I meant in both the gene lists on the project page and in the dropdown for search.

**Comment by hanars** [comment]
this has been updated

**Comment by KaitlynSparks** [comment]
Fantastic! Thank you.
