### ISSUE TITLE
Variant search issue in THA_201

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2767]
**Describe the bug**
There seems to be something off with the variant search in THA_201. A standard recessive or dominant permissive search is returning 0 variants. We do have trio data. 

If I set the same search to ? for the parents in the inheritance section, variants are returned, but for many, it appears as 'No Call' for one of the parents.  

**Link to page(s) where bug is occurring**
Recessive permissive search with 0 variants - https://seqr.broadinstitute.org/variant_search/results/00fe51cd64d9c137747a8d7a4bdacb2b?page=1&sort=in_omim

No call - https://seqr.broadinstitute.org/variant_search/results/c54c771254f93c36bb2fb7a070ad2798?page=1&sort=in_omim

**Scope of the bug**
Case specific

**Screenshots**
<img width="1226" alt="Screen Shot 2022-05-31 at 1 41 33 PM" src="https://user-images.githubusercontent.com/37872186/171246675-1b36d641-397a-4044-9086-229c4cbddc80.png">

**Comment by hanars** [comment]
@staceyhall or @williamphu do we know if there is anything weird about this samples in this family? It appears that there is "no call" for every single variant in at least 1 of the parents, which is very much not what we would expect. That seems like an issue with the data itself

**Comment by shall48** [comment]
@hanars I don't know of anything weird with this family. Is this something that could be a relatedness issue? We have not done a check on this family since it has not been loaded in a while.

**Comment by hanars** [comment]
Yeah I also wonder if we ever ran the QC pipeline on this project, I would be interested to know if it flagged anything

**Comment by williamphu** [comment]
@shall48 can you confirm that these individuals are in the latest WES callset? I can run relatedness if so, and take a look at the calls in the callset.

**Comment by shall48** [comment]
@hanars I am not sure what is going on here as the relatedness check came back fine.

**Comment by hanars** [comment]
Did we run the QC pipeline to see if there are any other issues? Maybe the data is just really low quality?

**Comment by williamphu** [comment]
We have not yet, I can run that and get back in a few days

**Comment by hanars** [comment]
@mike-w-wilson William was checking the quality of these samples before he left but I don't think he ended up doing it. Could you take a look?

**Comment by williamphu** [comment]
Sorry about the delay, I've been offline with moving. I just pulled Sample QC on these individuals, but I don't know how to interpret the scores:
[Thaker_WES_THA_201.tsv.zip](https://github.com/broadinstitute/seqr/files/9049154/Thaker_WES_THA_201.tsv.zip)

**Comment by mike-w-wilson** [comment]
This file looks like picard metric file that is put into the sample QC pipeline. The sample QC output will end up here: `gs://seqr-datasets/v02/GRCh3*/RDG_W*S_Broad_**ternal/v*/sample_qc/final_output/seqr_sample_qc.tsv
`

**Comment by lynnpais** [comment]
Cohort is not active. Closing this out for now.
