### ISSUE TITLE
Dominant search in RGP_1496

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2782]
**Describe the bug**
Proband fibroblasts genome (RGP_1496_3_fbs) has been loaded in May 2022 from family page. A dominant search for het variants just in fibroblasts (RGP_1496_3_fbs) return 10 000 variants with no genotype calls in RGP_1496_3_fbs (screenshot). Other searches show genotype in RGP_1496_3_fbs. Am I missing something here? This is not the result I am expecting. Thank you for your help. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/f489c8e7ca39500c6a6c535108c931ef?page=1&sort=splice_ai

**Scope of the bug**
Just this family 

**Screenshots**
![Screen Shot 2022-06-10 at 5 19 16 PM](https://user-images.githubusercontent.com/84086816/173153272-f6041046-79ef-4f76-99cf-4a1732d39636.png)

**Comment by hanars** [comment]
I'm not sure how, but somehow the custom allele count and custom affected status added up weirdly in this search and did not apply properly. But leaving affected status alone and just setting the allele counts so only variants in RGP_1496_3_fbs 
 works: https://seqr.broadinstitute.org/variant_search/results/2738229727c8139f3daa1e1c65b9941f?page=1&sort=splice_ai

**Comment by hanars** [comment]
Heres what I did for allele counts: 
<img width="884" alt="image" src="https://user-images.githubusercontent.com/24598672/173431537-360f509f-2223-4e29-985d-38503deacef2.png">

I also only got one variants based on this search, which had a lot of other filters applied as well. If you truly want all the de-novo variants called in fibs but not blood, this the search that returns that but there are 20,000 variants: https://seqr.broadinstitute.org/variant_search/results/b1df34fd064700bef166061aa36af146?page=1&sort=splice_ai

**Comment by Glemiret** [comment]
Thanks! I got it now:)
