### ISSUE TITLE
Applying the "No data expected" analysis status to all RGP cases with a Case Review status of Not Accept

### ISSUE THREAD

**Issue by MCOLeary** [broadinstitute/seqr#2786]
Recently, a new analysis status option "No data expected" was created. We'd like to have this status applied to all RGP cases with a case review status of "Not Accepted" in the "Rare Genomes Project_Genomes_HMB" and "Rare Genomes Project_Genomes_GRU" projects.  

This is a one-time request. We will manually apply this status option for all new cases going forward.

**Comment by hanars** [comment]
I'm also updating "Lost to follow up" and "Inactive" families
