### ISSUE TITLE
Filtering cases in seqr

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2795]
**Is your feature request related to a problem? Please describe.**
We would like to improve the ability to filter cases in projects in seqr.

**Describe the solution you'd like**
Below is the UI proposed. It includes drop downs with the ability to check off multiple boxes in a category. Use 'AND' between categories, e.g., Analyzed By AND Analysis Date. User hits Enter after making selections (is this the best approach)?  

**Describe alternatives you've considered**
As you said, this will likely need a few iterations to get just right. Happy to provide more detail or discuss as you are working on this feature. 

**Additional context**
<img width="902" alt="Screen Shot 2022-06-22 at 3 42 25 PM" src="https://user-images.githubusercontent.com/37872186/175123908-e63853c4-48dd-43b8-bd23-1aaf8323c2f8.png">

**Comment by hanars** [comment]
Can you please submit a separate ticket for the new filters you want to add. I am treating this as a ticket for just the UI change and the ability to select multiple filters across different categories. In the mocked up UI there do appear to be filters that are not currently available in seqr, but I need more details in the ticket than you provide here (i.e. what exactly the new filters are, what category they are in, and what do they do)

**Comment by hanars** [comment]
The redesign for these filters is now live
