### ISSUE TITLE
Noncoding exon transcript variants

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2804]
**Is your feature request related to a problem? Please describe.**
The issue to address: the majority of noncoding transcript exon variant are in obscure transcripts from coding genes (that are unlikely to be clinically or biologically interesting), a minority are actual transcripts of RNA genes that are never coding (the ones we are interested in). 

**Describe the solution you'd like**
We discussed to add 2 annotations categories for noncoding transcript exon variants enabling to specifically select noncoding variants that are in the canonical transcript of that gene. This would replace the current “noncoding transcript exon variant” annotation (see screenshot) to the following 2 annotations:
“noncoding transcript exon variants (canonical)” 
Hover over the question mark shows the following text: “a sequence variant that changes noncoding exon sequence in a canonical transcript for that gene, typically a noncoding gene”
“noncoding transcript exon variants (all)”
Hover over the question mark shows the following text: “a sequence variant that changes noncoding exon sequence in any transcript for that gene, often a noncoding version of a protein coding gene”

**Describe alternatives you've considered**
This is the best solution we came up with during our group discussion in June 2022. 

**Additional context**
<img width="304" alt="Screen Shot 2022-06-28 at 1 56 42 PM" src="https://user-images.githubusercontent.com/84086816/176543862-ba58f14d-0443-461e-9e66-8e935c15ab60.png">

**Comment by anneodonnell** [comment]
This is a problem in analysis and I'd put it as moderate-high priority to work on. We have some work arounds that our team can do manually but external users will not know to do that (and it's not efficient for our team long term either). Thanks!

**Comment by hanars** [comment]
@lynnpais can you make sure there is a corresponding pipeline ticket for this and link that here

**Comment by lynnpais** [comment]
Pipeline ticket [# 378](https://github.com/broadinstitute/seqr-loading-pipelines/issues/378#issue-1484878609)

**Comment by lynnpais** [comment]
@Glemiret is this working now as expected?

**Comment by Glemiret** [comment]
Hi Lynn and Hana, 
What I currently see in seqr searches annotations is different than what was suggested in the above ticket (see screenshot). There are 4 options, 2 have the same hover over text. This seems confusing to me. Do you know what was the reason for these options? 
Thanks, 
Gabrielle 
![Screenshot 2023-07-24 at 1 37 36 PM](https://github.com/broadinstitute/seqr/assets/84086816/9066a5c6-049a-482a-9c0c-a3f3d25638fb)

**Comment by hanars** [comment]
this ticket has not been implemented yet so I would not exppect the changes to have gone through. @lynnpais just because a linked pipeline ticket is done does not mean that the work has been done on seqr's end to make something happen - if there is both a seqr and pipleine ticket it means that there is separate work in both the pipeline and seqr repos. The result of a blocked ticket having its linked pipeline ticket completed is to unblock the seqr ticket, not assume its done

**Comment by lynnpais** [comment]
noted - sorry for the confusion.

**Comment by hanars** [comment]
this has been added
