### ISSUE TITLE
Filtering cases in seqr - new features

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2809]
**Is your feature request related to a problem? Please describe.**
Related to #2795 Filtering cases in seqr

**Describe the solution you'd like**
In addition to the UI change, we would like the following new filters:
1. In the Analyzed By section, the ability to filter cases by a specific user by typing the name of the analyst
2. Create a new section: Analysis Date. This should refer to the Analyzed By information on the family page. With this feature, a user should be able to for example select 'Not Analyzed' under Analyzed By and 'WES/WGS' under Analysis Date, to display all cases where the WES/WGS data has not been analyzed by anyone.
2.1. Under Analysis Date filter, create a new field: >1 year since last analysis. This date should refer to the Analyzed By information on the family page. The idea is to help a user identify all cases that have not been analyzed. The user can further specify, what type of data has not been analyzed >1 yr by checking of WES/WGS in Analysis Date.

**Describe alternatives you've considered**
NA

**Additional context**
<img width="902" alt="175123908-e63853c4-48dd-43b8-bd23-1aaf8323c2f8" src="https://user-images.githubusercontent.com/37872186/177342171-80ee9217-de87-4488-950e-731e05a1e6c0.png">

**Comment by hanars** [comment]
Discussed and decided to move the "Analysis Date" section under "Analysed By", but as a visually distinct section that had AND behavior with other categories

**Comment by hanars** [comment]
please submit new requests as a separate ticket, the work encapsulated in the original ticket is already done and I will be releasing it without the requested updates

**Comment by hanars** [comment]
This is now live. Please submit a new issue if any of the behavior is not working the way you want
