### ISSUE TITLE
Gene-specific IGV error in family 859-18105734

### ISSUE THREAD

**Issue by eoheir** [broadinstitute/seqr#2811]
**Describe the bug**
When trying to view the reads for any variant called in the HCN1 gene in family [859-18105734](https://seqr.broadinstitute.org/project/R0623_neurodev_wave1_sa/family_page/F039702_859_18105734), I'm receiving the following error message:
![Screen Shot 2022-07-05 at 12 22 55 PM](https://user-images.githubusercontent.com/57765157/177373241-9fe1877c-9683-4b44-87ac-95501c785632.png)

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0623_neurodev_wave1_sa/saved_variants/variant/SV0120146_545695889_f039702_85
https://seqr.broadinstitute.org/project/R0623_neurodev_wave1_sa/saved_variants/variant/SV0120148_545695891_f039702_85
https://seqr.broadinstitute.org/variant_search/variant/5-45695886-C-T/family/F039702_859_18105734

**Scope of the bug**
Just this specific gene in this one family.

**Comment by hanars** [comment]
This error apparently means the reference genome specified for IGV is not actually the reference genome the cram was aligned against. It does seem that there is a Broad specific hg38 which can differ slightly from other hg38s and can cause this error. This looks like an external cram which might explain the issue. Is this something we can bring up with the PM team, to see if we can get a re-aligned cram?

**Comment by hanars** [comment]
My concern is that we have never (as far as anyone has told me) seen this error before for all the many other Broad-sequenced crams we show in seqr. So it seems more likely to me that the cram that was delivered in this particular case was not aligned the way it usually is

**Comment by shall48** [comment]
I confirmed with the Neurodev team that these were sequenced at the Broad and aligned to Homo_sapiens_assembly38 (hg38) like all of their other samples.

**Comment by Caustint** [comment]
In case it changes anything, I am able to reproduce this issue in other unrelated NeuroDev samples in this project. This family is interesting since HCN1 reads load for the maternal sample, but not the proband or dad: https://seqr.broadinstitute.org/variant_search/results/f55819c24c4922c838841cad2be09273?page=1&sort=in_omim

For the variants in this family, maternal reads load for the first variant, but not the other positions: https://seqr.broadinstitute.org/variant_search/results/6aee88f69c8986b75559337bb1e6e17f?page=1&sort=in_omim

**Comment by Caustint** [comment]
@hanars do you still think this is a cram issue given that there is variability in seqr's ability to load reads within a single sample?

**Comment by hanars** [comment]
If we are 100% confident that this is the same cram type as all of our other crams I can try to take a look, but I am incredibly worried that any changes to fix this will break other crams

**Comment by hanars** [comment]
can someone try looking at these crams in TGG viewer and see if it works there?

**Comment by shall48** [comment]
@hanars I received the following message from DSP on this:

"ok, so this does appear to be some sort of reference mismatch.  In particular, it looks like an issue arising during slice validation for cram decoding.  I’m not particularly familiar with seqr, so I’m not sure exactly where to look for the issue, but some ideas are:
1) Do they need to specify a reference when loading crams?  If so then that is the most likely source of the issue.  The reference they specify must be an exact match to the one used to create the crams.  There are a number of different “hg38” references floating around, so if they are using a slightly different version, that is likely the issue.
2) If the user doesn’t need to specify a reference, I would reach out the the seqr developers.  There may be a mismatch between the reference we use to generate these crams and the reference they are using (likely queried from a database somewhere) to decode them."

**Comment by Caustint** [comment]
Thanks for looking into this! Can your contact in DSP tell us what
reference they used to create this cram?

**Comment by hanars** [comment]
So the issue for seqr is that we do not have the ability to show different reference genomes in IGV for the "same" genome build. So we obviously use a different reference for 37 and 38, but there is only 38 reference genome that we will use for IGV, although as DSP points out there are theoretically several. 

Every other cram in seqr, including the proband, uses the same hg38 reference in IGV, these are the only 2 we have found that are different. IGV only allows you to provide one reference per browser, so even if we did do a huge engineering lift in seqr to allow certain crams to specify a different reference, it would still not solve our problem as this family is not all aligned on the same version. We need these crams to be realigned if we want to show them.

 If it helps, the reference fasta URL we are specifying in IGV is `https://s3.amazonaws.com/igv.broadinstitute.org/genomes/seq/hg38/hg38.fa`

**Comment by shall48** [comment]
I am meeting with the neurodev team and DSP to share the CRAMs for this family back to DSP so they can review the alignment.

DSP also had the following questions:

What specific sequence of operations leads to this error?  Does it happen as soon as seqr is launched?  as soon as igv is launched/the data is opened in igv?  Only after navigating to a specific genomic coordinates in igv?  Are they able to navigate to other coordinates in igv without hitting this error?  After hitting this error, can they navigate to a different genomic coordinates and have the data load successfully?  (sorry if some of these questions doen’t make sense, I’ve never used seqr, so some of them might not be applicable)

**Comment by eoheir** [comment]
This error occurs when trying to open IGV for the HCN1 variants listed above. I did not run into this issue for any other genes - IGV loads normally for coordinates outside of the HCN1 gene. Even after hitting this error when trying to view a region within HCN1, I am able to directly navigate to different genomic coordinates outside of the gene and have the data load successfully.

**Comment by hanars** [comment]
@stephditroia found another example: https://seqr.broadinstitute.org/project/R0532_cmg_walsh_exomes_pmg/saved_variants/variant/SV0084303_545696050_f029756_wa

**Comment by shall48** [comment]
I have been told "it looks like the issue here is due to small differences between the hg38 we use in production, and the version IGV makes available by default.  They can load our specific production hg38 version using Genomes -> Load Genome from URL and using gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta .  This should solve the issue."

**Comment by hanars** [comment]
Okay I will give this a try, it's possible to use that reference file for seqr IGV. There's a small chance that we will start seeing this issue on other older crams/bams but I think the risk is worth it since the vast majority of hg38 crams in seqr we're all generated the same way

**Comment by shall48** [comment]
If it works can you let me know so I can tell DSP this is all set

**Comment by hanars** [comment]
This issue has been fixed! Thanks so much @shall48 for figuring this out.
