### ISSUE TITLE
seqr link for variant search broken

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#2816]
**Describe the bug**
Tried the seqr link to search for a variant across seqr and got this error (which is a bit different than what I typically see so wanted to share)

![image](https://user-images.githubusercontent.com/10407888/177628567-08a2e811-f09b-4874-b1a9-37563458b427.png)

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0351_cmg_bonnemann_exomes/saved_variants/family/F023311_bon_b12_71

![image](https://user-images.githubusercontent.com/10407888/177628687-33474000-cfd8-4447-9557-d1e203262f33.png)

**Scope of the bug**
I tried on another family and am getting the same error.

**Comment by hanars** [comment]
Try logging back out and logging back in again

**Comment by anneodonnell** [comment]
yep, that fixed it. Thanks!
