### ISSUE TITLE
Add seqr MME as a filter option on the Saved Variants Summary Data Page

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2820]
**Is your feature request related to a problem? Please describe.**
I frequently use the "Saved Variants" tab of the Summary Data Pages to investigate cases we have received MME emails about. Searching the gene symbol often returns many results (example linked below), so it would be helpful to be able to narrow the results to those that have been tagged with "seqr MME". Currently, "MatchBox (MME)" is a filtration option, but this tag is no longer in use. 

**Describe the solution you'd like**
Add seqr MME to the filtration options on the Saved Variants page.

**Describe alternatives you've considered**

**Additional context**
https://seqr.broadinstitute.org/summary_data/saved_variants/ALL/ENSG00000124126

**Comment by Caustint** [comment]
In honesty I did not realize you can do that on the Matchmaker summary
page. I will definitely make use of that in the future, so thanks for the
tip!

On the other hand, it's sometimes nice to simultaneously look at other
cases in which the gene has been flagged as interesting (even if not
submitted to MME) to see if there are other investigators we could bring
into the collaboration, so it would be nice to also add seqr MME as a
filter option on the Saved Variants page unless that is difficult to do.
Would definitely be low priority.

**Comment by hanars** [comment]
> it's sometimes nice to simultaneously look at other cases in which the gene has been flagged as interesting (even if not
submitted to MME) 

I don't see how adding seqr MME  as a filter option would help with this case. If you applied it, you wouldn't see the other cases, you would only see the cases actually in matchmaker, the same as if you go to the matchmaker summary page now

**Comment by Caustint** [comment]
I guess I'm saying I might sometimes choose to go to the Saved Variants
page rather than the Matchmaker page. On the saved variants page, I could
toggle the MME filter on and off to quickly find the case(s) for which the
gene was submitted to MME, but before applying the MME filter I could also
see the list of cases for which other variants in the same gene were
flagged as interesting but not yet submitted to MME, which may be relevant
to a collaboration. Otherwise to achieve the same thing I would have to go
to the Matchmaker summary page to find the case that was submitted to
Matchmaker and then separately look up the gene in the saved variants page
to see if we have any other cases that might be worth connecting to the
study (two searches on two different pages instead of one search and some
filtering). I don't feel that strongly about it, I just thought it would be
a nice option to have. Happy to be overruled.


*Christina Austin-Tse, PhD, FACMG*
Analysis Team Lead, Center for Mendelian Genomics, Broad Institute of MIT
and Harvard
Clinical Molecular Geneticist, Center for Genomic Medicine, Massachusetts
General Hospital
Instructor in Pathology, Harvard Medical School
Pronouns: She/her

**Comment by hanars** [comment]
I see the point, but it's a lot of work for what is honestly still not a great experience. I think the better direction to go here is some sort of automated tag to indicate that a variant is actually in matchmaker. We've discussed this before and the existing matchmaker tag is used to differently to switch it over, but we could add another new tag that is automatically added/removed. Then it would be visually clear on the saved variant page which variants are actually in matchmaker. I'll leave this ticket open, but I think I won't implement this until after we make that new tag, which would need it's own ticket

**Comment by lynnpais** [comment]
No longer needed after speaking to Chrissy.
