### ISSUE TITLE
Update UniProt gene page

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2821]
**Describe the bug**
UniProt has updated its website, we need to reflect this on the Gene Page in seqr. 

**Link to page(s) where bug is occurring**
For example, the UniProt link on the Gene Page for WTI - https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/variant/SV0094001_1132391981_f030227_r

**Scope of the bug**
For all genes, not case specific.

**Screenshots**
<img width="1359" alt="Screen Shot 2022-07-07 at 2 15 28 PM" src="https://user-images.githubusercontent.com/37872186/177841672-0f84f8af-4e53-44c2-92b2-c4794e62c780.png">

**Comment by hanars** [comment]
this is fixed
