### ISSUE TITLE
Recessive inheritance changes upon search

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#2822]
**Describe the bug**
On any recessive search the inheritance dropdown always changes to homozygous recessive after you hit search. I do not think it affects the search itself but is visually confusing. This happens in all projects and on all recessive searches. 

**Screenshots**
Pre-search
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/44381119/177842840-95c396cf-1f2c-449d-a5b9-4da445e2b05b.png">
 Post-search
<img width="1448" alt="image" src="https://user-images.githubusercontent.com/44381119/177842910-fd15a561-6e9c-43a0-988e-b51c963a9705.png">

**Comment by hanars** [comment]
this is fixed now, let me know if you are still seeing it
