### ISSUE TITLE
RNA-seq IGV viewer: add ability to filter junctions by the number of uniquely-mapped or total reads

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#2827]
Based on the discussion at the most recent RNA-seq meeting, the feature that would be most useful to port from tgg-viewer is these 2 filters:
<img width="169" alt="image" src="https://user-images.githubusercontent.com/6240170/178316610-6c7e5aea-ea43-474e-83e1-6c6c92b5f450.png">
which hide splice junctions that are supported by fewer than a minimum number of uniquely mapped reads and/or total reads. 
These help to filter out noise and clutter in regions where many spurious junctions are shown with only a couple reads supporting them.

**Comment by hanars** [comment]
these options have been added
