### ISSUE TITLE
Filtering cases in seqr - update options under Analysis Status

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2845]
Is your feature request related to a problem? Please describe.
Related to #2809, filtering cases in seqr

Describe the solution you'd like
Request to update selections under Analysis Status to those listed on the Project Page

Describe alternatives you've considered
NA

Additional context
<img width="692" alt="1" src="https://user-images.githubusercontent.com/37872186/179809809-5be08e12-4b36-4e28-8507-0c6e91337082.png">

**Comment by hanars** [comment]
These have been updated
