### ISSUE TITLE
seqr family filters: >1 year

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2846]
**Describe the bug**
The new filters on the project are terrific! They mostly well except for when the >1 year filter is applied. It adds all cases irrespective of the analyst name selected. This does not happen when I select say, Lynn Pais + WES/WGS. This shows only WES/WGS assigned to me. However if I select, Lynn Pais + WES/WGS + >1 year, it returns all cases where I am not the analyst. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/project_page

**Scope of the bug**
All projects with multiple analysts

**Screenshots**
<img width="1261" alt="Screen Shot 2022-07-19 at 3 31 43 PM" src="https://user-images.githubusercontent.com/37872186/179836917-5698fda8-497c-4812-abf9-3215594d9622.png">

**Comment by hanars** [comment]
Discussed offline and determined the behavior issue is with the "assigned to me filter" - this should be an "and" and not an "or"

**Comment by hanars** [comment]
I think this is fixed now. The "analysed by me" behavior is the same as before, but the A'ssigned to me" filter will now only return cases currently assigned to you, regardless of the analysed by filters/ status
