### ISSUE TITLE
PanelAPP Gene List MOI filter

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2847]
**Describe the bug**
If a gene list is selected without clearing the previous one, the option to choose MOI is disabled. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/4c138a14cf60e63ceef24ccbbf2a4b9f?page=1&sort=xpos

**Scope of the bug**
Across seqr

**Screenshots**

**Comment by hanars** [comment]
FYI @david-ma - fix PR is here in case you want to pull it in: https://github.com/broadinstitute/seqr/pull/2850

**Comment by hanars** [comment]
this is fixed
