### ISSUE TITLE
PanelApp Gene List - 413 error

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2848]
**Describe the bug**
Variant search using the MOI filter for PanelApp is leading to a search error

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/a39ab90b34c7ed4b3dbb07a10b90d8af?page=1&sort=xpos

**Scope of the bug**
NA

**Screenshots**
<img width="1308" alt="Screen Shot 2022-07-19 at 4 36 03 PM" src="https://user-images.githubusercontent.com/37872186/179843652-e6235011-c193-4626-bea2-c2b1d40897b8.png">

**Comment by hanars** [comment]
please provide a screenshot or description of the full search params you did

**Comment by lynnpais** [comment]
Using another example here, which is giving the same error - for [SHE_1363](https://seqr.broadinstitute.org/project/R0542_aicardi_wes/family_page/F031439_she_1363), I ran a standard de novo/dominant permissive search, selected the Mendeliome PanelApp gene list and set MOI to Dominant. 
<img width="1281" alt="Screen Shot 2022-07-20 at 12 31 58 PM" src="https://user-images.githubusercontent.com/37872186/180035567-19d59688-9ea3-44da-852e-3a456e9e3842.png">
<img width="1266" alt="Screen Shot 2022-07-20 at 12 32 06 PM" src="https://user-images.githubusercontent.com/37872186/180035587-53b2e6b0-7ed5-41c1-9481-fcee9de34b9f.png">

**Comment by hanars** [comment]
FYI @david-ma - PR: https://github.com/broadinstitute/seqr/pull/2851

**Comment by hanars** [comment]
this is now working: https://seqr.broadinstitute.org/variant_search/results/b6075ad0e2c92808b53c04eacea297bd?page=1&sort=xpos

**Comment by david-ma** [comment]
I was unable to reproduce this bug or #2847 locally but I have cherry picked the new fixes for mcri, thanks Hana!

**Comment by hanars** [comment]
to recreate you need to select a very large gene list. It is also possible that your ngnx/ server configuration has a different max request size threshhold than ours

**Comment by hanars** [comment]
also there was a small bug in this, the fix is here: https://github.com/broadinstitute/seqr/pull/2859
