### ISSUE TITLE
Capitalization of gnomAD link on SVs

### ISSUE THREAD

**Issue by eoheir** [broadinstitute/seqr#2868]
**Is your feature request related to a problem? Please describe.**
Anne pointed out that the 'gnomAD' link found underneath SVs is currently not capitalized correctly, and would like to update this. 

![image](https://user-images.githubusercontent.com/57765157/181366518-d3902128-8620-4783-878f-e4d797fa5260.png)

**Describe the solution you'd like**
Change 'gnomad' to 'gnomAD.' 

**Additional context**
Example SV: https://seqr.broadinstitute.org/project/R0407_cmg_wendy_chung_genomes/saved_variants/variant/SV0122067_774743689_f020761_ch

**Comment by hanars** [comment]
this is fixed
