### ISSUE TITLE
Searching full mito chromosome gets an error message

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#2869]
**Describe the bug**
I tried to search for all mito variants in a case to be able to see more of a variety of variants but I get an error message. 
**Link to page(s) where bug is occurring**
I tried in this case: https://seqr.broadinstitute.org/variant_search/results/8a18aee630aa1e76913b3d69309a9246?page=1&sort=xpos

I also tried a smaller search region: chrM:2500-13569 and got the same error. 

**Screenshots**
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/10407888/181626853-d39d854c-f576-4389-a63c-41d89a5e4a50.png">

**Comment by hanars** [comment]
We made a change to the pipeline which had an unintended consequence of breaking some searches in RGP. We will revert the change and re-export the RGP data which should fix the issue

**Comment by hanars** [comment]
this issue is now fixed
