### ISSUE TITLE
Functionality to delete a variant curation entry

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2873]
**Is your feature request related to a problem? Please describe.**
Unable to clear a user-entered variant curation using the Classify feature. One can edit, but not delete. 

**Describe the solution you'd like**
Add functionality to allow a user to delete a variant curation entry using Classify>clear form>submit.

**Describe alternatives you've considered**
Open to other suggestions on how to delete an entry. 

**Additional context**
Added an example where I want to delete the curation - https://seqr.broadinstitute.org/project/R0583_gregor_manton_wes/saved_variants/variant/SV0123059_2121530914_f033141_m
<img width="1246" alt="Screen Shot 2022-08-05 at 12 04 29 PM" src="https://user-images.githubusercontent.com/37872186/183117401-fcfb42d4-96bd-4706-90f2-dfeb407d758a.png">

**Comment by hanars** [comment]
This has been added. If you clear the form and then hit submit it will now let you save the cleared classification
