### ISSUE TITLE
Unresponsive page when trying to update project categories bug

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2879]
**Describe the bug**
On the main seqr page, I click the star and add a keyword and then submit. Page then becomes unresponsive. 

**Link to page(s) where bug is occurring**
Main page - https://seqr.broadinstitute.org/
Error - https://seqr.broadinstitute.org/

**Scope of the bug**
NA

**Screenshots**
<img width="1375" alt="Screen Shot 2022-08-11 at 10 18 07 AM" src="https://user-images.githubusercontent.com/37872186/184154823-ec0f02d5-8f1e-4da4-a778-c8b0616e6976.png">

<img width="908" alt="Screen Shot 2022-08-11 at 10 14 57 AM" src="https://user-images.githubusercontent.com/37872186/184154833-cd5ec107-ceb6-44a8-8b79-07dfcf5e0fd5.png">

<img width="774" alt="Screen Shot 2022-08-11 at 10 15 03 AM" src="https://user-images.githubusercontent.com/37872186/184154860-1d778d80-6981-4ee8-9caf-7c73d5f17c6c.png">

**Comment by hanars** [comment]
I'm not seeing this issue right now - can you confirm it is still happening? If it is still an issue, can you detail exactly which category(s) you are adding to which project?

**Comment by lynnpais** [comment]
I added 'neurodevelopmental' to a total of 4-6 projects. The last one - the page became unresponsive.

**Comment by hanars** [comment]
if you refresh the page can you continue adding it?

**Comment by hanars** [comment]
@lynnpais this should be fixed now, but its always a bit hard fr me to validate that a performance fix actually worked. Can you try it out and let me know?
