### ISSUE TITLE
Add denominator for Helix mito database allele counts

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2880]
**Is your feature request related to a problem? Please describe.**
In the popup that appears after hovering over mitochondrial frequency data, the Helix data denominator is displayed as null, eg "17772 out of null" under allele counts and "AC_het=50 out of null" under heteroplasmy

**Describe the solution you'd like**
I know the denominator isn't in the download, but a quick calculation shows the total allele count was 195983, so I would advocate for replacing all instances of "null" in the Helix data with 195983. 

**Describe alternatives you've considered**
I calculated across ~7000 entries in the download and it does seem like the denominator is consistent across all positions. When the download gets updated the denominator will probably have to be recalculated. 

**Additional context**
Variant referenced for examples above: https://seqr.broadinstitute.org/variant_search/variant/M-14905-G-A/family/F019697_rgp_175

**Comment by hanars** [comment]
@ShifaSZ seems like we should be annotating the AN for this in the pipeline so it will be properly set on all variants. Can you take charge of updating the pipeline and regenerating this index?

**Comment by ShifaSZ** [comment]
I found that `counts_hom/AF_hom` and `counts_het/AF_het` all have the same value if AF_hom or AF_het is not zero in the downloaded file. I'm going to add a new field `helix_AN` to the mito indices using the value.

**Comment by hanars** [comment]
This is now available in the RGP project
