### ISSUE TITLE
Changes to display of mito frequency data

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2881]
**Is your feature request related to a problem? Please describe.**
It's not immediately clear that the frequency data displayed for mito variants in seqr reflects homoplasmic AF. Furthermore, less experienced users may not realize that they need to hover over the frequency info to see whether the variant is heteroplasmic in population databases (in other words, when the homoplasmic frequency is 0, users may falsely assume the variant is completely absent from gnomAD).

**Describe the solution you'd like**
Proposing a few modifications to the display on the variant page as well as the pop up that appears when you hover over the frequency data - screenshot below. I think we should display both homoplasmic and heteroplasmic frequencies on the variant, adding the text "hom" or "het" to indicate which is which. In the popup, change the header "Allele Counts" to "Homoplasmy". Finally, we can remove the heteroplasmic AF data from the popup since it's already being displayed on the variant page. 
![image](https://user-images.githubusercontent.com/67653781/184370066-4533e28c-27bc-4636-bd8b-61cdecaa568e.png)

**Describe alternatives you've considered**

**Additional context**
My mockup above was based on this variant: https://seqr.broadinstitute.org/variant_search/variant/M-14905-G-A/family/F019697_rgp_175

**Comment by ShifaSZ** [comment]
How do you think about displaying the frequencies differently if the `variant.chrom` is `M`? @hanars

**Comment by hanars** [comment]
I don't understand the question. We should display whatever frequencies come back from the server

**Comment by ShifaSZ** [comment]
Use the `this callset` AF as an example, the differences between the nuclear variants and mitochondria ones are below.

Nuclear variant page
```
This Callset 0.090 AC=228 out of 2520
```
and corresponding popup message
```
Allele Counts (header)
This Callset: 228 out of 2520
```

Per request of this ticket, the mitochondria variant page will become
```
This Callset hom 0.090 het 0.00079
```
Popup message:
```
Homoplasmy (header1)
This Callset: 228 out of 2520

Heteroplasmy (header2)
This Callset: 2 out of 2520
```
So maybe we should display the AF differently based on the chromosome. Alternatively, we could also change the AF/AC back to AF_hom/AC_hom for mitochondria. And we can display AF_hom/AC_hom differently from AF/AC without checking the chromosome.

**Comment by hanars** [comment]
We display data differently based on the caller type, not the chromosome. Variants called with the mitochondrial caller have the mitochondrial annotations. Variants called with the regular GATK variant caller have the annotations of regular variants, even if it does happen to call a variant on chromosome M. Do not add any logic that will affect the display of regular variants, the data available in the ES index based on the data annotated in the pipeline is the ONLY thing we should be showing in seqr, and we should absolutely not update the regular variant pipeline to handle mitochondrial variants specially - thats why we wrote an entire mito-specific pipeline in the first place.

**Comment by ShifaSZ** [comment]
Okay. Is the caller type available in the variant or in any other data structures in the front end?

**Comment by hanars** [comment]
The mito calls will have heteroplasmy frequencies, the regular variants won't. Make the display conditional on whether the data exists

**Comment by ShifaSZ** [comment]
One more question, do we need to display the af_hom and af_het if they are 0 (not missing)?

**Comment by hanars** [comment]
yes, if we know that the variant has an AF of 0 thats very important. The frequency display should use shared helper functions so you really should not be writing your own logic

**Comment by hanars** [comment]
We will show both callset hom and het on the variant, but will show them on 2 separate lines for clarity/ consistancy

**Comment by ShifaSZ** [comment]
Per the discussion we had, I update the display as below figure.
![image](https://user-images.githubusercontent.com/33550059/186496027-5f2e898d-b837-4119-87d9-0a9df26c7e33.png)
Any suggestions?

**Comment by Caustint** [comment]
Thanks! Can we add "homoplasmy" to the first this callset line? So in your
example it would be "This callset homoplasmy 0.0016 AC=4 out of 2519"

We should also be consistent about whether we are capitalizing "callset" in
the first and second lines. I don't feel strongly about it, but it seems we
do capitalize the C for nuclear variants, so we should probably change the
second line from "This callset" to "This Callset"


*Christina Austin-Tse, PhD, FACMG*
Analysis Team Lead, Center for Mendelian Genomics, Broad Institute of MIT
and Harvard
Clinical Molecular Geneticist, Center for Genomic Medicine, Massachusetts
General Hospital
Instructor in Pathology, Harvard Medical School
Pronouns: She/her

**Comment by hanars** [comment]
I also think we should show AC for callset heteroplasmy for consistency, but I don't feel too strongly about that

**Comment by ShifaSZ** [comment]
Now, it looks like the below picture. A few things to be confirmed: the 0 ACs won't be displayed in the popup; Do we need to add 'mito' after the `This Callset`, or should we remove all the `mito` to make them consistent?
![image](https://user-images.githubusercontent.com/33550059/186508212-416909e4-a059-430b-917c-d6d1bb75a5a6.png)

**Comment by hanars** [comment]
AC should behave the exact same way AC behaves for every single other population in seqr. As long as the behavior is consistent across all populations, it is correct. You also need to share an example where callset heteroplasty actually has a value and is showing AC and AN

**Comment by ShifaSZ** [comment]
If we show the `AC` on the main page for the callset heteroplasmy, it is like the below figure.
<img src="https://user-images.githubusercontent.com/33550059/186511693-c2484566-3525-4343-9320-ec1ed1cbe7f2.png" height="40%" width="40%"/>

Another example
<img src="https://user-images.githubusercontent.com/33550059/186513019-f874ea32-1883-4f1a-b8c8-69445e88f741.png" height="40%" width="40%"/>

**Comment by hanars** [comment]
The "Heteroplasmy AllelCounts" header is very misleading - max observed heteroplasmy is not an allele count. Do whatever is simplest in the code in terms of how you handle the display, but you need to keep it accurate

**Comment by Caustint** [comment]
We could just change the headers to "Homoplasmy" and "Heteroplasmy"?

**Comment by ShifaSZ** [comment]
The `max observed heteroplasmy` is put into a separate section of the popup details. Let me know if it is okay or not.
<img src="https://user-images.githubusercontent.com/33550059/187297519-fc1c829b-8b24-44fc-b562-153939954012.png" width=40% hight=40% />

**Comment by ShifaSZ** [comment]
The popup is like the below picture now. A slight change is that data fields group in population rather than data field (ac or max_hl) in the heteroplasmy section. So two max_hl data are not displayed in consecutive lines.
<img src="https://user-images.githubusercontent.com/33550059/187468721-29b8c0d9-f54e-480b-8a49-f589ffd806ef.png" width=40% hight=40% />

**Comment by hanars** [comment]
@ShifaSZ on hover the helix populations show "X out of null". Please fix this

**Comment by ShifaSZ** [comment]
It is because of the dataset. We need to reload the dataset into the ES.

**Comment by hanars** [comment]
then please do that

**Comment by ShifaSZ** [comment]
A new index has just been loaded: r0384_rare_genomes_project_gen__mitochondria__wgs__grch38__20220912

**Comment by hanars** [comment]
@ShifaSZ I still see the "out of null" issue. Please fix it and then comment here once you confirm it is actually fixed
https://seqr.broadinstitute.org/variant_search/variant/M-14905-G-A/family/F019697_rgp_175

**Comment by ShifaSZ** [comment]
One second, I haven't updated the project dataset with the new index yet.

**Comment by ShifaSZ** [comment]
The RGP HMB project is updated. There should be no "out of null" for the project.

**Comment by hanars** [comment]
yep this looks good to me. @Caustint can you take a look and let us know if you are happy with the updated display?

**Comment by Caustint** [comment]
Looks good!

*Christina Austin-Tse, PhD, FACMG*
Analysis Team Lead, Center for Mendelian Genomics, Broad Institute of MIT
and Harvard
Clinical Molecular Geneticist, Center for Genomic Medicine, Massachusetts
General Hospital
Instructor in Pathology, Harvard Medical School
Pronouns: She/her
