### ISSUE TITLE
Add explanation of mitochondrial copy number in quality metric popup display

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2882]
**Is your feature request related to a problem? Please describe.**
Copy number is displayed on mitochondrial variants, but most users will not be familiar with what this metric means or how it's calculated

**Describe the solution you'd like**
Add some explanatory text to the bottom of the popup that appears when you hover over genotype information (screenshot below). Suggested text: CN = (2*mean mtDNA coverage)/(median nuclear coverage). Median for blood samples ≈ 250. CN is typically higher in other tissues. Low values may indicate mtDNA depletion.

**Describe alternatives you've considered**
Text was reviewed and agreed upon by Anne and the analyst team.

**Additional context**
![image](https://user-images.githubusercontent.com/67653781/184645267-da47622e-1848-4b91-ae5f-0f2acedc3ff0.png)

**Comment by hanars** [comment]
Added
