### ISSUE TITLE
Minor modifications of saved searches

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#2884]
Discussed with analysis team. Here are minor modifications of saved searches, mostly about SV frequencies: 

**De novo dominant restrictive + de novo dominant permissive:**
gnomAD genome SVs AF: 0.001
This SV callset AF 0.001

**De Novo/ Dominant - SV only - Proband/Duo**
This SV callset AF 0.001

**Recessive Restrictive and recessive permissive**
This SV callset AF 0.01

**Recessive SV:** 
callset AF: 0.03
This SV callset AF 0.01

**De novo dominant SV only trio**  *this one also has some changes in the annotations
This SV callset AF 0.001
The following annotations (see screenshot)

![Screen Shot 2022-08-08 at 6 52 47 PM](https://user-images.githubusercontent.com/84086816/184687647-b1355a40-7530-4e9f-bed2-0074bc48d19b.png)

Let me know if you have any questions. Thank you.

**Comment by hanars** [comment]
these have all been updated

**Comment by Glemiret** [comment]
Thank you!
