### ISSUE TITLE
RELEASE 9/6 - switch seqr auth over to AnVIL

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2917]
**Is your feature request related to a problem? Please describe.**
Update seqr auth to AnVIL

**Describe the solution you'd like**
Switch seqr auth over to AnVIL, and close out ability to add/ remove collaborators in seqr

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hanars** [comment]
released
