### ISSUE TITLE
Grant staff level access for two members of the Talkowski laboratory

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#2918]
**Is your feature request related to a problem? Please describe.**
Two members of the Talkowski lab will be doing an analysis project on CMG data. 

**Describe the solution you'd like**
We'd like to give Lily Wang and Michael Duyzend (if he doesn't already have it, I haven't checked with him) staff level access to all CMG data in seqr. Their seqr login emails are:
mduyzend@broadinstitute.org
lily@broadinstitute.org

**Describe alternatives you've considered**

**Additional context**
Discussed and approved by Heidi and Anne

**Comment by hanars** [comment]
they should be all set now
