### ISSUE TITLE
MME link on Family Page unresponsive

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2919]
**Describe the bug**
A clear and concise description of what the bug is, and what you instead expect to be happening

**Link to page(s) where bug is occurring**
Family Page with MME link- https://seqr.broadinstitute.org/project/R0208_kang_v11/family_page/F010651_k1398 
Blank page after selecting MME link - https://seqr.broadinstitute.org/project/R0208_kang_v11/family_page/F010651_k1398/matchmaker_exchange

**Scope of the bug**
seqr-wide

**Screenshots**
<img width="1382" alt="Screen Shot 2022-08-25 at 9 04 03 AM" src="https://user-images.githubusercontent.com/37872186/186672304-a31857bc-43e6-44ac-b5e6-ed7867845aad.png">

**Comment by hanars** [comment]
This is now working again
