### ISSUE TITLE
Enable HGMD for BCH users

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2926]
Can we have HGMD enabled for the following BCH projects in seqr. They have been verified to have a current license.

**Fleming**
CMG_Fleming_WES,
TGG_Shimamura_WES

**Beggs/Manton**
https://seqr.broadinstitute.org/project/R0344_cmg_beggs_exomes/project_page
https://seqr.broadinstitute.org/project/R0485_cmg_beggs_wgs/project_page
https://seqr.broadinstitute.org/project/R0319_cmg_beggs_external/project_page
https://seqr.broadinstitute.org/project/R0380_cmg_gazda_wgs/project_page
https://seqr.broadinstitute.org/project/R0523_cmg_manton_doose_wes/project_page
https://seqr.broadinstitute.org/project/R0303_cmg_manton_exomes/project_page
https://seqr.broadinstitute.org/project/R0359_cmg_manton_genomes/project_page
https://seqr.broadinstitute.org/project/R0383_gazda_exomes/project_page
https://seqr.broadinstitute.org/project/R0583_gregor_manton_wes/project_page
https://seqr.broadinstitute.org/project/R0344_cmg_beggs_exomes/project_page
https://seqr.broadinstitute.org/project/R0485_cmg_beggs_wgs/project_page
https://seqr.broadinstitute.org/project/R0523_cmg_manton_doose_wes/project_page
https://seqr.broadinstitute.org/project/R0303_cmg_manton_exomes/project_page
https://seqr.broadinstitute.org/project/R0359_cmg_manton_genomes/project_page
https://seqr.broadinstitute.org/project/R0583_gregor_manton_wes/project_page
https://seqr.broadinstitute.org/project/R0587_gregor_manton_wgs/project_page
https://seqr.broadinstitute.org/project/R0310_manton_pcrfree_4s/project_page
https://seqr.broadinstitute.org/project/R0418_manton_qi_project/project_page

**Engle**
CMG_Engle_Ext_WES, CMG_Engle_WES, CMG_Engle_WGS, Engle Exome, Engle Genome (NIH), Engle Genome (NYGC), Engle_Moebius, Engle_WGS, Engle_WGS-2-sample, Engle_WGS_900

**Walsh**
https://seqr.broadinstitute.org/project/R0456_cmg_walsh_exomes_ch/project_page https://seqr.broadinstitute.org/project/R0478_cmg_walsh_exomes_id/project_page https://seqr.broadinstitute.org/project/R0455_cmg_walsh_exomes_lispac/project_page https://seqr.broadinstitute.org/project/R0451_cmg_walsh_exomes_microce/project_page https://seqr.broadinstitute.org/project/R0532_cmg_walsh_exomes_pmg/project_page https://seqr.broadinstitute.org/project/R0503_cmg_walsh_wgs/project_page https://seqr.broadinstitute.org/project/R0638_tgg_walsh_rgp_wgs/project_page https://seqr.broadinstitute.org/project/R0346_walsh_lab_exomes/project_page

**Comment by hanars** [comment]
These have all been granted HGMD access
