### ISSUE TITLE
Case review status dropdown issue when page is minimized

### ISSUE THREAD

**Issue by gvannoy** [broadinstitute/seqr#2947]
When the browser that seqr is open in is reduced below full screen (i.e. half of a split split screen), the case review status drop down menu is cut off and hard to use and read. 

https://seqr.broadinstitute.org/project/R0594_rare_genomes_project_gen/case_review

![image](https://user-images.githubusercontent.com/40441144/189743013-50719bad-c28f-48f4-a8bc-d3bf4064d290.png)

**Comment by hanars** [comment]
this is fixed
