### ISSUE TITLE
Utility function `file_iter` doesn't support local .gz format VCF files

### ISSUE THREAD

**Issue by ShifaSZ** [broadinstitute/seqr#2956]
**Describe the bug**
When we open a local .gz file (e.g., a compressed VCF file) to do validation, the `file_iter` function uses `dd` command to read the required range of data. But it doesn't use `gunzip` to decompress the data even when the `raw_content` parameter is set to False.

**Link to page(s) where bug is occurring**
The bug is found when debugging the VCF validation feature. When we provide a local `.gz` file to the function `validate_vcf_and_get_samples`, it'll fail.

**Scope of the bug**
No end-user functions use the `file_iter` function to fetch non-raw contents. So the bug won't affect the end users.
Simply adding `gunzip` may not solve the issue. The file could be a `block gzip` file. The output may need decoding to get Python strings. So it requires careful consideration for the solution.

**Screenshots**
No screenshots

**Comment by hanars** [comment]
this is not a standalone bug and does not warrant a ticket. If you have opened a PR where we try to use helper a function for a never-before-used file format and it doesn't work, it is up to you to get that PR working. Thats is in scope for the new PR, and does not warrant a ticket. If you want to fix it in a separate PR and then branch off of that to make review easier thats fine, but it is still related to the original ticket. Unless you can actually point to current, live, application behavior that is not working, this ticket should not exist

**Comment by hanars** [comment]
To be clear, this is not a bug because local users do not and can not have anvil activated, so its an unreachable issue
