### ISSUE TITLE
Add new population databases

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2957]
**Is your feature request related to a problem? Please describe.**
We would just like to add 2 new population databases, Iranome and GME.

**Describe the solution you'd like**
- Include http://www.iranome.com/about and http://igm.ucsd.edu/gme/. Neither have restrictions on data use.
- The default AF should be 1 (as we have for TopMed) in the variant search section
- We would also like to have frequencies returned for variants, but this might require work on Mike's part?

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by lynnpais** [comment]
Didn't mean to say frequencies shouldn't be displayed for variants. 

I'll add a pipeline tag for now.

**Comment by hanars** [comment]
you should probably also create a ticket in the pipeline repo so this ends up on Mike's radar

**Comment by lynnpais** [comment]
Pipeline ticket here [https://github.com/broadinstitute/seqr-loading-pipelines/issues/360#issue-1374790907](url)

**Comment by lynnpais** [comment]
Decided to go with a link to the Iranome page instead.

Hana, can you please include the link below on the top of the gene page? 

http://www.iranome.ir/

**Comment by hanars** [comment]
what about GME?

**Comment by hanars** [comment]
If we are handling these 2 databases in totally different ways we need 2 tickets to track that work

**Comment by lynnpais** [comment]
Yes, will update shortly. Just confirming a few things with Anne.

**Comment by lynnpais** [comment]
Creating two new tickets, and closing this one out.
