### ISSUE TITLE
Add timestamp to AnVIL loading projects config

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/seqr#2962]
If an AnVIL user requests loading using the same file name as a previous loading, the seqr loading pipeline's job avoidance activates and will not load the new samples.

**Describe the solution you'd like**
Adding a timestamp to the project paths version in the config should help prevent this issue.

See slack discussion here: https://the-tgg.slack.com/archives/C02B0CRT3PV/p1661809080493579

**Comment by ShifaSZ** [comment]
The slack discussions conclude that we will add a timestamp to the DAG variable `project_path` by changing `"v1"` at the end of the variable to `"v"+timestamp`. For example, 
```
"project_path": "gs://seqr-datasets/v02/GRCh38/AnVIL_WES/R0650_uw/v1"
```
will become
```
"project_path": "gs://seqr-datasets/v02/GRCh38/AnVIL_WES/R0650_uw/v20220919"
```

**Comment by hanars** [comment]
this has been changed in the latest seqr release, the next time we get an AnVIL request we should confirm it works
