### ISSUE TITLE
Manual SV broke saved variants page

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#2963]
I created a manual CNV tag for this family and can no longer view the saved variants page. Every time I click the saved variants bar the screen turns blank. Other families in this project are not affected. 

Family page: 
https://seqr.broadinstitute.org/project/R0554_tgg_shimamura_wes/family_page/F031912_shi_fhcrc_342

Blank page:
https://seqr.broadinstitute.org/project/R0554_tgg_shimamura_wes/saved_variants/family/F031912_shi_fhcrc_342

**Comment by hanars** [comment]
this is fixed now
