### ISSUE TITLE
Hufnagel genomes project missing in seqr

### ISSUE THREAD

**Issue by eoheir** [broadinstitute/seqr#2978]
**Describe the bug**
We just noticed that the Hufnagel genomes project which used to be loaded in seqr is suddenly missing. 

**Link to page(s) where bug is occurring**
This is the link I've used to access this project in the past, but when I try it now I get an 'Error 404: Page Not Found':
https://seqr.broadinstitute.org/project/R0552_mgrc_hufnagel_genomes/project_page 

**Scope of the bug**
Anne happened to notice this for this specific project, not sure if others are affected as well. 

**Screenshots**
![Screen Shot 2022-09-28 at 4 25 29 PM](https://user-images.githubusercontent.com/57765157/192881693-6bfd1e8a-ffc2-478f-9fa2-5375a861aca0.png)

**Comment by eoheir** [comment]
I just noticed that the NeuroDev_Wave1_SA and NeuroDev_Wave1_Kenya projects are missing as well, even though I was able to access them both earlier today.

**Comment by hanars** [comment]
seqr switched over today to checking AnVIL for access for projects, and it looks like the analysts were not properly added to these projects. I've pinged the PM team on this one, but if you notice any other missing projects feel free to reach out to them directly

**Comment by anneodonnell** [comment]
Is there any way to systematically query if there are other projects that this happened with - I don't want to rely on us noticing it.

**Comment by hanars** [comment]
yes, I pulled a list of all the projects that need this access and gave it to Alicia and she is in the process of going through it

**Comment by hanars** [comment]
Alicia confirmed that access is set for all projects

**Comment by lynnpais** [comment]
Yes, Hana generated a list from seqr and Alicia Pham is double checking
that all analysts have access.
