### ISSUE TITLE
Permission error searching for other individuals in callset with a variant

### ISSUE THREAD

**Issue by eoheir** [broadinstitute/seqr#2985]
**Describe the bug**
For certain variants, I am getting a 'Permission Denied' error when I use the 'seqr' variant link to search for the other individuals in the callset with the same variant. 

**Link to page(s) where bug is occurring**
Example variant 1: https://seqr.broadinstitute.org/project/R0624_neurodev_wave1_kenya/saved_variants/variant/SV0124559_2114108716_f039517_8
seqr search results page for variant 1: https://seqr.broadinstitute.org/variant_search/results/620257d8b91c77a1e88628578d796262?page=1&sort=protein_consequence

Example variant 2: https://seqr.broadinstitute.org/variant_search/variant/suffix_344457_DEL_07132022/family/F039623_859_97949070
seqr search results page for variant 2: https://seqr.broadinstitute.org/variant_search/results/217e3e8a99b8d1e183e606bfb05686fa?page=1&sort=protein_consequence

**Scope of the bug**
I've noticed this in just a few cases so far, and it's only for some variants (the seqr link will work fine for most variants within the family, but then I will get this error for one specific variant). For variant 1 above, I know that the link had worked for me previously, so I think this must be a new issue. 

**Screenshots**
![Screen Shot 2022-10-04 at 3 39 35 PM](https://user-images.githubusercontent.com/57765157/193910507-d08775a3-939f-4305-ace6-25f68993f963.png)

**Comment by hanars** [comment]
Can you try clicking the seqr search link on thee variants again and see if I was able to fix the issue?

**Comment by eoheir** [comment]
It's working now, thanks!
