### ISSUE TITLE
Not being able to see all project

### ISSUE THREAD

**Issue by I-zah** [broadinstitute/seqr#2987]
Hello,

Our group has around 4 projects in seqr, however I am no longer able to see/access them. I can only see the DEMO project even in I select see All projects.
The screenshot of my serq is:
![image](https://user-images.githubusercontent.com/115088046/194071382-5b180d88-dbaa-4e4b-a4c3-0b535ac64c9a.png)

Could you please let me know how I can access the projects that we have.

Many thanks in advance!
Irina

**Comment by lw453** [comment]
Hi seqr team, chiming in to say I'm experiencing the same issue. Thanks!

**Comment by hanars** [comment]
Can you please log into anvil and share with me the list of workspaces you have access to there? Feel free to email me if you aren't comfortable posting that publicly here

**Comment by I-zah** [comment]
Hello,

The project are:
CMG_Muntoni_Exomes
CMG_Muntoni_Extenal_Exome
CMG_Muntoni_Extenal_Genome

Thanks you!

**Comment by hanars** [comment]
I'm sorry if I was unclear. Please log into [AnVIL](https://anvil.terra.bio/#workspaces) and give me a list of workspaces that you see there that you have access to

**Comment by hanars** [comment]
Also, what happens if you go directly to the page for a project: https://seqr.broadinstitute.org/project/R0497_cmg_muntoni_exomes/project_page

**Comment by hanars** [comment]
@I-zah please provide a screenshot of when you lsee when you log into AnVIL. Please make sure you are using the correct account with the user account [i.zaharieva@ucl.ac.uk](mailto:i.zaharieva@ucl.ac.uk)

**Comment by hanars** [comment]
@I-zah we are blocked on being able to resolve this issue until you can provide us the requested information

**Comment by hanars** [comment]
Closed due to inactivity
