### ISSUE TITLE
Clicking 'Other Project Discovery Tags' turns screen blank

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#2988]
My screen turns blank when I click `Other Project Discovery Tags` on the variant linked below. Refreshing the page brings me back to the variant but will not show additional projects where variant is tagged. This happens on and off across several projects. Any advice on how to prevent it?

https://seqr.broadinstitute.org/project/R0640_tgg_shimamura_sankaran_w/saved_variants/variant/SV0125649_919379623_f040583_as

**Comment by hanars** [comment]
this is fixed now
