### ISSUE TITLE
page for uploading "External Analysis" metadata is no longer available

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#2991]
I'd like to upload the list of samples analyzed for STRs, in order to populate
<img width="321" alt="image" src="https://user-images.githubusercontent.com/6240170/194359236-8c11e167-4814-4054-906c-f66c5f9205e5.png">

I previously used https://seqr.broadinstitute.org/summary_data/external_analysis for this, but this link now brings up a blank page:
![image](https://user-images.githubusercontent.com/6240170/194359387-8d6bf7fe-7113-4353-9a16-ce59e60c9300.png)

and I don't see a way to get to it from other seqr UIs.

**Comment by hanars** [comment]
this should be fixed now, can you try again?

**Comment by bw2** [comment]
It works now! Thanks. 

Also, would be nice if parser could be less rigid / had better error messages. 
When I initially tried uploading a table with an extra tab in the header (`Project\tFamily\t` instead of `Project\tFamily`), I got this "list index out of range" error
<img width="786" alt="image" src="https://user-images.githubusercontent.com/6240170/194400718-8978f33d-785d-47a2-9bed-40337ad0d78e.png">

Also, briefly confusing that it shows "No match found for the following families:" but doesn't list any families.
<img width="830" alt="image" src="https://user-images.githubusercontent.com/6240170/194402290-816fe55c-5fe0-43b5-83ed-866096d0c2d8.png">
