### ISSUE TITLE
Add Geno2MP variant link 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#2999]
**Is your feature request related to a problem? Please describe.**
We would like to have a link to the variant (if present) in Geno2MP with the other pop databases

**Describe the solution you'd like**
Add Geno2MP variant link below This Callset details. The link on the Gene Page can be removed. Attached a mock up below. 

**Describe alternatives you've considered**
NA
**Additional context**
Reviewed the plan with Anne
<img width="967" alt="Screen Shot 2022-10-12 at 9 46 30 AM" src="https://user-images.githubusercontent.com/37872186/195360726-ad0cdf20-7f97-43dd-b14f-042f18067274.png">

**Comment by hanars** [comment]
To show it as a population like in this mock up, we need to update the pipeline. If that is what you want please link a pipeline ticket here. 
If you just want the geno2mp link with no frequency shown, we need to show it somewhere else on the variant, maybe with the seqqr/google/pubmed links

**Comment by lynnpais** [comment]
We'd like a link to the variant in Geno2MP, so no need for a pipeline change. It makes sense now to have it with the seqr/google/pubmed links.

**Comment by hanars** [comment]
Can you provide an example of a working geno2mp link?

**Comment by lynnpais** [comment]
Example Geno2MP variant link - https://geno2mp.gs.washington.edu/Geno2MP/#/gene/17%253A10534960/chrLoc/10534960/10534960/17

**Comment by hanars** [comment]
this has been added
