### ISSUE TITLE
Remove 1K genomes from pop data

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3000]
**Is your feature request related to a problem? Please describe.**
1K genomes is included in gnomAD, so it needn't be shown separately.

**Describe the solution you'd like**
Remove 1K genomes from pop data

**Describe alternatives you've considered**
NA

**Additional context**
Reviewed with Anne

**Comment by hanars** [comment]
do we want to remove just the ability to filter by this population, or also remove the display of the frequency on the variant

**Comment by lynnpais** [comment]
Both, remove ability to filter and display.

**Comment by hanars** [comment]
this has been removed
