### ISSUE TITLE
Add Iranome variant link

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3002]
**Is your feature request related to a problem? Please describe.**
We would like to have a link to the variant in the Iranome dataset in the pop databases section. 

**Describe the solution you'd like**
Add a link to the variant in the Iranome dataset if present. If absent, it can something like variant not found. 

**Describe alternatives you've considered**
NA

**Additional context**
Approved by Anne

<img width="967" alt="Screen Shot 2022-10-12 at 9 46 30 AM" src="https://user-images.githubusercontent.com/37872186/195362830-38108bb0-de1f-4a09-b35a-268e8ef74c05.png">

**Comment by hanars** [comment]
The right hand side is only for actual populations with frequencies, I don't want it to be a bunch of a links with no information shown. If we are not going to actually load the frequency, we should show the link elsewhere

Also, I need an actual link to Iranome

**Comment by lynnpais** [comment]
That makes sense, fine to add it the Iranome (iranome.ir) variant link beside the seqr and Pubmed ones.
<img width="986" alt="Screen Shot 2022-10-12 at 1 40 09 PM" src="https://user-images.githubusercontent.com/37872186/195411565-fe5f076f-bc56-4f32-8c6b-218da97f9436.png">

**Comment by hanars** [comment]
Can you provide an example of a working Iranome oage we would link to?

**Comment by lynnpais** [comment]
Here's a variant link - http://www.iranome.ir/variant/17-41201364-T-C
So if the variant in seqr is present in Iranome, it would go to the page above. If absent, would it be possible to have a message saying variant not in Iranome or something similar?

**Comment by hanars** [comment]
This is what the page would look like: 
<img width="1497" alt="Screen Shot 2022-10-12 at 1 57 19 PM" src="https://user-images.githubusercontent.com/24598672/195414510-76ad0fc7-26ab-4a7c-9e71-a5411675b44b.png">

**Comment by hanars** [comment]
this has been added
