### ISSUE TITLE
Slow loading of pages

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3004]
**Describe the bug**
Slow loading of pages. It took 38 seconds to load my projects. I/ the other analysts will add additional examples as I come across them. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/

**Scope of the bug**
Across seqr

**Screenshots**
NA

**Comment by hanars** [comment]
@lynnpais I know its hard to validate performance fixes, but this should be much better now. Can you see if you experience consistently faster behavior now?
