### ISSUE TITLE
Bug when searching with no affected individuals in index

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3005]
**Describe the bug**
The GQ, AB seem to be missing for one of the samples. Hence I seem to be getting far too many variants returned in the search. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/73810ebd5b9852b01eae915da42c8f55?page=1&sort=in_omim

**Scope of the bug**
Case specific

**Screenshots**
<img width="1261" alt="Screen Shot 2022-10-13 at 9 33 37 AM" src="https://user-images.githubusercontent.com/37872186/195611514-5ceb7668-bd51-46a8-b17d-46c5e11c7338.png">

**Comment by lynnpais** [comment]
If I run both affecteds together, the quality metrics show, but not if I set the proband to ? and the fbs sample as affected.

**Comment by hanars** [comment]
this is fixed now, search is returning 1 variant
