### ISSUE TITLE
Cookie policy statement

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3016]
**Describe the bug**
There's an error in the cookie policy that users need to accept before logging into seqr.

**Scope of the bug**
Affects all users

**Screenshots**
<img width="713" alt="Screen Shot 2022-10-20 at 9 17 02 AM" src="https://user-images.githubusercontent.com/37872186/196978466-ea69b7d5-db40-4bcb-9211-7175df5e8870.png">

**Comment by hanars** [comment]
fixed
