### ISSUE TITLE
AnVIL Loading request generated empty sample ID file

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/seqr#3017]
**Describe the bug**
The[ most recent AnVIL loading request](https://seqr.broadinstitute.org/project/R0657_global_at_family_datapla/project_page) generated a blank ID file here: gs://seqr-datasets/v02/GRCh38/AnVIL_WGS/R0657_global_at_family_datapla/base/R0657_global_at_family_datapla_ids.txt. The VCF contains 317 individuals. The seqr project contains 310 which we will subset to. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0657_global_at_family_datapla/project_page

**Scope of the bug**
The previous request worked fine.

**Comment by mike-w-wilson** [comment]
I need to update the linked file manually to get this project to run but the file simply has the s header in it and nothing else.

**Comment by hanars** [comment]
this is a bug if you load data without setting sex or affected status on any of the individual, which is why we never ran into it before

**Comment by hanars** [comment]
this is fixed now
