### ISSUE TITLE
Add variant link to Mastermind 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3021]
**Is your feature request related to a problem? Please describe.**
Add new variant database

**Describe the solution you'd like**
We would like to add a link to a the Mastermind database, similar to the newly added Iranome and older Google and pubmed. The variant will be have to listed in the following format, KMT2E.c.167delA and entered into https://mastermind.genomenon.com/  Result is here - https://mastermind.genomenon.com/detail?gene=kmt2e&mutation=kmt2e:c.167del&boolean=true&gene_op=and&mutation_op=and&cnv_op=and&disease_op=and&hpo_op=and&unii_op=and&keyword_op=and

**Describe alternatives you've considered**
Not a high priority. 

**Additional context**
Discussed with Anne

**Comment by hanars** [comment]
I think we need an upper limit on the number of links we show in that location, 5 is about the max that looks good. We can have them wrap to another line but I'm worried that the seqr link is getting lost and that a long multi-line list of links becomes unreadable. I'm not saying no to this per say but I think it would be good to rethink this display section before making it a dumping ground for a ton of information

**Comment by lynnpais** [comment]
We can hold off on this for now.
