### ISSUE TITLE
Add KEGG to Gene Page

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3022]
**Is your feature request related to a problem? Please describe.**
We would like a resource for gene pathways

**Describe the solution you'd like**
Add the KEGG pathway database link to Gene Page - https://www.kegg.jp/kegg/pathway.html
Example for GRM4 - https://www.kegg.jp/kegg-bin/search_pathway_text?map=map&keyword=GRM4&mode=1&viewImage=true

**Describe alternatives you've considered**
NA

**Additional context**
Not high priority.

**Comment by hanars** [comment]
this has been added
