### ISSUE TITLE
Update display of gnomAD noncoding flag

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3027]
**Describe the bug**
Consistent representation of 'gnomAD' - pls update text to 'gnomAD genomic constraint'. Also in the hover over, yellow should be 

**Link to page(s) where bug is occurring**
On variant page 

**Scope of the bug**
Across seqr, for variant with the gnomAD noncoding flag

**Screenshots**
<img width="172" alt="image" src="https://user-images.githubusercontent.com/37872186/197605515-5b453411-363e-4ebe-ab9a-492824a5b99f.png">

**Comment by lynnpais** [comment]
Please ignore the incomplete sentence "Also in the hover over, yellow should be"

**Comment by hanars** [comment]
changing the case of a word is a feature request not a bug

**Comment by hanars** [comment]
updated to "gnomAD Constraint" as the full proposed wording did not fit
