### ISSUE TITLE
Update pTriplo and pHaplo gene scores 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3034]
**Is your feature request related to a problem? Please describe.**
New pTriplo and pHaplo are available to replace TS and HI.

**Describe the solution you'd like**
Need to update TS and HI gene scores (currently shown under the gene on the variant page) to pTriplo and pHaplo using the info here - https://zenodo.org/record/6347673#.Y1q6V-zMIV9. 

On the Gene Page, remove the note saying these scores are being developed. 

Add the following note, 
for pHaplo - This metric was developed by the Talkowski lab [Collins et al., 2022  with link] which predicts whether a gene is haploinsufficient based on large chromosomal microarray data set analysis. Scores >0.86 are considered to have high likelihood to be haploinsufficient.

for pTriplo -  This metric was developed by the Talkowski lab [Collins et al., 2022  with link] which predicts whether a gene is triplosensitive based on large chromosomal microarray data set analysis. Scores >0.94 are considered to have high likelihood to be triplosensitive. 

Link to paper - https://pubmed.ncbi.nlm.nih.gov/35917817/

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hanars** [comment]
Data was updated via this ticket back in August: 
discussion - https://github.com/broadinstitute/seqr/discussions/2872
ticket - https://github.com/broadinstitute/seqr/issues/2874

keeping open this ticket to track the changes to the notes
