### ISSUE TITLE
Filter variant results by LIRICAL or Exomiser rank

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#3073]
For families where LIRICAL or Exomiser scores are available, it would useful to filter variant search results to the genes that have LIRICAL or Exomiser rank above a certain threshold. 

One logical place for this would be in the InSilico (or in the Annotations) section - for example:

<img width="1584" alt="image" src="https://user-images.githubusercontent.com/6240170/203151446-99794ab6-d31a-4c5a-8446-c5acc3c22fe0.png">

Search results would then only include genes ranked at or above the given threshold.

**Comment by hanars** [comment]
waiting to implement this until MVP has been live for a bit and the analysts have had time to assess utility

**Comment by lynnpais** [comment]
Sort functionality is adequate for now
