### ISSUE TITLE
Show LIRICAL or Exomiser rank in the tag

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#3074]
Currently, genes are just tagged as "LIRICAL" or "Exomiser" and users have to mouse over to get the rank. 
Since ranks from these tools will only be 1 to 3 digits and take up minimal space, it would be very helpful to include them in the tag. For example, if NCAPG2 was ranked #1 by LIRICAL, the tag would look like

![image](https://user-images.githubusercontent.com/6240170/203152036-f8f29c85-7e97-4a22-b952-8d133558c3ef.png)

**Comment by hanars** [comment]
After MVP has been live for a bit we will do a round of feedback with the analysts and adjust the experience based on their feedback. These sorts of changes will be considered at that time, so closing this out to prevent request duplication
