### ISSUE TITLE
Login causes ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by mattsolo1** [broadinstitute/seqr#3075]
**Describe the bug**

Clicked "Sign In" on the seqr home page. Logged in to my Google account. The page throws `ERR_TOO_MANY_REDIRECTS`. 

![image](https://user-images.githubusercontent.com/8867295/203423837-9a379d0d-e3e2-45ca-8374-9a4785034171.png)

Looked at network requests, can see repeated thrashing.

![image](https://user-images.githubusercontent.com/8867295/203423887-1f19037c-151b-46a9-b151-ff3ef7d95b5e.png)

**Link to page(s) where bug is occurring**

https://seqr.broadinstitute.org

**Comment by hanars** [comment]
For some reason your seqr account was deactivated. I have reactivated your account and you should be all set now

**Comment by mattsolo1** [comment]
Cool thanks! Is the issue specific to me or would anyone trying to log in without access experience this? May want to display a page explaining to the user what happened if the login fails.

**Comment by hanars** [comment]
It would only happen if I had personally gone into the seqr database and deactivated someones account, which is not a thing I do anymore and have not done in a long time. Its essentially only done at this point for people who have left the Broad entirely
