### ISSUE TITLE
Update variant link display

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3080]
**Is your feature request related to a problem? Please describe.**
As we are adding more variant links, the space below the chromosomal coordinates is becoming noisy.

**Describe the solution you'd like**
Since the Google and PubMed links are not used much, create a dropdown (show an arrow) and move these links here. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hanars** [comment]
updated. Added an ellipses that when clicked expands to show all the hidden links
