### ISSUE TITLE
Send a data loaded message to slack channel for anvil projects

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/seqr#3081]
**Is your feature request related to a problem? Please describe.**
Currently, only the ACS that runs the loading pipeline and the requester knows when an AnVIL project is loaded. This leads to confusion amongst other members of the group as to the status of a project.

**Describe the solution you'd like**
Send a message to the #anvil-data-loading channel when an AnVIL project has an index added to it. We currently do this for internal projects. This message would allow more members of our team to be aware of a project's loading status.

**Comment by hanars** [comment]
this has been added
