### ISSUE TITLE
gnomAD constraint cut offs

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3082]
**Is your feature request related to a problem? Please describe.**
Currently, the current cut-offs for gnomad constraint (in silico score) is yellow for >0 and red for >1.5. However, this does not match with what is listed here - https://gnomad.broadinstitute.org/news/2022-10-the-addition-of-a-genomic-constraint-metric-to-gnomad/

**Describe the solution you'd like**
May I know how the current cut offs were decided? I cannot find the relevant ticket to check this myself. We might need to update the cut offs.

**Describe alternatives you've considered**
NA

**Additional context**
<img width="1241" alt="Screen Shot 2022-11-29 at 1 55 09 PM" src="https://user-images.githubusercontent.com/37872186/204621441-6b48a36e-4490-4282-bb0b-6ebec42a25ed.png">

**Comment by hanars** [comment]
It looks like there were no cut offs included in the original ticket so I think I picked them based on looking at the distribution of values, but happy to update these to whatever is recommended

**Comment by lynnpais** [comment]
Yes, please update to Z >= 2.18 (yellow) and Z >= 4.0 (red)

**Comment by hanars** [comment]
updated
