### ISSUE TITLE
Case review status dropdown menu not loading

### ISSUE THREAD

**Issue by brmangilog** [broadinstitute/seqr#3090]
**Describe the bug**
A clear and concise description of what the bug is, and what you instead expect to be happening
The Case Review dropdown menu does not fully load so I am unable to change a family's case review status. I wanted to change RGP_931's status to Accept but Inactive was the only option that I was able to select.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/case_review

**Scope of the bug**
Originally found in RGP_931 but appears to affect all families with a shorter list of details (RGP_945 and lower)

**Screenshots**
![Screen Shot 2022-12-01 at 3 48 27 PM](https://user-images.githubusercontent.com/119630154/205157261-042f20f4-8897-4fd6-abcd-bdc21ff653b5.png)
![Screen Shot 2022-12-01 at 3 52 47 PM](https://user-images.githubusercontent.com/119630154/205157279-e8065b8a-e09f-4c85-a889-0bdbf0d3c4e7.png)

**Comment by hanars** [comment]
As an interim fix, if you scroll the page and then reopen it it will fix the issue, its only a problem if the dropdown opens up which it does if its too. close to the bottom of the page

**Comment by hanars** [comment]
this is fixed

**Comment by brmangilog** [comment]
Thank you!
