### ISSUE TITLE
Public gene notes not being saved

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3091]
**Describe the bug**
Public gene notes not being saved on the gene page when selecting the 'add to gene notes' on the variants page.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/41b9c5e25f036abfd78b7c3fb8a81390?page=1&sort=in_omim

**Scope of the bug**
Not tested in other projects

**Screenshots**
<img width="1244" alt="Screen Shot 2022-12-02 at 11 10 10 AM" src="https://user-images.githubusercontent.com/37872186/205336277-f837d713-4970-4c96-a106-ee332dc940df.png">

**Comment by hanars** [comment]
I am seeing this note as a gene note - just wanted to confirm whether you added it separately or if there is in fact no bug?

**Comment by lynnpais** [comment]
I added the note separately, using the Add Note function on the gene page.

**Comment by hanars** [comment]
This bug occurs when adding a note as the first note/tag added for a variant. If a variant has been previously tagged/ has notes already the bug does not occur

**Comment by hanars** [comment]
this is fixed
