### ISSUE TITLE
Phenotype-based prioritization: Exomiser table upload error.

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#3098]
Uploading gs://bw-proj/seqr-bw/project__phenotypes/2022_11_21__seqr_test/RGP_56_3_exomiser.for_seqr.tsv
to https://seqr.broadinstitute.org/data_management/phenotype_prioritization currently produces this error:
![image](https://user-images.githubusercontent.com/6240170/205713659-465abf09-1497-49c9-81f5-b77beba63149.png)
In the table, most scores are numbers, but some are empty string (to indicate "None") and the error is likely caused by that. 

The expected behavior is that missing scores are stored in the database as None and then shown as blank in the details view:
![image](https://user-images.githubusercontent.com/6240170/205713852-5369008d-0eac-41b6-8d2c-a11de61e8eb6.png)

**Comment by hanars** [comment]
Duplicates https://github.com/broadinstitute/seqr-private/issues/1203
