### ISSUE TITLE
Annotation files for genome 37 not available anymore at ENSEMBL

### ISSUE THREAD

**Issue by fbelleau** [broadinstitute/seqr#3100]
**Describe the bug**

We are using SEQR with genome 37 version for SEQR analysis, annotations dataset for this genome version are not available anymore and we can not install new SEQR servers using this command :

```
BUILD_VERSION=37
 
docker-compose exec pipeline-runner download_reference_data.sh $BUILD_VERSION
```

Can you provide a procedure to install the needed files ?

**Link to page(s) where bug is occurring**

This link does not give access to genome 37 version anymore

http://ftp.ensembl.org/pub/release-99/fasta/homo_sapiens/dna/

**Scope of the bug**

We are not able to load annotation data for the pipeline runner analysis with genome 37 version.

**Screenshots**

Here are the error messages we get :

<img width="782" alt="image" src="https://user-images.githubusercontent.com/995409/205739858-4e4d5fbf-c958-4e73-a61f-910ce044fd88.png">

**Comment by hanars** [comment]
Discussed in https://github.com/broadinstitute/seqr/discussions/3097 , please keep all conversation in that thread to prevent duplication
