### ISSUE TITLE
Add Sort By feature for LIRICAL results

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3111]
**Is your feature request related to a problem? Please describe.**
We would like to have the ability to sort variants in search that are flagged by LIRICAL

**Describe the solution you'd like**
Add LIRICAL as an option to the Sort By drop down on the variant page

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hanars** [comment]
this search will be implemented similar to the OMIM search, by pulling gene info from the seqr DB before querying ES

**Comment by ShifaSZ** [comment]
I need clarifications for below questions:
1. The requirement says we need to sort by `LIRICAL`. Do we also need to sort by other phenotype-based prioritization tools such as `EXOMISER`?
2. We should sort the variants according to the highest rank value in each variant's associated `LIRICAL` or `EXOMISER` data. Is that correct?

**Comment by hanars** [comment]
> 1. The requirement says we need to sort by `LIRICAL`. Do we also need to sort by other phenotype-based prioritization tools such as `EXOMISER`?

Yes. 

> 2. We should sort the variants according to the highest rank value in each variant's associated `LIRICAL` or `EXOMISER` data. Is that correct?

Yes, although I think we should only sort on the top ranked genes, probably the top 100

**Comment by hanars** [comment]
In search results, this sort should return an error if applied to multiple families, as the logic to determine how to relatively prioritize multiple families is too complex

**Comment by hanars** [comment]
this has been added
