### ISSUE TITLE
Add frequency filter for LIRICAL results

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3112]
**Is your feature request related to a problem? Please describe.**
Too many common variants are being returned in a search using LIRICAL's  Search for Variants in High-Ranked Genes feature. 

**Describe the solution you'd like**
Limit the variants in the search to <1% AF in gnomAD

**Describe alternatives you've considered**
Reviewed with analyst team.

**Additional context**
NA

**Comment by hanars** [comment]
We should use the default `GeneSearchLink` to set behavior, which would apply a <1% AF and an "any affected" inheritance filter

**Comment by ShifaSZ** [comment]
> We should use the default `GeneSearchLink` to set behavior, which would apply a <1% AF and an "any affected" inheritance filter

I can see that the `GeneSearchLink` applies the search settings of the below constants.
```
const INITIAL_GENE_SEARCH = {
  inheritance: { mode: ANY_AFFECTED },
  freqs: FREQUENCIES.filter(({ name }) => name !== THIS_CALLSET_FREQUENCY && name !== SV_CALLSET_FREQUENCY).reduce(
    (acc, { name }) => ({ ...acc, [name]: { af: 0.1 } }), {},
  ),
}
```
My question is when to apply the search settings for `LIRICAL's Search for Variants in High-Ranked Genes`. In the project variant search, since we don't know whether there are some LIRICAL High-ranked genes, we can't apply the settings by default. On the variant page and family page, both the "Gene Search" and the "Search for variants in high-ranked genes" have applied the <0.1 AF setting. Is there anything more that we need to do for this ticket?

**Comment by hanars** [comment]
This ticket is about modifying the search link in the Lirical modal on the family page

**Comment by ShifaSZ** [comment]
Since the search link in the Lirical modal on the family page uses the `GeneSearchLink` component, the initial gnomAD AF is set to 0.1. Can we simply change gnomAD AF from 0.1 to 0.01  in the initial settings of `GeneSearchLink`? Or should we pass in the initial gnomAD AF setting to the component?

**Comment by hanars** [comment]
we should use whatever the default `GeneSearchLink` behavior is for the lirical link with no modifications, as I said above

**Comment by ShifaSZ** [comment]
So I'm going to change the initial AF of `GeneSearchLink` to 0.01. But I don't know if there is any negative impact on the other use cases of the component.

**Comment by hanars** [comment]
`GeneSearchLink` will not change. All you are doing is using that component, as it is, for the litrical link. As I have said repeatedly, whatever the search that component generates is the search we are going to use for lirical. I'm not sure how to be clearer than this: `We should use the default GeneSearchLink behavior`

**Comment by hanars** [comment]
You need to use the same behavior to define a new helper component:
```
const geneSearchProps = af => ({
  inheritance: { mode: ANY_AFFECTED },
  freqs: FREQUENCIES.filter(({ name }) => name !== THIS_CALLSET_FREQUENCY && name !== SV_CALLSET_FREQUENCY).reduce(
    (acc, { name }) => ({ ...acc, [name]: { af } }), {},
  ),
})

const INITIAL_GENE_SEARCH = geneSearchProps(0.1)
const RARE_GENE_SEARCH = geneSearchProps(0.01)

export const GeneSearchLink = props => <ConnectedSearchResultsLink initialSearch={INITIAL_GENE_SEARCH} {...props} />
export const RareGeneSearchLink = props => <ConnectedSearchResultsLink initialSearch={RARE_GENE_SEARCH} {...props} />
```

**Comment by ShifaSZ** [comment]
Can we let `GeneSearchLink` pass in an `af` property? It seems more generic. Once we have the `af` property, we can update the `search` generation in the `mapDispatchToProps` like below.
```
    const search = {
      ...geneSearchProps(ownProps.af || 0.1),
```
How do you think about we add an `af` prop?

**Comment by hanars** [comment]
this discussion belongs on the PR not the ticket

**Comment by hanars** [comment]
this has been updated
