### ISSUE TITLE
Add 'Families/Individuals with data' section to Project Overview

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#3116]
**Is your feature request related to a problem? Please describe.**
On a seqr project page, you see a quick overview of the number of families and individuals listed in that project. Right now this list does not require data (e.g. a counted trio may have 3 individuals listed in seqr but only 1 with sequencing data). A powerful metric that is needed for manuscripts and GREGoR progress reporting is how many families (proband only, duo, trio, quad+) have data. 

**Describe the solution you'd like**
I would like to add a **'xxx Families, xxx Individuals with data'** section to this project overview. If we need to save on space, we can consider removing the category breakdown for listed families. I think comparing the two groups is interesting, but ultimately this family breakdown is more useful for individuals with sequencing data. 

> **xxx Families, xxx Individuals with data**
>     xx families with 1 individual
>     xx families with 2 individuals
>     xx trios
>     xx quads
>     xx families with 5+ individuals

I also want to confirm that a trio is a family with proband/mother/father relationship and not just a family with 3 individuals (e.g. parent and two sibs). I can make an additional ticket for this if needed.

**Comment by hanars** [comment]
section has been added

**Comment by stephditroia** [comment]
This looks great! Thanks Hana! I will follow up with a new ticket about confirming maternity/paternity in trios (noting here only because it was the last line of the original post).

**Comment by hanars** [comment]
Yeah sorry I missed that line. Trio is any family of 3, it doesn't check the family structure, but we can change it so trio is an actual mother/father/proband  group and make a different category for "3 people not a trio", just make a new ticket

**Comment by stephditroia** [comment]
That sounds perfect. I'll make a new ticket. Thanks.
