### ISSUE TITLE
Show automated MME tags in the saved variants bar

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#3118]
**Describe the bug**
Automated MME tags are not showing in the Saved variants bar or on the Saved variants page. 

**Scope of the bug**
This is missing on both the project page and saved variants page

**Screenshots**
<img width="1598" alt="image" src="https://user-images.githubusercontent.com/44381119/207672515-fe8645e6-b3f8-4574-86d4-be5446b1402a.png">

**Comment by hanars** [comment]
The tag is showing under the family name, where it is intended. As this tag can not be edited, it was decided that it would be visually confusing for it to be shown exactly as if it were an editable tag

I will transition this to a feature request for being able to select it in the bar, as that was not part of the original request

**Comment by hanars** [comment]
this has been added
