### ISSUE TITLE
Filter by saved variants on project page

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#3119]
**Is your feature request related to a problem? Please describe.**
In large projects with multiple analysts (RGP), I would like to view MME submissions or high-priority candidates on only my cases. 

**Describe the solution you'd like**
An easy solution (that may have other useful applications) is adding a 'filter by' option on the Saved Variants column on the project page. For my use case, I can filter by cases assigned to me and MME tag (or Analyst high priority tag). 

![image](https://user-images.githubusercontent.com/44381119/207674384-185fd05a-0dbc-4994-b4cf-ebb1f5492f56.png)

**Comment by hanars** [comment]
Filters have been added
