### ISSUE TITLE
Clear all notes/tags from GREGoR Training Projects A-L

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#3126]
I will be using the GREGoR Training Projects to teach a class on **1/5/23** and it would be very helpful if we could have all variant notes/tags cleared for at least 5 projects so the students can start with a clean slate. I figured we might as well wipe them all clean while we're at it (so I'm requesting clearing projects A-L). Thanks!

**Comment by hanars** [comment]
tags have been cleared
