### ISSUE TITLE
Update seqr to support the updated SV data

### ISSUE THREAD

**Issue by ShifaSZ** [broadinstitute/seqr#3129]
**Is your feature request related to a problem? Please describe.**
The SV loading pipeline is going to be updated (See [here](https://github.com/broadinstitute/seqr/issues/3064)). To make the seqr to be ready for the new SV callset format, it requires updating the seqr search filtering and display

**Describe the solution you'd like**
See the [ticket](https://github.com/broadinstitute/seqr/issues/3064) for details.

**Describe alternatives you've considered**
No alternatives

**Additional context**
No additional context

**Comment by ShifaSZ** [comment]
The `Multiallelic SV` predictions use a field name of `MSV_EXON_OVR` in the old format but `MSV_EXON_OVERLAP` in the new format. Should we handle them as two different `structural consequences` during the transitioning phase? We must keep the old field name for backward compatibility. We also could rename the field to the old format while loading the new dataset. But it makes it harder to migrate to the new field name in the future.

**Comment by hanars** [comment]
We should change the consequence in the UI so the new value is whats sent to the server. Then in the server side code we should check and if the new value is there we should also add the old value to search so we search on both the new and old value. Once every project has been reloaded, we can go back and remove that piece of code

**Comment by ShifaSZ** [comment]
Okay, I will add special handling in the backend.
