### ISSUE TITLE
Ability to add mutltiple filters to a custom gene search

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3138]
**Is your feature request related to a problem? Please describe.**
Custom search most often times out giving a 504 error when searching for variants a gene(s) across all data. To make things work, we have been using very minimal filters, but this returns far too many variants to review. 

**Describe the solution you'd like**
Be able to apply multiple filters (including inheritance, AF, annotations, & call quality) and have the search go through on the first attempt. 

**Describe alternatives you've considered**
NA

**Additional context**
Here's an example of a de novo search that times out - https://seqr.broadinstitute.org/report/custom_search/997f7238b48b417017ed725ed7888bd6?page=1&sort=xpos

Based on our conversation earlier this morning, I waited 5mins and tried and again, and voila - it worked!

**Comment by hanars** [comment]
Is there a reason annotation filters aren't included as part of the desired criteria?

**Comment by hanars** [comment]
Note that the frequency and annotation filters work totally fine here. The search finished pretty quickly and in the first try when I applied those filters and not the inheritance and quality filters

**Comment by hanars** [comment]
I know you mentioned you also want this search to be able to work on a short list of genes, not just one at a time. Can you send me an example of a small set of genes you are interested in

**Comment by hanars** [comment]
The search example you provided did not include SVs. Is hat the use case you anticipate here, or will you also want this to work searching across all data types

**Comment by hanars** [comment]
@lynnpais this should be working better now, especially for heavily filtered searches (i.e strict annotation/frequency/location) criteria. Let me know over the next few days how its working for you

**Comment by hanars** [comment]
closing this out as I believe everything is working. Any new issues can be reported as new tickets
