### ISSUE TITLE
Custom search times out when using chr coordinates

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3139]
**Describe the bug**
Custom search for variants in a defined chromosomal location by entering the coordinates does not seem to be going through, despite waiting at least 5 mins and trying again. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/report/custom_search/f6967d2fe206eb18e6436ba172882642?page=1&sort=xpos

**Scope of the bug**
NA

**Screenshots**
<img width="1172" alt="Screen Shot 2023-01-05 at 1 05 04 PM" src="https://user-images.githubusercontent.com/37872186/210849620-daebe1ed-11fd-41a7-aa91-a1f111f00b14.png">

**Comment by hanars** [comment]
This search works fine when AF and annotation filters are applied and no inheritance of quality filters are applied. This means that this issues is just a subset of the issue in https://github.com/broadinstitute/seqr/issues/3138 and can be addressed there
