### ISSUE TITLE
Unable to add an assigned analyst to cases

### ISSUE THREAD

**Issue by eoheir** [broadinstitute/seqr#3141]
**Describe the bug**
I am trying to assign analysts to cases in the NeuroDev_Wave1_Kenya project but am not able to. After clicking the 'edit' icon next to Assigned Analyst on the family page, I entered Ike's email address and clicked 'Submit,' but the assigned analyst field remains blank. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0624_neurodev_wave1_kenya/family_page/F039415_860_65800681 

**Scope of the bug**
I specifically ran into this in the NeuroDev_Wave1_Kenya project, but I quickly checked a few other projects (Neurodev_Wave1_SA and CMG_Beggs_WGS) and seem to have the same issue in those as well.

**Comment by hanars** [comment]
This happens because the PM team did not properly grant access in AnVIl. Please reach out to them and let them know that the analyst user group needs WRITE access and "can share" permission on all the access workspaces
