### ISSUE TITLE
Update pedigree symbol for unknown sex

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3143]
**Is your feature request related to a problem? Please describe.**
Need to be consistent with current pedigree symbols

**Describe the solution you'd like**
For unknown gender and not affected: clear diamond
For unknown gender and affected:  colored diamond
<img width="281" alt="Screen Shot 2023-01-09 at 1 18 18 PM" src="https://user-images.githubusercontent.com/37872186/211379456-5641f292-6cb4-4e8d-b773-7257d6e20048.png">

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hanars** [comment]
Not super important in this ticket, but in general its important to be careful about the difference between sex and gender. Sex is a biological property, and it is what we show in seqr, as it impacts which chromosomes an individual has and has diagnostic relevance. Gender is a personal identity and is currently not shown in seqr

**Comment by lynnpais** [comment]
yup, and I should know better too.

**Comment by hanars** [comment]
this has been updated
