### ISSUE TITLE
Issues navigating to tagged variants using 'Saved Variants' bar

### ISSUE THREAD

**Issue by eoheir** [broadinstitute/seqr#3155]
**Describe the bug**
There seems to be a new bug with the saved variants bar at the top of the 'Saved Variants' page for individual cases. Typically, when you click on a specific tag category within the saved variants bar (i.e. analyst high priority, review, KGP, etc.), you will be immediately shown all variants with that tag for _that specific family_. Today, the analysts noticed that clicking on a specific tag category within the saved variants bar causes seqr to load for several minutes and then show you all variants with that tag _across the entire project_.

**Link to page(s) where bug is occurring**
Example: Clicking on the orange 'analyst high priority' section of the saved variants bar on https://seqr.broadinstitute.org/project/R0623_neurodev_wave1_sa/saved_variants/family/F039660_859_18256634 brings you to https://seqr.broadinstitute.org/project/R0623_neurodev_wave1_sa/saved_variants/Analyst%20high%20priority, which shows all analyst high priority variants across the entire NeuroDev_Wave1_SA project, rather than just for that specific family.

**Scope of the bug**
Seems to be happening across multiple projects - I've noticed it in both NeuroDev and RGP.

**Comment by hanars** [comment]
this is fixed
