### ISSUE TITLE
Check family structure when reporting 'Families/Individuals with data'

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#3156]
**Is your feature request related to a problem? Please describe.**
The new 'xxx Families, xxx Individuals with data' section on a seqr project page reports any 3 individuals as a trio. We would like seqr to check family structure when reporting these numbers (i.e. a trio is a mother/father/proband and quad is mother/father/proband/sibling). To simplify this section, we want to combine any families with a confirmed mother/father/proband + other family members into a 'trios+' section. Families with 3 or more individuals but missing a mother or father sample will be reported in  'other family structures'.

Proposed new categories:
> xxx Families, xxx Individuals with data
> xx families with 1 individual
> xx families with 2 individuals
> xx duos (parent-child)
> xx trios (parents-child)
> xx trios+ (parents-child plus other)
> xx other family structures 

Related ticket: https://github.com/broadinstitute/seqr/issues/3116

**Comment by stephditroia** [comment]
Edited to add duos (parent/child only) and slightly changed wording according to feedback from analysis team.

**Comment by hanars** [comment]
For clarity/consistency, these change will apply to both the new "with data" section and the main overview section

**Comment by stephditroia** [comment]
Works for me

**Comment by hanars** [comment]
this has been aded
