### ISSUE TITLE
Addition of a link to DECIPHER showing search results for CNV coordinates 

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#3158]
On the variant page, we would like to add a link leading to DECIPHER browser showing the search results for the genomic coordinates of CNVs (Hg38) present in seqr. 
For example, for this deletion, I added the Decipher link under the genomic coordinates to the right of pubmed (red arrow)
![Screen Shot 2023-01-13 at 12 34 42 PM](https://user-images.githubusercontent.com/84086816/212385230-ae4cf6c5-7da8-4b9c-917b-95fd5445a5a0.png)
Clicking on the DECIPHER link would lead to this page: 
https://www.deciphergenomics.org/search/patients/results?q=2%3A74466072-74469468

Let me know if you have any question. Thank you.

**Comment by hanars** [comment]
this has been added

**Comment by Glemiret** [comment]
Thanks Hana! I just checked 2 random CNVs and the coordinates used to query DECIPHER were Hg19, but DECIPHER uses HG38 (so the interval was incorrect). Can you change to use HG38? Thank you!

**Comment by hanars** [comment]
please submit a bug ticket with links to the variants that are causing issues

**Comment by Glemiret** [comment]
I checked multiple CNVs across different projects and the link to DECIPHER uses Hg19 instead of Hg38 in all of them so I don't think this is a bug. The use of Hg38 was specified in the original feature request, so I think this is part of the original ticket. Thank you for modifying it!

**Comment by hanars** [comment]
I implemented this using hg38 coordinates, as asked. If there is an issue with that, thats either a change to the feature request or a bug with how I did that implementation. Either way, as far as I can figure out I did what this ticket asks, so if I didn't and there is more work to do I need a new ticket clearly specifying what you want me to change
