### ISSUE TITLE
Option to exclude solved cases in a search

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3159]
**Is your feature request related to a problem? Please describe.**
When running a family variant search or custom search across all seqr data for variants in a gene(s), a large number of results are often returned, many of which are in solved cases. We'd like to reduce the number of search results by excluding solved cases.  

**Describe the solution you'd like**
Have the option to exclude cases considered solved in the search results. One option is to show this checkbox below the Add Project/ Add Project Group feature, but open to other ideas. The case status on the Family page can be used for reference for which cases are solved. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hanars** [comment]
this has been added
