### ISSUE TITLE
Update Google link to Google Scholar 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3160]
**Is your feature request related to a problem? Please describe.**
Results returned by a Google search for a variant are not very relevant. We would like to limit the results to Google Scholar. 

**Describe the solution you'd like**
Update the variant link (beneath the chr coordinates on the variants page) to a Google Scholar search.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hanars** [comment]
please provide example google scholar links

**Comment by lynnpais** [comment]
I'm going to get some additional information from the team, so hold off on this one for now. Moving to blocked (on me).

**Comment by hanars** [comment]
for future reference, please make sure to move blocked issues into the blocked column on zenhub, not just add a label

**Comment by hanars** [comment]
updated
