### ISSUE TITLE
Add Mastermind to the list of variant links 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3161]
**Is your feature request related to a problem? Please describe.**
We would like to improve our search for variants reported in literature. 

**Describe the solution you'd like**
We would like to include a variant link to Mastermind on the saved variants page (below the chr coordinates). For example, this variant https://seqr.broadinstitute.org/project/R0358_cmg_vcgs_exomes/saved_variants/variant/SV0022097_9109734487_r0358_cmg would link to this page in Mastermind https://mastermind.genomenon.com/detail?gene=znf462&mutation=znf462:R2211fs&boolean=true&gene_op=and&mutation_op=and&cnv_op=and&disease_op=and&hpo_op=and&unii_op=and&keyword_op=and

**Describe alternatives you've considered**
NA

**Additional context**
The search in Mastermind works using the following format gene + p. info - ZNF462:p.Arg2211GlyfsTer59
<img width="1383" alt="Screen Shot 2023-01-13 at 3 29 43 PM" src="https://user-images.githubusercontent.com/37872186/212413420-4a36c53d-e1a6-433b-b349-f97a3011eb6e.png">

**Comment by hanars** [comment]
added
