### ISSUE TITLE
Arrangement of variant links on the saved variants page

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3162]
**Is your feature request related to a problem? Please describe.**
I've put in a few tickets to add/ edit variant links. We's like to re-order them too. 

**Describe the solution you'd like**
We'd like the variant links to be ordered as follows: seqr > Google (Scholar) > Mastermind. The links to Geno2MP and Iranome can be moved to the dropdown. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hanars** [comment]
this is not a separate ticket. Please include this information on both the google scholar and mastermind tickets
