### ISSUE TITLE
text entries on family page 

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#3165]
**Describe the bug**
I am unable to erase the "coded phenotype" and "post-discovery OMIM" fields on family page. I click on it, erase the text and click submit, no changes was applied. I can only replace it with other text (in this case, I added the word" none") , but would like to have the fields empty here. Is this possible to go back to an empty field for these entries after some text had been added? 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0474_cmg_sherr_exomes/family_page/F025264_she_3357

**Scope of the bug**
It happened in other families, I can provide more links if needed. 

**Screenshots**
![Screen Shot 2023-01-17 at 3 24 17 PM](https://user-images.githubusercontent.com/84086816/213005106-54ce9944-3bce-4cce-b1dd-ad438710fc25.png)

**Comment by hanars** [comment]
this is fixed now (and I removed the entries for the example family you gave to confirm that it was working)

**Comment by Glemiret** [comment]
thank you!
