### ISSUE TITLE
Support sharded VCFs in AnVIL loading

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr#3173]
The seqr loading pipeline can accept sharded VCF's, which are handled by passing a single glob patter as the `vcf_path` to the pipeline DAG. In the case where the sharded VCF is in the form `gs://anvil-bucket/joint-call/0000-project-vcf.vcf.gz`, `gs://anvil-bucket/joint-call/0001-project-vcf.vcf.gz`, `gs://anvil-bucket/joint-call/0002-project-vcf.vcf.gz`... then the VCF path we pass to the pipeline would be `gs://anvil-bucket/joint-call/*-project-vcf.vcf.gz`

However, the UI and VCF validation fro AnVIL loading currently will not support sharded VCF's, as the use will be forced to select a single file from the dropdown. We need to add logic to the endpoint that generated the list of possible VCFs to detect cases where there is a sharded VCF and show the user the glob pattern intsead of all the shards, and we then need to update the validation logic to work on the glob pattern as well

**Comment by ShifaSZ** [comment]
Are there any patterns other than VCF files starting with `[0-9]+`? For example, sub-folders with shard numbers, files beginning with `shard-[0-9]+`, etc.

**Comment by hanars** [comment]
We should assume that all shards are in the same folder, and have the same filename other than one place in the filename where there is a variable `[0-9]+`. Technically this number could be anywhere in the file, for example `gs://anvil-bucket/project-vcf-000*.vcf.gz`, but for the specific use case we can assume it is either the beginning of the file name or the end

**Comment by ShifaSZ** [comment]
It seems that each sharded VCF file can have different samples. In that case, one of the VCF files must have a complete header, and we need to know which one is the file. Is it okay to only support all pieces with the same header? @hanars

**Comment by hanars** [comment]
Let me confirm with the requesting team

**Comment by mike-w-wilson** [comment]
Sorry to be late to this but hail's import_vcf requires all shards to have the same header and sample order.

**Comment by lynnpais** [comment]
Do we have an ETA for when the collaborator will be able to upload their data? Asking as they checked in via email.

**Comment by hanars** [comment]
I will release this tomorrow, lets tell her Thursday

**Comment by hanars** [comment]
this functionality is now live
