### ISSUE TITLE
Wrong Decipher link 

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#3176]
**Describe the bug**
The link leading to DECIPHER webpage is incorrect, it leads to the wrong coordinates. please use Hg38, not HG19 for all the CNVs

**Link to page(s) where bug is occurring**
Any seqr page with a CNV
Ex: https://seqr.broadinstitute.org/project/R0284_pierce_retinal_degenerat/saved_variants/family/F021157_ogi1770/Known%20gene%20for%20phenotype

https://www.deciphergenomics.org/search/patients/results?q=19%3A54609974-54635124
DECIPHER has the wrong coordinates here 

**Scope of the bug**
yes, multiple projects

**Comment by hanars** [comment]
The Decipher link you provide in this ticket is identical to the decipher page you are taken to when you click on the "Decipher" link on the variant you provided. Please provide a link to the Decipher page you would want to be taken to for that variant instead

**Comment by Glemiret** [comment]
yes I was trying to explain the bug (that is why I wrote "DECIPHER has the wrong coordinates here"). The correct DECIPHER link is the one with Hg38 coordinates so this one: https://www.deciphergenomics.org/search/patients/results?q=19%3A54106667-54131817. Thank you

**Comment by hanars** [comment]
this is fixed

**Comment by Glemiret** [comment]
I checked a couple of CNVs from different projects and it now looks great. Thanks a lot👍
