### ISSUE TITLE
Time-sensitive - data for grant submission

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#3177]
For a grant Vijay is submitting soon, we just realized that he needs to make a table of ancestry breakdown of everyone with RNAseq data. I was going to talk to the PMs but I don't think this is very straightforward for them given the ancestry comes from the DNA not the RNA. 

So I'm wondering if it's possible to pull a list of all individuals in seqr that have RNAseq: the RNA sample ID, the DNA sample ID, affected/unaffected status, and then the ancestry. If the ancestry is blank, that's ok but still please include these in the output - it's probably something I can ask the PMs to track down on any samples with missing data. 

This isn't something that we will routinely ask for (though we could need it randomly sometime again for a grant submission).

**Comment by hanars** [comment]
I would like to gently push back against having me pull this information. The information about ancestry for all of our internal samples can be found in the [sample metadata report](https://seqr.broadinstitute.org/report/sample_metadata/all) and getting a list of which samples we have RNA for should be pretty straightforward for the PM team to deliver. Filtering an excel file to a subset of that file is straightforward and therefore anyone with basic proficiency in excel can take the list of RNA samples and the sample metadata report and get the stats they need. 

If there is really no one in our lab who feels like they have the ability to use excel like that then if the PM team can get me the list of RNA samples I can generate the subsetted sample metadata report for you, but I do think this is something that we should have someone less technical doing

**Comment by anneodonnell** [comment]
Good point - I was thinking we didn't have the RNA metadata available yet but that's just for GREGoR. I can't get the sheet you suggested to download though. Any advice?

**Comment by hanars** [comment]
that page can take up to 10 minutes to load, its a pretty slow report. If you come back after 10 minutes and its not loaded, or if its showing an error message, thats a bug that needs its own ticket (although its fair to make that a time-sensitive ticket)
