### ISSUE TITLE
Add variant link: AoU

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3179]
**Is your feature request related to a problem? Please describe.**
We'd like to include a variant link to a newer database, AoU

**Describe the solution you'd like**
In the list of variant links (below genomic coordinates), add a new link to look up the frequency in the All of Us database using https://databrowser.researchallofus.org/genomic-variants 

**Describe alternatives you've considered**
NA

**Additional context**
 New order for the variant links: seqr I Google (scholar - but no need to mention) I Pubmed I (the next three go in the dropdown [AoU I Iranome I GME I Mastermind]

**Comment by hanars** [comment]
added
