### ISSUE TITLE
Collapse individual details in case review

### ISSUE THREAD

**Issue by gvannoy** [broadinstitute/seqr#3181]
Each family display is very large in Case Review, with about half of the space taken up by individual details that we do not use at this step. This makes the Case Review page very slow to load and cumbersome to scroll through when there are many families to review. 

I'd propose making the details for each individual collapsible (defaulting to collapsed) and expandable with a small carrot. The only field we use in this section (below Internal Summary) is the Review Status dropdown menu for the proband. Fig 1 shows the section to condense in yellow with the one field we use in green. Fig 2 is a rough mock-up of a proposed solution. 

Fig 1
![image](https://user-images.githubusercontent.com/40441144/214337461-9aff8515-7bfe-4667-bcfd-8fcfc229396e.png)

Fig 2
![image](https://user-images.githubusercontent.com/40441144/214339070-4dae163b-41d2-4e93-abea-bc564c5044e5.png)

**Comment by hanars** [comment]
this has been updated
