### ISSUE TITLE
Overwrite of "Analysed by" names in seqr projects

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#3192]
**Describe the bug**
At some point this week all "Analysed by" categories in the RGP HMB and GRU projects were changed such that each data type is now listed as analyzed by a member of the Ops team (Marcky Antonio or Jillian Serrano, who do not do analysis in seqr) rather than the analyst who actually worked on the case. As far as I can tell, the analyzed by dates were not changed. Can the names be restored?

**Link to page(s) where bug is occurring**
Examples here: https://seqr.broadinstitute.org/project/R0594_rare_genomes_project_gen/family_page/F033126_rgp_2113
https://seqr.broadinstitute.org/project/R0624_neurodev_wave1_kenya/family_page/F039448_860_27511526

**Scope of the bug**
I see the same phenomenon in other projects, though different team members names have been added (eg Stacey Hall in the Neurodev_Wave1_Kenya project)

**Screenshots**
![image](https://user-images.githubusercontent.com/67653781/215128041-a0b1aca5-2f4f-4b26-8065-57c107c0a121.png)
![image](https://user-images.githubusercontent.com/67653781/215129316-feefb2ef-d23f-4598-9f65-efaea8a2de0d.png)

**Comment by hanars** [comment]
The good news is that this is a bug with how we are displaying the list of names, but the real data is still properly stored in the database so we still have the accurate information in our database which means I can bring back the correct names

**Comment by Caustint** [comment]
Phew!

**Comment by hanars** [comment]
this is fixed
