### ISSUE TITLE
Restrict variants to high priority genes

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3199]
**Is your feature request related to a problem? Please describe.**
We updated the HPO prioritized gene list on the Family Page to show the top ten results. However, the feature to show variants in high-ranked genes returns variants in genes that are not part of the top 10. In the example here, the search is returning ~10,000 variants. 

**Describe the solution you'd like**
Restrict variants returned using the Search for variants in high-ranked genes to the prioritized genes in the list on the Family Page. 

**Describe alternatives you've considered**
NA

**Additional context**
Family page - https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F031995_rgp_2007
<img width="703" alt="Screen Shot 2023-02-02 at 1 06 52 PM" src="https://user-images.githubusercontent.com/37872186/216407555-bf804658-cfe4-42af-a609-bb4de5b2dc4d.png">

Results page- https://seqr.broadinstitute.org/variant_search/results/2bc1bf376c14ba1046d38abb317a46b5?page=1&sort=pathogenicity
<img width="1245" alt="Screen Shot 2023-02-02 at 1 07 36 PM" src="https://user-images.githubusercontent.com/37872186/216407815-92a2ecb1-5ac9-4c0d-8ec7-cfc1fe4bb3f6.png">

**Comment by hanars** [comment]
this is now working
