### ISSUE TITLE
Splice junction outliers

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#3200]
Each *splice junction* is represented by 4 values: chromosome, start (1-based) position, end position, strand (+ or -). 
Usually (but not always) the splice junction is associated with a gene. The gene may be missing if it's a novel junction outside of annotated genes. 

A *splice junction outlier* is a splice junction that also has a p-value (ie. 0.0002), a z-score (ie. -3.5), a tool name that generated these (ie. "FRASER"), and an integer read count representing the number of RNA-seq reads that span the junction. 

To add splice junction outliers to seqr, we should:
- show a "splice junction outliers " button on the family page under the individual that has RNA-seq data (similar to expression outliers)
- RNA-seq sample tissue type (eg. "fibroblasts" or "whole blood") should also be shown somewhere
- splice junction outlier page for that individual should show:
    - volcano plot (each point is a splice junction, x-axis is the z-score, y-axis is the p-value)
    - table with one row per gene or splice junction  (TBD) - with columns: rank by p-value, gene name (empty if gene is missing), splice junction chrom/start/end/strand (clicking here should jump to this interval in IGV.js),  read count, zscore, p-value
    - button to search for variants in this family with the region filter set to all splice junction intervals above some p-value threshold (TBD)
  
- variant search results should show "splice junction outlier" tags on variants that are near outlier junction intervals +/- 200bp 
	- hover over the tag should show info about the splice junction outlier (chrom/start/end/strand,  z-score, pvalue, maybe tissue and read count also)
	- there should be a way to show the splice junction region in IGV (+/- 200bp) and automatically show the splice junction track for that sample + the GTEx track for the same tissue as the sample

----
Input format for splice junction outliers. 
The data upload UI should make it possible to upload a table with these columns:

- seqr individual id 
- tissue type
- ENSG gene id 
- chrom
- start (1-based coordinates)
- end 
- type (string) - example values: psi5, psi3, theta
- strand  ("+" or "-")
- read count (integer number of RNA-seq reads that span the splice junction)
- z-score
- p-value
- deltaPsi (float) 
- rareDiseaseSamplesWithJunction - integer - this is the number of rare disease samples that have support for that junction
- rareDiseaseSamplesTotal - integer - number of rare disease samples total (for that tissue)
- dotSize (float) - values are between 0 and 1 and represent the size of the circle to draw in the volcano plot.

**Comment by hanars** [comment]
Overall this looks good to me! This will be blocked until we can get an example of the file you describe, but otherwise I think we are all set. Some comments for implementation:

> RNA-seq sample tissue type (eg. "fibroblasts" or "whole blood") should also be shown somewhere

Family page: Lets show this in the header when the user opens the volcano plat/ table - header should say `RNA-Seq Splice Junction Outliers: <sample_id> (<tissue_type>)`
Search results: Show when user hovers over the tag

**Comment by ShifaSZ** [comment]
@bw2 Should the input data column `seqr individual id` be the sample Id rather than an individual id? I'm asking this question because other Rna Seq datasets (outliers and TPMs) are sample-based.

**Comment by hanars** [comment]
The individual ID will be easier to map and it is fine (better even) for the sample ID to be the same as the individual ID, so you can still make it a sample centric model without needing a sample ID column

**Comment by bw2** [comment]
@ShifaSZ this is an example input table
https://docs.google.com/spreadsheets/d/1ZFNNP61fDqwMwYYqWQTuBxBrVYw2rEvteb8kQyk2KSw/edit?usp=sharing

**Comment by ShifaSZ** [comment]
@bw2 Do you mind changing the `gene` column to `geneId`?

**Comment by bw2** [comment]
Sure! Done.

**Comment by bw2** [comment]
from RNA-seq meeting: 
- make a new page (rather than popup) - it should open in a new tab
- show OURIDER and FRASER on the same "RNA-seq results"
- input table:
    - add deltaPsi
    - number of rare disease samples that have some support for that junction
    - number of rare disease samples total (for that tissue)
- on that page:
   - OUTRIDER & FRASER volcano plots will be next to each other 
   - FRASER volcano plot - point size varies based on log(abs(deltaPsi)) 
   - RNA-seq splice junction outlier table 
          - not more than the top 50 splice junctions (based on sorting by pValue) and where pValue < 0.01
          - add link to each row in the table to search for that specific outlier

**Comment by bw2** [comment]
variant search results:
- show tags on variants that overlap an outlier splice junction +/- 5kb
- tag name should be: "RNA splice"
- OUTRIDER tag should be changed to: "RNA expression"
- double-check that splice junction outlier tags will work for SVs (needs interval intersection to work)

**Comment by bw2** [comment]
example of what the splice junction outlier volcano plot should look like:
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/6240170/219699480-1cd0284d-8460-47ef-a890-890feee8abc6.png">

**Comment by hanars** [comment]
One amednment to the example: like with the current outrider plot, we will only show gene  information for the significant data points

**Comment by ShifaSZ** [comment]
> * seqr individual id
> * tissue type

@bw2 Can one individual have multiple tissue types for a single splice junction in the input data table? If yes, we need to assign different sample ids for each tissue type of an individual. Do you prefer auto-generated sample ids or providing sample ids in the input table?

**Comment by hanars** [comment]
Each row in the provided table includes a tissue type which means that each junction is only present in one tissue type. Per the table specified Ben will be providing Individual ID and we will use tht as the sample ID. We should already support duplicate sample IDs as long as the tissue type differs

**Comment by bw2** [comment]
I think it will be very rare, but possible for an individual to have RNA-seq data for more than one tissue type (ie. 1 blood sample, 1 muscle sample).

**Comment by bellmartin** [comment]
As a user - I would like to comment that we do have quite a few samples with more than one tissue type. Often do this when the sample is still undiagnosed after first RNAseq analysis, and there is a set of genes of interest that were not expressed in original tissue type. For us, that is often lcl's as the first tissue type, then fibroblasts as second tissue.

**Comment by ShifaSZ** [comment]
> * type (string) - example values: psi5, psi3, theta

Should the `type` field have a choices list of 'psi5', 'psi3', and 'theta'? Or can it have different values other than these three?

**Comment by bw2** [comment]
As far as the SQL data type, I'd vote for keeping it a string in case we add data for other tools that have additional outlier types.

**Comment by hanars** [comment]
> > * type (string) - example values: psi5, psi3, theta
> 
> Should the `type` field have a choices list of 'psi5', 'psi3', and 'theta'? Or can it have different values other than these three?

Lets make it a char field with a max length of 12. So that way we don't need to run a database migration if this ever changes but also will enforce that its a short type identifier and not like a paragraph

**Comment by ShifaSZ** [comment]
Thanks. BTW. Do we have a utility function to get two letters `chrom`  from the chromosome string, such as `chr12`? It could be wrong by simply removing the first three letters. Some chromosome strings in the example data file are like `chr22_KI270734v1_random`.

**Comment by bw2** [comment]
I should filter these out before uploading them to seqr. I think it's fine to ignore rows that are not from chr1-22,X,Y,Mt.

**Comment by hanars** [comment]
The closest we have is this which could be broken into its own helper function:
https://github.com/broadinstitute/seqr/blob/master/seqr/utils/xpos_utils.py#L50

That will throw a validation error for the chrmosome you describe, seqr in general does not accept alternate contigs, which seems like that might be the behavior we want anyways

**Comment by hanars** [comment]
@bw2 can we also have a project column in this file, to prevent some of the issues we just ran into with the other RNA data

**Comment by ShifaSZ** [comment]
> input table:
...
> * number of rare disease samples that have some support for that junction
> * number of rare disease samples total (for that tissue)

Do we use these two numbers on the output page?

**Comment by bw2** [comment]
It would be good to include these in the table of outlier results and in
pop ups in search results.

**Comment by ShifaSZ** [comment]
> * FRASER volcano plot - point size varies based on log(abs(deltaPsi))

The value of `deltaPsi` in the example data range from `0.54` to `0.99`. All the ` log(abs(deltaPsi))` result in a negative value. It doesn't look right. What is the right mapping from `deltaPsi` to the point size?

**Comment by bw2** [comment]
Please use the 'dotSize' column in the example data for the point size.

**Comment by ShifaSZ** [comment]
I got it. I'll scale the size in a range of 1~20 pixels.

**Comment by ShifaSZ** [comment]
> * add a link to each row in the table to search for that specific outlier

We need to search for the gene of the outlier. Correct?

**Comment by hanars** [comment]
there should be a gene search link next to the gene name, similar to how we do on the phenotype prioritization table. Than there should be a column with a search link for just that junction. Searching for the junctions should be a search for the interval of the junction with a  +/- 200bp window around it, which will align with the window we use for showing the label for the outlier in search results

**Comment by ShifaSZ** [comment]
> * show tags on variants that overlap an outlier splice junction +/- 5kb

For OUTRIDER, we show the tag when the gene of the variant and the gene of the expression outlier are the same. We don't check the locus coordination. We could do the same thing for the FRASER. Or should we add the overlapping coordination checks?

**Comment by bw2** [comment]
If I understand the question correctly, for FRASER it would be better to tag based on overlap if possible (rather than just based on the gene name).  I mentioned adding 5000bp to the splice junction interval on both sides when doing this overlap check, and Hana suggested +/-200bp. Another good option would be +/-500bp. I think we should start with +/-5000bp and adjust if people think there are too many tags.

**Comment by hanars** [comment]
For Junction outliers we will show the tag based on overlap iwth the region, not the gene. This will use the same logic we use for gene lists that have intervals

**Comment by bw2** [comment]
I see the option to upload splicing outliers
<img width="862" alt="image" src="https://github.com/broadinstitute/seqr/assets/6240170/aa013fb6-173a-4285-bd4e-9799287af6c2">
Is it fine to start using this feature?

**Comment by hanars** [comment]
no, we will let you know when this is available. The loading is mostly complete but we do not want to actually add data until the UI for showing it has been completed

**Comment by hanars** [comment]
@bw2 all functionality for this is now live, so feel free to add data whenever you want. If its easy for you, I might recommend only adding for like a single project or a subset of samples, just so we can validate that everything looks right, but if everything is called together don't worry about it and just add everything

**Comment by bw2** [comment]
That's exciting! I will try it out on one project and let you know.

**Comment by bw2** [comment]
Just tried loading some data and it worked well!
<img width="881" alt="image" src="https://github.com/broadinstitute/seqr/assets/6240170/33ae7b9c-4c84-435a-a788-d783ebd60834">
<img width="1336" alt="image" src="https://github.com/broadinstitute/seqr/assets/6240170/47db4f6e-439b-4d8a-aa8e-9cbdc75b0ab2">
gs://tgg-rnaseq/gagneur/fraser/fraser_v1_test_results_table_for_seqr.RGP_1760_3_M1_muscle.tsv
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F031753_rgp_1760/rnaseq_results/I0081040_rgp_1760_3
and search is working!

Thanks for building this! 
Will have some more feedback/comments next week.
