### ISSUE TITLE
Errors when submitting table to "External Analysis" form

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#3205]
https://seqr.broadinstitute.org/summary_data/external_analysis

<img width="876" alt="image" src="https://user-images.githubusercontent.com/6240170/217369239-b10cdc8d-0acb-4842-b58f-adcbd5e29d80.png">

**Comment by bw2** [comment]
Regenerating the file in the correct format and re-uploading avoided the error. This issue is to request a clearer error message if possible.

**Comment by bw2** [comment]
Also, submitting the file with 20,000 rows results in a 504 after ~30 seconds:
<img width="810" alt="image" src="https://user-images.githubusercontent.com/6240170/217370619-27508cc5-75ef-4538-af60-20a4fa759f8e.png">

**Comment by hanars** [comment]
please provide an example of the file with the incorrect file format that generated the vague error

**Comment by bw2** [comment]
Even though the upload failed with a 504 error, the server processed some of the rows, leading to duplicated entries when I retried the upload (2 days ago and again today):
<img width="627" alt="image" src="https://user-images.githubusercontent.com/6240170/217930287-f1c9b806-0397-4f63-abd3-f34f46b6f9e6.png">

**Comment by bw2** [comment]
The table I'm trying to upload is in DMs on slack.

**Comment by hanars** [comment]
this is fixed for the future., it should be much faster now
