### ISSUE TITLE
OMIM info on gene page

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3222]
**Describe the bug**
OMIM box appearing on gene page and blocking other links

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0594_rare_genomes_project_gen/saved_variants/family/F040516_rgp_2333/Review

**Scope of the bug**
Across projects

**Screenshots**
<img width="1326" alt="Screen Shot 2023-02-16 at 10 11 30 AM" src="https://user-images.githubusercontent.com/37872186/219406254-323f4602-0727-404d-999f-d7282431169e.png">

**Comment by hanars** [comment]
moving your mouse should make it go away - does that not work for you?

**Comment by lynnpais** [comment]
Moving the mouse does not always make it go away. It comes back on the gene page. It also blocks the links behind it.

**Comment by hanars** [comment]
this is fixed
