### ISSUE TITLE
Variant search bug

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3225]
**Describe the bug**
Variants in the results list go missing when I choose to 'unpair' variants in an unrelated gene. In the example here, I ran a recessive permissive search. The results included compound heterozygous variants in COL6A6. There were also poor quality variants in MUC4, so I selected unpair to remove the pairs. This took away many other variants in other genes including COL6A6, HSPG2 and others. 

**Link to page(s) where bug is occurring**
Recessive permissive search results - https://seqr.broadinstitute.org/variant_search/results/8472467c924bca1f317ccdf92289cf65?page=1&sort=pathogenicity

Results after selecting unpair - https://seqr.broadinstitute.org/variant_search/results/8472467c924bca1f317ccdf92289cf65?page=1&sort=pathogenicity

**Scope of the bug**
Noticed it in RGP_1157 today. Not sure of other cases. 

**Screenshots**

**Comment by hanars** [comment]
This is now fixed
