### ISSUE TITLE
Ability to search for variants in a single gene 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3228]
**Is your feature request related to a problem? Please describe.**
We'd like to narrow down a variant search to a gene of interest. 

**Describe the solution you'd like**
Add a link to each gene prioritized by Lirical or Exomiser on the Family page to search for variants in that specific gene.

**Describe alternatives you've considered**
NA

**Additional context**
<img width="1061" alt="Screen Shot 2023-02-17 at 2 15 45 PM" src="https://user-images.githubusercontent.com/37872186/219766697-d6b0d55e-dad4-4fdc-b2de-7ba9081e72ec.png">

**Comment by hanars** [comment]
per-gene search has been added
