### ISSUE TITLE
Enable edit individuals access for external AnVIL users

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3229]
**Is your feature request related to a problem? Please describe.**
Give external users additional control over their data, and reduce time spent by internal team on requests. 

**Describe the solution you'd like**
Grant restricted permission to external AnVIL users to be able to edit: affected status, delete individuals, change sex, and relatedness in a family. They should be able to make changes on the individual level, not bulk level.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hanars** [comment]
I have added an "edit individual" button (and delete button) on the family page that will allow users to make these changes on a single-individual level
<img width="173" alt="Screen Shot 2023-03-10 at 4 41 25 PM" src="https://user-images.githubusercontent.com/24598672/224433812-140471ba-50dc-4968-baa7-789386e0df61.png">
