### ISSUE TITLE
Add data types on Project Page

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3230]
**Is your feature request related to a problem? Please describe.**
Improve ability to filter on cases

**Describe the solution you'd like**
Add gCNV/SV and RNASeq data as data types to filter on in the Data Loaded category on the Project Page. This will help analysts sort cases that have a new data type loaded in seqr. 

**Describe alternatives you've considered**
NA

**Additional context**
<img width="1295" alt="Screen Shot 2023-02-17 at 2 29 10 PM" src="https://user-images.githubusercontent.com/37872186/219769467-9b04beb6-b523-4ef7-8b01-d802e4d05186.png">

**Comment by hanars** [comment]
this has been added
