### ISSUE TITLE
RNA-seq outlier data file

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#3264]
Unable to load RNA-seq outlier data file:
gs://tgg-rnaseq/gagneur/outrider/results/latest_samples/fibroblasts__126_samples_7462C2E26C_without_GTEX__ods__q22_all_results.tsv

Getting this error:
<img width="804" alt="image" src="https://user-images.githubusercontent.com/6240170/222522265-a34581d3-c4d4-458a-a3d4-838c6476179e.png">

I'm still able to load this older data file with the same format though: 
gs://tgg-rnaseq/gagneur/outrider/results/latest_samples/whole_blood__110_samples_B25088DB1C_with_GTEX__ods__q20_all_results.tsv
So something about specific about the 1st file is causing an issue.

**Comment by hanars** [comment]
Associated cloud reporting error: https://console.cloud.google.com/errors/detail/CPrJ8vj1veD55AE;time=P30D?project=seqr-project&utm_source=error-reporting-notification&utm_medium=email&utm_content=new-error

**Comment by hanars** [comment]
This issue is fixed, although I get a readable "missing required column" error for that file now. Probably best to hold off on outlier loading until https://github.com/broadinstitute/seqr/issues/3265 can go live
