### ISSUE TITLE
RNA-seq outlier data - specify project at loading

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#3265]
Example: RGP_1770_3

I don't specify the project id in the upload. One solution might be to require a project column in RNA-seq outlier tables.

**Comment by hanars** [comment]
please provide a path to an example file path that includes the new project ID column

**Comment by hanars** [comment]
also, while we are updating the file format, would it be possible to add tissue type as well? Not worth it if its difficult, but if its straightforward it would probably be better

**Comment by bw2** [comment]
sure!  We should probably have these columns for each rnaseq file type. 
Here is an updated expression outlier table:
gs://tgg-rnaseq/gagneur/outrider/results/latest_samples/muscle__178_samples_4FCF578DDB_without_GTEX__ods__q38_all_results.tsv
It has "tissue" and "project" columns, and "sampleID" has been renamed to "sample_id" for consistency.
I will do the same thing for splice junction outliers.

**Comment by ShifaSZ** [comment]
That's great. I will probably update only the code for the TPMs for this ticket.

**Comment by hanars** [comment]
> That's great. I will probably update only the code for the TPMs for this ticket.

@ShifaSZ you are thinking of a different ticket, https://github.com/broadinstitute/seqr/issues/3266 this ticket is literally only for outlier data

**Comment by ShifaSZ** [comment]
After adding the `project` column, can its value be empty? When empty, do we load the data to all the projects with individual ids?

**Comment by hanars** [comment]
the project is required, we fail the file validation if it is missing

**Comment by ShifaSZ** [comment]
Okay. And we won't support loading two rows of data with an identical sample id but different projects in an input file.

**Comment by hanars** [comment]
> we won't support loading two rows of data with an identical sample id but different projects
We will support that, thats a very reasonable use case. Its why I've been pushing to make the sample lookup based on sample-project pairs instead of just a sample ID

**Comment by hanars** [comment]
> And we must pass sample-project pairs down to the _match_and_update_rna_samples and _find_or_create_missing_sample_records to create different samples with the same sample ids but belonging to different projects.

This is why I changed the code to make the logic for getting the lookup a generic function. For the cases where we have project IDs `get_individual_sample_lookup` will be keyed by Id-project tuples and `get_individual_sample_key` will return a tuple as well

> The assumption is that the sample data for different projects must be identical.

This is not true. There is no requirement that sample IDs are unique across project and therefore there might be different data associated with a duplicated sample ID.

**Comment by ShifaSZ** [comment]
We can solve the duplicated individual id issue with the `get_individual_sample_lookup` and `get_individual_sample_key` functions. But we still have issues if there are duplicated sample ids. Data with the same sample id will be stored with the same key in the `samples_by_id` and `samples_to_load`. The data for both projects will be loaded into a single sample model.
Besides that, the `_find_or_create_missing_sample_records` can only create one sample model for the duplicated individual because it creates the sample models base on the sample ids, not the sample-project pairs.

**Comment by ShifaSZ** [comment]
We maybe should use `get_individual_sample_key` to get keys for the `samples_by_id` and pass the keys into `_find_or_create_missing_sample_records`.

**Comment by ShifaSZ** [comment]
There are some new fields in the new Outlier data format. They are 'symbol', 'biotype', 'description', 'chr', 'start', 'end', 'strand', and 'q'. Should we re-use the `LocusList` and `LocusListInterval` models to store these new fields? Or should we add more fields to the Outlier model?

**Comment by hanars** [comment]
The only change you will make for this ticket is making sure we check the project when loading expression outlier (i.e. outrider) data. Any other change is out of scope and would require a different ticket it was something we would need to do

**Comment by hanars** [comment]
this has been updated
