### ISSUE TITLE
Load and display gene expression data when TPM=0

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#3267]
On this page
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/variant/SV0058379_1551404402_f027499_r

TPM data isn't showing correctly - possibly because the sample's gene expression value = 0:

<img width="602" alt="image" src="https://user-images.githubusercontent.com/6240170/222551591-f4f93ba7-c745-4e20-89aa-aa45dc4b5a4a.png">

I would expect it to still show a point for the sample + the TPM distributions for GTEx and RDG samples.

**Comment by hanars** [comment]
we cactually had no TPM data available for that gene. I have updated the UI to only show the "show expression" button for genes with available data

**Comment by bw2** [comment]
Based on testing this just now by loading
gs://tgg-rnaseq/seqr_data/RDG_and_GTEX_tpms_for_all_tissues__with_metadata_pivoted__20220503__latest_samples_for_seqr.tsv.gz
and looking at ENSG00000186417 for RGP_1017, I don't think the code distinguishes between "data missing" and TPM=0
I think it's still worth showing gene expression plots for genes with TPM=0 so people can see expression in GTEx and other samples.

**Comment by hanars** [comment]
The code for determining whether or not TPM data is loaded does  correctly handles this case. We may not load data where TPM=0, but that would be a separate feature request

**Comment by hanars** [comment]
please submit new issues for new feature requests, reopening closed issues makes it impossible for our team to track our work
