### ISSUE TITLE
Hover over blocking Family ID

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3271]
**Describe the bug**
In certain cases, the hover over is blocking Family ID. This makes it hard get access the Family Page. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/variant/17-10537410-CT-C/family/F028107_rgp_1067

**Scope of the bug**
Across seqr

**Screenshots**
<img width="1396" alt="Screen Shot 2023-03-06 at 2 31 54 PM" src="https://user-images.githubusercontent.com/37872186/223211963-14e7a17d-5276-4896-af52-5d826eb76bd4.png">

**Comment by hanars** [comment]
this is fixed
