### ISSUE TITLE
Custom search timing out

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3277]
**Describe the bug**
Custom search is timing out despite running again after ~5-6minutes. When we last discussed this, you mentioned adding filters is helpful and waiting a few minutes and trying again. Any other suggestions? This is somewhat high priority as we've been requested by the Baylor team to look for recessive variants in COG3. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/report/custom_search/18279188e2220375b1d59c570dc46956?page=1&sort=in_omim

**Scope of the bug**
NA

**Screenshots**
<img width="1288" alt="Screen Shot 2023-03-08 at 10 51 08 AM" src="https://user-images.githubusercontent.com/37872186/223762131-b2afcf11-793a-47b2-9a5f-b17d2b8d6e47.png">

**Comment by hanars** [comment]
Removing the quality filters makes it run faster and for me that search completed on the first try. There are only 56 results so I think manually filtering for quality is fine in this case: https://seqr.broadinstitute.org/report/custom_search/0ceab0ad37c54f9cf8796f7de03ee9a9?page=1&sort=xpos
