### ISSUE TITLE
"Has Notes" counts total number of notes rather than number of variants with notes

### ISSUE THREAD

**Issue by wwgordon** [broadinstitute/seqr#3278]
Describe the bug
The "has notes" tag appears to be counting the number of total notes, rather than the number of variants with notes. In the screenshot below, only one variant has notes, but this single variant has 5 notes.

Scope of the bug
Across seqr

Screenshots
![image](https://user-images.githubusercontent.com/6362516/224136005-b9468708-50ae-4f03-823d-a43fc23198ec.png)

**Comment by hanars** [comment]
this is fixed in the latest seqr release
