### ISSUE TITLE
Interface for updating IGV track file paths (ranseq, read data and other tracks) by uploading a single cross-project table 

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#3279]
Proposed table columns: `project`,  `sample_id`, ~`track_type`~, `path`

where track type could be drawn from existing seqr DB choices, or be some new set like:
"DNA reads"
"RNA splice junctions"
"RNA coverage"  
"RNA reads" ? 
"DNA Variants" ? 

I'm not sure if seqr currently supports the track types with '?' next to them. 

An IGV splice junction track requires 2 paths (splice junctions bed file, coverage wig file). These could be specified in one row (by adding a 'path2' column, or as separate rows).

Hypothetically, a DNA single-sample VCF would be a useful track type to show for RNA (and other) analyses since it makes it easy to see which variants are near splice junctions. We already generate the single sample VCFs anyway when running LIRICAL/Exomiser, so it would just be a matter of adding their paths to seqr.

Also, for RNA data paths, would it be useful to include a 'tissue' column?

**Comment by hanars** [comment]
We will maintain current behavior for loading RNA IGV data, except we will add the project column to prevent ambiguity. So the columns will be `project`, `individual id`, and `file path`. seqr automatically detects the track type based on the file extension, and if there is more than one available track type there needs to be a separate row in the uploaded file with the exact file path for that track type. So for example, have one row with a path ending in `junctions.bed.gz` and another row with the path ending in `.bigWig` for the same sample and seqr will correctly load and display these as a merged track. seqr will not accept ? or other wildcads in track paths. Adding tissue type to IGV is out of scope

**Comment by hanars** [comment]
> a DNA single-sample VCF would be a useful track type to show for RNA (and other) analyses since it makes it easy to see which variants are near splice junctions.

I am not sure what this is. If you mean showing the BAM/CRAM track regularly in IGV, thats already supported. If you mean some other sort of track, then thats not currently supported in seqr and would require a separate feature request

**Comment by bw2** [comment]
This issue is ment to be for implementing the upload interface. 
After discussing this at the RNA-seq meeting, we agreed it would be useful to show for RNA-seq splice junction analysis (but probably for other IGV.js use-cases as well). 

IGV.js already supports a single sample VCF track type. 
From seqr's point of view it should work no differently than a bam track - it's a single file path ("gs://bucket/file.vcf.gz").

This is how IGV displays it (the middle track here):
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/6240170/225743883-56fda256-5877-4bca-ba0b-f1180765687a.png">

**Comment by hanars** [comment]
these are 2 different feature requests. One is "make an entirely new UI for a different person to be able to add IGV tracks to multiple projects". Another is "Support displaying a new track type in IGV"

For this ticket, I will build a new UI that will support all existing track types, in the existing upload format. If we want to support new track types, that needs a separate ticket

**Comment by bw2** [comment]
Rereading this ticket, do I understand correctly that the current plan is to implement a loading interface for IGV.js tracks that supports loading a single table with data file paths for all seqr projects that have RNA-seq data?

**Comment by hanars** [comment]
There is now a bulk update view for IGV. Files must conform to the same format as for the project-specific view, with an extra column for the project name.https://seqr.broadinstitute.org/data_management/add_igv
