### ISSUE TITLE
Update information for pedigree for AnVIL data loading

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3284]
**Is your feature request related to a problem? Please describe.**
When uploading a pedigree, users may leave column F blank which is associated with unknown status.  

**Describe the solution you'd like**
To limit errors, users should be directed to enter one of three, affected, unaffected or unknown, but not leave column F blank. 

**Describe alternatives you've considered**
NA

**Additional context**
As discussed on Slack.

**Comment by hanars** [comment]
we should also make this change for sex

**Comment by lynnpais** [comment]
In the description, note that there are consequences to selecting 'Uknown'

**Comment by hanars** [comment]
this has been implemented
