### ISSUE TITLE
Load gene expression (TPM) for genes when TPM=0 

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#3285]
TPM data isn't showing when the sample's gene expression value = 0.

Based on testing this by loading
gs://tgg-rnaseq/seqr_data/RDG_and_GTEX_tpms_for_all_tissues__with_metadata_pivoted__20220503__latest_samples_for_seqr.tsv.gz
and looking at ENSG00000186417 for RGP_1017

**Comment by hanars** [comment]
we made an explicit decision during our initial implementation that we did not want to load data with 0 expression, so this change is a feature request not a bug.

**Comment by ShifaSZ** [comment]
@bw2 There are mismatched rows(same gene id but different data) in the test data file you provided above. Do you have updated data for testing?
![image](https://github.com/broadinstitute/seqr/assets/33550059/4f985945-b186-4105-943f-780f79753c59)

**Comment by hanars** [comment]
This behavior has been changed, so any future loading for TPM data will keep the 0 values
