### ISSUE TITLE
Add MT clinvar version to seqr UI

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/seqr#3293]
The [clinvar version](https://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh38/) is now annotated on project indicies in ES. Adding the version, which is a release date, in someway to a seqr project will inform analysts of a project's clinvar annotation version which could help clarify discrepancies between the project data annotation and the clinvar site. 

```
{
  "r0652_pipeline_test__wgs__grch38__variants__v02__vcfv00__20230324" : {
    "aliases" : { },
    "mappings" : {
      "_meta" : {
        "hail_version" : "0.2.109",
        "genomeVersion" : "38",
        "clinvar_version" : "2023-03-05",
        "sampleType" : "WGS",
        "datasetType" : "VARIANTS",
        "sourceFilePath" : "gs://seqr-datasets/test_and_demo_datasets/R0652_pipeline_test.vcf.bgz"
      },...
```

**Comment by hanars** [comment]
The code for this has been added. After our next clinvar update this will be made available as projects are reloaded
