### ISSUE TITLE
Custom search timing out 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3295]
**Describe the bug**
Custom search 504 error. I did try a few times, waiting 2-3 minutes in between. In [https://github.com/broadinstitute/seqr/issues/3277](url) you mentioned removing quality filters, but that does not help. Unable to sort by position before running a search. Any suggestions? I'm looking for recessive variants in SH3D19.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/report/custom_search/0978937e31cfc10b3d18ddaaacc4c7c8?page=1&sort=in_omim

**Scope of the bug**
NA

**Screenshots**
NA

**Comment by hanars** [comment]
completed sorted by position: https://seqr.broadinstitute.org/report/custom_search/0978937e31cfc10b3d18ddaaacc4c7c8?page=1&sort=xpos

you can change the sort by doing any other successful search, changing the sort on that, and then going to a new tab and running your search there. if you wanted you could also put in a feature request for being able to change the sort on failed searches
