### ISSUE TITLE
Search/ summary page based on HPO terms

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3296]
**Is your feature request related to a problem? Please describe.**
For the MVP, we would like to use HPO IDs (currently shown on the Family Page) as a search parameter and also pull stats based on these IDs.

**Describe the solution you'd like**
1. As a search variable:
~Be able to create analysis groups/ search for variants across Families that share one or more (OR logic) HPO terms entered by the user.~

2. For stats:
Show HPO terms on ~the Saved Variants~ a summary data page and the corresponding Family IDs as we do for genes in submitted to MME. 

**Describe alternatives you've considered**
Open to suggestions. Once this is implemented, we might have other suggestions. 

**Additional context**
Discussed in the last sprint planning meeting.

**Comment by lynnpais** [comment]
Based on our meeting today-

On summary page, have the ability to search for HPO terms (OR logic) which will return all cases with those terms. Include variant search ability all these cases. Include the number of families and individuals with the HPO terms individually.

**Comment by hanars** [comment]
Will implement https://github.com/broadinstitute/seqr/issues/822

**Comment by hanars** [comment]
This is now availalbe
