### ISSUE TITLE
Request to add callset AF to downloaded search results

### ISSUE THREAD

**Issue by melnel000** [broadinstitute/seqr#3300]
**Is your feature request related to a problem? Please describe.**
I would like to prioritize my downloaded search results by the callset AF.

**Describe the solution you'd like**
Please can you add callset AF as a field in the downloaded search results.

**Describe alternatives you've considered**
I have not considered alternatives.

**Additional context**
<img width="651" alt="Screen Shot 2023-03-27 at 10 50 16 PM" src="https://user-images.githubusercontent.com/9977227/228063559-20c3e149-7f0a-4f95-a842-9af0549d3cf2.png">

**Comment by hanars** [comment]
this has been added to the download
