### ISSUE TITLE
RNAseq Splice Junction Outliers data model and loading

### ISSUE THREAD

**Issue by ShifaSZ** [broadinstitute/seqr#3311]
This task is a part of the Splice Junction Outliers feature request epic. The works in the task include the following.
- Add a new data model for the Splice Junction Outlier datasets
- Add a loading UI and load Splice Junction Outlier datasets

**Comment by ShifaSZ** [comment]
Do we also need to provide a management command to load the splice junction data? If yes, I will create a separate PR for that.

**Comment by hanars** [comment]
no lets just use the UI
