### ISSUE TITLE
Odd search results

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3318]
**Describe the bug**
- Missing c. information for certain variants (here, PCARE missense) in the search results when using the saved recessive SV search. 
- For the PCARE variant, unable to select 'missense variant' which shows the other transcripts the variants falls in. 
   These issues are in the search results only, and look fine on the saved variants page.
- Also, the saved recessive SV search seems to only have SNVs/ Indels in the results.  

**Link to page(s) where bug is occurring**
Recessive SV results -
https://seqr.broadinstitute.org/variant_search/results/d8f98d563b866d36c29b6488a04f1e51?page=1&sort=in_omim

Search page - https://seqr.broadinstitute.org/variant_search/family/F031020_rgp_1525

**Scope of the bug**
Likely in other cases too

**Screenshots**

<img width="1272" alt="Screen Shot 2023-04-10 at 1 30 40 PM" src="https://user-images.githubusercontent.com/37872186/230958633-26ac629a-6761-4a3e-9385-04bb4706247f.png">

**Comment by hanars** [comment]
this is now fixed
