### ISSUE TITLE
Ability to use multiple tags on saved variants page

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3320]
**Is your feature request related to a problem? Please describe.**
Need a way to select AIP tag + [other] tag(s) on the saved variants page. 

**Describe the solution you'd like**
We would like to be able to filter through saved variants with more than one tag. This is primarily for AIP results, but can be useful in other scenarios. Currently, the dropdown on the saved variants page allows you to choose only one tag. It would be useful to be able to select more than one from the dropdown. 

**Describe alternatives you've considered**
NA

**Additional context**
Discussed with Chrissy and in our sprint planning meeting.

**Comment by hanars** [comment]
Ticket refers to the saved variant summary page: https://seqr.broadinstitute.org/summary_data/saved_variants

The behavior will be an AND not an OR (i.e. variants will only be displayed if they have all the selected tags)

**Comment by ShifaSZ** [comment]
> Ticket refers to the saved variant summary page

Can we also change the project saved-variant behaviors to allow multiple tags? This is because both the summary page and project saved-variant share the same React component.

**Comment by hanars** [comment]
Sure

**Comment by stephditroia** [comment]
Not sure of the appropriate place to mention this, but the use case described in the related ticket [https://github.com/broadinstitute/seqr/issues/3514] would require OR behavior since discovery tags are mutually exclusive.

**Comment by hanars** [comment]
Ah, in that case thats out of scope for this ticket

**Comment by hanars** [comment]
> > Ticket refers to the saved variant summary page
> 
> Can we also change the project saved-variant behaviors to allow multiple tags? This is because both the summary page and project saved-variant share the same React component.

This has gotten way too complicated to get the behavior for category filters right, and is blowing up the scope of this work for a change that was not originally requested. I am changing my response to this - this change will only apply to the summary page, not the project page. We can just abstract out the dropdown one more level, so its no longer shared between the two pages

**Comment by ShifaSZ** [comment]
When downloading the saved variants filtered by multiple tags, the filename includes the tags separated by semicolons (`;`). Is it okay?
