### ISSUE TITLE
Show "RNA splice" tags on search result variants

### ISSUE THREAD

**Issue by ShifaSZ** [broadinstitute/seqr#3324]
Show "RNA splice" tags on search result variants that overlap an outlier splice junction +/- 200bp

- hover over the tag should show info about the splice junction outlier (chrom/start/end/strand, z-score, p-value, maybe tissue and read count also)

- variant search results:

- OUTRIDER tag should be changed to: "RNA expression"
- double-check that splice junction outlier tags will work for SVs (needs interval intersection to work)

**Comment by hanars** [comment]
this ticket is about showing a tag on the search results page and your comment is about the outlier table on the RNA page, so I do not think the question belongs on this issue. However, on the RNA page, IGV should show between the volcano plots and the table

**Comment by ShifaSZ** [comment]
I mean the outlier table in the hover over as the figure below.
![image](https://user-images.githubusercontent.com/33550059/236555726-1675eb5f-81f3-490d-8f04-170ad7b6123e.png)

**Comment by ShifaSZ** [comment]
We could show the IGV by clicking the tag or the outlier row. But the outlier row is more precise. We can get the locus of the splice junction outlier for the IGV.
