### ISSUE TITLE
SV only search returning SNVs/ Indels

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3326]
**Describe the bug**
The saved recessive SV search seems to only have SNVs/ Indels in the results.

**Link to page(s) where bug is occurring**
Recessive SV results -
https://seqr.broadinstitute.org/variant_search/results/d8f98d563b866d36c29b6488a04f1e51?page=1&sort=in_omim

Search page - https://seqr.broadinstitute.org/variant_search/family/F031020_rgp_1525

**Scope of the bug**
Likely affecting SV only searches in other cases as well 

**Screenshots**
<img width="1274" alt="Screen Shot 2023-04-12 at 10 19 35 AM" src="https://user-images.githubusercontent.com/37872186/231486887-14638341-8e56-45f9-9c96-a0f5745de4ea.png">

**Comment by hanars** [comment]
This is realted to https://github.com/broadinstitute/seqr/issues/2725 and is actually discussed in the comments: https://github.com/broadinstitute/seqr/issues/2725#issuecomment-1306005033 . As stated there:
> you allow VUS/Conflicting in your pathogenicity filter, so the second hit in that pair is being returned because it matches that criteria. The clinvar override applies to both variants, not just the second hit
