### ISSUE TITLE
Clear project notes and tags for seqr workshops

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3331]
**Is your feature request related to a problem? Please describe.**
Prep for upcoming workshops

**Describe the solution you'd like**
Clear notes and tags for seqr workshops from GREGoR Training Projects B, C,D, E, F, G, H, and K. 
Needed by 05/02/23.  

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hanars** [comment]
these have been cleared
