### ISSUE TITLE
Upcode to Gencode v39

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3336]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when ... when I can't find the gene I am interested in / has a weird name like AC003001.1.

**Describe the solution you'd like**
Upcode to Gencode v39. This is what gnomAD is currently on. Also be able to search for the alternate gene names.
Would also be helpful if you could do a quick audit to see which genes would be impacted.

**Describe alternatives you've considered**
NA

**Additional context**
Discussed with you and Anne.

**Comment by hanars** [comment]
> Would also be helpful if you could do a quick audit to see which genes would be impacted.

I am happy to do an audit of a short specific list of genes (i.e specific RGP discoveries or the like), but doing a full diff report changes the scope of this work.

**Comment by lynnpais** [comment]
short specific list of genes (i.e specific RGP discoveries or the like) - this is fine

**Comment by hanars** [comment]
@lynnpais it was easier to generate a full list of all the changed gene names. Can you take a look and let me know if any of them are a problem? 
https://docs.google.com/spreadsheets/d/1n3-GSn7W7CRLh6tWuv_e7_VpcFO_muYj30JfnwOZro8/edit#gid=0

**Comment by lynnpais** [comment]
It's a very long list. I spot checked and it looked fine to me. In general,
I saw the updated gene names as opposed to the older ones.

Thanks.

**Comment by hanars** [comment]
> Also be able to search for the alternate gene names.

Is this required for this to go live? Or is this a "nice to have"? In general, "other gene names" shown in seqr come from dbnsfp, not previous versions of gencode, so while I would anticipate that many of these name changes would be reflected their, there may be some that are not. Changing to keep previous gencode version gene names would considerably blow up the scope of this work

**Comment by hanars** [comment]
I added another tab to spreadhseet of just changes to RGP discovery genes, there are only 5:
```
ADSSL1 | ADSS1
DIABLO | ENSG00000284934
MARCH5 | MARCHF5
NARS | NARS1
WARS | WARS1
```

**Comment by lynnpais** [comment]
Discussed with the analysts - good to proceed.

**Comment by hanars** [comment]
This has been updated
