### ISSUE TITLE
Co-occurrence information for biallelic variants

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3338]
**Is your feature request related to a problem? Please describe.**
It is hard for an analyst to discern if biallelic variants shown in a recessive search are in cis or trans when there is no parental data.

**Describe the solution you'd like**
Use gnomAD's co-occurrence tool which gives a probability of two variants being in cis or trans. On the variant page, display a link on the right hand side below the variant link that goes to gnomAD's co-occurrence page. Pre-fill the page with the 'Variant ID' for variant 1 and variant 2. Note: this currently works only if the variant is in gnomAD v2.  The feature can only shown if both variants are in gnomAD v2. 

Here's an example for the biallelic MTMR4 variants in RGP_1434- https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F032068_rgp_1434/Review
The variant IDs are 17-56572427-G-A and 17-56588818-T-C. 
The added link should take you to - https://gnomad.broadinstitute.org/variant-cooccurrence?dataset=gnomad_r2_1&variant=17-56572427-G-A&variant=17-56588818-T-C

**Describe alternatives you've considered**
NA

**Additional context**
Discussed in product meeting.

**Comment by hanars** [comment]
this has been added
