### ISSUE TITLE
SpliceAi look up link

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3340]
**Is your feature request related to a problem? Please describe.**
The analysts would like an easier way to look up potential splice effects predicted by SpliceAi. 

**Describe the solution you'd like**
Link out to spliceAI lookup https://spliceailookup.broadinstitute.org/ with auto-fill of variant and 1000bp padding 

**Describe alternatives you've considered**
NA

**Additional context**
SpliceAI seems to be part of VEP 104. We are planning to update to VEP 105 most likely. So let's hold off on this for a bit.

**Comment by lynnpais** [comment]
Example link with 1000bp padding default:
For this intronic variant in seqr, https://seqr.broadinstitute.org/project/R0594_rare_genomes_project_gen/saved_variants/variant/SV0140417_x32441421_f040915_rg, 
a link to the SpliceAi look up site would be - https://spliceailookup.broadinstitute.org/#variant=X-32441421-T-C&hg=38&distance=1000&mask=1 
<img width="1224" alt="Screenshot 2023-07-10 at 3 03 02 PM" src="https://github.com/broadinstitute/seqr/assets/37872186/940ae5c4-72c9-4948-b64a-642ae07f2547">

**Comment by hanars** [comment]
we can make either the "splice AI" text or the numeric value the link, whichever is easer

**Comment by ShifaSZ** [comment]
If I understand correctly, we can add a `SpliceAI` link to each variant following the links to `seqr`, `gnomAD`, `Decipher`, and `pubmed` as in the following picture.
![image](https://github.com/broadinstitute/seqr/assets/33550059/28e37cf9-b9dd-48d4-b171-508488bf3da7)

**Comment by hanars** [comment]
no the actual splice AI value shown in the Predictions section becomes a link

**Comment by ShifaSZ** [comment]
Okay, in the prediction section.

**Comment by ShifaSZ** [comment]
If we add the link to the value, we can add a hint `Click to open SpliceAI lookup page` in the hover message on the value. The UI looks like the figure below.
<img src="https://github.com/broadinstitute/seqr/assets/33550059/61076cdc-770b-47c6-9dd8-251b899882e1" width=350 height=100 />

**Comment by hanars** [comment]
No, if the value is a link, it should just be a link. It should be blue and open a new tab when clicked on and not have a hover, the way every other link on this page looks and behaves. Just use the standard html for a link

**Comment by ShifaSZ** [comment]
It has a bit of styling conflict with the value. We may have to provide a prop to the `PredictionValue`.

**Comment by hanars** [comment]
yes, in general when we change how something is displayed we need to make updates to their components. Passign the url or a function to generate the url would be a good way to conditionally render a link

**Comment by hanars** [comment]
this has been added to seqr
