### ISSUE TITLE
Saved Variants page doesn't load

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#3349]
This Saved Variants page doesn't load:
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/

and indefinitely shows a spinner. The console looks like:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/6240170/234404632-5f84cce4-8e88-47fd-9b76-924ee1e21dac.png">

**Comment by hanars** [comment]
this page is now working (although it is still slow)
