### ISSUE TITLE
Incorrect pedigree image

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3362]
**Describe the bug**
Parents marked as consanguineous but this was not the input. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F031594_rgp_1694

**Scope of the bug**
Case specific. 

**Screenshots**
<img width="711" alt="Screen Shot 2023-05-04 at 5 25 47 PM" src="https://user-images.githubusercontent.com/37872186/236321309-f247bf98-90b4-46ca-a145-a01d4ad34d69.png">

**Comment by hanars** [comment]
this is now fixed
