### ISSUE TITLE
Write Pedigree Browser Feature - write to alternate buckets

### ISSUE THREAD

**Issue by matren395** [broadinstitute/seqr#3363]
Problem: the new feature on the Seqr webpage to write a project pedigree is fantastic, BUT when I am working with callsets (incoming WGS v38) with multiple individual Seqr projects, having each of their pedigrees write to a separate bucket will be annoying to download and get them all together. 

Solution/Alternative: I would like it if there was a way to set which bucket the outgoing Pedigrees would write to, so I could write them all to some /v38_pedigrees/ bucket , so that then I can download them all at once from one place and send them to the PM team more easily. Alternatively, having them write to the project bucket (as they already are) AND downloading them locally with one click of a button could be appreciated. 

Other: This is a very cool tool - and much better than the old cookies approach !!! - but at the moment that approach would still likely be faster than having go deal with pedigrees in multiple different buckets.

**Comment by hanars** [comment]
So the way you are using these files is not what this feature is intended for - this feature was never intended to involve a human being interacting with these pedigree files after they have been written. Can you please explain the use case in which a human being needs to access these files directly? If at any point in the pipeline a pedigree file is needed for multiple projects, having the pipeline or airflow code read in multiple TSVs and aggregate them should be trivially easy to write, and is in fact how the original script involving cookies worked, as it had to iterate through each project to generate the pedigrees
