### ISSUE TITLE
Seqr: list of saved variants by previous analysts not working for me--Mugdha

### ISSUE THREAD

**Issue by MugdhaSingh1819** [broadinstitute/seqr#3375]
**Describe the bug**
I am trying to look at the saved variants, the link is not returning me the list of variants.
**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0497_cmg_muntoni_exomes/saved_variants/family/F026792_mun_fam12/Analyst%20high%20priority

**Scope of the bug**
No not all , but some . I discussed with Emily and Lynn on two separate cases and they were able to open the link but its was not opening for me.

**Screenshots**
![Screenshot 2023-05-16 at 2 21 20 PM](https://github.com/broadinstitute/seqr/assets/133809303/5e7b1fe1-bd94-4b7e-b65f-c54df44ebdff)

**Comment by hanars** [comment]
This seems like an issue with your browser. try clearing your local storage: https://help.disco.ac/articles/94975-how-to-clear-local-storage-in-your-browser

**Comment by hanars** [comment]
try clearing your cookies as well then

**Comment by MugdhaSingh1819** [comment]
Thank You very Much it worked!!
