### ISSUE TITLE
Make project page filter settings project-specific 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3379]
**Is your feature request related to a problem? Please describe.**
Cases appear to be hidden in non-RGP projects as I always have the Assigned to me filter for the RGP project. The filters we use in the RGP project are typically not used in other projects. 

**Describe the solution you'd like**
Have case filters set for a project saved for that project only, and not across other projects. This will allow a user to have project specific filters. 

**Describe alternatives you've considered**
NA

**Additional context**
Previously discussed.

**Comment by hanars** [comment]
Implement by changing the `familyTableFilterState` state to be nested by project and have a distinct per-project state

**Comment by ShifaSZ** [comment]
> Implement by changing the `familyTableFilterState` state to be nested by project and have a distinct per-project state

Do we add a category for each project?

**Comment by hanars** [comment]
> > Implement by changing the `familyTableFilterState` state to be nested by project and have a distinct per-project state
> 
> Do we add a category for each project? Or add a second-level filter?

I do not know what you mean by category. Currently  `familyTableFilterState` looks like `{analysedBy: [], analysisStatus: [], firstSample: [], savedVariants: []}`. After this PR, it will look like
```
{
  R0123_project_guid_1: {analysedBy: [], analysisStatus: [], firstSample: [], savedVariants: []},
  R0789_project_guid_2: {analysedBy: [], analysisStatus: [], firstSample: [], savedVariants: []},
  ...
}
```

We should not like proactively go in and create an entry for each project, projects will be added at the time they are first accessed

**Comment by ShifaSZ** [comment]
I see. It is about the family filtering, not the project.

**Comment by hanars** [comment]
These are filters for the family table on the project page. They persist across sessions, so whatever filters you apply will be applied on any other project page you go to. We are changing that behavior so the filters you apply on one project page do not apply on another project page, but if you later come back to the same project page your filters will persist

**Comment by hanars** [comment]
this has been implemented
