### ISSUE TITLE
Family ID hover over

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3380]
**Describe the bug**
Several of the analysts are no longer seeing the case details when you hover over the Family ID.

**Link to page(s) where bug is occurring**
Here's on example - https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F027463_rgp_859/Review

**Scope of the bug**
Likely multi project

**Screenshots**
![Screen Shot 2023-05-17 at 12 03 18 PM](https://github.com/broadinstitute/seqr/assets/37872186/d324cfa2-bebf-49c6-a5e4-341badc7d93c)

**Comment by hanars** [comment]
this is fixed now
