### ISSUE TITLE
HPO terms variant search bug

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3385]
**Describe the bug**
Variant search on HPO terms page not working.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/summary_data/hpo_terms

**Scope of the bug**
NA

**Screenshots**
<img width="358" alt="Screen Shot 2023-05-18 at 2 58 41 PM" src="https://github.com/broadinstitute/seqr/assets/37872186/ff2874ba-c2fa-4d75-85c1-9dc6eb692a67">

**Comment by hanars** [comment]
triggered by search term "ataxia"

**Comment by hanars** [comment]
this is fixed now
