### ISSUE TITLE
CMG_Walsh_Exomes_ID IGV down

### ISSUE THREAD

**Issue by Jenniferneil** [broadinstitute/seqr#3391]
Hello, 
the IGV for our "CMG_Walsh_Exomes_ID" cohort has not been working for quite some time.   a small pop-up box says "Not found" and the IGV says Error loading track data.  This is for all cases in this cohort.  thanks for your hep. 
~ Jen

**Comment by hanars** [comment]
Please reach out directly  to your project manager to resolve this issue
