### ISSUE TITLE
8 high severity vulnerabilities while running npm i

### ISSUE THREAD

**Issue by kf-cuanschutz** [broadinstitute/seqr#3395]
**Describe the bug**
Hi I installed redis, google-ci and npm. NPM was installated through conda with `conda install nodejs -c conda-forge --repodata-fn=repodata.json`

While running npm i I got the following error :

```
up to date, audited 1946 packages in 3s

18 packages are looking for funding
  run `npm fund` for details

# npm audit report

d3-color  <3.1.0
Severity: high
d3-color vulnerable to ReDoS - https://github.com/advisories/GHSA-36jr-mh4h-2g58
fix available via `npm audit fix --force`
Will install d3-scale@4.0.2, which is a breaking change
node_modules/d3-color
  d3  4.0.0-alpha.1 - 6.7.0
  Depends on vulnerable versions of d3-color
  node_modules/d3
  d3-interpolate  0.1.3 - 2.0.1
  Depends on vulnerable versions of d3-color
  node_modules/d3-interpolate
    d3-brush  0.1.0 - 2.1.0
    Depends on vulnerable versions of d3-interpolate
    node_modules/d3-brush
    d3-scale  0.1.5 - 3.3.0
    Depends on vulnerable versions of d3-interpolate
    node_modules/d3-scale
    d3-scale-chromatic  0.1.0 - 2.0.0
    Depends on vulnerable versions of d3-color
    Depends on vulnerable versions of d3-interpolate
    node_modules/d3-scale-chromatic
    d3-transition  0.0.7 - 2.0.0
    Depends on vulnerable versions of d3-color
    Depends on vulnerable versions of d3-interpolate
    node_modules/d3-transition
    d3-zoom  0.0.2 - 2.0.0
    Depends on vulnerable versions of d3-interpolate
    node_modules/d3-zoom

8 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix
```

Any hint on how to fix this?

My node-js version is  16.10.0 
My redis-cli version is 7.0.11
My gcloud versions are as follows:
Google Cloud SDK 428.0.0
bq 2.0.91
bundled-python3-unix 3.9.16
core 2023.04.25
gcloud-crc32c 1.0.0
gsutil 5.23

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/...

**Scope of the bug**
Issue occured when running npm i

**Screenshots**

**Comment by hanars** [comment]
These are all issues that the seqr team has evaluated and  have risk acceptance for. These errors should not prevent seqr from running normally. If you want to update seqr to work with different versions of these packages, please feel free to make the necessary code changes and submit a pull request

**Comment by kf-cuanschutz** [comment]
Thank you very much on the update! We'll thus start using the package.
