### ISSUE TITLE
Odd gene notes

### ISSUE THREAD

**Issue by ksoca** [broadinstitute/seqr#3396]
**Is your feature request related to a problem? Please describe.**
I found a note that I think needs to be removed.  I found it during my search for a causative variant in a trio. 

**Describe the solution you'd like**
Removal of a shared note from a gene card. 

**Describe alternatives you've considered**
a follow-up note to dismiss an erroneous note.

**Additional context**
This was found during a case analysis. Perhaps other notes were left behind by this particular user. 

Add any other context, links to relevant seqr pages, or screenshots about the feature request here.
The message that was found: as dkaj sdas dkjahdkjahdkjsahdkjahdkajs hdkajhdkjah ds - By Geeky VT (11/19/2021)
The link to the gene card where this was found: https://seqr.broadinstitute.org/variant_search/variant/22-28679723-T-G/family/F043632_beg_1476

**Comment by hanars** [comment]
Thanks for reporting! This has been removed
