### ISSUE TITLE
Unable to load IGV

### ISSUE THREAD

**Issue by apham98** [broadinstitute/seqr#3398]
**Describe the bug**
I'm receiving the following error when uploading the IGV file paths "Cannot read properties of undefined (reading 'individualId')"

**Link to page(s) where bug is occurring**
I had this issue for the following projects so far:
https://seqr.broadinstitute.org/project/R0682_gregor_beggs_wgs/project_page
https://seqr.broadinstitute.org/project/R0684_gregor_ogrady_wgs/project_page

**Scope of the bug**
I've had this issue for two separate projects so far.

**Screenshots**
Attaching screenshot and file I tried to upload (also tried uploading tsv version)
![Screen Shot 2023-05-24 at 1 02 29 PM](https://github.com/broadinstitute/seqr/assets/108075186/717d409a-e78f-46b3-852b-ef54de511469)
[sample (11).xlsx](https://github.com/broadinstitute/seqr/files/11557296/sample.11.xlsx)

**Comment by hanars** [comment]
The seqr service account does not have access to these crams, which is what is causing this error. Either these crams are not in a bucket seqr has access to, or theres a typo in the file path. I will keep this ticket open because this should have a better error message in that case

**Comment by apham98** [comment]
I was able to get access for the seqr service account and that fixed it. Thanks for your help!

**Comment by hanars** [comment]
this has been changed to give a better error message in the future
