### ISSUE TITLE
Update SV GQ display

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3403]
**Is your feature request related to a problem? Please describe.**
Accurate display of SV variant GQ is needed. 

**Describe the solution you'd like**
Show actual GQ rather than -- when GQ is 0.

**Describe alternatives you've considered**
NA

**Additional context**
Per team discussion.

**Comment by lynnpais** [comment]
#https://github.com/broadinstitute/seqr-loading-pipelines/issues/490

**Comment by hanars** [comment]
This is fixed. In the future, please provide links to examples of the issue
