### ISSUE TITLE
Flag outliers

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3405]
**Is your feature request related to a problem? Please describe.**
Need a way to identify variants in cases with large number of outliers. Flagged samples/ outlier info is displayed on the Family Page.

**Describe the solution you'd like**
- For SVs, show a SV quality flag in the variant view
- For SNVs, display this flag in the hover over only
-
**Describe alternatives you've considered**
NA

**Additional context**
Per Thursday's team discussion.

Does this need a pipeline ticket?

**Comment by hanars** [comment]
This has been added
