### ISSUE TITLE
Searches in Recessive Permissive| X-Linked Recessive showing error in GREGoR_Beggs_WGS cohort samples_BEG_1631

### ISSUE THREAD

**Issue by MugdhaSingh1819** [broadinstitute/seqr#3406]
**Describe the bug**
While searching for variants that come under Recessive permissive searches and are X-linked recessive I get following error
RequestError: 400 - 'search_phase_execution_exception' - query_shard_exception. These error are not in other cohorts e.g. Sherr cohort but only in recently uploaded  GREGoR_Beggs_WGS cohort. I checked for BEG_1631 and BEG_1476. Checked with other analysts as well.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/83295150cb42e72157a42bdfb71b49a8?page=1&sort=protein_consequence

**Scope of the bug**
Within one GREGoR_Beggs_WGS  only (https://seqr.broadinstitute.org/project/R0682_gregor_beggs_wgs/project_page)

**Screenshots**

![Screenshot 2023-05-26 at 1 06 04 PM](https://github.com/broadinstitute/seqr/assets/133809303/69d8d24e-f3cc-42ad-b0dc-2b49abf1c2f6)

**Comment by hanars** [comment]
X-linked recessive search is currently broken on new projects, however doing a full "recessive" search, sorting by position, and looking at the bottom of results in the X chromosome, will include all the X-linked variants, as a workaround while this is being fixed: 
https://seqr.broadinstitute.org/variant_search/results/0af16510f0dbfbd26861ee669a92707f?page=1&sort=xpos

**Comment by hanars** [comment]
this is fixed now
