### ISSUE TITLE
Add FAQ link to seqr

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3412]
**Is your feature request related to a problem? Please describe.**
We get several questions from users which can be handled better by directing them to the FAQ section. 

**Describe the solution you'd like**
Add a link that reads, 'FAQ', to the bottom of the seqr website. Content for this page is here - https://docs.google.com/document/d/1Es00XkBCCMk2gGBaK1yT4z8Qd6p7kY3Wb4cOPPiJm2M/edit?usp=sharing

**Describe alternatives you've considered**
NA

**Additional context**
Discussed previously.

**Comment by hanars** [comment]
I'd also like to add this more prominently on the landing page for seqr as well - in the `About  seqr` and `seqr  is available through three methods:` sections I think it would make sense to link to the FAQ

**Comment by hanars** [comment]
FAQ page has been added, there is a link in the page footer: https://seqr.broadinstitute.org/faq
