### ISSUE TITLE
Set SV GQ to 10 in saved searches for affected individuals

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3429]
**Is your feature request related to a problem? Please describe.**
Too many poor quality SVs are being returned in a search. 

**Describe the solution you'd like**
Update saved searches to have a min GQ of 10 and for affected individuals only. The update will apply to the following saved searches: de novo/dominant restrictive and permissive, recessive restrictive and permissive, and the SV only searches for proband/duo and trios. 

Hoping this can be done within a few days of loading the new SV data available for the CMG cohorts. Will communicate separately about loading the SV data.

**Describe alternatives you've considered**
NA

**Additional context**
Reviewed with Anne and analysts

**Comment by hanars** [comment]
The "affected individuals only" setting is all-or-nothing for quality filters. So this would also impact the behavior for SNPs/Indels for GQ and AB filters. Is that okay? Do we want to adjust those filters accordingly?

Also, the protocol for me updating saved searches is that someone needs to save what they want the new search to be, and then you tell me the name of the new search you created and which saved search you want it to replace. So in this case you would make 6 new saved searches by applying teach of the original searches you want, tweaking the filters for the new behavior, and then saving it. Then you would make this ticket with the list of searches you saved and what they map to (i.e. Lynn's "De-Novo/Dominant Permissive new" should replace "De-Novo/Dominant Permissive"

**Comment by lynnpais** [comment]
Yes, the affected individuals only feature should be applied to all variants and GQ and AB filters. 

The new searches have been saved in seqr with " - New" at the end of it - 
"De novo/ Dominant Restrictive - New" to replace De novo/ Dominant Restrictive
"De novo/ Dominant Permissive - New" to replace De novo/ Dominant Permissive
"Recessive Restrictive - New" to replace Recessive Restrictive
"Recessive Permissive - New" to replace Recessive Permissive

Once replaced, please edit the name of the search to not include "- New" at the end

**Comment by hanars** [comment]
To clarify, are you adjusting the GQ/AB filters in these searches as well? I do not think it is a good idea to change the default searches to "affected only" but leave the thresholds the same, I think it is going to result in a lot of junky variants. The feature is intended to be paired with stricter quality filters. Before taking these new searches live, can you confirm you have tested all of them across a variety of projects and families that the results are still meaningful?

**Comment by lynnpais** [comment]
This actually returned a ton of junk as you predicted. Closing this ticket for now.

When Hail migration is complete, we can think about changing the bucket ranges for GQ and adjust saved searches then.
