### ISSUE TITLE
Airtable GREGoR data model tab column changes

### ISSUE THREAD

**Issue by apham98** [broadinstitute/seqr#3430]
**Is your feature request related to a problem? Please describe.**
The column names of the [GREGoR data model tab](https://airtable.com/app3Y97xtbbaOopVR/tblku4fYy6NgLByM0/viwW0oo8JF362uXic?blocks=hide) in Airtable have been updated to have separate columns for WES, WGS, and RNA so that all individuals are only on one line. The updated DNA column names are below in the following format:

"Old column name" --> "updated column name"
- New column: "name of new column that has been added to the table"

The updated columns are listed below:

CollaboratorSampleID --> CollaboratorSampleID_wes 
- New columns: CollaboratorSampleID_wgs, CollaboratorSampleID_rna

 
seq_library_prep_kit_method --> seq_library_prep_kit_method_wes
- New column: seq_library_prep_kit_method_wgs

 
read_length --> read_length_wes
- New column: read_length_wgs

 
experiment_type --> experiment_type_wes
- New column: experiment_type_wgs

 
targeted_regions_method --> targeted_regions_method_wes
 
date_data_generation --> date_data_generation_wes
- New column: date_data_generation_wgs

 
target_insert_size --> target_insert_size_wes
- New column: target_insert_size_wgs

 
sequencing_platform --> sequencing_platform_wes
- New column: sequencing_platform_wgs

 
aligned_dna_short_read_file --> aligned_dna_short_read_file_wes
- New column: aligned_dna_short_read_file_wgs

 
aligned_dna_short_read_index_file --> aligned_dna_short_read_index_file_wes
- New column: aligned_dna_short_read_index_file_wgs
 

md5sum --> md5sum_wes
- New column: md5sum_wgs

 
alignment_software --> alignment_software_dna
 
mean_coverage --> mean_coverage_wes
- New column: mean_coverage_wgs 

**Additionally, new RNA columns have been added to Airtable. I'm attaching an excel sheet with the GREGoR data model column name as well as the column name in Airtable/relevant formatting notes below. There is one tab in the excel sheet for the "experiment_rna_short_read" table and one tab for the "aligned_rna_short_read" table but all of the Airtable columns are in the "GREGoR Data Model" tab in Airtable**

[RNA Columns GREGoR Data Model Airtable.xlsx](https://github.com/broadinstitute/seqr/files/11692113/RNA.Columns.GREGoR.Data.Model.Airtable.xlsx)

**Comment by hanars** [comment]
The SMID field in this table is now blank - this is required for all rows and until it is properly repopulated I can not proceed with these updates

**Comment by hanars** [comment]
Decided to hold off on this due to some last minute changes to the data model that can not be integrated before the next round of reporting is due. Will revisit the conversation about how to handle data in the next round of reporting, and will create new ticket(s) accordingly

Created this branch with the changes, which may or may not be usefiul for future development
https://github.com/broadinstitute/seqr/compare/dev...gregor-rna-tables?expand=1
