### ISSUE TITLE
Fix GQ typo in hover over on search page 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3432]
Change "SV-QG" to "SV-GQ" on third line of the hover text for GQ (under Call Quality) on the search page 

<img width="279" alt="Screen Shot 2023-06-12 at 11 38 10 AM" src="https://github.com/broadinstitute/seqr/assets/37872186/b17bd03b-824d-435d-8ee3-c402a596a90c">

**Comment by hanars** [comment]
fixed
