### ISSUE TITLE
Do not open new tab when selecting the family ID

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3441]
**Is your feature request related to a problem? Please describe.**
There was a recent change where clicking on the family ID on the saved variants page opens a new tab. Analysts are not fond of it. 

**Describe the solution you'd like**
Clicking on the Family ID should take you to the Family page in the same tab. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hanars** [comment]
this has been changed back
