### ISSUE TITLE
Add a link to go to the saved variants page on the search page

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3442]
**Is your feature request related to a problem? Please describe.**
It takes quite a few clicks to the variants you have tagged after running a search. 

**Describe the solution you'd like**
It would be very useful to have a link saying something like, Go to Saved Variants, on the bottom of the search page. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hanars** [comment]
Clicking on the family id on the variant takes you to the saved variant page, so thats only one click
