### ISSUE TITLE
Broken link to search families with specific HPO term

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3443]
**Describe the bug**
Broken link to search families with specific HPO term 

**Link to page(s) where bug is occurring**
Page with link - https://seqr.broadinstitute.org/summary_data/hpo_terms

After selecting "Variant Search - 599 Families" I get the error - his site can’t be reachedseqr.broadinstitute.org unexpectedly closed the connection. Pasting the link at the end as it's large. 

**Scope of the bug**
NA

**Screenshots**

<img width="1300" alt="Screen Shot 2023-06-15 at 10 49 08 AM" src="https://github.com/broadinstitute/seqr/assets/37872186/3caeb336-66da-4e2c-b0da-37ed9d427d44">
<img width="682" alt="Screen Shot 2023-06-15 at 1 24 37 PM" src="https://github.com/broadinstitute/seqr/assets/37872186/d156a8d2-4152-4c52-9f71-61fd3093b602">

https://seqr.broadinstitute.org/variant_search/families/R0303_cmg_manton_exomes;F015789_0635,F015802_man_0042,F015834_0030,F020189_1185,F022168_man_0987,F023842_1216,F023844_1226,F028728_man_1503,F028729_man_1506,F028744_man_0887,F030824_man_1908:R0285_cmg_gleeson_exomes;F013497_5942,F019851_2003:R0276_inmr_neuromuscular_disea;F012745_cj,F018090_ii,F018448_hw,F018449_hx,F021377_gc,F021475_ip:R0375_cmg_topf_tubitak_wes;F018354_fizm002,F018355_fizm010,F018359_fizm021,F018360_fizm024,F018361_fizm025,F018362_fizm026,F018363_fizm027,F018370_fmal001,F018371_fmal002,F018372_fmal004,F018373_fmal006,F018376_fmal011,F018377_fmal014,F018383_fmal021,F018385_fmal023,F018386_fmal024,F018387_fmal027,F018388_fmal031,F023147_fdiy025,F023148_fdiy026,F023153_fdiy0031,F023154_fdiy0032,F023155_fdiy0033,F023162_fizm001,F023165_fizm006,F023170_fizm018,F023171_fizm019,F023172_fizm020,F023175_fizm029,F023176_fizm030,F023178_fizm032,F023181_fizm035,F023183_fmal003,F023185_fmal008,F023190_fmal025,F023193_fmal029,F023194_fmal030,F023195_fmal033,F023197_fmal035,F023198_fmal036,F023200_fmal039,F023201_fmal040,F023202_fmal041,F023205_fmal044,F023209_fmal048,F023211_fmal050,F023212_fmal051,F023213_fmal052,F023214_fmal053,F023215_fmal054,F023218_fmal057,F023220_fmal059,F023221_fmal060,F023223_fmal062,F023224_fmal063,F023225_fmal064,F023226_fmal065,F023227_fmal066,F023229_fmal068,F023231_fmal070,F023234_fmal073,F023235_fmal074,F023236_fmal075,F023237_fmal076,F023238_fmal077,F023239_fmal078,F027347_top_fizm038,F027349_top_fizm040,F027350_top_fizm041,F027360_top_fizm051,F027361_top_fizm052,F027363_top_fizm054,F027365_top_fizm056,F027367_top_fizm058,F027368_top_fizm059,F027370_top_fizm061,F027372_top_fizm063,F027377_top_fmal080,F027379_top_fmal082,F027381_top_fmal084,F027384_top_fmal087,F027389_top_fmal093,F027392_top_fmal096,F027393_top_fmal097,F027394_top_fmal098,F029521_top_fmal502,F029529_top_fmal526:R0344_cmg_beggs_exomes;F016770_beg_1291,F018289_beg_1142,F020506_beg_0761,F020510_beg_1121,F020513_beg_1329,F020514_beg_1345,F020523_beg_1126,F020524_beg_1134,F020530_beg_1314,F020535_beg_1083,F024085_beg_21,F024104_beg_1452,F024106_beg_1459,F028032_beg_112,F028036_beg_140,F028054_beg_1108,F028058_beg_1245,F028059_beg_1476,F028062_beg_1443,F028068_beg_1496:R0351_cmg_bonnemann_exomes;F017389_b16_66,F017387_b16_36,F017394_b16_90,F018909_bon_b17_21,F018910_bon_b17_12,F018911_bon_b17_26,F019732_bon_b16_168,F019734_bon_uc499,F021145_bon_b12_65,F022126_bon_b17_59,F022128_bon_b14_01,F022971_bon_b17_68,F022977_bon_b18_03,F022997_bon_b04_17,F022998_bon_b17_41,F023000_bon_b17_42,F023001_bon_b15_03,F023317_bon_b18_07,F023318_bon_b17_47,F023319_bon_b17_46,F023320_bon_b17_23,F023321_bon_b18_05,F023323_bon_b17_79,F023324_bon_b18_09,F023325_bon_b17_44,F023326_bon_uc516,F023327_bon_b16_34,F023328_bon_b18_11,F023329_bon_b17_86,F023813_bon_b17_54,F023815_bon_b18_23,F023816_bon_b18_24,F023817_bon_b18_26,F023818_bon_b18_37,F023966_bon_b14_23,F023968_bon_b16_151,F023970_bon_b18_50,F024855_bon_b12_101,F024856_bon_uc355,F024857_bon_uc35,F024859_bon_b18_54,F025453_bon_b16_59,F025455_bon_b16_86,F025456_bon_b16_39,F026293_bon_b17_75,F026295_bon_b11_16,F026299_bon_b18_82,F025454_bon_b15_130,F026903_bon_b17_29,F026913_bon_b13_46,F026915_bon_b15_102,F026916_bon_b15_104,F027140_bon_b14_134,F027481_bon_b19_16,F027483_bon_b18_97,F027480_bon_b19_05,F027495_bon_b19_08,F029278_bon_b19_38,F030264_bon_b18_59,F030671_bon_b19_54,F030672_bon_b14_125,F030673_bon_b16_70,F030674_bon_b14_148,F030677_bon_b19_61,F030998_bon_b20_16,F031017_bon_b08_51,F031399_bon_b20_26,F031535_bon_b20_33,F031533_bon_b20_25,F031541_bon_b20_40,F034112_bon_uc563,F034111_bon_uc564,F034110_bon_b21_26,F034114_bon_b21_23:R0330_cmg_laing_wes;F016445_fam2:R0312_cmg_bonnemann_genomes;F015964_b09_25,F015965_b14_48,F015966_b10_02,F015974_uc223,F015978_b13_52,F015984_b14_117,F015986_b12_74,F018395_b14_51,F018393_b15_26,F018900_bon_b13_16,F018905_bon_b15_101,F022131_bon_b16_59,F022132_bon_b16_102,F023862_bon_uc499,F025550_bon_b17_36,F027329_bon_b17_23,F028239_bon_b18_23,F028240_bon_b18_24,F028241_bon_b18_54,F029286_bon_b17_54,F029971_bon_b16_59,F029972_bon_b17_12,F031576_bon_b20_37,F031575_bon_b18_72,F031577_bon_b16_38,F038254_bon_b21_58,F038309_bon_b18_70:R0379_ogrady_wes;F018896_ssh_e,F026800_ogr_ssh_w,F026802_ogr_ssh_z,F026804_ogr_ssh_ab,F030549_ssh_ac,F030553_ssh_ff,F030554_ssh_gg:R0384_rare_genomes_project_gen;F018961_rgp_7,F019159_rgp_13,F019653_rgp_107,F019691_rgp_164,F019820_rgp_233,F019818_rgp_232,F023809_rgp_543,F026334_rgp_673,F027141_rgp_762,F027144_rgp_766,F027410_rgp_779,F027411_rgp_806,F027433_rgp_844,F027447_rgp_854,F027510_rgp_880,F027630_rgp_910,F027638_rgp_920,F027640_rgp_924,F027641_rgp_921,F027646_rgp_930,F027743_rgp_957,F027747_rgp_961,F027749_rgp_947,F027762_rgp_980,F027879_rgp_995,F027962_rgp_1004,F027963_rgp_1006,F028006_rgp_1022,F028007_rgp_1016,F028018_rgp_1036,F028107_rgp_1067,F028111_rgp_1075,F028113_rgp_1072,F028682_rgp_1109,F028751_rgp_1125,F028756_rgp_1129,F029266_rgp_1141,F029503_rgp_1157,F029943_rgp_1170,F029944_rgp_1171,F030182_rgp_1214,F030187_rgp_1220,F030197_rgp_1233,F030201_rgp_1236,F030206_rgp_1243,F030231_rgp_1261,F030234_rgp_1255,F030240_rgp_1271,F030241_rgp_1270,F030243_rgp_1297,F030402_rgp_1312,F030403_rgp_1311,F030417_rgp_1283,F030418_rgp_1281,F030422_rgp_1304,F030592_rgp_1328,F030598_rgp_1335,F030606_rgp_1347,F030607_rgp_1346,F030608_rgp_1339,F030626_rgp_1374,F030656_rgp_1413,F030977_rgp_1500,F030989_rgp_1512,F031036_rgp_1544,F031027_rgp_1546,F031323_rgp_1568,F031364_rgp_1542,F031063_rgp_1547,F031368_rgp_1577,F031367_rgp_1582,F031389_rgp_1613,F031412_rgp_829,F031444_rgp_1635,F031443_rgp_1637,F031477_rgp_1645,F031594_rgp_1694,F031593_rgp_1703,F031585_rgp_1704,F031607_rgp_1713,F031631_rgp_1738,F031626_rgp_1742,F031633_rgp_1747,F031751_rgp_1762,F021133_rgp_410,F031767_rgp_1786,F031770_rgp_1787,F031938_rgp_1820,F031962_rgp_1855,F031968_rgp_1864,F031979_rgp_1870,F031981_rgp_1883,F032068_rgp_1434,F032151_rgp_2018,F032186_rgp_2054,F032162_rgp_2036:R0394_cmg_kang_lgmd_wes;F019624_k1431,F019625_k1430,F019627_k1425,F024870_kun_k1445,F030438_kan_1454:R0406_cmg_topf_panel_wes;F020500_bb2337:R0416_cmg_topf_cms_wes;F021385_top_n687636,F021388_top_n759272,F021389_top_n760903,F021390_top_n778763,F021391_top_n773989,F021393_top_n779104,F021397_top_n772379,F021402_top_n769653,F021427_top_n799019,F021428_top_n803981,F021429_top_n797450,F021432_top_n401855,F021433_top_n719623,F021437_top_este1759,F021440_top_este1952,F021441_top_este2001,F021443_top_este1712,F021445_top_este2201,F021446_top_este1733,F021447_top_este1711,F021448_top_este1707,F021449_top_este1716,F021450_top_este1724,F021451_top_este1867,F021458_top_este2174,F021459_top_este2177,F022117_top_n807548,F022118_top_n810177,F022122_top_n810594,F022124_top_n77207,F022125_top_n799366,F029543_top_ser01,F029544_top_964:R0293_inmr_neuromuscular_disea;F021484_hw,F030572_hx,F031471_jd,F031779_ah,F031777_ec,F031782_ip,F031469_bd:R0280_cmg_hildebrandt_exomes;F022605_hil_a3729:R0317_cmg_topf_bonn_wes;F023119_bonn18:R0451_cmg_walsh_exomes_microce;F023507_mc17100,F023549_mc25100,F023574_mc29100,F023620_mc38700,F023636_mc4200:R0456_cmg_walsh_exomes_ch;F023733_ch1100,F023736_ch1400,F023775_js1900:R0358_cmg_vcgs_exomes;F024832_vcgs_fam105,F024845_vcgs_fam118,F029330_vcgs_fam221,F030736_vcgs_fam284,F031349_vcgs_fam297:R0495_cmg_topf_ea_cms_wes;F025645_top_465,F025659_top_744,F025667_top_922,F025670_top_bb3505:R0485_cmg_beggs_wgs;F025783_beg_0761,F025788_beg_21,F029982_beg_1291:R0294_myoseq_v20;F026044_msof026,F027149_mabe006,F027173_mkha017,F027572_mgla052,F030294_mbru061:R0497_cmg_muntoni_exomes;F026782_mun_fam2,F026783_mun_fam3,F026784_mun_fam4,F026788_mun_fam8,F026790_mun_fam10,F031013_mun_fam19,F031005_mun_fam23,F031010_mun_fam24:R0517_cmg_uchicago_wes;F027724_phil_0060,F027736_phil_1194:R0408_cmg_perth_wes;F029288_uwa_lai8983,F029289_uwa_lai8985,F029299_uwa_lai12753,F029302_uwa_lai13085:R0532_cmg_walsh_exomes_pmg;F029693_wal_oth2600,F029710_wal_ps2200,F029719_wal_pmg18500,F029725_wal_pmg400,F029732_wal_pmg5300,F029687_wal_ce1600,F029776_wal_pmg12100,F029763_wal_ps9300,F029695_wal_pmg20300,F029824_wal_ps5700,F029828_wal_pmg8700,F029851_wal_ps4500,F029857_wal_pmg4000,F029881_wal_pmg21800,F029868_wal_pmg22200,F029898_wal_pmg23200:R0536_cmg_muntoni_external_gen;F030213_mun_famlama2:R0492_cmg_lerner_ellis_wes;F030273_ler_0086:R0382_cmg_myoseq_exomes;F030462_mbru061,F030516_mnew027,F030518_mnew030,F030538_mval064:R0546_rare_genome_project_exte;F031068_rgp_1134:R0594_rare_genomes_project_gen;F032188_rgp_2058,F032339_rgp_2066,F032341_rgp_2051,F032368_rgp_2092,F033108_rgp_2107,F034031_rgp_2124,F034128_rgp_2153,F034133_rgp_2157,F034139_rgp_2161,F034141_rgp_2160,F034137_rgp_2163,F038237_rgp_2182,F038249_rgp_2187,F039406_rgp_2263,F040474_rgp_2276,F040589_rgp_2341,F040915_rgp_2387,F040928_rgp_2401,F041782_rgp_2450,F041804_rgp_2447,F040882_rgp_2365:R0562_mgrc_bonnemann_wes;F032194_bon_b21_22,F033997_bon_b21_10,F034000_bon_b21_38,F033999_bon_b21_45,F038233_bon_b21_41,F038227_bon_uc568,F038229_bon_b21_52,F038230_bon_b21_49,F038261_bon_b22_17,F040540_bon_uc297,F040539_bon_b22_02,F040536_bon_b22_23,F040541_bon_b22_32,F040538_bon_b22_29,F040542_bon_b22_28,F040903_bon_b22_01,F040902_bon_b08_42,F040901_bon_b22_35,F041835_bon_b22_49,F041838_bon_uc453,F041836_bon_b19_41,F043373_bon_b22_54,F043371_bon_b22_27,F043372_bon_b22_59,F044220_bon_b14_25,F044222_bon_b14_29,F044226_bon_b14_36,F044769_bon_b23_01,F044770_bon_b22_64,F044771_bon_uc424:R0565_mgrc_bonnemann_wgs;F032195_bon_b21_35,F032343_bon_b18_97,F040545_bon_uc35,F040900_bon_b14_134,F041763_bon_b20_17,F041767_bon_b20_25,F041770_bon_b21_22,F041772_bon_b20_33,F041765_bon_b20_16,F041764_bon_uc563,F041771_bon_uc368,F041816_bon_b21_38,F043279_bon_b21_49,F043377_bon_b22_53,F044949_bon_b21_10,F044950_bon_b21_45,F044948_bon_b21_52:R0567_tgg_myoseq_wgs;F032239_12_569,F032235_11_794,F032232_11_238,F032236_08_205,F032243_10_332,F032263_00_1912,F032258_99_186,F032244_11_2273,F032254_i0187,F032231_i0203,F032252_i0270,F032260_dna_15_009,F032238_dna_20_193,F032249_dna_17_076,F032316_dna_20_119,F032334_maac004,F032325_maac030,F032324_maac053,F032308_maac059,F032306_mant041,F032319_mbel091,F032320_mbel133,F032317_mbel274,F032305_mbel285,F032336_mbrn021,F032312_mesp036,F032315_minn001,F032326_mkha022,F032307_mleu054,F032335_mnew018,F032303_mpau020,F032314_mpau085,F032331_msof055,F032313_mwar004:R0607_gregor_training_project_;F039250_gt6,F039242_gt3:R0608_gregor_training_project_;F039262_gt6,F039254_gt3:R0609_gregor_training_project_;F039274_gt6,F039266_gt3:R0610_gregor_training_project_;F039286_gt6,F039278_gt3:R0611_gregor_training_project_;F039298_gt6,F039290_gt3:R0612_gregor_training_project_;F039310_gt6,F039302_gt3:R0613_gregor_training_project_;F039322_gt6,F039314_gt3:R0615_gregor_training_project_;F039334_gt6,F039326_gt3:R0616_gregor_training_project_;F039346_gt6,F039338_gt3:R0617_gregor_training_project_;F039358_gt6,F039350_gt3:R0618_gregor_training_project_;F039370_gt6,F039362_gt3:R0619_gregor_training_project_;F039382_gt6,F039374_gt3:R0639_tgg_bonnemann_turkey_wes;F040531_bon_b22_04,F040534_bon_b22_05,F040529_bon_b22_06,F040528_bon_b22_08,F040523_bon_b22_10,F040527_bon_b22_11,F040524_bon_b22_12,F040532_bon_b22_13,F040525_bon_b22_14,F040530_bon_b22_16,F041748_bon_b22_37,F041753_bon_b22_38,F041749_bon_b22_40,F041755_bon_b22_41,F041747_bon_b22_42,F041752_bon_b22_45:R0644_gregor_beggs_wes;F040909_beg_1551,F040911_beg_1604,F040906_beg_1612:R0682_gregor_beggs_wgs;F043632_beg_1476:R0684_gregor_ogrady_wgs;F044007_ssh_e,F044004_ogr_ssh_w,F044006_ogr_ssh_z,F044001_ssh_ff,F044002_ssh_gg:R0696_tgg_bgm_ext_wgs;F044767_udn577110:R0700_tgg_bonnemann_turkey_wgs;F044937_bon_b22_04,F044939_bon_b22_11,F044940_bon_b22_13,F044938_bon_b22_08:R0587_gregor_manton_wgs;F044941_man_1185:R0692_gregor_muntoni_wes;F044262_mun_fam8

**Comment by hanars** [comment]
The issue is search should be disabled in > 500 families but the link is not being disabled the way it should be

**Comment by hanars** [comment]
link is now properly disabled
