### ISSUE TITLE
Update validation for AnVIL VCFs

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3447]
As we are no longer using the depth field from the VCF and are computing it ourselves, we can stop validating that it is there before accepting AnVIL VCFs.

Additionally, as of https://github.com/broadinstitute/seqr-loading-pipelines/pull/373 we compute our own callstats and do not need to validate for AC, AN, and AF.

https://github.com/broadinstitute/seqr/blob/f860a2cd15892e164f4b92dd06870178f55a2b1a/seqr/utils/vcf_utils.py#L10

**Comment by hanars** [comment]
I have updated the validation so we will accept GVS from AnVIL
