### ISSUE TITLE
Stop validating AC, AN, and AF in anvil requests

### ISSUE THREAD

**Issue by mike-w-wilson** [broadinstitute/seqr#3448]
As of https://github.com/broadinstitute/seqr-loading-pipelines/pull/373 we compute our own callstats and do not need to validate for AC, AN, and AF. https://github.com/broadinstitute/seqr/blob/f860a2cd15892e164f4b92dd06870178f55a2b1a/seqr/utils/vcf_utils.py#L10

**Comment by hanars** [comment]
Combined with https://github.com/broadinstitute/seqr/issues/3447, as it is much easier to do all the validation undates at once
