### ISSUE TITLE
Add spacing to RNA-seq links like "Show RNA-Seq OUTRIDER" 

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#3458]
Can space be added to
<img width="236" alt="image" src="https://github.com/broadinstitute/seqr/assets/6240170/c08cb8d3-52c7-4664-9104-300dd3502119">
and
<img width="330" alt="image" src="https://github.com/broadinstitute/seqr/assets/6240170/69169bd7-4b0d-40cd-9457-78472fe71453">

to make it look like
<img width="265" alt="image" src="https://github.com/broadinstitute/seqr/assets/6240170/3c11101b-2e3d-44ff-9982-0342ce864e8a">
and
<img width="211" alt="image" src="https://github.com/broadinstitute/seqr/assets/6240170/06c68137-efc6-43da-ace9-f74a8b8781e5">

I could submit a PR to for example, add `margin-left: 15px !important` to each button @ 
https://github.com/broadinstitute/seqr/blob/master/ui/pages/Project/components/FamilyTable/IndividualRow.jsx#L186

**Comment by hanars** [comment]
fixed

**Comment by ShifaSZ** [comment]
You must have a very good (wide) screen :) But you are right. We should add a hard break between the two buttons.

**Comment by hanars** [comment]
this is now fixed
