### ISSUE TITLE
Interval local filter error when search on SV indices

### ISSUE THREAD

**Issue by ShifaSZ** [broadinstitute/seqr#3485]
**Describe the bug**
When a variant search with an interval location filter searches on a structural variant index, the interval filter does not properly handle breakend and multi-chromosome events. 
For example, if the location filter is `chr20:45824623-45827445`, ~the search results include variants from all chromosomes other than chr20.~ the search includes breakend events whose start is before chromosome 20 (i.e chromosome 1) and whose end is after chromosome 20 (i.e. chromosome 21)

**Link to page(s) where bug is occurring**
This is an example search: https://seqr.broadinstitute.org/variant_search/results/3fd78f3581752a065fd9af0bb07f6b3a?page=1&sort=pathogenicity

**Scope of the bug**
All projects with structural variant indices.

**Screenshots**
For example, the first search result variant in the following picture is on chromosome 1, but the search interval filter is on chromosome 20.
![image](https://github.com/broadinstitute/seqr/assets/33550059/9161b5e0-b66d-455c-8529-450f64a858ad)

**Comment by hanars** [comment]
this is now fixed
