### ISSUE TITLE
Move SpliceAI link to text 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3491]
**Is your feature request related to a problem? Please describe.**
Related to ticket #3340 

**Describe the solution you'd like**
Make the 'SpliceAI' text itself the link rather than the value as the value might change when we link out. 

**Describe alternatives you've considered**
NA

**Additional context**
Great to have this seqr!

**Comment by hanars** [comment]
I would rather not do this. It is more consistant the way it is with how everything else looks in seqr (i.e the links for frequencies are the values). 

> the value might change when we link out

The link is to a 1Kb window and is not in any way a function of the value. I'm not really sure what the value changing has to do with the link, or how moving the link next to the value changes anything
