### ISSUE TITLE
Validate Ensembl Gene IDs during RNA loading

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr#3495]
**Is your feature request related to a problem? Please describe.**
RNA Splice Outlier loading requires ensemble gene IDs, but will silently accept any value for gene ID, leading to downstream bugs in the data after loading

**Describe the solution you'd like**
At loading time, add validation that Gene IDs are valid Ensembl Ids present in the seqr database

**Describe alternatives you've considered**
None

**Additional context**
This should be added for splice outliers and anything else that shares the functionality. If other parts of RNA loading share the impacted code they should have the new validation too, but if they are not already sharing code they should be left alone

**Comment by ShifaSZ** [comment]
Can we look up the GeneInfo database to see if the gene ID is valid?

**Comment by hanars** [comment]
yes that would be the only way to do it
