### ISSUE TITLE
Update display colors for in silico scores 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3505]
**Is your feature request related to a problem? Please describe.**
The analyst team would like to request an update to the colors used for the in silico scores based on new guidelines from ClinGen.
These changes should apply to all in silico tools (CADD, MPC, MutPred2, PrimateAi, REVEL, SIFT, VEST4) used in seqr and represented in the table below.

**Describe the solution you'd like**
1. Use new colors and ranges as described below:

<img width="965" alt="Screenshot 2023-07-21 at 11 59 00 AM" src="https://github.com/broadinstitute/seqr/assets/37872186/089a5837-7cf6-490a-8f9e-8a608dda497d">

Benign: Very strong + Strong = dark green
Benign: Moderate + Supporting = light green
VUS: In between ranges benign supporting and pathogenic supporting = Grey
Pathogenic Supporting = orange
Pathogenic Moderate = red 
Pathogenic Strong + very strong = dark red

The cutoff ranges can also be found here in Table 2 - https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9748256/ 

2. Reorder position of in silico scores: 
Revel, Vest4, Mutpred2, CADD, MPC, SpliceAI. Others can go in the show more section.

**Describe alternatives you've considered**
NA

**Additional context**
Discussed during analyst team meeting.

**Comment by ShifaSZ** [comment]
We currently have two cut-off values (warningThreshold and dangerThreshold) and three colors(green for benign, yellow for warning, and red for danger). Does it mean we need four thresholds and five colors for this ticket?

**Comment by hanars** [comment]
@lynnpais do you want us to keep the current 3-color system and combine the green and reds in the above chart, or do you want us to switch to a 5-color system?

**Comment by lynnpais** [comment]
Move all to the a new 6-color system using the ranges in the image above - 
Benign: Very strong + Strong = dark green
Benign: Moderate + Supporting = light green
VUS: In between ranges benign supporting and pathogenic supporting = Grey
Pathogenic Supporting = orange
Pathogenic Moderate = red
Pathogenic Strong + very strong = dark red

**Comment by hanars** [comment]
coding implementation notes - we should switch `warningThreshold` and `dangerThreshold` to an array `threshholds`, rather than try to maintain 5 different variables

@lynnpais is there any flexibility for the colors? It is possible to implement with the colors you propsed,  but we could use the built-in color schemes from our UI library if we tweaked it a little, which creates a more consistent UI across seqr than when we need to add custom colors to everything. The colors would be as follows:
Benign: green
Benign: light green
VUS: Grey
Pathogenic Supporting: yellow
Pathogenic Moderate: orange
Pathogenic Strong: red

**Comment by lynnpais** [comment]
Good to be consistent with existing UI colors. Okay to go with colors for -
Benign: green
Benign: light green
VUS: Grey
Pathogenic Supporting: yellow (I take it is the same yellow we are using for the in silicos)

For the last two, 
Pathogenic Moderate: red (existing red)
Pathogenic Strong: dark red (one new color. Only a very few variants will actually have this color). 

The reason is that most variants currently showing red will be orange as they fall in the moderate range per the new ClinGen guidelines. None of the variants will ever have a red CADD score. All this can be confusing to an analyst, so propose to have one new dark red color to differentiate.

It would also be great to have these ranges and corresponding colors shown in the hover over like we currently do.

**Comment by hanars** [comment]
Makes sense. Would this purple be acceptable for the very strong pathogenic? If not, we can make dark red work 
 
![Screenshot 2023-08-08 at 10 18 55 AM](https://github.com/broadinstitute/seqr/assets/24598672/feeacfef-c078-4603-aff6-6cc46e0e94d6)

**Comment by ShifaSZ** [comment]
Can the `polyphen` in seqr use the above thresholds for the `PolyPhen2`?

**Comment by hanars** [comment]
Its the same thing, the ui code has friendly names for things but if you look at the server side mapping code you can see what the data source for everything is: https://github.com/broadinstitute/seqr/blob/master/seqr/utils/search/elasticsearch/constants.py#L345

**Comment by ShifaSZ** [comment]
Suppose a prediction doesn't have a benign threshold but has a pathogenic supporting point. What color should we display for the value smaller than the pathogenic supporting threshold? Grey, light green, or green?

**Comment by hanars** [comment]
colors/thresholds should map to the image included in the description, which is pretty unambiguous. What is a specific example of a score hwere there is ambiguity about what to show?

**Comment by ShifaSZ** [comment]
For example, if a score of 1.1 for MPC, what color should it display?

**Comment by hanars** [comment]
light green

**Comment by ShifaSZ** [comment]
Why not grey?

**Comment by hanars** [comment]
@lynnpais your call

**Comment by lynnpais** [comment]
Let's go with grey [ClinGen paper states they were not able to identify thresholds for benignity (BP4) for MPC]

**Comment by hanars** [comment]
scores have been updated
