### ISSUE TITLE
Update and harmonize outlier and gene search parameters 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3506]
**Is your feature request related to a problem? Please describe.**
We would like to update and harmonize outlier gene search parameters across seqr. 

**Describe the solution you'd like**
Use the following search parameters :
Inheritance from ‘All’ to ‘Any affected’
Frequency of 0.03 in gnomAD and 0.03 for this callset 
Call quality GQ of 40 and AB of 10. No VQSR.

The proposed changes pertain to the following:
1. RNASeq page - Search for variants in [expression] outlier genes
2. RNAseq results page - Search for variants in [splice junction] outlier regions
3. RNAseq results page - Junction
4. Saved variants page - Gene search (change text in hover over to say <3%. It is currently 10%). 

**Describe alternatives you've considered**
NA

**Additional context**
Discussed in the analyst team meeting.

**Comment by hanars** [comment]
"No VQSR" translates to "Pass Variants Only" under the quality filter

This involves changing the gene search everywhere is appears in seqr, so behavior can be shared

**Comment by lynnpais** [comment]
By "No VQSR" we mean Show all variants, NOT pass only.
<img width="301" alt="Screenshot 2023-07-21 at 12 58 40 PM" src="https://github.com/broadinstitute/seqr/assets/37872186/4a3ef5d1-4978-4a54-a14b-e5de9a8f6f15">

**Comment by ShifaSZ** [comment]
> Inheritance from ‘All’ to ‘Any affected’

The initial search for the gene search link has an `any_affected` inheritance mode. But it is converted to `all` mode because it doesn't have an inheritance filter field. What should the initial inheritance filter be? @hanars If we select the `Any Affected` on the search page, the inheritance filter is `{A: "has_alt"}`. Should we use the filter in the initial search?

**Comment by ShifaSZ** [comment]
Okay. I'll update [these codes](https://github.com/broadinstitute/seqr/blob/df88da531228363944381504b65944b29e57d9e5/ui/pages/Search/components/VariantSearchFormContent.jsx#L67C1-L72C1) to accept a mode with an inheritance filter field.

**Comment by ShifaSZ** [comment]
> the search link should be posting a search body directly to the backend.

The search link for the search button opens the search page and doesn't post to the backend. Only when the users click on the `Search` button on the search page the search request is sent to the backend.

**Comment by hanars** [comment]
> The search link for the search button opens the search page and doesn't post to the backend. Only when the users click on the `Search` button on the search page the search request is sent to the backend.

Then you are looking at the wrong place, or the behavior is totally broken. The links Lynn clearly lists above all open a new tab with a search running, there is no opportunity to edit the search. The gene search link component does not give the user the opportunity to edit search parameters until after the search has run and variants have been returned. For the purposes of this ticket, we do not care about the search form on that page, we care about the variants

**Comment by ShifaSZ** [comment]
You are right. The users can't update the search before the search results return. I just checked the search results and found the search has been done with `any_affected`, but the UI displayed is `All`. So what we need to fix is to update the inheritance mode display.

**Comment by hanars** [comment]
As I said above:
> If this is simply a matter of the search is correctly applying "any affected" to the actual search but then its not showing it to the user on the search results page but the search results are correct, thats not in the scope of this ticket, thats a different low priority bug

Make a different low priority ticket for that issue, and focus your work on the actual changes for this ticket

**Comment by hanars** [comment]
@lynnpais the ticket states that search should have a "frequency of 0.03 in gnomAD and 0.03 for this callset" but does not specify what the frequency should be for other populations, and currently topmed is also included in these searches with a frequency of `0.1`. Do we want to 
a) leave the topmed filter where it is
b) not filter on topmed at all or 
c) have the same 0.03 filter for topmed as for everything else

**Comment by lynnpais** [comment]
b) do not filter on topmed at all

**Comment by hanars** [comment]
Also, I realize its not on the list, but can we also have the gene search link in the lirical view behave the same as this? It would  be nice to have consistancy everywhere

**Comment by lynnpais** [comment]
Yes, fine to include gene searches for Lirical and Exomiser.

**Comment by hanars** [comment]
updated
