### ISSUE TITLE
Page timing out when trying to retrieve saved variants 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3507]
**Describe the bug**
Page is timing out when trying to retrieve saved variants even though the number of variants are relatively small

**Link to page(s) where bug is occurring**
All the following were timing out. Tried three times each. 

[Tier 1 - Novel gene and phenotype](https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/Tier%201%20-%20Novel%20gene%20and%20phenotype)
Page with error - https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/Tier%201%20-%20Novel%20gene%20and%20phenotype

[Known gene for phenotype](https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/Known%20gene%20for%20phenotype)
Page with error - https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/Known%20gene%20for%20phenotype

[Tier 2 - Phenotype expansion](https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/Tier%202%20-%20Phenotype%20expansion)
Page with error - https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/Tier%202%20-%20Phenotype%20expansion

**Scope of the bug**
Only checked RGP so far

**Screenshots**

<img width="1265" alt="Screenshot 2023-07-21 at 3 30 26 PM" src="https://github.com/broadinstitute/seqr/assets/37872186/c4f96fdc-c81b-4881-985a-6316a5108e58">

**Comment by hanars** [comment]
FWIW saved variants page fetches all the variants for the project or family, regardless of which tag you are showing, so it doesn't matter if the tag has a small umber of variants, the time will be proportional to the total number of variants for the tag or family. Still worth fixing, but thought you should be aware

**Comment by hanars** [comment]
still not working after attempted fix

**Comment by hanars** [comment]
this is fixed now
