### ISSUE TITLE
Not able to display 'Tier 1 - Phenotype expansion' variants on saved variants summary page

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#3514]
**Describe the bug**
I am grabbing all variants with a discovery tag from the 'saved variants' Summary Data Page. All tags have worked except for 'Tier 1 - Phenotype expansion'. Selecting this specific tag in the dropdown turns to a blank page. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/summary_data/saved_variants/Tier%201%20-%20Phenotype%20expansion

**Scope of the bug**
Only this tag has given me an issue so far. I've done all other Tier 1, Tier 2, KGP, and Analyst high-priority tags successfully. 

On a related note, it would be a nice feature to be able to select multiple tags at once.

**Comment by hanars** [comment]
For the related note, there is already a ticket for that! https://github.com/broadinstitute/seqr/issues/3320

**Comment by hanars** [comment]
this has been fixed
