### ISSUE TITLE
AnVIL data loading error (e is not a function)

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3527]
**Describe the bug**
External users are running into an error, “e is not a function”, when requesting data loading via AnVIL. The request seems to go through, but because of the error, users seem to be submitting multiple requests.

**Link to page(s) where bug is occurring**
Don't have a link but these were the request that came in -

hbrand@broadinstitute.org requested to load 176 new and 95 re-loaded WGS samples (GRCh38) from AnVIL workspace talkowski-reprod-med/SeqR_REU at
        gs://fc-a7b7fe6f-e7be-40fa-b4d5-d1ad70865cfe/vcf_files/ReproductiveMedicine_Talkowski_GenomicDisorders_WGS.vcf.gz to seqr project [SeqR_REU](https://seqr.broadinstitute.org/project/R0698_seqr_reu/project_page) (guid: R0698_seqr_reu)

jhan34@meei.harvard.edu requested to load 1 new and 102 re-loaded WGS samples (GRCh38) from AnVIL workspace ogi-terra/seqr_JinuHan_Inherited Eye Disease - WGS at
        gs://fc-10cc9940-535d-489d-bb5c-ac219b814c8c/wgs_jointcalls_filtered_07312023.vcf.gz to seqr project [SouthKorea - Inherited Eye Disease - WGS](https://seqr.broadinstitute.org/project/R0711_seqr_jinuhan_inherited_e/project_page) (guid: R0711_seqr_jinuhan_inherited_e)

**Scope of the bug**
AnVIL data loading pipeline

**Screenshots**

<img width="668" alt="Screenshot 2023-07-31 at 12 41 05 PM" src="https://github.com/broadinstitute/seqr/assets/37872186/404b59ac-59c2-4e17-81c9-02b1003a100a">

**Comment by hanars** [comment]
this should be fixed now
