### ISSUE TITLE
"Unknown Gene IDs:" error when loading splicing outliers.

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#3535]
Attempting to load this table of splice junction outliers, but getting "Unknown Gene IDs:" error:
gs://tgg-rnaseq/gagneur/fraser/fraser_v1_test_results_table_for_seqr.RGP_2058_3__muscle.tsv

<img width="1251" alt="image" src="https://github.com/broadinstitute/seqr/assets/6240170/67c1d0b6-68d9-49f3-8f55-b5d3fe7d0ab8">

I'm also seeing this error on the table I loaded originally
gs://tgg-rnaseq/gagneur/fraser/fraser_v1_test_results_table_for_seqr.RGP_1760_3_M1_muscle_v2.tsv
even though it worked several weeks ago.

**Comment by hanars** [comment]
Please provide an example of the file you are loading that is causing the errors so we can investigate.

That said, we are not supposed to be loading more splice outlier data at this time, the decision was made to hold off until we have time to intergrqte Fraser 2 data and have the analysts look more closely at a few test cases. Unless there have been conversations with Anne and Lynn I have been unaware of, you should not be loading this data at all

**Comment by bw2** [comment]
The example file is 
gs://tgg-rnaseq/gagneur/fraser/fraser_v1_test_results_table_for_seqr.RGP_2058_3__muscle.tsv

**Comment by hanars** [comment]
@ShifaSZ it appears the gene ID validation does not work if the gene is completely absent, which is a supported case. We should fix this, although as I said above we are not planning to load any more fraser1 data to seqr so this is not particularly urgent

**Comment by bw2** [comment]
the same table format is used for FRASER v1 and FRASER v2

**Comment by hanars** [comment]
yes, but AFAIK the FRASER2 data is not ready yet, and since we are not supposed to load more FRASER1 at all, that means that fixing this is lower priority and can wait until our next sprint and should not disrupt our priorities, the way it would if we needed to load data today

**Comment by hanars** [comment]
this issue should be resolved now, @bw2 we should be good to load FRASER2 data
