### ISSUE TITLE
Updated LoF constraint tag incorporating new Shet values

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3539]
**Is your feature request related to a problem? Please describe.**
We would like to merge the LoF + HI tags for genes in seqr and add one more metric (Shet) for calling LoF constraint. 

**Describe the solution you'd like**
_Variant page:_
Display only one 'LoF constr' tag for a gene if it meets criteria for any one LoF, HI or Shet (new) data. Shet constrained genes are here on sheet 1 - https://docs.google.com/spreadsheets/d/1enxGBWCAFBHdrRlqCj_ueleiDo9K9GWn/edit#gid=1642044433

In the hover over, show the rank for LoF (currently the first line in the LoF hover over), Shet value (column C in sheet 1 above), and HI score (currently last line in HI hover over) for each gene. Include the citation for each, LoF - Karczewski (2020), SHet - Zeng (2023), and HI - Collins (2022). Remove all additional text currently displayed.
Note for Shet - The S is capitalized and het is subscript. Paper here - https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10245655/

_Gene page:_
Add a row for Shet (after LoF but before Haploinsufficient) and show the score for a gene. Scores for all genes are in column C on sheet 2 - https://docs.google.com/spreadsheets/d/1enxGBWCAFBHdrRlqCj_ueleiDo9K9GWn/edit#gid=1146995171

Text to display with the RPS15A gene as an example- Shet: 0.61.
Note: This score was developed by the Pritchard lab [Zeng et al 2023] to predict gene constraint based on functional and evolutionary information. Scores >0.1 are considered to have high likelihood to be under extreme selection.

**Describe alternatives you've considered**
NA

**Additional context**
As discussed

**Comment by ShifaSZ** [comment]
The task includes a backend database loading, looking up, and frontend display. Is that right? @hanars

**Comment by hanars** [comment]
Yes

**Comment by ShifaSZ** [comment]
Separated DB tables for the two sheets may also work because the number of rows differs.

**Comment by hanars** [comment]
we will have one DB table for Shet. We will not accept loading from google sheets. You need to save this as a single standardized file (tsv, csv) and put it in GCP. If there is one sheet that works for loading, just put that in GCP. If not, merge sheets together into one big sheet, and put that in GCP. It can go in the gs:///seqr-reference-data/gene_constraint bucket, which is where we currently load gene constraint from

**Comment by ShifaSZ** [comment]
The Sheet 1 - https://docs.google.com/spreadsheets/d/1enxGBWCAFBHdrRlqCj_ueleiDo9K9GWn/edit#gid=1642044433 seems to include all the rows with Shet scores higher than a cutoff. Can we use the cutoff rather than the data rows in the sheet?

**Comment by hanars** [comment]
We should use sheet 2 which has all the genes and scores. We should not load any cutoff. When writing the code for display in the UI, we will define a cutoff the way we do for other constraint scores. Based on the text we will be shhwing the user, it looks like that cutoff is 0.1 but we can confirm

**Comment by hanars** [comment]
@lynnpais to clarify, do we want to change the behavior for TS gene tags or no?

**Comment by lynnpais** [comment]
No, leave TS scores and tags as is.

**Comment by hanars** [comment]
this has been updated
