### ISSUE TITLE
Error editing existing Individual ID using Bulk Edit Individuals

### ISSUE THREAD

**Issue by apham98** [broadinstitute/seqr#3545]
**Describe the bug**
I would like to update 2 individual IDs by switching them with each other as relatedness checks revealed the individuals have been swapped within the family. This has occurred with two families. I am listing the sample IDs I would like to swap below for reference:

CHU_247_1_D1 and CHU_247_2_D1 (mom and dad are swapped)
CHU_639_3_D1 and CHU_639_2_D1 (proband and mom are swapped)

Here is the csv I used to bulk edit the individuals: 
[cmg_wendy_chung_exomes_individuals.csv](https://github.com/broadinstitute/seqr/files/12306992/cmg_wendy_chung_exomes_individuals.csv)

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0524_cmg_wendy_chung_exomes/project_page

**Scope of the bug**
Just this project for two families

**Screenshots**
Below is the error I am receiving
![Screenshot 2023-08-09 at 5 02 35 PM](https://github.com/broadinstitute/seqr/assets/108075186/85dcb138-e780-46c3-9f69-924bc04fc41b)

**Comment by hanars** [comment]
you can do this yourself, by doing it in 2 steps. First rename them all to something new (maybe the desired new ID with an _1 after it) and then rename them again to the actual ID
