### ISSUE TITLE
Add documentation for loading RNASeq data to README

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3549]
**Is your feature request related to a problem? Please describe.**
We need documentation for users looking to load RNASeq data to their local seqr instance.

**Describe the solution you'd like**
Add as a document in the seqr repo, linked to the README provided for local install users. Ben posted a summary of the data formats to github ticket #3548. Also mention where to upload these tables in the UI, any setup steps to give someone permissions to do these uploads, and where the data appears in seqr after it's loaded.

**Describe alternatives you've considered**
NA

**Additional context**
As requested via slack.

**Comment by lynnpais** [comment]
Might this get completed today? I've mentioned it in the CZI grant and would like to add a URL.

**Comment by hanars** [comment]
Yeah I can figure that out

**Comment by hanars** [comment]
Added here: https://github.com/broadinstitute/seqr/blob/master/deploy/LOCAL_INSTALL.md#loading-rnaseq-datasets
