### ISSUE TITLE
Change GQ in Gene Search to 20

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3554]
**Is your feature request related to a problem? Please describe.**
We recently updated our gene searches to be more aligned, however for the Gene Search on variants page, we need to be a bit more permissive. 

**Describe the solution you'd like**
Change GQ in Gene Search to 20 (from 40)on variants page. 
<img width="1295" alt="Screenshot 2023-08-15 at 12 57 10 PM" src="https://github.com/broadinstitute/seqr/assets/37872186/12456920-2b5b-4301-9ae8-5dbc78d58224">

The search would be - https://seqr.broadinstitute.org/variant_search/results/9f5444d4bdf92d688f2d937f58f14057?page=1&sort=xpos

**Describe alternatives you've considered**
NA

**Additional context**
Discussed with analysts

**Comment by hanars** [comment]
please provide the details of the changes to search criteria that you want, a search link is insufficient

**Comment by lynnpais** [comment]
Change GQ in Gene Search to 20 (from 40)on variants page. That is all. Keep other metrics as is. Included the link as an example.

**Comment by hanars** [comment]
updated
