### ISSUE TITLE
Blank columns in Airtable for called_variants_dna_short_read GREGoR data model table

### ISSUE THREAD

**Issue by apham98** [broadinstitute/seqr#3560]
**Is your feature request related to a problem? Please describe.**
The Airtable fields for the columns `called_variants_dna_short_read_id`  `called_variants_dna_file` and `caller_software` were originally populated as "NA" as these fields did not exist since we are not uploading VCFs. These are updated to now be blank.

**Describe the solution you'd like**
We will always include the called_variants_dna_short_read table but include it empty when none of the rows have the needed data.

**Describe alternatives you've considered**
NA

**Additional context**
As discussed via slack.

**Comment by hanars** [comment]
reports have been updated as requested
