### ISSUE TITLE
Add link to AnVIL data loading video on seqr FAQ page

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3562]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when ... folks ask about data loading when we have the info on the website. 

**Describe the solution you'd like**
To the seqr FAQ > Q. How can I analyze my data in seqr > Through AnVIL where requests can be placed for loading a joint called vcf into seqr > Add, "See video tutorial" hyperlink the video tutorial to https://www.youtube.com/watch?v=TvYz_VI9vN0&ab_channel=BroadInstitute

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hanars** [comment]
this has been added
