### ISSUE TITLE
Investigate missing samples from mito ES data loading 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3563]
**Describe the bug**
Four samples (VCGS_FAM110_344, VCGS_FAM141_441, VCGS_FAM141_442, VCGS_FAM13_41) seem to be missing from the recent attempt to load ES mito data. The tsv file Sarah shared has 481 samples, but only 477 loaded per the slack notification in the seqr data loading channel. I checked in seqr too, these four samples do not have mito data.

Confirmed with Sarah that these samples have data in the callset 

<img width="1056" alt="Screenshot 2023-08-17 at 3 55 23 PM" src="https://github.com/broadinstitute/seqr/assets/37872186/fd804685-784b-4d65-9024-f697611d35c3">

Also confirmed with Stacey the IDs are the same in both call sets and there aren't any notes on these samples in airtable to indicate there is any remapping.

**Link to page(s) where bug is occurring**
NA

**Scope of the bug**
ES mito data loading pipeline

**Screenshots**
NA

**Comment by hanars** [comment]
investigations are not bugs

**Comment by hanars** [comment]
these samples have no het calls in the data, only hom calls. When detecting which samples are in the index, seqr does a quicjk check for het calls so is missing htese. We could update the seqr logic if needed to also check homs, but I ffeel like instead we should go back t Sarah and figure out why this happened, as it seems like a QC issue
