### ISSUE TITLE
Update validation of mito variants 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3566]
**Is your feature request related to a problem? Please describe.**
 Currently, when detecting which samples are in the index, seqr checks for het calls and can miss samples with only hom calls as we noticed recently. 

**Describe the solution you'd like**
Per Sarah, some individuals won't carry any heteroplasmic variants in the mtDNA (just homoplasmic, which are normally haplogroup defining), especially children as these normally accumulate with age. So we need to update the seqr logic to also check homs.

**Describe alternatives you've considered**
NA

**Additional context**
Just fyi, before we load ES mito data for other projects, we need a few other things which I am working on.

**Comment by hanars** [comment]
> Just fyi, before we load ES mito data for other projects, we need a few other things which I am working on.

Is this exome only or also genomes?

**Comment by lynnpais** [comment]
For ES only. We need to update the GQ as it is -10 for ES.

**Comment by hanars** [comment]
what is the priority on this?

**Comment by lynnpais** [comment]
Medium-high level priority. This and another ticket #3580 are blocking loading of mito data. Sarah has already reviewed the mito data outside of seqr, but she is working on a new callset, and would be good to have it all in seqr. Can discuss further at the sprint planning meeting next week.

**Comment by lynnpais** [comment]
Won't be an issue in V3. Fine not loading until it is live.
