### ISSUE TITLE
Remove GQ from hover over for mito calls

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3567]
**Is your feature request related to a problem? Please describe.**
GQ not relevant for mt ES/GS calls

**Describe the solution you'd like**
GQ not relevant for mito calls per Sarah. Remove from hover over. 

<img width="208" alt="Screenshot 2023-08-18 at 2 35 02 PM" src="https://github.com/broadinstitute/seqr/assets/37872186/801c6eff-e6d3-496b-966c-aa56fd0e8d16">

**Describe alternatives you've considered**
NA

**Additional context**
Discussed with Sarah

**Comment by hanars** [comment]
Is this true for both exome and genome data, or just exome? Do we also want to remove it from where it is shown under the genotype? If so do we want to show something else there? Do we want to change the filtering behavior so applying the GQ filter no longer applies to mito variants? It seems not ideal not to have any way to filter low quality variants...

**Comment by lynnpais** [comment]
This ticket was to remove from the hover over. We are also considering making changes to the filtering behavior, but requires some discussion with the analysts. I will submit a separate ticket later in the week. Closing this for now.
