### ISSUE TITLE
Update constraint metrics for mt variants

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3568]
**Is your feature request related to a problem? Please describe.**
Existing Helix constraint info is old. Update with Nicole Lake's new data. 

**Describe the solution you'd like**
Use new values from supplemental tables in the study (https://www.biorxiv.org/content/10.1101/2022.12.16.520778v2)
Display the mitochondrial local constraint score (MLC) in a traffic light system like we do for the in silico tools
High constraint is >=0.75 - red; 0.50-0.74 is yellow; <0.50 is green

Cite the paper in the hover over.

Remove Helix constraint info which currently shows as a red tag
<img width="1261" alt="Screenshot 2023-08-18 at 2 39 28 PM" src="https://github.com/broadinstitute/seqr/assets/37872186/07a76872-99c4-43f8-b611-591f6422df19">

**Describe alternatives you've considered**
NA

**Additional context**
Discussed with Sarah

**Comment by hanars** [comment]
This requires a change to the loading pipeline, the ticket needs to be made for that repo

**Comment by hanars** [comment]
We are not citing papers for in silico tools. This is way too much information and impossible to maintain, as well as totally inconsistent with other data types
