### ISSUE TITLE
Look into cause for warning flag for certain mt variants

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3569]
**Is your feature request related to a problem? Please describe.**
There seem to be yellow warnings for several mt variants in ES and GS data, but I am not sure what is triggering it. 

**Describe the solution you'd like**
Look into why the warnings are displayed. We typically have it if the inheritance does not line up but that's not the case here- https://seqr.broadinstitute.org/variant_search/variant/M-66-G-T/family/F025868_3386 or in some of the other examples I looked into. 

**Describe alternatives you've considered**
NA

**Additional context**
<img width="1313" alt="Screenshot 2023-08-18 at 3 20 25 PM" src="https://github.com/broadinstitute/seqr/assets/37872186/bde55f74-330f-492b-acf8-217751c27b6c">

**Comment by hanars** [comment]
What does the warning say when you hover over it? Please include screenshot of the hover

**Comment by lynnpais** [comment]
The hover over is showing what you would typically get with hovering over the genotype. No error message. 
<img width="1320" alt="Screenshot 2023-08-21 at 7 18 13 AM" src="https://github.com/broadinstitute/seqr/assets/37872186/f2cd7382-1f34-4084-98b8-721d0063ab3d">


The CN is below 250 but I do not think it is because of that because other variants with a CN <250 do not have the flag.
<img width="1227" alt="Screenshot 2023-08-21 at 7 22 06 AM" src="https://github.com/broadinstitute/seqr/assets/37872186/812f0f8b-4ca1-4561-b855-338cb5d3be9c">

More examples here - https://seqr.broadinstitute.org/report/custom_search/cc000630332542d88ab64cd1721be77e?page=1&sort=in_omim

**Comment by hanars** [comment]
No, what happens when you hover over the triangle itself, not the rest of the genotype
