### ISSUE TITLE
Error Resetting Password/Welcome Email

### ISSUE THREAD

**Issue by jlieviant** [broadinstitute/seqr#3577]
We are using seqr on a local installation without Google Auth enabled. When the user attempts to reset the password using the URL (`<BASE_URL>/login/set_password/<password_hash>`), the HTTP GET request would be completed with a 200 status code, and the form would appear very briefly before turning into a blank page. And on the Javascript console this error appears:

```
Uncaught TypeError: o is not a function
    at app-0a8e49d1.js:1:116481
    at Array.forEach (<anonymous>)
    at N.k.concat.a.reduce.e.concat.P.<computed> (app-0a8e49d1.js:1:116454)
    at app-0a8e49d1.js:1:116746
    at Array.reduce (<anonymous>)
    at N (app-0a8e49d1.js:1:116364)
    at Object.resumeValidation (app-0a8e49d1.js:1:123655)
    at app-0a8e49d1.js:1:382045
    at Fu (app-0a8e49d1.js:1:360683)
    at t.unstable_runWithPriority (app-0a8e49d1.js:1:378630)
```

**Comment by hanars** [comment]
does refreshing the page fix the issue?

**Comment by jlieviant** [comment]
Refreshing the page will also show the error message, and the same flickering form then blank page.

**Comment by jlieviant** [comment]
After updating to the latest release on gcloud-prod (image gcr.io/seqr-project/seqr@sha256:787955b8de3c2ff419d594564529a11fba2ea1c4734e6de3fb8a9ca4253d864f) I still encounter the same issue. Is there perhaps a more recent release?

**Comment by hanars** [comment]
sha256:979b1a45516c3e2063d5b05f4e2b5cfc4388282f71465e11c2b3bf189550a9ba is the latest release

**Comment by jlieviant** [comment]
The latest release still has the same issue for us. Could you please point to the commit or issue that might have fixed it?

**Comment by hanars** [comment]
Not really, I can't point at the commit that has the issue in the first place, nor am I able to recreate the bug in any of the latest releases. I have set up seqr locally from the latest release and have no problem using the local username/password authentication.

One thought I have is it is possible that you missed the necessary steps to migrate your local instance when we made some changes to how the images work - make sure you have complied with the steps in  https://github.com/broadinstitute/seqr/discussions/2501
