### ISSUE TITLE
Update Pathogenicity override information on variant page

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3578]
**Is your feature request related to a problem? Please describe.**
Clearly list pathogenicity override criteria 

**Describe the solution you'd like**
At our last check in, you mentioned it overrides quality (VQSR, GQ, AB). If so, update Pathogenicity override information on the Variant page to include quality. 

<img width="1225" alt="Screenshot 2023-08-28 at 8 21 11 AM" src="https://github.com/broadinstitute/seqr/assets/37872186/c69dda08-58e8-4784-8769-9361d3590506">

**Describe alternatives you've considered**
NA

**Additional context**
Discussed with analysts

**Comment by hanars** [comment]
we do not mark issues as closed until they have been released to production, this will go in the next release
