### ISSUE TITLE
Change hover over text for SpliceAI on the Variant Page

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3579]
**Is your feature request related to a problem? Please describe.**
Need to include information on what it is doing when selecting search parameters. It is not clear to users that this overrides some other parameters. 

**Describe the solution you'd like**
Mention what SpliceAI overrides, similar to how we show it for the Pathogenicity override. 
<img width="1254" alt="Screenshot 2023-08-28 at 8 25 51 AM" src="https://github.com/broadinstitute/seqr/assets/37872186/0e6b265d-e673-40e8-b52f-d7baf1237573">

**Describe alternatives you've considered**
NA

**Additional context**
Discussed with the analysts

**Comment by hanars** [comment]
updated
