### ISSUE TITLE
Update Mito GQ filter

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3580]
**Is your feature request related to a problem? Please describe.**
'GQ' for ES and GS mito variants is not the right term nor is it relevant. Additionally, the current 'GQ' for ES is always -10 which filters out the variants. Per Sarah, we should filter on coverage, heteroplasmy level (already in seqr), and the absence of flags like "common_low_heteroplasmy", "indel_stack" (to be added).

**Describe the solution you'd like**
1. Remove GQ from hover over for ES and GS mito variants on the variants page
2. Do not filter on GQ for ES and GS mito variants
3. Include flags/ warnings (if not already) such as "common_low_heteroplasmy", "indel_stack" under Filter Value, i.e. Pass variants mean no flags. We will need to update the hover over. A line can be included below current text about Hard, VQSR filters, "For mitochondrial variants, show variants that have PASSed quality filters (such as common_low_heteroplasmy) or show all variants"
<img width="1241" alt="Screenshot 2023-08-28 at 8 37 08 AM" src="https://github.com/broadinstitute/seqr/assets/37872186/7bbd2209-d9b2-4012-b602-fcff232a674a">

**Describe alternatives you've considered**
NA

**Additional context**
Discussed with analyst team

**Comment by hanars** [comment]
Point 3 which updates how filtering works will require updates to the pipeline and reloading all the data

**Comment by lynnpais** [comment]
No longer requires pipeline updates

**Comment by hanars** [comment]
Hi Lynn, this actually added more confusion for me for understanding this ticket. Currently, things that are in the VCF as "filters" ARE already being filtered by the "pass only" quality filter. This ticket was requesting a change to ALSO filter out variants with common_low_heteroplasmy or other flags that are already available in the seqr data. Can you please provide screenshots of variants that you would like to be filtered out by the pass filter that are currently being returned, and indicate what on that variant you want to be filtered out?

Canges to display of variants unrelated to filtering, such as changing how common_low_heteroplasmy is shown are unrelated to changes in filtering and need their own ticket

**Comment by lynnpais** [comment]
Updating per our discussion, for this ticket we only need to - 
1. Remove GQ from hover over for ES and GS mito variants on the variants page
2. Do not filter on GQ for ES and GS mito variants

Will submit another ticket if any additional work is needed.

**Comment by hanars** [comment]
Implemented for hail backend, will go live once backend is live

**Comment by hanars** [comment]
the final set of changes are now live
