### ISSUE TITLE
cannot empty text field

### ISSUE THREAD

**Issue by zhanglw05** [broadinstitute/seqr#3582]
Final form convert '' to undefined, and thus we cannot empty a text field, like family desc. We tried to add https://final-form.org/docs/react-final-form/types/FieldProps#parse this fix, but this break other form functionality in seqr. I do not see a fix in your code. How you get rid of this default behaviour of final form?

**Comment by hanars** [comment]
this has been fixed in the latest seqr release, thanks again for letting us know about the issue
