### ISSUE TITLE
RGP_1004_1 Sample ID Change + Pedigree

### ISSUE THREAD

**Issue by gshah21** [broadinstitute/seqr#3594]
**Describe the bug**
I need to change the Sample ID for RGP_1004_1 to RGP_1004_1_2. Every time I try to, it doesn't let me because it wants  RGP_1004_mggf and RGP_1004_mggm to be added as Individual ID (screenshot below). However, they are already added. What I'd expect to happen is the Individual ID changed from RGP_1004_1 to RGP_1004_1_2 and for the pedigree to reflect all the relationships accordingly (right now the pedigree is not showing relations properly).

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/...
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F027962_rgp_1004

**Scope of the bug**
This only seems to be happening to RGP_1004 within the HMB project.
However, this issue needs to be resolved in order for the latest RGP callset data to be loaded in seqr.

**Screenshots**
![Screenshot 2023-09-08 at 1 38 48 PM](https://github.com/broadinstitute/seqr/assets/70112261/be81412d-6ab2-4a71-bfbf-4665471ac99e)

Please reach out to me via slack (Lalai Shah) if I haven't explained the issue clearly. Thanks for your help!

**Comment by hanars** [comment]
You cannot change an Individual ID from this form. To change the Individual ID, use the "Bulk Edit Individuals" functionality, and explicitly set the "Previous Individual ID" column. You also can not set a parental ID if the parent is not in seqr. You can add more Individuals in the bulk update data if there are parents you want to add to seqr

**Comment by hanars** [comment]
This also seems like what you are doing goes against our standard best practices for how we handle Individual data in seqr projects/ RGP. You may want to discuss the changes you are making with someone else who would usually be in charge of these sorts of changes, to make sure what you are doing is, in fact, what you want to be doing

**Comment by gshah21** [comment]
Hi Hana! Thank you for letting me know, I was able to change the Individual ID like you suggested and it worked perfectly! When I was trained, the way I was shown to change individual IDs is how I explained previously. If this is not the right way, I will no longer do it like this since I'm the one who often changes Individual IDs for the RGP project. 

Unfortunately, the pedigree still looks messy. It should have 4 generations as we've uploaded all the necessary IDs. I'm happy to draw out a pedigree if that would help you visualize it easier. Is there a way to fix the pedigree?

**Comment by hanars** [comment]
seqr github issues are used to report bugs and feature requests to the seqr engineering team. The seqr engineering team is not a seqr support team and does not have the bandwidth to help with basic seqr usage questions. Please reach out to someone on your team with expertise in this are to get adivoce on resolving this issue. Unless there is a specific bug preventing you from doing your job, this is not a reasonable request to make of our engineers

It is also inappropriate to share restricted data such as pedigrees in a public github repositpory. I will delete the image you shared.

**Comment by gshah21** [comment]
Sounds good, I apologize for any inconvenience!
