### ISSUE TITLE
Noncoding exon transcript variant (canonical) filter not working as expected

### ISSUE THREAD

**Issue by Glemiret** [broadinstitute/seqr#3602]
**Describe the bug**
We tried the new annotation option adding "non-coding transcript exon variant (**canonical**)" in the annotations selection of a recessive restrictive search for **RGP_248** (the use case in which we would want variants in RNU4ATAC returned). The variants are not returned. The variants are returned if "non-coding transcript exon variant (**all**)" is selected as an annotation for the first and second hit, which was seqr behavior before the addition of this new annotation option. 

The variants are returned on a recessive permissive search, but under CLASP1 (the coding gene at that locus) which was seqr behavior before the addition of this new annotation option. I currently get an error message when selecting "non-coding transcript exon variant (all)" in a recessive permissive search.

We tried on another seqr family **(MAN_2071)**, another family with variants in RNU4ATAC. The same thing happens. Variant pair in RNU4ATAC (and displayed as RNU4ATAC and not CLASP1) are returned only on a recessive permissive search when "non-coding transcript exon variant (**all**)" is selected as an annotation (not returned when "non-coding transcript exon variant (**canonical**)" is selected). 

**Our questions:** 
1) It seems that the "non-coding transcript exon variant (**canonical**)" annotation is not behaving as is was intended to. Do you know why? 
2) What is the difference between "non-coding transcript variant" and "non-coding transcript variant (all)" in the current annotation list? See screenshot below. Should one be removed? 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/6349385e73ad2ed50eba70669cb6a828?page=1&sort=xpos
https://seqr.broadinstitute.org/variant_search/results/307e877eb0f7808b0ab8932f6f9d7fb0?page=1&sort=xpos

**Scope of the bug**
We tested this annotation only in RGP_248 and MAN_2071

**Screenshots**
![Screenshot 2023-09-12 at 11 10 02 AM](https://github.com/broadinstitute/seqr/assets/84086816/a77e34b1-7ba1-456c-abaa-408780739a50)

**Comment by hanars** [comment]
> 1. It seems that the "non-coding transcript exon variant (canonical)" annotation is not behaving as is was intended to. Do you know why?

Nothing off the top of my head, it looks like there is a bug that needs fixing

> 2. What is the difference between "non-coding transcript variant" and "non-coding transcript variant (all)" in the current annotation list?

You have a typo in your question. One is "non-coding transcript variant"  and one is "non-coding transcript EXON variant (all)" . These are different annotations output by VEP, I do not know the details of what  "non-coding transcript variant" without the "exon" means in VEP, but its a separate annotation

**Comment by Glemiret** [comment]
Thank you Hana. I'll look into this separate VEP annotation.

**Comment by hanars** [comment]
this bug is now fixed, and the variants are coming back as expected in the linked searches
