### ISSUE TITLE
Move sample metadata to summary data view in seqr

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3612]
**Is your feature request related to a problem? Please describe.**
We would like to allow sample metadata access to seqr users other than analysts

**Describe the solution you'd like**
Move sample metadata into Summary Data section in seqr. 

Change default to skip Airtable information. 

**Describe alternatives you've considered**
NA

**Additional context**
From today's discussion. Can be done after V3 migration.

**Comment by hanars** [comment]
this is done
