### ISSUE TITLE
Update seqr's terms of use

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3617]
**Is your feature request related to a problem? Please describe.**
Our terms of use needs to be updated. We received the go ahead from Sarah. 

**Describe the solution you'd like**
The revised terms are here - https://docs.google.com/document/d/1WVGlteSGued5RGVId_4YddRB0P76SVkceEjgpiScAJ0/edit?usp=sharing

**Describe alternatives you've considered**
NA

**Additional context**
Discussed this morning.

**Comment by hanars** [comment]
these have been updated
