### ISSUE TITLE
Update hover over text for in silicos scores with source of recommendations

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3618]
**Is your feature request related to a problem? Please describe.**
We'd like clearly list the source for the recent changes to the color ranges for the in silico scores.

**Describe the solution you'd like**
In the hover over, add the text, "Based on 2022 ClinGen recommendations (PMID: [36413997])"(https://pubmed.ncbi.nlm.nih.gov/36413997)

This is only relevant to the in silico scores that were recently updated - https://github.com/broadinstitute/seqr/issues/3505

**Describe alternatives you've considered**
NA

**Additional context**
Discussed today.

**Comment by hanars** [comment]
thsi should also include showint the range for colors, not just <

**Comment by hanars** [comment]
updated
