### ISSUE TITLE
Change 'De Novo/Dominant Restrictive' saved search GQ threshold to 30

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#3627]
**Is your feature request related to a problem? Please describe.**
We assessed all previously flagged de novo XL discovery variants in the RGP cohort. Surprisingly, 4 out of 10 are missed with our current quality threshold due to paternal GQ30 (which seems to be a common paternal GQ on de novo chrX variants in WGS). In an RGP-wide trio search, I found 33 high-quality XL variants called de novo and only 48% were captured with a GQ40 filter, whereas 67% were caught with a GQ30. (XL variants missed by both were low ab and/or not truly de novo). Given the historically high ‘solve’ rate of de novo XL variants, the analysts have decided to reduce the GQ threshold to 30 only for the 'De Novo/Dominant Restrictive' saved search. This increases trio searches by 1-2 variants without significantly changing proband-only or duo searches. 

**Describe the solution you'd like**
Change the De Novo/Dominant Restrictive saved search Genotype Quality threshold to 30. 

**Describe alternatives you've considered**
We have considered changing all saved searches to GQ30 but there are too many poor-quality variants returned without much gain. We also considered changing the saved searches to default 'affected only' quality filters, but that also returned too many poor-quality variants. 

**Additional context**
Example of paternal GQ30 in a high-quality candidate:
![image](https://github.com/broadinstitute/seqr/assets/44381119/7efdedaf-84ac-42b1-8a58-72624ee5ff8a)

**Comment by hanars** [comment]
Is there a reason we are not instead using a higher GQ cutoff with the "affected only" option? This feels like it would be a more direct solution to this issue

**Comment by stephditroia** [comment]
I don't disagree with you and think that strategy would help with duo/proband-only case analysis. We haven't looked closely enough at what a comfortable "affected only" threshold would be. I'll bring this idea back to analysis meeting.

Any issues with reducing the GQ for this search in the meantime?

**Comment by hanars** [comment]
not really, but feature requests generally don't get implemented for at least a week or two so it seems like by the time I get around to this you may have had time to reconsider is all. Also, its kind of annoying to update saved searches and I try to do it infrequently, so if we are going to make updates like a week apart I would rather hold off and do one round

**Comment by stephditroia** [comment]
Broad analysis team is collecting data on whether lowering GQ for the family, raising GQ with the "affected only" option, or using the "affected only" option with the current GQ is the best solution to this de novo XL variant issue. None are ideal so we are gathering more data. I will update here with our conclusion and rationale once we've decided.

**Comment by Caustint** [comment]
The analyst team has reviewed and we have settled on lowering GQ to 30 for both the de novo/dominant restrictive **_and_** permissive searches. The analysts feel strongly that all variants returned by the restrictive searches should also be present in the permissive search results. We find that using the "affected only" option in the de novo/dominant permissive search adds too many variants and we'd have to increase GQ beyond a comfortable cutoff (>70) to counteract that. Does this make sense? Let me know if you want me to enter a separate ticket for the de novo/dominant permissive search modification. 

I will note that the analysts frequently make use of the "affected only" toggle option in their custom searches, so that feature has not gone to waste.

**Comment by hanars** [comment]
no additional ticket is needed, I can update both searches as part of this ticket. Thanks for figuring this out!

**Comment by hanars** [comment]
GQ filter has been updated for both dominant searches
