### ISSUE TITLE
Add seqr FAQ in Spanish to webpage

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3638]
**Is your feature request related to a problem? Please describe.**
Improve reach to Spanish speaking individuals

**Describe the solution you'd like**
Add page with [FAQ in Spanish](https://docs.google.com/document/d/1q1bbfMR8S1Uzu9LpkbuvisslTaLu8z-OMu9tTDG2x7g/edit?usp=sharing) to the current [FAQ section in seqr](https://seqr.broadinstitute.org/faq). 

**Describe alternatives you've considered**
NA

**Additional context**
Previously discussed.

**Comment by hanars** [comment]
this is now live https://seqr.broadinstitute.org/faq/es
