### ISSUE TITLE
Use updated logic from config thresholds on Variant Search page.

### ISSUE THREAD

**Issue by bpblanken** [broadinstitute/seqr#3642]
**Is your feature request related to a problem? Please describe.**
Variant Search page does not display color thresholds:
<img width="297" alt="Screenshot 2023-09-29 at 1 35 28 PM" src="https://github.com/broadinstitute/seqr/assets/5325727/2757a2d7-02a7-404b-a4ae-17c8594f8b0f">

**Describe the solution you'd like**
Also show the color thresholds for each predictor:
<img width="197" alt="Screenshot 2023-09-29 at 1 33 58 PM" src="https://github.com/broadinstitute/seqr/assets/5325727/b0d8c20f-e1ac-4fb2-8e65-0504a9a1ff73">

**Describe alternatives you've considered**
NA

**Additional context**
Per discussion [here](https://github.com/broadinstitute/seqr/pull/3637#discussion_r1340685577)

**Comment by hanars** [comment]
this is now live in production
