### ISSUE TITLE
Unable to access saved variants page for some cases

### ISSUE THREAD

**Issue by eoheir** [broadinstitute/seqr#3647]
**Describe the bug**
In certain cases, clicking on the saved variants bar on the family page brings me to a blank page instead of displaying the variants. One of my collaborators is having the same issue as well. 

**Link to page(s) where bug is occurring**
Family page 1: https://seqr.broadinstitute.org/project/R0623_neurodev_wave1_sa/family_page/F039600_859_56662200 
Blank saved variants page 1: https://seqr.broadinstitute.org/project/R0623_neurodev_wave1_sa/saved_variants/family/F039600_859_56662200

Family page 2: https://seqr.broadinstitute.org/project/R0624_neurodev_wave1_kenya/family_page/F039540_860_76414447
Blank saved variants page 2: https://seqr.broadinstitute.org/project/R0624_neurodev_wave1_kenya/saved_variants/family/F039540_860_76414447

Family page 3: https://seqr.broadinstitute.org/project/R0476_cmg_wilkins_haug_exomes/family_page/F027863_wilk_bwh014
Blank saved variants page 3: https://seqr.broadinstitute.org/project/R0476_cmg_wilkins_haug_exomes/saved_variants/family/F027863_wilk_bwh014

**Scope of the bug**
I've noticed this across a few different projects so far (all 3 NeuroDev projects and Wilkins-Haug), but it is not all families - some load normally while others do not. The above links are just a few examples where I've run into this, but let me know if you need more. 

**Screenshots**

<img width="1436" alt="Screenshot 2023-10-04 at 9 34 47 AM" src="https://github.com/broadinstitute/seqr/assets/57765157/5754fbab-4b5d-4378-ac84-d55011b2d5d9">

**Comment by hanars** [comment]
this is actually the same issue as https://github.com/broadinstitute/seqr/issues/3595 but I thought that it was only impacting RGP and turns out its some other projects as well. 

I have now fixed this in all projects
