### ISSUE TITLE
Add AlphaMissense annotations using the VEP plugin

### ISSUE THREAD

**Issue by AlessandroLas** [broadinstitute/seqr#3650]
**Is your feature request related to a problem? Please describe.**
I would like to know if is it possible to to add annotations by VEP plugins and also to use these annotations for filtering the variants.

In particular, I would like to add the AlphaMissense (https://www.science.org/stoken/author-tokens/ST-1429/full) annotations by using the VEP plugin (https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html#alphamissense) and then to use those annotation for sorting/filtering variants.

**Describe the solution you'd like**
 I would like to get the AlphaMissense annotations added to the defaults.

**Describe alternatives you've considered**
I would like to have instructions on how to add VEP plugins (in particular for AlphaMissense).

**Comment by hanars** [comment]
VEP is not configurable in seqr, so there is no way to add this plugin without completely redoing how VEP is called in the pipeline. 

We do plan to incorporate AlphaMissense into seqr, but after evaluating it we have decided that we believe their pre-computed table of all possible SNPs will be a more effective way to integrate this data than via VEP. We are planning to do this integrations, and have a separate ticket to track that work: https://github.com/broadinstitute/seqr/issues/3653 . Therefore, I am going to close out this issue for now, and you can track progress on that ticket

**Comment by AlessandroLas** [comment]
Thanks.
