### ISSUE TITLE
Search using genomic location not working 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3652]
**Describe the bug**
Search using genomic location not working as expected.

**Link to page(s) where bug is occurring**
Example variant I used to run the search below - https://seqr.broadinstitute.org/project/R0594_rare_genomes_project_gen/saved_variants/variant/SV0135898_122660875_f032182_rg

Search page which resulted in the error - https://seqr.broadinstitute.org/variant_search/results/ff4b659bb0e4d3222606ac1c35f72072?page=1&sort=xpos

**Scope of the bug**
Across projects. Reported by an external collaborator. Chrissy and I checked too. 

**Screenshots**

<img width="1308" alt="Screenshot 2023-10-05 at 7 16 42 PM" src="https://github.com/broadinstitute/seqr/assets/37872186/0e9a1d23-655f-47d3-88e2-261759876da3">

**Comment by hanars** [comment]
There is a search box labeled "genes/intervals" and there is a search box right next to it labeled "variants". To search for a specific variant, you have to put it in the "variants" search box, not the "genes/intervals" search box
