### ISSUE TITLE
Add Non-coding transcript exon variant (canonical) to recessive permissive search

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#3683]
**Is your feature request related to a problem? Please describe.**
Related to ticket [2725](https://github.com/broadinstitute/seqr/issues/2725), we'd like variants like the RNU4ATAC ones identified in RGP_248 to be returned in the recessive permissive saved search.

**Describe the solution you'd like**
We'd like to add **Non-coding transcript exon variant (canonical)** to the **Annotations (second hit)** parameters for the recessive permissive saved search only.

**Describe alternatives you've considered**
We considered adding to de novo/dominant searches as well but it adds too many variants to be worth it. Adding noncoding transcript exon variant (all) returns too many hits as well. 

**Additional context**

**Comment by hanars** [comment]
blocked on receiving clarification

**Comment by Caustint** [comment]
Thanks for reminding me of the first vs second hit distinction, particularly for homozygous variants. I suspect we had lost sight of this when creating the current recessive permissive saved search, and I think it would make sense to modify the search so the second hit is the more permissive one (ie remove homozygous/hemizygous UTR and silent variants from our search results). I'm guessing the best approach would be for me to save a new search on my account that reflects all the changes I'd like to make?

**Comment by hanars** [comment]
yes, you making the new search would be perfect

**Comment by Caustint** [comment]
I saved the search as "Recessive permissive update 11-06-23"

Thanks!

**Comment by hanars** [comment]
standard search has been updated! Sorry for all the delay and back-and-forth on this
