### ISSUE TITLE
Implement seqr changelog feature

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3690]
**Is your feature request related to a problem? Please describe.**
Need an efficient way to keep users abreast of features updates. 

**Describe the solution you'd like**
Utilize GitHub discussions that users can subscribe to which can be managed by Lynn/ analyst team. Call this section 'Feature updates’. Add a link on the top of the seqr page next to the log in name. 

The content of this page will pull from the RSS feed available for the [Feature Updates](https://github.com/broadinstitute/seqr/discussions/categories/feature-updates) github discussion category. 

See https://github.com/orgs/community/discussions/31#discussioncomment-4048867 for an example of what the URL structure for the category-specific feed looks like

**Describe alternatives you've considered**
This was the best option per our discussion.

**Additional context**
<img width="651" alt="Screenshot 2023-10-26 at 9 07 43 AM" src="https://github.com/broadinstitute/seqr/assets/37872186/0530c03e-34f6-472d-8f8f-a12130fdaec3">

**Comment by hanars** [comment]
Now live at: https://seqr.broadinstitute.org/feature_updates
