### ISSUE TITLE
Mistake on update reference data in seqr code

### ISSUE THREAD

**Issue by TheACKx** [broadinstitute/seqr#3710]
**Describe the bug**
Need to write in update reference data in seqr code  ./manage.py but in documentation it has written manage.py
Wrong one (in docs) : docker-compose exec seqr manage.py update_all_reference_data --use-cached-omim --skip-gencode
Fixed one :  docker-compose exec seqr ./manage.py update_all_reference_data --use-cached-omim --skip-gencode

**Link to page(s) where bug is occurring**
https://github.com/broadinstitute/seqr/blob/master/deploy/LOCAL_INSTALL.md

**Scope of the bug**
It affects all projects.

**Screenshots**
![githuberror](https://github.com/broadinstitute/seqr/assets/129230763/f09145b4-8886-4d31-a916-df1f4c318ee0)
![githuberror2](https://github.com/broadinstitute/seqr/assets/129230763/f6892e7f-8255-4f3c-a338-6f7519783dd2)

**Comment by hanars** [comment]
seqr is an open source platform, and we encourage users that find issue in our documentation to submit a pull request with the necessary updates!
