### ISSUE TITLE
Unable to sort search results by pathogenicity in one family

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#3716]
**Describe the bug**
I will be using case 354A5 in the new [MGH-Pathways-Teaching](https://seqr.broadinstitute.org/project/R0744_mgh_pathways_teaching/project_page) project during a course I am teaching at the end of November. I find that I am able to get results from the de novo/dominant restrictive (~200 variants) and permissive (~594 variants) searches if I sort by position, but if I try to sort by pathogenicity I end up with a completely blank screen that is not fixed by refreshing.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/6894abe833f65d84409492f21d4727c2?page=1&sort=pathogenicity

**Scope of the bug**
Other proband only cases in the same project that return similar numbers of variants (eg https://seqr.broadinstitute.org/variant_search/results/21dd00a6a664dfa0fb40780bfd6a72c9?page=1&sort=pathogenicity) do not have the same issue. The same case is also loaded in the MGH-Pathways project and I am also getting a blank screen there: https://seqr.broadinstitute.org/variant_search/results/153a369f7178f2c5b6cdf4bd4bcda186?page=1&sort=pathogenicity

**Screenshots**
![image](https://github.com/broadinstitute/seqr/assets/67653781/c7f1627e-2feb-4be2-9518-b96a0c789774)

**Comment by hanars** [comment]
This is an error if any gene that has a significant sHet but no computed constraint is returned in search results. There are only 7 such genes total, so it a pretty hard error to run into, but for this particular search there is one variant in such a gene thats returned on the first page if you sort by pathogenicity but the second page if you sort by something else. But you can get a similar issue if you go to a saved variant in one of those genes: https://seqr.broadinstitute.org/summary_data/saved_variants/ALL/ENSG00000276644

**Comment by hanars** [comment]
this search is now working again
