### ISSUE TITLE
Capture users' emails for AnVIL data loading requests

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3721]
**Is your feature request related to a problem? Please describe.**
We'd like to capture users' emails from AnVIL data loading requests.

**Describe the solution you'd like**
A user's email should be captured in the [AnVIL data loading request sheet](https://airtable.com/appUelDNM3BnWaR7M/tbljif5De7AKysdbi/viwxCMYX7wPmBhwEg?blocks=hide) 'email' column.

**Describe alternatives you've considered**
NA

**Additional context**
Currently blocked on PMs needing to create the email field. When done, can work this ticket along with #3720

**Comment by hanars** [comment]
email was already being sent, no change needed
