### ISSUE TITLE
Loss of valid gene annotation 

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#3723]
**Describe the bug**
A previously flagged PTPN23 variant is no longer annotated with a gene in seqr and no longer searchable by gene. The variant is returned by searching genomic coordinates. Variant is coding in the MANE transcript and is high quality. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0594_rare_genomes_project_gen/saved_variants/variant/SV0129093_347411194_f032379_rg

**Scope of the bug**
This is the first I've come across this. I found it while prepping slides. 

**Screenshots**
<img width="1708" alt="image" src="https://github.com/broadinstitute/seqr/assets/44381119/55d456fa-c30a-441b-bb21-946fc65cfa3a">

**Comment by hanars** [comment]
Confirmed that variant has `"sortedTranscriptConsequences": null` in elasticsearch, so issue is upstream of seqr search

**Comment by hanars** [comment]
WAe have confirmed that the VEP annotations are present in the output from running the annotation step of the loading pipeline of the latest RGP callset, but absent from the elasticsaerch index itself. One solution is to just reload RGP and see if that fixes the issue. A disadvantage to that is we will never really know why this failed in the first place though. @bpblanken any thoughts?

**Comment by hanars** [comment]
Reloading the data has fixed this issue
