### ISSUE TITLE
Investigate updating reference data to gnomAD v4

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3727]
**Is your feature request related to a problem? Please describe.**
Need to update to gnomADv4

**Describe the solution you'd like**
Investigate updating reference data to gnomAD v4 including what's new in the data

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by gilmorera** [comment]
Hi @lynnpais @bpblanken Any progress on this?  If so have you found any caveats to doing the data processing?  My group is about to try it out later this week.

**Comment by hanars** [comment]
This issue is not under current development, so no updates on our end!

**Comment by gilmorera** [comment]
Ok.  I know there was a field change in the gnomad data that required some changes in the hail pipeline for updating to v3.1:  https://github.com/broadinstitute/seqr-loading-pipelines/issues/226#issuecomment-849918364

So I'll respond here if we run into any issues.
