### ISSUE TITLE
Update in silico score information & display

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3728]
**Is your feature request related to a problem? Please describe.**
Need revisions to the work done in #3505 

**Describe the solution you'd like**
1. Spelling/ spacing
All CAPS for - FATHMM, SIFT, CADD, REVEL, MPC, VEST
Requires partial caps and spaces removed for - PolyPhen, MutTaster, MutPred, PrimateAI

2. Remove citation in the hover over for SpliceAI and MPC as they were not changed/ not included in the new guidelines published

3. Reorder the scores as follows
CADD, REVEL, VEST, Mutpred2, MPC, SpliceAI. Others can go in the show more section.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by jklugherz** [comment]
@lynnpais 
#2 says to remove citations for two in silico predictors. should I replace the citation with an older guideline or just remove the citation?
![image](https://github.com/broadinstitute/seqr/assets/25799914/6a9f6d28-d643-4101-ae53-08633b2d01e3)

**Comment by hanars** [comment]
They are different versions of the same score. The actual versioning of the data is handled in the seqr loading pipeline and search backend, from the front end perspective the API response should have `mutpred` as the name of the field in the response, and we should show it to the user without the version number

**Comment by jklugherz** [comment]
out of the possible [predictors](https://github.com/broadinstitute/seqr/blob/6bd1328dad35c2182afb64b9756bd0a46cd13461/ui/shared/utils/constants.js#L1314), which ones _do_ require a citation in the hover over?

**Comment by hanars** [comment]
> out of the possible [predictors](https://github.com/broadinstitute/seqr/blob/6bd1328dad35c2182afb64b9756bd0a46cd13461/ui/shared/utils/constants.js#L1314), which ones _do_ require a citation in the hover over?

cadd
fathmm
gerp
mpc
mut_pred
polyphen
primate_ai
revel
sift
vest

**Comment by hanars** [comment]
these have been updated
