### ISSUE TITLE
Incorrect inheritance_description in sample metadata

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#3731]
**Describe the bug**
Sample metadata for MAN_2480 lists the TBX3 heterozygous variant as de novo instead of autosomal dominant. The variant is present in the affected father and two affected children. We do not have data on the father's parents. 

**Link to page(s) where bug is occurring**
Metadata: https://seqr.broadinstitute.org/summary_data/sample_metadata/R0583_gregor_manton_wes
Variant: https://seqr.broadinstitute.org/project/R0583_gregor_manton_wes/saved_variants/family/F043569_man_2480/Known%20gene%20for%20phenotype

**Scope of the bug**
The curation team caught this. I have not seen an incorrect inheritance before, but I have not checked either.

**Screenshots**
<img width="221" alt="image" src="https://github.com/broadinstitute/seqr/assets/44381119/8aa02a9d-e1e2-46d8-9372-0a5fdc12d242">
<img width="1323" alt="image" src="https://github.com/broadinstitute/seqr/assets/44381119/3a9cd5c7-1985-4543-a40d-5f8a8511591d">
<img width="1302" alt="image" src="https://github.com/broadinstitute/seqr/assets/44381119/02af6629-e925-4bbe-96d6-887186bc1e21">

**Comment by hanars** [comment]
now correctly reporting as AD

**Comment by stephditroia** [comment]
@hanars I'm finding a few more of these in the RGP findings table. Not urgent to fix, but wanted to see if you uncovered a larger issue when fixing the case reported in this ticket? I am keeping track of the ones I've found.

**Comment by hanars** [comment]
The genetic findings table in the gregor reports actually shares no code at all with the sample metadata or CMG AnVIL reports. So that would be a separate bug report. If you are talking about RGP in the sample metadata table, then we should reopen this issue and you should add links to where you are seeing the issue

**Comment by stephditroia** [comment]
Here are families where seqr metadata lists _de novo_ inheritance without both parent samples. Unlike the example above, these families are mostly duos (affected proband with one unaffected parent). This list only includes examples from GREGoR WES projects and Rare Genomes GRU project, so there are likely many more. The correct inheritance for these variants should be Autosomal dominant (consistent with the logic of single het variants in proband-only cases). 

- ENN_083
- ENN_031
- RGP_2333 (proband with unaffected sibs)
- RGP_2172
- RGP_2107
- RGP_2442
- RGP_2123
- RGP_2035

**Comment by stephditroia** [comment]
Heterozygous variants in proband-only cases are currently reported as Autosomal dominant. See: 
RGP_2028
RGP_2058
RGP_2058
RGP_2133
RGP_2142
RGP_2347
RGP_2396
RGP_2587
RGP_2626

At a minimum we should be consistent with reporting het variants across proband-only and duo cases. I also strongly feel we should not claim _de novo_ status if we do not have the data to confirm it, but fine to wait until sign off from Sam and PMs.

**Comment by hanars** [comment]
As an FYI, I am very hesitant to make changes to a report that we have been submitting unchanged for years. I think changing the logic of what we report will probably create headaches and confusion as we run into issues where there are inconsistencies between older and newer submissions and where things change within projects. For the new gregor reports I am of course happy to iterate as those are still new, but the AnVIL CMG report probably needs to remain unchanged. The question of how the sample metadata report should relate to these reports is a bigger question that we should address holistically, not as an ad hoc thing for changing one field. This probably needs a meeting before we have a ticket

**Comment by stephditroia** [comment]
@hanars - were the next steps for changing the inheritance_description logic figured out pre-break? I know there were meetings with Sam but not sure where things landed.

**Comment by hanars** [comment]
Sam submitted this [ticket](https://github.com/broadinstitute/seqr/issues/3778) which transforms the "sample metadata" sheet to an updated "individual metadata" sheet that more closely aligns with the logic we use for gregor reports. It no longer has that inheritance_description logic, it just reports variant_inheritance the way we do for Gregor. Our plan is to take the first draft of this report live and then if there are any changes needed based on that we can create a follow up ticket to make any remaining tweaks

**Comment by stephditroia** [comment]
Sounds perfect. TY!
