### ISSUE TITLE
Add LitVar2 link

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3737]
**Is your feature request related to a problem? Please describe.**
Add a link to LitVar to improve the ability to search for variants in literature.

**Describe the solution you'd like**
Add a link to Litvar2 at the end of the current options (PubMed, Mastermind, etc.) we have to search the literature for a specific variant. We can use the ClinGen allele identifier to search variants. Here's an example of the Litvar page for the p.T995I variant in NLRP1 - https://www.ncbi.nlm.nih.gov/research/litvar2/docsum?variant=litvar@CA8326971%23rs34733791%23%23&query=CA8326971

**Describe alternatives you've considered**
NA

**Additional context**
Requested by an AnVIL user, but is also useful to other analysts.

**Comment by hanars** [comment]
We generally do not have the clingen allele identifier for most seqr variants, it would be hard to add it. For MVP lets use hgvs or rsid

**Comment by hanars** [comment]
done. Note this is only available for variants with both RSID and CAID
