### ISSUE TITLE
Unable to access the saved variants page in one family

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3747]
**Describe the bug**
Unable to access the saved variants page when selecting the colored bar on the Family Page. I get a blank screen even after refreshing.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F028471_rgp_1101

Family page - https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F028471_rgp_1101

**Scope of the bug**
Tried one other RGP case which is fine, so this maybe case specific

**Screenshots**

**Comment by hanars** [comment]
this is family specific

**Comment by hanars** [comment]
So this family has a pair of comp hets that were tagged together, but now somehow seem to have no shared gene. That should be totally impossible, so the display for this in seqr is breaking. The variants can be viewed separately with no issue here:

https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/variant/SV0109168_34467031_f028471_rgp
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/variant/SV0109169_34163187_f028471_rgp

Any idea what happened here? I can change these to 2 separately tagged review variants and that will fix the issue, but will sort of remove the reason they were tagged. We can also investigate which variant lost a gene annotation and why if you think that is important. It would be helpful if you happened to remember which gene they used to share, it look slike @lynnpais you were the one to originally tag them
