### ISSUE TITLE
Error when re-submitting a form while new file is still uploading

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3750]
**Describe the bug**
An AnVIL user encountered the error below when trying to put in a data loading request for a subset of samples.

He noted, "I deleted the project and uploaded again the VCF file, then the pedigree CSV file, this time with only 4 individuals, and it generated the error below. This error was generated the previous time too, but I clicked Submit and at that point the error disappeared and the system warned that there was a different number of subjects between the VCF and the pedigree. I then loaded a pedigree with all 54 subjects and the submission was accepted".

The request did come through finally.

**Link to page(s) where bug is occurring**
NA

**Scope of the bug**
Affecting the AnVIL data loading pipeline

**Screenshots**
![image](https://github.com/broadinstitute/seqr/assets/37872186/cc5f22e9-3240-4f9c-b8a1-f41f4becfba3)

**Comment by hanars** [comment]
this is fixed so this should not happen for subseuent users
