### ISSUE TITLE
Sample metadata access error

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3754]
**Describe the bug**
Alba is trying to download sample metadata to annotate the SV callset but is getting the error, 'not enough values to unpack (expected 3, got 2)' when selecting View all Broad projects under the Sample Metadata tab. I too am encountering the same. 

**Link to page(s) where bug is occurring**
Sample Metadata link - https://seqr.broadinstitute.org/summary_data/sample_metadata
Page with error - https://seqr.broadinstitute.org/summary_data/sample_metadata/all

**Scope of the bug**
NA

**Screenshots**
<img width="1408" alt="Screenshot 2023-11-28 at 9 24 34 AM" src="https://github.com/broadinstitute/seqr/assets/37872186/e2fc17bf-b8c7-44ac-a2d4-79d09f8800aa">

**Comment by hanars** [comment]
triggers unhandled error: https://console.cloud.google.com/errors/detail/CMK93qH0wan2cg;time=P30D?project=seqr-project&utm_source=error-reporting-notification&utm_medium=slack&utm_content=resolved-error

**Comment by hanars** [comment]
this is now fixed
