### ISSUE TITLE
Moving data and notes from CMG project to GREGoR project

### ISSUE THREAD

**Issue by apham98** [broadinstitute/seqr#3757]
**Is your feature request related to a problem? Please describe.**
Data and notes for MUN_FAM8_001_D1 needs to be moved from their CMG project to their GREGoR project.

**Describe the solution you'd like**
Would you be able to copy gCNV data and notes for MUN_FAM8_001_D1 from [CMG_Muntoni_Exomes](https://seqr.broadinstitute.org/project/R0497_cmg_muntoni_exomes/project_page) to [GREGoR_Muntoni_WES](https://seqr.broadinstitute.org/project/R0692_gregor_muntoni_wes/project_page)?

**Describe alternatives you've considered**
Stacey let me know that your capabilities to copy data and notes over may go away so if that has already happened please let me know. Alternatively, would the "Load Data" page on seqr work to load the gCNV for the sample to the GREGoR project?

**Comment by apham98** [comment]
I'm looking to remove MUN_FAM8_001_D1 from the CMG project after the data and notes are moved to GREGoR so I will go ahead and use the "Load Data" page to load the gCNV and have the analyst move over the notes manually. Thank you for the help!

**Comment by hanars** [comment]
please do not use the "Load Data" functionality. I guess I wasn't clear enough, but for now I can add gCNV data for that family without transferring anything else. In the future, once we change the seqr backend, then you will need to use "Load Data", but dfor now that generasted a lot of unneccessary work for a. lot of people instead of a tiny amount of work just for me

**Comment by hanars** [comment]
If you need the gCNV data from the CMG project made available in the Gregor project, you need to let me know and I will handle that

**Comment by apham98** [comment]
Apologies for misunderstanding. By adding the gCNV data from the CMG project to the GREGoR project, would I still be able to remove the family from the CMG project once that is done?

**Comment by hanars** [comment]
yep! But thats an understandable concern

**Comment by hanars** [comment]
all set!
