### ISSUE TITLE
Error viewing saved variants in a single family

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3761]
**Describe the bug**
Selecting the colored saved variants bar on the Family Page leads to a blank screen. This might be similar to the recent issue we discussed. 

**Link to page(s) where bug is occurring**
Family page - https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F030705_rgp_1456
Page with error - https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F030705_rgp_1456

**Scope of the bug**
Family specific. Tho maybe affecting a few. 

**Screenshots**
NA

**Comment by hanars** [comment]
Only affecting families with matchmaker submissions

**Comment by lynnpais** [comment]
Checked with Alba - she is not sure why this happened and/or if it is affecting other variants, so she will check with their pipeline team. She did note that the annotation is fixed in the current release of callset.

**Comment by lynnpais** [comment]
Yes, that's my understanding. 

Alba added additional info - It looks like the Mane select annotation source was missing some genes, this has been fixed now. She also offered to either flag new annotations in the VCF or just share a list/excel file. 

If the latest callset is correct, we shouldn't encounter the issue once we load it. So I think we just get the excel file from Alba (and not have any changes made to the VCF) but let me know if you have other recommendations.





[11:30](https://the-tgg.slack.com/archives/D0324FJJY3B/p1701707440270939)
I am not sure how this may have affected the phase 3 though

**Comment by hanars** [comment]
I'm not sure what we would do with the excel file from Alba though? Its not like thats a thing seqr is able to ingest or do anything with. It seems like the easiest solution is to wait for the next callset and then reload the data and the problem will be solved, but if we need an interim solution we can figure that out

**Comment by lynnpais** [comment]
Per discussion, we will try to load the latest callset. Revisit this ticket if the issue persists.

**Comment by lynnpais** [comment]
Per discussion, we will try to load the latest callset. Revisit this ticket if the issue persists.

**Comment by hanars** [comment]
this is fixed, and the saved variant page is now working again
