### ISSUE TITLE
Ensure AnVIL pedigrees written by the "Write Pedigree" feature are deposited in the right directory.

### ISSUE THREAD

**Issue by bpblanken** [broadinstitute/seqr#3763]
**Is your feature request related to a problem? Please describe.**
The pipeline requires pedigrees from AnVIL to be in the same place as they'll be created from AnVIL loading requests.

e.g.

```
gs://seqr-datasets/v02/GRCh38/AnVIL_WGS/{project_guid}/base/{project_guid}_pedigree.tsv
```

**Describe the solution you'd like**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by hanars** [comment]
this is now live

**Comment by bpblanken** [comment]
There's a bug in this one unfortunately.  Pedigrees are dropping into the wrong location:

```
bblanken@wmbbe-67c seqr-pipeline-airflow % gsutil ls gs://seqr-datasets/v02/GRCh38/RDG_WES_Broad_AnVIL/base/projects
gs://seqr-datasets/v02/GRCh38/RDG_WES_Broad_AnVIL/base/projects/R0579_wiggs_wes_variantcalling
gs://seqr-datasets/v02/GRCh38/RDG_WES_Broad_AnVIL/base/projects/R0582_uci_wes_n21
gs://seqr-datasets/v02/GRCh38/RDG_WES_Broad_AnVIL/base/projects/R0584_chan_cohort_wes_330
gs://seqr-datasets/v02/GRCh38/RDG_WES_Broad_AnVIL/base/projects/R0585_210406_210506_210601_joi
```

**Comment by bpblanken** [comment]
The pedigree for `R0579_wiggs_wes_variantcalling` for example, is being deposited as a file here:

```
gs://seqr-datasets/v02/GRCh38/RDG_WES_Broad_AnVIL/base/projects/R0579_wiggs_wes_variantcalling
```

when it should be:

```
gs://seqr-datasets/v02/GRCh38/AnVIL_WES/R0579_wiggs_wes_variantcalling/base/R0579_wiggs_wes_variantcalling_pedigree.tsv
```

**Comment by matren395** [comment]
this issue for sample_ids just recurred in `gs://seqr-datasets/v02/GRCh38/AnVIL_WGS/R0761_icgd_collaboration_raj_g/base`, which should be something like `gs://seqr-datasets/v02/GRCh38/AnVIL_WGS/R0761_icgd_collaboration_raj_g/base/R0761_icgd_collaboration_raj_g_ids.txt`

**Comment by hanars** [comment]
until this ticket is resolved and the fix is deployed, this will continue to occur

**Comment by hanars** [comment]
this is now deployed so this should stop happening, let me know if this continues for some reason
