### ISSUE TITLE
Show Gene Expression button doesn't always appear on initial variant search results, but then appears on browser refresh

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#3765]
For example, this variant search:
https://seqr.broadinstitute.org/variant_search/results/38ef157d97f165da2e4ffd9109c99f0e?page=1&sort=in_omim
<img width="1634" alt="image" src="https://github.com/broadinstitute/seqr/assets/6240170/d7b566fb-8902-4a59-a2fd-ccaee0021a72">
initially shows all variants without a "Gene Expression" button
<img width="1031" alt="image" src="https://github.com/broadinstitute/seqr/assets/6240170/42055a5d-e385-461c-867d-a4312a8973d2">

but the button appears if I then refresh the page 
<img width="975" alt="image" src="https://github.com/broadinstitute/seqr/assets/6240170/fbf7f416-522e-46a0-a041-e4f0ce9a9f4e">

This might be related to the same issue which was fixed earlier:
https://github.com/broadinstitute/seqr/issues/3592

**Comment by hanars** [comment]
this appears to be a bug related to whether the URL has `loadFamilyContext=false` vs `loadFamilyContext=true`

**Comment by hanars** [comment]
this is now fixed
