### ISSUE TITLE
TransportError: 500 - '' - no detail

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3766]
**Describe the bug**
The seqr link on the Variants Page to search for that variant in the callset is throwing an error. In this example, there are 20 other alleles in the callset. 

**Link to page(s) where bug is occurring**
Variant for which I tried the seqr link shown beneath the chrom coordinates - https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/variant/SV0149276_2223766252_f031620_r
Page with error - https://seqr.broadinstitute.org/variant_search/results/21be18a94ed80b7106839ff04dea7b2c?page=1&sort=in_omim

**Scope of the bug**
Multifamily. Same error when I tried it in RGP_2015 - https://seqr.broadinstitute.org/variant_search/results/0beefdc40d80d1bae52191218f0d5109?page=1&sort=in_omim

**Screenshots**
<img width="1299" alt="Screenshot 2023-12-01 at 9 29 05 AM" src="https://github.com/broadinstitute/seqr/assets/37872186/ba6fecd3-00ce-4e19-a42d-8486e4a23f0e">

**Comment by hanars** [comment]
Error alert: https://console.cloud.google.com/errors/detail/CLyou-zJpNz4Yw;time=P30D?project=seqr-project

**Comment by hanars** [comment]
This is now fixed and both links are working. I think it was an error with space/ node allocation because cleaning up ~1Tb of unused indices and waiting for the cluster to rebalance seems to have fixed the issue
