### ISSUE TITLE
Family metadata report

### ISSUE THREAD

**Issue by sambaxter** [broadinstitute/seqr#3779]
**Is your feature request related to a problem? Please describe.**
We would like to create a family metadata report that will replace the CMG discovery sheet.  The CMG discovery sheet can be deleted.

**Describe the solution you'd like**
Please update the new individual metadata sheet to include the fields in column D of [this sheet](https://docs.google.com/spreadsheets/d/1pluDJN57tXS7QhyG2_J9HPMa6jP2cWtifDkMLse7PVU/edit#gid=860014992)

**Describe alternatives you've considered**

**Additional context**
Add any other context, links to relevant seqr pages, or screenshots about the feature request here.

**Comment by hanars** [comment]
This has been added to seqr
