### ISSUE TITLE
Variant metadata report

### ISSUE THREAD

**Issue by sambaxter** [broadinstitute/seqr#3780]
**Is your feature request related to a problem? Please describe.**
We would like to create a new metadata report called the Variant metadata.  This will be based heavily on the [genetics findings table](https://github.com/broadinstitute/seqr-private/issues/1289#issuecomment-1816761636) including the logic that this will only be variants with a discovery tag in a proband.

**Describe the solution you'd like**
Please update the new individual metadata sheet to include the fields in column G of [this sheet](https://docs.google.com/spreadsheets/d/1pluDJN57tXS7QhyG2_J9HPMa6jP2cWtifDkMLse7PVU/edit#gid=860014992)

Ideally this is Indexed off genetic_findings_id but it is sorted by Project ID -> Family ID -> Participant ID 
Unless stated otherwise directly pull from genetics findings table

**Additional context**
Add any other context, links to relevant seqr pages, or screenshots about the feature request here.

**Comment by hanars** [comment]
This has been added to seqr

**Comment by stephditroia** [comment]
Hey Hana - is it possible to move the variant metadata report to `Summary Data`. Both UW and Stanford GREGoR sites have asked if I know of an easy way for them to make the GREGoR findings table from seqr, and this would be it.

**Comment by hanars** [comment]
yeah thats possible, it would need a new ticket though
