### ISSUE TITLE
Login causes ERR_TOO_MANY_REDIRECTS 

### ISSUE THREAD

**Issue by chloereuter** [broadinstitute/seqr#3782]
Clicked "Sign In" on the seqr home page. Logged in to my Google account. The page throws ERR_TOO_MANY_REDIRECTS.

<img width="1003" alt="image" src="https://github.com/broadinstitute/seqr/assets/153759387/c2150aca-f230-4e5f-a42b-27c5d37beab3"> 

Tried to clear cookies, restart computer, use incognito mode and nothing worked. 

May be related to bug #3075 (Login causes ERR_TOO_MANY_REDIRECTS)

Link to page(s) where bug is occurring
https://seqr.broadinstitute.org/

**Comment by hanars** [comment]
Yes, there is a banner explaining the situation on the seqr homepage. You need to log in to [anvil](https://anvil.terra.bio/) and accept the terms of service

<img width="1507" alt="Screenshot 2023-12-13 at 1 56 34 PM" src="https://github.com/broadinstitute/seqr/assets/24598672/36e3384b-d4b5-4380-b05c-17cfee3369a2">
