### ISSUE TITLE
Copy to clipboard button for chr position

### ISSUE THREAD

**Issue by msingerb** [broadinstitute/seqr#3796]
**Is your feature request related to a problem? Please describe.**
It gets annoying to highlight and copy the chr position for either HG19 or HG38 and avoid clicking on the links to UCSC.

**Describe the solution you'd like**
Can we have a link added, either next to or below the hg19 and hg38 coordinates that allows you to quickly copy the position. The best solution would be to copy it in the format of Chr-position. I think another option would be to just copy the position number and not the chromosome. This would be the most helpful.

**Describe alternatives you've considered**
Another option would be to have a hover over option that allows you either to click the link to UCSC or copy the position for both the hg19 and hg38 positions. 

**Additional context**
As we are moving away from Hg19 I do think this is most important for Hg38. Its also easier to copy the hg19 coordinates right now since it doesn't have the ref/alt next to it.

**Comment by hanars** [comment]
@lynnpais after the break can you weigh in on which of these proposed solutions we should go with, all of them are very straightforward so its just a product decision

**Comment by lynnpais** [comment]
Decided to add a copy button next to the Hg38 coordinate

**Comment by hanars** [comment]
button has been added
