### ISSUE TITLE
Clear notes and tags from GREGoR Training Projects E,F,G

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#3800]
**Is your feature request related to a problem? Please describe.**
I'm hoping to using GREGoR Training Projects E, F, G, and H to teach a class this Friday, 1/5/24. 

**Describe the solution you'd like**
GREGoR Training Project H is already clear but if you could clear notes and tags from E, F, and G I would really appreciate it!

**Describe alternatives you've considered**

**Additional context**
https://seqr.broadinstitute.org/project/R0611_gregor_training_project_/project_page
https://seqr.broadinstitute.org/project/R0612_gregor_training_project_/project_page
https://seqr.broadinstitute.org/project/R0613_gregor_training_project_/project_page

**Comment by hanars** [comment]
done!
