### ISSUE TITLE
GTEx data not displaying on gene page

### ISSUE THREAD

**Issue by eoheir** [broadinstitute/seqr#3819]
**Describe the bug**
The GTEx tissue-specific expression data is currently not showing up on any gene pages.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/summary_data/gene_info/ENSG00000175701 

**Scope of the bug**
All projects

**Screenshots**
<img width="1435" alt="Screenshot 2024-01-11 at 1 35 15 PM" src="https://github.com/broadinstitute/seqr/assets/57765157/e2344e55-1a5c-479f-b38b-92d1486f8d72">

**Comment by hanars** [comment]
GTEX has deprecated the version of their API we were using :( Will update to the latest version ASAP

**Comment by hanars** [comment]
This is also impacting viewing expression data for specific genes on variants - for example selecting any of the "Show Gene Expression" buttons on this page: https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F027968_rgp_1017

The error handling for this behavior is really nice so it does not look like theres an issue, but the graph should show a bar for GTEX and that is currently not being shown

**Comment by hanars** [comment]
GTEX is now working again
