### ISSUE TITLE
Add user to seqr with access to all projects

### ISSUE THREAD

**Issue by msingerb** [broadinstitute/seqr#3825]
**Is your feature request related to a problem? Please describe.**
no problem

**Describe the solution you'd like**
I'd like this user (ebroeren@broadinstitute.org) to have analyst access to all seqr projects. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by hanars** [comment]
analayst status is handled by the PM team, not the seqr engineering team. Ask the PM team to add her to all the standard user groups in Terra/AnVIL
