### ISSUE TITLE
Saved Variant page not opening for families in seqr

### ISSUE THREAD

**Issue by kathrynrussell** [broadinstitute/seqr#3866]
**Describe the bug**
I'm able to log into seqr and open a family page as normal, but when I click the colorful "saved variant" bar, the page that opens is completely white with no content. I'm not able to see any variants or variant info. 

**Link to page(s) where bug is occurring**
This is an example page where the saved variants aren't showing up. 
https://seqr.broadinstitute.org/project/R0285_cmg_gleeson_exomes/saved_variants/family/F013583_3871

**Scope of the bug**
I've tried a handful of projects and this seems like it's happening for all of them. However, I've asked a few other seqr users, and this seems like it's only happening for me. 

**Screenshots**
<img width="1512" alt="Screenshot 2024-02-09 at 11 35 50 AM" src="https://github.com/broadinstitute/seqr/assets/146103793/a52fd1a0-3e1b-4e97-9792-f097538d4454">

<img width="1511" alt="Screenshot 2024-02-09 at 11 35 59 AM" src="https://github.com/broadinstitute/seqr/assets/146103793/0091e07b-3638-498f-aaee-1ba44e768d1b">

**Comment by hanars** [comment]
Stepahnie also had this issue in an RGP family: https://github.com/broadinstitute/seqr/issues/3874

**Comment by lynnpais** [comment]
Will this issue be fixed before we move to v3?

**Comment by hanars** [comment]
they will go out together in the same release

**Comment by lynnpais** [comment]
[Analyst high priority](https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/Analyst%20high%20priority) link results in a blank page - https://seqr-dev.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/Analyst%20high%20priority

This seems to be happening only to the variants tagged Analyst high priority in the RGP project. Other variant types are showing, so not exactly identical to the original issue posted here.
