### ISSUE TITLE
Link to SpliceAI scores "masked scores" box checked

### ISSUE THREAD

**Issue by carmenglaze1** [broadinstitute/seqr#3867]
**Describe the bug**
the automatic link to spliceAI scores is not going to the default where the "masked scores" checkbox should be unchecked

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/...

**Scope of the bug**
Are you experiencing this issue in all projects? Within specific families within one project?

All projects

**Screenshots**

![Screenshot 2024-02-09 114003](https://github.com/broadinstitute/seqr/assets/146103822/19faa1fe-f5c9-41a7-acf2-30bb9bd6ac61)
![Screenshot 2024-02-09 114010](https://github.com/broadinstitute/seqr/assets/146103822/a4f9ad22-86b1-4044-81b8-08735f4bbb6b)

Attached is a screenshot of the seqr page with automatic link to spliceAI and then a separate screenshot of spliceAI and what the default should be, with the "masked scores" box unchecked

**Comment by hanars** [comment]
Hi Carmen, in addition to screeshots you should always provide a link to the page where the bug is occuring when submitting bugs. In this case, you should also be providing links to the page that is being linked to, and the page you would instead want it to link to.
Thanks!

**Comment by carmenglaze1** [comment]
Thanks Hana! I will be sure to add links in future requests. For this one, I wasn't sure since this is happening in all seqr projects not just one family.

Seqr page: https://seqr.broadinstitute.org/project/R0562_mgrc_bonnemann_wes/saved_variants/family/F033997_bon_b21_10/Tier%201%20-%20Novel%20gene%20and%20phenotype

SpliceAI page that seqr opens:
https://spliceailookup.broadinstitute.org/#variant=17-75592082-T-A&hg=38&distance=1000&mask=1&ra=0

What the SpliceAI should be:
https://spliceailookup.broadinstitute.org/#variant=17-75592082-T-A&hg=38&distance=1000&mask=0&ra=0

**Comment by hanars** [comment]
So the URLs you provided for the page that opens and the page it should be are identical. Please make sure to provide a different url if you want the seqr behavior to change

**Comment by carmenglaze1** [comment]
Hi, the URLs are actually not identical though very similar. The first one, "what seqr opens", has the "masked scores" box checked. You can see in the URL it says "mask=1". In the second URL, "what spliceAI should be", has the "masked scores" box UNchecked. In the URL it says "mask=0". Ideally we want the SpliceAI link on Seqr to open with the "masked scores" box unchecked, so the scores are not masked. Hopefully this better explains what I was hoping to convey. Thanks!

**Comment by hanars** [comment]
oops my bad!

**Comment by hanars** [comment]
okay this is all fixed! sorry again for the confusion

**Comment by carmenglaze1** [comment]
No worries! Thank you Hana!
