### ISSUE TITLE
Make reports available to local seqr installs

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#3881]
**Is your feature request related to a problem? Please describe.**
Both UW and Stanford GREGoR sites have asked if there is an easy way to make the GREGoR findings table from seqr. The new Variant Metadata is very similar to the findings table and would be the best solution for them. Unfortunately, Variant Metadata currently lives in the `Reports` tab, which is an internal resource. 

**Describe the solution you'd like**
We would like to move Variant Metadata from `Reports` to `Summary Data` to give external seqr users access.

**Additional context**
<img width="1316" alt="image" src="https://github.com/broadinstitute/seqr/assets/44381119/fa7e4b21-0d49-4b82-b920-86d55306c153">

**Comment by hanars** [comment]
So I know I said I would do this, but I would like to instead propose that local installations have access to all the reports by default - I think that would be easier in the long run

**Comment by stephditroia** [comment]
Sounds like that would work for this issue.

**Comment by hanars** [comment]
these reports have been moved to the summary data tab

**Comment by hanars** [comment]
Moving the reports from the report tab to the summary data tab has created an unsustainable support burden on the seqr team for the main seqr installation, as now external users with insufficient permissions to configure these projects are seeing these reports. 

The actual solution is to move the reports back to the rpeort tab, but change the permissioning on that tab/ those reports and to expose at least part of the reports tab to local installs by default
