### ISSUE TITLE
SHOW READS is missing on the seqr-wide variant search page

### ISSUE THREAD

**Issue by Ikeoluwa-O-O** [broadinstitute/seqr#3907]
**Describe the bug**
 "SHOW READS" is no longer present on the resulting page of a seqr-wide variant search. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/summary_data/variant_lookup?variantId=phase4_all_batches.chr3.final_cleanup_DUP_chr3_4714&genomeVersion=38&sampleType=WGS&include_genotypes=true

**Scope of the bug**
This issue is occurring in multiple projects (confirmed in [Rare Genomes Project_Genomes_GRU](https://seqr.broadinstitute.org/project/R0594_rare_genomes_project_gen/project_page) + [Rare Genomes Project_Genomes_HMB](https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/project_page) + [GREGoR_Manton_WGS](https://seqr.broadinstitute.org/project/R0587_gregor_manton_wgs/project_page) + [GREGoR_SCHN_WGS](https://seqr.broadinstitute.org/project/R0705_gregor_schn_wgs/project_page) + [GREGoR_SCHN_WES](https://seqr.broadinstitute.org/project/R0559_mgrc_wilson_wes/project_page)). 

**Screenshots**
![Screenshot 2024-02-20 at 5 25 14 PM](https://github.com/broadinstitute/seqr/assets/84587859/3cc8d15d-6c01-4f54-bcff-f7e3f9e9801d)

**Comment by hanars** [comment]
this is now fixed
