### ISSUE TITLE
variant search across seqr error

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#3915]
**Describe the bug**
Looked up a variant in seqr and it has an AC of 9 so wanted to see the other cases with the variant but the search hit a "unexpected end of JSON input" error message. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/summary_data/variant_lookup?variantId=12-120291839-T-TA&genomeVersion=38&sampleType=&include_genotypes=true

This was the original page where I pushed the seqr search link from - in case it's helpful to have this too: 
https://seqr.broadinstitute.org/summary_data/variant_lookup?genomeVersion=38&variantId=12-120291839-T-TA

**Scope of the bug**
I only need to look up this one variant at the moment so didn't search more broadly. 

**Screenshots**
I get this error message (both times that I tried the search - through both this evening)
![image](https://github.com/broadinstitute/seqr/assets/10407888/dadea40d-3c70-4a01-b61f-836481bad15f)

**Comment by hanars** [comment]
This sounds like an error that occurred due to unlucky timing with your request. I just opened the link and it loaded fine, can you try again and confirm whether it is still not working for you?

**Comment by anneodonnell** [comment]
I'm still getting the same JSON error (tried twice) - but I guess it's personal, not a general issue.

**Comment by anneodonnell** [comment]
It ran for me today! I wanted to also mention that the search returns 8 families when the AC in seqr is 9. Should I make a new GitHub ticket for that?

**Comment by hanars** [comment]
No, that 9th allele is in a sample you don't have access to, probably form an AnVIL project. Coming soon: internal variant matching so you can see some info about those alleles!

**Comment by hanars** [comment]
As an FYI, if you do find a case where being able to know about an allele you don't have access to would be really important/ helpful, Ben and I can look them up and tell you the level of info we are allowed to share. It takes us time so it can't be like an all the time request, but for a few important cases its doable
