### ISSUE TITLE
Hover-over popups for gene lists are misaligned

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#3918]
**Describe the bug**
The popups that appear when you hover over the gene list tags on variant search results are misaligned such that they obstruct all the other gene list tags, which makes it hard to scan through the tags when multiple are present. Can we fix so the popups appear above or below the tag (consistent with how other popups behave)?

**Link to page(s) where bug is occurring**
The example used in the screenshot below is this one: https://seqr.broadinstitute.org/variant_search/variant/14-54844022-T-A/family/F023350_rgp_522

**Scope of the bug**
Happens for all variants as far as I am aware. Other popups (eg when you hover over tags for LOF CONSTR, GenCC, ClinGen, etc) look fine, it's just the gene list tags that are problematic. 

**Screenshots**
I drew an arrow to the tag I was hovering over here: 
![image](https://github.com/broadinstitute/seqr/assets/67653781/653ea0fb-d7e6-4ce9-adb6-e66a256512e3)

**Comment by hanars** [comment]
this is now fixed
