### ISSUE TITLE
Blank page when trying to access the Variant Lookup feature

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3932]
**Describe the bug**
Blank Variant Lookup page

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/summary_data/variant_lookup

**Scope of the bug**
NA

**Screenshots**
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0NnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f9047440ee65de9f4881e92f2ab0a2638a9f3bd/Screenshot%202024-02-29%20at%202.40.29%20PM.png" alt="Screenshot 2024-02-29 at 2.40.29 PM.png" />

**Comment by hanars** [comment]
this is now fixed
