### ISSUE TITLE
Hover over option for the saved variants is not working for a particular case

### ISSUE THREAD

**Issue by MugdhaSingh1819** [broadinstitute/seqr#3946]
**Describe the bug**
I am not able to see the saved and tagged variants by other analysts in the hover over option labelled as (Discovery Genes:OSBPL5). This is specific to a particular case. Other cases there is not issue. Link is provided below
**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0303_cmg_manton_exomes/saved_variants/family/F025477_man_1398

**Scope of the bug**
This bug is only specific to a particular case MAN_1398

**Screenshots**
I get a blank screen like below
![Screenshot 2024-03-04 at 4 43 59 PM](https://github.com/broadinstitute/seqr/assets/133809303/a9d90bb2-00b8-499f-a5ce-68c622a9b069)

**Comment by hanars** [comment]
this has now been fixed
