### ISSUE TITLE
RGP recessive search 504 error 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#3947]
**Describe the bug**
Unable to run a recessive permissive search. Tried a couple of times, but end up getting a 504 error.

**Link to page(s) where bug is occurring**
Search page - https://seqr.broadinstitute.org/variant_search/family/F031880_rgp_1817
Page with error -
https://seqr.broadinstitute.org/variant_search/results/6d0ca9bd7a30b532a46ca33c0ce728c4?page=1&sort=in_omim

**Scope of the bug**
Haven't tried other cases. 

**Screenshots**
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2kwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--057269973d27714b3e1585563a08d59634bda74d/Screenshot%202024-03-05%20at%202.10.52%20PM.png" alt="Screenshot 2024-03-05 at 2.10.52 PM.png" />

**Comment by hanars** [comment]
this is now working
