### ISSUE TITLE
Unable to upload table of analyzed family ids via the External Analysis UI

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#3960]
I'm trying to update the list of cases included in my most recent STR analysis @ https://seqr.broadinstitute.org/summary_data/external_analysis

I consistently get this error:

<img width="1331" alt="image" src="https://github.com/broadinstitute/seqr/assets/6240170/87139c6b-ae12-4449-a99e-f3da8c372559">

The table I'm uploading looks like:
```
Project	Family
CMG_PCGC_WGS	1-12345
CMG_PCGC_WGS	1-12346
CMG_PCGC_WGS	1-12347
...
```

**Comment by hanars** [comment]
It takes a while for large files to upload. Are you waiting until the file upload is complete before hitting submit? Until you see a blue box with a summary of the data that was parsed from the upload, do not hit submit

**Comment by bw2** [comment]
The file is small (< 1Mb). There's this JS error in the console:

<img width="1375" alt="image" src="https://github.com/broadinstitute/seqr/assets/6240170/c786cfb8-b246-4d99-9569-1b228a18e32a">

**Comment by hanars** [comment]
this file includes external seqr projects and is not valid to be loaded to seqr. The error is realted to nginx flagging a project with the work "copy" in its name as unsafe, which would not be an issue if we were only including valid internal projects
