### ISSUE TITLE
Error Requesting RNAseq Loading

### ISSUE THREAD

**Issue by apham98** [broadinstitute/seqr#3964]
**Describe the bug**
Receiving a 504 error when submitting request to load RNA-seq data with the TPM data type.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/data_management/rna_seq

**Scope of the bug**
I was able to load Outlier data using this page. I have tried waiting a few minutes and trying to submit again at the suggestion of Lynn but am still receiving the same error.

**Screenshots**
<img width="1061" alt="Screenshot 2024-03-12 at 2 19 32 PM" src="https://github.com/broadinstitute/seqr/assets/108075186/45a21919-3efd-47f1-8569-45f6b361b7da">

**Comment by hanars** [comment]
please add the data path to the ticket and make sure I have access to the file

**Comment by apham98** [comment]
I've added you to the workspace and here is the data path: gs://fc-6ce53c6a-a00f-4c4f-8dc7-5e91057fd88f/RDG_and_GTEX_tpms_for_all_tissues__with_metadata_pivoted__20240306.tsv.gz

**Comment by hanars** [comment]
It appears that much of the data in this file is missing a project, which is required. This table format is not explicitly throwing errors, but its also not the actual expected TPM table to load to seqr and includes so much extra data that it is causing loading to time out. Pease create an updated upload file that contains only rows that are actually valid seqr samples (I would recommend leaving out all of the GTEX data) and only the columns that are supposed to be included in the upload:
```
sample_id       project gene_id TPM tissue
```

**Comment by apham98** [comment]
Thank you. Jialan who provided the RNAseq files is out this week but once she's back I can try loading with that updated file

**Comment by jialanm** [comment]
Hi @hanars, thanks for the information. Some samples without projects or wgs sample IDs were included, and I have removed them now.

However, I'd like to double check on the file columns. Ben's previous tpm table included all the columns that I included in this file. I want to make sure that removing some of them would not cause a problem in seqr loading.

**Comment by hanars** [comment]
I clearly stated above which columns seqr wants this file to have. Removing columns that are not part of what seqr expects will only be a good thing. I do not know why Ben insisted on delivering an incorrect file format but as the technical lead on seqr you should trust me about what the expected file format is and not Ben

Also, as mentioned above, we should really stop delivering the full GTEX data to seqr. It doesn't neccessarily cause an error but it does really slow down the loading process

**Comment by jialanm** [comment]
I see. I didn't mean to doubt but only to confirm since I have no experience loading before. I'll generate the required file and give it to Alicia.

**Comment by apham98** [comment]
I did just try the updated file (gs://fc-6ce53c6a-a00f-4c4f-8dc7-5e91057fd88f/RDG_and_GTEX_tpms_for_all_tissues__with_metadata_pivoted__20240318.tsv.gz) and it looks like I'm still receiving the same 504 error when submitting the loading request

**Comment by jialanm** [comment]
All GTEx samples have been removed from the updated file.

**Comment by hanars** [comment]
okay, then I will take a look. For future reference, its generally good practice to use accurate and descriptive file names. A file named `RDG_and_GTEX_tpms_for_all_tissues` implies that it does, in fact, contain GTEX :)

**Comment by hanars** [comment]
As a heads up, once the perfomrance fx goes in this file will still not load beccause it has invalid gene IDs:
```
ERCC-00002, ERCC-00003, ERCC-00004, ERCC-00009, ERCC-00012, ERCC-00013, ERCC-00014, ERCC-00016, ERCC-00017, ERCC-00019, ERCC-00022, ERCC-00024, ERCC-00025, ERCC-00028, ERCC-00031, ERCC-00033, ERCC-00034, ERCC-00035, ERCC-00039, ERCC-00040, ERCC-00041, ERCC-00042, ERCC-00043, ERCC-00044, ERCC-00046, ERCC-00048, ERCC-00051, ERCC-00053, ERCC-00054, ERCC-00057, ERCC-00058, ERCC-00059, ERCC-00060, ERCC-00061, ERCC-00062, ERCC-00067, ERCC-00069, ERCC-00071, ERCC-00073, ERCC-00074, ERCC-00075, ERCC-00076, ERCC-00077, ERCC-00078, ERCC-00079, ERCC-00081, ERCC-00083, ERCC-00084, ERCC-00085, ERCC-00086, ERCC-00092, ERCC-00095, ERCC-00096, ERCC-00097, ERCC-00098, ERCC-00099, ERCC-00104, ERCC-00108, ERCC-00109, ERCC-00111, ERCC-00112, ERCC-00113, ERCC-00116, ERCC-00117, ERCC-00120, ERCC-00123, ERCC-00126, ERCC-00130, ERCC-00131, ERCC-00134, ERCC-00136, ERCC-00137, ERCC-00138, ERCC-00142, ERCC-00143, ERCC-00144, ERCC-00145, ERCC-00147, ERCC-00148, ERCC-00150, ERCC-00154, ERCC-00156, ERCC-00157, ERCC-00158, ERCC-00160, ERCC-00162, ERCC-00163, ERCC-00164, ERCC-00165, ERCC-00168, ERCC-00170, ERCC-00171
```

**Comment by hanars** [comment]
Also, there are some samples where the project GUID was used to populate the project column instead of the project name, which also will not allow this file to load

**Comment by jialanm** [comment]
Great. All project GUIDs have been substituted with project names. 

For gene IDs, all previous samples are annotated by `gencode.v26.GRCh38.ERCC.genes.gtf`. I assume to get loaded in seqr, samples need to be annotated by GENCODE 39. Let me know if my understanding is incorrect. 

@lynnpais could you let me know which samples you'd like to re-run with GENCODE 39, if any?

**Comment by hanars** [comment]
I do not believe this is an issue with which genocde you use, I think its an issue with using gencode with the `ERCC` genes which seems to be some special add on, given that every single gene that threw an error in seqr is name `ERCC`

**Comment by bw2** [comment]
Sorry about the issues here! I gave @jialanm some outdated and/or incorrect info about what should be included in these files - particularly about including GTEx samples. For the gencode version, if seqr annotations (and gnomAD) are currently based on gencode v39, I think it's worth updating our TPMs pipeline to also use that version. Previously, we reused the gencode version from GTEx v8, but gencode has gone through so many versions since then that I think it's worth updating to the version now used by seqr/gnomAD in order to reduce missing values.

**Comment by bw2** [comment]
Also, is it worth creating a feature request to document the expected columns and values (both on these types of upload pages  and in the error messages)?

**Comment by hanars** [comment]
The columns and values for data loading were addded to seqr based on very detailed github tickets that were submitted, I believe by you. If your team would like to go back through those tickets and document what exactly you asked us to support, you should feel free and we would be happy to review for accuracy

**Comment by hanars** [comment]
The seqr team has no preference how your team handles Gencode, except to say that seqr will fail if there are unexpected gene IDs. Since the only errors seqr ran into were related to the `ERCC` genes it seems to me that you should be focusing on updating your gencode version to not include those and not worry about the exact version, as seqr seems to have no conflict with the version you are using. However, if your team want to also change the version you are using yhats an internal discussion for you guys to have

**Comment by hanars** [comment]
the performance issue should be fixed once a file with only valid genes and projects is created
