### ISSUE TITLE
ClinGen allele IDs pulling incorrectly 

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#4007]
**Describe the bug**
In the `Variant metadata` table there is a column for ClinGen allele ID but the numbers are nonsense. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/report/variant_metadata/gregor

**Screenshots**
<img width="1333" alt="image" src="https://github.com/broadinstitute/seqr/assets/44381119/e4022046-3e10-4fe7-af07-b93327fcca33">

ClinVar entry for the first variant - [NEB c.9619-2A>G](https://www.ncbi.nlm.nih.gov/clinvar/variation/379231/?oq=NEB+c.9619-2A%3EG&m=NM_001164508.2(NEB):c.9619-2A%3EG) - highlighting the ClinGen allele ID CA1909252
<img width="1151" alt="image" src="https://github.com/broadinstitute/seqr/assets/44381119/9f4a4882-8f13-4dc4-8e87-6555d5735ef4">

ClinGen allele registry page for the first variant - [NEB c.9619-2A>G](https://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/by_caid?caid=CA1909252)
<img width="1151" alt="image" src="https://github.com/broadinstitute/seqr/assets/44381119/bd1992f5-1284-4396-a3a3-96ace4a680e0">

**Comment by jklugherz** [comment]
@hanars @bpblanken I don't think we have the Clingen Allele ID in our variant annotations yet. The [UI](https://github.com/broadinstitute/seqr/blob/master/ui/pages/Report/components/VariantMetadata.jsx#L15) is using the [Clinvar Allele ID](https://www.ncbi.nlm.nih.gov/clinvar/docs/identifiers/#allele) to populate this column, that ID is different from the [Clingen Allele ID](https://clinicalgenome.org/docs/clingen-allele-registry-links-information-about-genetic-variants/), which are always prefixed by 'CA'.

**Comment by hanars** [comment]
This is just the clinvar allele ID, but the column is mislabeled. I will change the column header to make this clear
