### ISSUE TITLE
[DUE 8/15] Variant look up: Option to contact 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4023]
Add the ability to contact other users regarding a variant of interest identified using the variant look up feature.

Default opt in by XX date if no action is taken. Can opt out any time. 

Lynn - Need to send notification to users that this feature will be going live on XX date.

**Comment by hanars** [comment]
For contact email, default to same as matchmaker contact but editable separate from MME. For internal projects, will have a different default email (@lynnpais to provide)

Will also have an additional new email address which all emails will be sent from. BCC the recipient and do not show the actual contact info for the match to the user (if match responds to email they will then have access to the contact info)

@lynnpais to also provide a template for what email template should look like. Will work like MME contact, with editable draft shown to user. 

Track sent emails similar to haw we track MME stats

**Comment by hanars** [comment]
Blocked on opt out functionality being live for sufficient time for users to opt out (one month?)

**Comment by lynnpais** [comment]
@hanars here's the email template on page 2 that the analyst team agreed on - https://docs.google.com/document/d/1MfEHKlgmrQ0MpS6fz65XbOFcKo-LiDhJg1lvZ-jenJ0/edit?usp=sharing. Let me know if you have any suggestions.

**Comment by hanars** [comment]
This is now live
