### ISSUE TITLE
Unhandled error for Grch37 MITO variant lookup

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr#4054]
We get an unhandled 500 error if a user tries to look up a mito variant on build 37. Since we do not have 37 data for mito, we should handle this with a descriptive error message
https://console.cloud.google.com/errors/detail/CJuAo8ml-ZTG_QE;time=P30D?project=seqr-project&utm_source=error-reporting-notification&utm_medium=slack&utm_content=new-error

**Comment by hanars** [comment]
New error: https://console.cloud.google.com/errors/detail/CPL54NaF2_-XCQ;time=P30D?project=seqr-project&utm_source=error-reporting-notification&utm_medium=slack&utm_content=new-error

**Comment by jklugherz** [comment]
😝 ^ that was me accidentally testing on prod seqr
