### ISSUE TITLE
Incomplete display of phenotype prioritized genes

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#4058]
**Describe the bug**
Not sure this is fixable but wanted to report the issue in case you have any ideas about what's happening: Occasionally when I want to review Exomiser/LIRICAL results by clicking on "Show Phenotype Prioritized Genes" on the family page, the popup window displays only a partial list of the exomiser and LIRICAL prioritized candidates (as in the screenshot below where only the rank 1 exomiser candidate is shown and only rank 2 and 5 LIRICAL candidates). The last time this happened, I discussed with Lynn but when she opened the exomiser/LIRICAL results in the same case, she saw the full list of candidates. I then clicked on a different prioritization option in the popup window (I think I tried to sort by "tool") and then closed/reopened the popup and saw the correct display (eg the same thing Lynn was seeing). Looking at RGP_273 today, I tried multiple prioritization options and opening and closing the popup and still saw an incomplete list (containing only FAT, ASNS, and POMGNT1) until I finally refreshed the family page, clicked on the "Show Phenotype Prioritized Genes" list again, and then saw the complete list (screenshot below). 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F020541_rgp_273

**Scope of the bug**
This has happened to me on multiple occasions over the course of a few months in different RGP cases. I think at least one of the other analysts has seen it as well. 

**Screenshots**
Incomplete display: ![image](https://github.com/broadinstitute/seqr/assets/67653781/5b684176-8072-430c-adce-a672bc12a2e3)

Complete display: ![image](https://github.com/broadinstitute/seqr/assets/67653781/d99e41ab-3230-4ed2-b903-ca327c52c379)

**Comment by hanars** [comment]
I was able to figure out the edge case where this occurs and have fixed it, so this should not happen in the future
