### ISSUE TITLE
Change GQ threshold on recessive saved searches to 30

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#4061]
**Is your feature request related to a problem? Please describe.**
We requested to lower GQ to 30 for the dominant saved searches in ticket #3627. Now requesting to also lower the threshold for the **recessive** saved searches for consistency. This will also help to alleviate concerns that saved searches won't perform as well on DRAGEN data with lower GQs. 

**Describe the solution you'd like**
We'd like to change the GQ threshold for both the recessive restrictive AND permissive saved searches to 30 (they are currently at 40).

**Describe alternatives you've considered**

**Additional context**
I'm told that the majority of variants have GQ in the 30-40 range in the DRAGEN data.

**Comment by hanars** [comment]
GQs have been updated
