### ISSUE TITLE
Update seqr UI to gnomADv4

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4063]
**Is your feature request related to a problem? Please describe.**
Need to update seqr to the latest version of gnomAD 

**Describe the solution you'd like**
Update seqr UI to gnomADv4. As discussed on slack, this would replace v2 and v3. 

I also understand there needs to be a gap between updating the numbers and links, so best to update the stats first and then the links.

**Comment by hanars** [comment]
Updated
