### ISSUE TITLE
Permission denied when attempting to change transcript

### ISSUE THREAD

**Issue by devon-bonner** [broadinstitute/seqr#4067]
**Describe the bug**
At the GREGoR Stanford Site we are receiving an error "Permission Denied" when we attempt to change the variant transcript. 

**Link to page(s) where bug is occurring**
Transcript page where we are receiving the error message: https://seqr.broadinstitute.org/project/R0742_gss_anvil_seqr_test/saved_variants/family/F050789_gss2537 

**Scope of the bug**
We are unable to change the transcript for any variant type across all projects including Seqr_Demo. 

**Screenshots**
Variant is being shown as associated with CLASP1 transcript, but we are interested in RNU4ATAC transcript.
![image](https://github.com/broadinstitute/seqr/assets/168872467/639e3a47-80d1-4dca-8aa2-abeca540eaff)

We attempted to change the transcript to RNU4ATAC, by clicking 'intron variant' link and selecting the RNU4ATAC transcript but we received a 'Permission Denied' error. 
![image](https://github.com/broadinstitute/seqr/assets/168872467/f832b2f4-f3a2-40ea-acfc-b76a2dc211b2)

**Comment by hanars** [comment]
This functionality is only available to users with permission to edit the corresponding seqr project, however due to a bug the button is being shown to all users. We will fix seqr to only show the button to users with adequate permission, but in the meantime for this variant you should have one of your project managers go in and update the transcript

**Comment by devon-bonner** [comment]
Thank you! We updated our analysts' permissions and are no longer receiving this error.

**Comment by hanars** [comment]
Button has been removed for users who do not have access to hopefully prevent this issue in the future!
