### ISSUE TITLE
Unable to edit dynamic analysis groups

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#4081]
**Describe the bug**
I am able to create dynamic analysis groups as expected. If I decide to edit a dynamic analysis group after it has been created, I click on the pencil icon next to the group and the Edit Dynamic Analysis Group popup appears, allowing me to make changes. However, when I hit Submit on the Edit Dynamic Analysis Group popup (whether I have made any changes or not), I get the error 'DynamicAnalysisGroup' object has no attribute 'analysis_group_guid' and the changes are not saved. 

**Link to page(s) where bug is occurring**
Screenshot below is from the Unsolved Cases group I created in https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/project_page

**Scope of the bug**
I have seen this in multiple projects. 

**Screenshots**
![image](https://github.com/broadinstitute/seqr/assets/67653781/24c3eaf0-0317-4a3c-b717-9a8c4f294741)

**Comment by hanars** [comment]
this is now fixed
