### ISSUE TITLE
issues uploading VCF to seqr

### ISSUE THREAD

**Issue by anatopf** [broadinstitute/seqr#4112]
**Describe the bug**
cannot upload VCF on seqr

**Link to page(s) where bug is occurring**
https://github.com/broadinstitute/seqr/issues/new?labels=bug&template=bug_report.md

**Scope of the bug**
Only tried it for one project

**Screenshots**
![image](https://github.com/broadinstitute/seqr/assets/68847177/257f01d9-d428-4d68-b9f1-c727b25a8cf4)

**Comment by hanars** [comment]
this issue has been addressed
