### ISSUE TITLE
import panel app job filing with timeout/ maxretry exception

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr#4113]
Errors:
https://console.cloud.google.com/errors/detail/CM3e-q3I-KHbrAE;time=P30D?project=seqr-project&utm_source=error-reporting-notification&utm_medium=slack&utm_content=new-error
https://console.cloud.google.com/errors/detail/CN6W4Zy7irzgOA;time=P30D?project=seqr-project&utm_source=error-reporting-notification&utm_medium=slack&utm_content=resolved-error
https://console.cloud.google.com/errors/detail/CJCR1tab05PIDA;time=P30D?project=seqr-project

logs: https://console.cloud.google.com/logs/query;query=%0Aresource.type%3D%22k8s_container%22%0Aresource.labels.cluster_name%3D%22seqr-cluster-prod%22%0Aresource.labels.project_id%3D%22seqr-project%22%0Aresource.labels.container_name%3D%22seqr-import-all-panels-uk-cronjob-pod%22%0Aresource.labels.pod_name%3D%22seqr-import-all-panels-uk-cronjob-28611360-hpv6t%22%0Aresource.labels.namespace_name%3D%22default%22%0Aresource.labels.location%3D%22us-central1-b%22;cursorTimestamp=2024-05-26T00:03:52.794814524Z;startTime=2024-05-25T23:34:22.794Z;endTime=2024-05-26T00:34:22.794Z?project=seqr-project

**Comment by jklugherz** [comment]
omg 😿
