### ISSUE TITLE
Add ClinGen Allele ID (CA#) to GREGoR report and variant metadata

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#4115]
**Is your feature request related to a problem? Please describe.**
We want to list ClinGen Allele IDs (CA#) for each variant on the variant metadata page and in the GREGoR report. 

**Describe the solution you'd like**
1. Variant metadata: Add a `ClinGen allele ID` column to the Variant Metadata page and populate with each variant's CA#. This column was recently replaced by 'Clinvar allele ID': #4007 
Fine to replace Clinvar allele ID in the variant metadata if we don't want to keep both. 

2. GREGoR report: Populate the `ClinGen_allele_ID` column in the genetic_findings table with the appropriate variant CA#. Leave column blank with CA# not available. [GREGoR data model V1.5 mapping  ](https://docs.google.com/spreadsheets/d/1W562-s2h3GSoBRR_fLeihFB0ZtqjixH1Hl80OWnCWZs/edit#gid=163493713)

**Comment by hanars** [comment]
This has been added
