### ISSUE TITLE
Case review feature is not working

### ISSUE THREAD

**Issue by Mutaz-Amin1** [broadinstitute/seqr#4119]
**Describe the bug**
The case review feature is not working. When I log in, the screen sticks in a blank page

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0594_rare_genomes_project_gen/case_review

**Scope of the bug**
Are you experiencing this issue in all projects? Within specific families within one project?

**Screenshots**
![image](https://github.com/broadinstitute/seqr/assets/171172872/0740e572-0459-40ab-8ab2-c945c3dc723e)

**Comment by hanars** [comment]
This is now working again. Thanks for reporting!

**Comment by hanars** [comment]
This is now working again. Thanks for reporting!
