### ISSUE TITLE
Add Motif Feature Consequence & Regulatory Region Consequence to Annotations

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4125]
Add Motif Feature Consequence & Regulatory Region Consequence to Annotations to return variants/ search based on this.

**Comment by hanars** [comment]
Available regulatory consequences: regulatory_region_ablation, regulatory_region_amplification, regulatory_region_variant, regulatory_region_fusion
Available motif consequences: TFBS_ablation, TFBS_amplification, TF_binding_site_variant, TFBS_fusion, TFBS_translocation

Add all consequences to their own section in annotation search, and remove any thagt are duplicated in the existing "other" annotations

**Comment by hanars** [comment]
@lynnpais, for the Annotation filter on search there is a dropdown where users can quickly choose from "High", "Moderate", and "all rare coding". I assume that these should not be included whith any of those dropdowns, but wanted to confirm

**Comment by lynnpais** [comment]
Correct. Do not add any Motif Feature & Regulatory Region Consequences to
the drop down options.

When the analyst team has had a chance to review the new annotations and
are ready to update the saved searches, we can consider updating this too
if needed.

**Comment by hanars** [comment]
Added
