### ISSUE TITLE
Update available searchable consequences

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4126]
- Add the Splice Region Variant fields to the Splice Region Variant annotation
splice_donor_5th_base_variant 
splice_donor_region_variant
splice_polypyrimidine_tract_variant 
extended_intronic_splice_region_variant
- Remove Initiator_codon_variant
- Confirm no unexpected changes
- Add coding_transcript_variant and Sequence_variant under Other category

**Comment by hanars** [comment]
Also, handle spliceregion.extended_intronic_splice_region_variant

**Comment by hanars** [comment]
@bpblanken when comparing the `consequence_terms` in the table global enum to the documented expected changes, I found that `extended_intronic_splice_region_variant` is not in the table global despite being listed in this ticket as an expected new consequence. Is this an artifact of looking at only a subset of the annotations table, or is this actually not a possible consequence?

**Comment by hanars** [comment]
@lynnpais when validating that the new consequences match what we expect, I found that there is actually one consequence that was in the old VEP output that is still in the new VEP output that we never actually added to the filters: `start_retained_variant`. I assume we do want the ability to filter on this going forward?

**Comment by hanars** [comment]
@bpblanken ignore my above comment. I realize that `extended_intronic_splice_region_variant` is a boolean value on the `spliceregion` struct, not a consequence term. I will add the necessary handling on the backend to properly filter on this

**Comment by lynnpais** [comment]
Yes, this should be included.

**Comment by hanars** [comment]
These have been added
