### ISSUE TITLE
Update the example variant text on the variant search page

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4129]
**Is your feature request related to a problem? Please describe.**
Would like to show an example of a variant using GRCh38 coordinates in the Location section of the Variant Search. This was requested by Chrissy.

**Describe the solution you'd like**
Change the example variant text to, 10-129958997-T-C

**Describe alternatives you've considered**
NA 

**Additional context**
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlFxQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d5e7234c43e6395232196cc7ef7731e6ec7a3c48/Screenshot%202024-05-31%20at%201.26.27%E2%80%AFPM.png" alt="Screenshot 2024-05-31 at 1.26.27 PM.png" />

**Comment by hanars** [comment]
This has been updated
