### ISSUE TITLE
List 'trios+' numbers on project page

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#4132]
**Is your feature request related to a problem? Please describe.**
I am trying to track the number of trios with data in a project (i.e. data for proband/mom/dad at minimum). The project page lists trios in the family of 3, but does not list trios for families of 4+.
<img width="189" alt="image" src="https://github.com/broadinstitute/seqr/assets/44381119/c1be5059-7726-43eb-967e-2fdc46fa33bc">

**Describe the solution you'd like**
I would like to list `trios+` under families with 4 individuals and families with 5+ individuals. Logic to calculate would be as follows (listing quads here but I'm ok with dropping quad and quad+ if it's too complicated): 
- duo = proband + parent
- trio = proband + mom + dad
- quad = proband + mom + dad + sibling
- trio+ = proband + mom + dad + other family member
- quad+ = proband +mom + dad + sibling + other family member

**Additional comments / alternative solutions**
`Families With Data` section should only count family members _with_ data to determine family structure. 
An alternative place to find this information is on the family metadata page, but `family_structure` in family metadata is not requiring data for mom and data to call trio at the moment.

**Comment by hanars** [comment]
I have updated the seqr display to reflect these changes. Let me know if you have any issues with it
