### ISSUE TITLE
Update fields in Saved Variants download

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4136]
Populate: Gene name, Callset freq, ClinVar significance
Remove: proband relationship, ancestry

**Comment by hanars** [comment]
@lynnpais what is the reason for removing fields here? In general we do not want to remove information from a download unless there is a really compelling reason to do so - the fact that one group is not using those fields is not a good enough reason to remove

**Comment by lynnpais** [comment]
It's what was discussed during the meeting. I believe the reasoning is that it would cause confusion because fields like is a pipeline we run on our data only. I am fine with not removing them

**Comment by hanars** [comment]
This has been fixed. @stephditroia this was reported by Stanford, if you want to let them know
