### ISSUE TITLE
Remove Sanger tag in Summary Data section 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4137]
Remove the three Sanger Tags from Summary data> Saved Variants

<img width="655" alt="Screenshot 2024-06-04 at 11 04 46 AM" src="https://github.com/broadinstitute/seqr/assets/37872186/fc34875c-9e09-4b82-996a-cc7db86a9d32">

**Comment by hanars** [comment]
edit: replace with working Sanger tag

**Comment by hanars** [comment]
Updated to use the current validation tags
