### ISSUE TITLE
Add ability to record a manual variant for AnVIL users

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4138]
**Is your feature request related to a problem? Please describe.**
Certain variants such as repeat expansions are not stored in seqr, but need to be recorded in seqr 

**Describe the solution you'd like**
Enable Manual Variant + Manual SV for AnVIL users

**Comment by hanars** [comment]
This ability has been added. @stephditroia I think this was one of the Stanford requests, if you want to let them know
