### ISSUE TITLE
Saved variants not showing as expected

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4142]
**Describe the bug**
Kaileigh noted that the saved variants are not being shown, despite there being variants tagged for Review. They do show when I click the saved variants bar.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F031486_rgp_1630

**Scope of the bug**
Likely case specific.

**Screenshots**

<img width="1319" alt="Screenshot 2024-06-05 at 7 11 45 PM" src="https://github.com/broadinstitute/seqr/assets/37872186/6ad07fd2-c473-4d1f-bfab-632f73230f16">

**Comment by hanars** [comment]
she has the "CMG Discovery Tags" category selected, and there are no discovery tags in this family
