### ISSUE TITLE
Update AoU variant search link

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4143]
**Is your feature request related to a problem? Please describe.**
The link to look up a variant in the AoU database is not working as expected and shows a blank page. It likely needs to be updated.

**Describe the solution you'd like**
Current AoU link takes you to - https://seqr.broadinstitute.org/project/R0594_rare_genomes_project_gen/saved_variants/variant/SV0154608_3192336973_f038272_r
But we should be seeing - https://databrowser.researchallofus.org/variants/3-192336973-G-A

**Describe alternatives you've considered**
NA

**Additional context**
<img width="1346" alt="Screenshot 2024-06-05 at 7 14 54 PM" src="https://github.com/broadinstitute/seqr/assets/37872186/b052819d-d145-4827-8414-624659d0b231">

Blank page -
<img width="1311" alt="Screenshot 2024-06-05 at 7 20 29 PM" src="https://github.com/broadinstitute/seqr/assets/37872186/8943e1ed-2277-4768-bc1e-eb848e1c1b3c">

**Comment by hanars** [comment]
link has been fixed
