### ISSUE TITLE
Django 3.2 support EOL

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr#4152]
### Discussed in https://github.com/broadinstitute/seqr/discussions/4151

<div type='discussions-op-text'>

<sup>Originally posted by **cyrus0824** June 10, 2024</sup>
I noticed that Django 3.2 has recently (as of April 1, 2024) become unsupported:  https://www.djangoproject.com/download/

Any plans to upgrade to a newer LTS version, or something else?</div>

**Comment by jklugherz** [comment]
let's upgrade to LTS version 4.2
<img width="803" alt="image" src="https://github.com/broadinstitute/seqr/assets/25799914/4af016b2-42fa-4e73-8e3d-872cedf602bd">

**Comment by hanars** [comment]
Latest seqr release includes Django bump to 4.2
