### ISSUE TITLE
Clicking on variant type to show transcripts not working

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#4160]
**Describe the bug**
I need to check a variant identify in other transcripts but when I try to do this, rather than showing the different transcripts, it is taking me to a blank page. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/summary_data/saved_variants/ALL/ENSG00000102038

I tried another random project from the variant search page and it is also happening here. 
Clicked on this page: https://seqr.broadinstitute.org/variant_search/results/6258cd3552a27459f79b883d4568985f?page=1&sort=xpos
Lands me on this blank page https://seqr.broadinstitute.org/variant_search/results/6258cd3552a27459f79b883d4568985f?page=1&sort=xpos

**Scope of the bug**
Are you experiencing this issue in all projects? Within specific families within one project?
In at least 2 random projects, one from saved variants page and one from variant search page. Probably a general issue. 

**Screenshots**
<img width="1002" alt="image" src="https://github.com/broadinstitute/seqr/assets/10407888/becace6d-003a-47b2-afdf-f50761a33974">

**Comment by hanars** [comment]
I am able to open all the links you are showing with no issue. Does refreshing the page fix the issue for you?

**Comment by anneodonnell** [comment]
I was also having the same problem today when I checked but didn’t troubleshoot further.

From: msingerb ***@***.***>
Date: Friday, June 14, 2024 at 1:23 PM
To: broadinstitute/seqr ***@***.***>
Cc: O'Donnell, Anne ***@***.***>, Author ***@***.***>
Subject: Re: [broadinstitute/seqr] Clicking on variant type to show transcripts not working (Issue #4160) [EXTERNAL]
* External Email - Caution *


I am having the same problem. Refreshing has not fixed it and others are having the same problem in different projects.

**Comment by hanars** [comment]
this is now fixed for all GRCh38 variants, there is still a bug for GRCh37

**Comment by hanars** [comment]
this is now fixed for all variants
