### ISSUE TITLE
Pedigree issues

### ISSUE THREAD

**Issue by evamar22** [broadinstitute/seqr#4161]
For the upcoming callset, I was uploading family members into seqr last week for a couple of families but encountered issues for 2 of them. Specifically, the pedigrees for family RGP_2747 and RGP_1170 are not displaying correctly. 

[RGP_2747](https://seqr.broadinstitute.org/project/R0594_rare_genomes_project_gen/family_page/F044240_rgp_2747)
_2 and _1 will not change to _mom and _dad, even after manually trying to change it both in the “Edit Individuals” section as well as on the pedigree itself.
[RGP_1170](https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F029943_rgp_1170)
Family member upload issue. Uploaded _mom, _dad, and _4_LR1 but will not appear in pedigree; pedigree only displays proband. When I manually go into “Edit Individuals” to change proband’s paternal and maternal ID’s it says these ID’s already exist (I’m assuming the upload went through) but they won’t appear or match with proband.

Additionally, I am also unable to go into the HMB Case Review page. Whenever I click on it the entire page appears blank and it never actually loads.

**Comment by hanars** [comment]
To edit individual IDs, you need to edit them using the "Bulk Edit Individuals" tab. If you ave not tried that yet, I would recommend you did that If you did try that and it did not work, please provide a copy of the file you used for bulk editing
<img width="1054" alt="Screenshot 2024-06-14 at 11 06 34 AM" src="https://github.com/broadinstitute/seqr/assets/24598672/15ee3104-0794-4d8c-be40-ac256fc37a05">

**Comment by evamar22** [comment]
Yes, I did that for both entries. Attached are the files I used for bulk
editing and adding the mentioned family members. As a reminder, the issue
is that the pedigrees are not displaying correctly even after upload.

Warmly,
Eva Martínez
Research Project Coordinator
------------------------------------------------
*Rare Genomes Project*
*Broad Institute of MIT and Harvard*
www.raregenomes.org
Phone: 617-714-7395
(Toll-Free: 855-534-4300)
Fax: 617-800-1909

**Comment by hanars** [comment]
Hi Eva, the files did not attach to the ticket

**Comment by evamar22** [comment]
Sorry, I've attached again.
[GRU Sib upload.xlsx](https://github.com/user-attachments/files/15840833/GRU.Sib.upload.xlsx)
[HMB Sib upload.xlsx](https://github.com/user-attachments/files/15840834/HMB.Sib.upload.xlsx)

**Comment by hanars** [comment]
As highlighted on the screensshot I provided above, you need a "Previous Individual ID" column if you want to change the indvidaul ID

**Comment by evamar22** [comment]
Understood, I'll try that method for family 2747. For family 1170 however the issue is different. Pedigree only shows proband and I uploaded both parents and sibling, however even after upload these family members still do not appear in seqr. Is there an issue you can view on your end regarding these family members? (Re: Family member upload issue. Uploaded _mom, _dad, and _4_LR1 but will not appear in pedigree; pedigree only displays proband. When I manually go into “Edit Individuals” to change proband’s paternal and maternal ID’s it says these ID’s already exist (I’m assuming the upload went through) but they won’t appear or match with proband.)

**Comment by hanars** [comment]
you need to set the family ID for every row in the table

**Comment by evamar22** [comment]
Both errors have been fixed following your guidance, thank you Hana!
