### ISSUE TITLE
Not able to open saved variants page

### ISSUE THREAD

**Issue by msingerb** [broadinstitute/seqr#4168]
**Describe the bug**
I am trying to open the saved variants page for this family (RGP_1157). Instead of opening I get a blank page. When I refresh it goes back to the family page.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F029503_rgp_1157

**Scope of the bug**
I have not tried many other projects, but I am able to open saved variant pages for other RGP families. I asked another person to try this saved variants page as well and they had the same problem.

**Screenshots**
![image](https://github.com/broadinstitute/seqr/assets/47390031/1263d68d-495c-4f35-83b6-dce733ccb265)

**Comment by hanars** [comment]
this has been fixed
