### ISSUE TITLE
Unable to view saved variants 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4185]
**Describe the bug**
I get a blank page when trying to view save variants. 

**Link to page(s) where bug is occurring**
Family page - https://seqr.broadinstitute.org/project/R0594_rare_genomes_project_gen/family_page/F040497_rgp_2320
Blank page - https://seqr.broadinstitute.org/project/R0594_rare_genomes_project_gen/saved_variants/family/F040497_rgp_2320

**Scope of the bug**
Affecting other RGP cases such as RGP_2529.

**Screenshots**
NA

**Comment by hanars** [comment]
This is now fixed
