### ISSUE TITLE
Update extended splice variant display 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4186]
**Is your feature request related to a problem? Please describe.**
Update extended splice variant display to be more informative

**Describe the solution you'd like**
We'd like the following:
1. Add SpliceRegion variant info to a hover over
2. Display SpliceRegion variant info similar to how we display SCREEN results, ie no yellow flag.

**Comment by hanars** [comment]
You need to provide the exact text you would like in the hover

**Comment by lynnpais** [comment]
Hover text for SpliceRegion is within brackets below:

- splice_donor_5th_base_variant: (variant falls in the 5th base after the splice donor junction (5' end of intron)
- splice_donor_region_variant: (variant falls in region between 3rd and 6th base after splice junction (5' end of intron))
- splice_polypyrimidine_tract_variant: (variant falls in polypyrimidine tract at 3' end of intron, between 17 and 3 bases from the end)
- extended_intronic_splice_region_variant: (variant falls in the first 9 bases of the 5' end of intron or the within the last 9 bases of the 3' end of intron)
