### ISSUE TITLE
Update gnomAD Variant Co-Occurrence link in seqr

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4188]
**Is your feature request related to a problem? Please describe.**
The gnomAD co-occurrence link is showing in seqr if the variants are present in v4 but Variant Co-Occurrence data is only calculated for variants in v2. 

**Describe the solution you'd like**
Would it be possible to show the Variant Co-Occurrence link if the variants are also present in gnomAD v2? 

**Additional context**
Example: https://seqr.broadinstitute.org/project/R0594_rare_genomes_project_gen/saved_variants/variant/SV0158592_1912676016_f040474_r,SV0158593_1912681648_f040474_r  - gnomAD Variant Co-Occurrence link shown but these variants are not in gnomADv2 <img width="1796" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXQrQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1006a296607a8ed3c49f8e6f196e8504caa874be/Screenshot%202024-06-20%20at%204.00.03%E2%80%AFPM.png" alt="Screenshot 2024-06-20 at 4.00.03 PM.png" />

**Comment by hanars** [comment]
this is not possible
