### ISSUE TITLE
Unable to access project variant search

### ISSUE THREAD

**Issue by divinemarcelino** [broadinstitute/seqr#4210]
**Describe the bug**
I was able to use project variant search last week, however, when I tried to use today, it only showed me a white screen. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/project/R0687_meei_janeywiggs_germline

**Scope of the bug**
Are you experiencing this issue in all projects? Within specific families within one project?
Yes. All projects in my seqr account

**Screenshots**

**Comment by hanars** [comment]
Also an issue with family search within the project: https://seqr.broadinstitute.org/variant_search/family/F044057_fph015

**Comment by hanars** [comment]
This bug is browser specific - the page loads in Chrome but not in safar (and potnetially other browsers)i. Since seqr is only supported in chrome, we will not be remedying this issue, and ask that you instead use seqr in a supported browser
