### ISSUE TITLE
Bulk-add or edit families with external data

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#4214]
**Is your feature request related to a problem? Describe the solution you'd like**

We would like the ability to bulk-add or edit families with external data through the 'Edit Families & Individuals' link on the project page. This request is related to ticket https://github.com/broadinstitute/seqr/issues/4049 

![image](https://github.com/broadinstitute/seqr/assets/44381119/836b315e-30bd-400b-bd7f-096ea5475cd4)

**Comment by stephditroia** [comment]
This was discussed in person (between Stephanie and Hana) with the conclusion that continued support for a bulk upload option is more efficient than either a developer or analyst spending time on a one-time upload of this data (~200 families).

**Comment by hanars** [comment]
External Data is now an optional column for the "Bulk Edit Families" upload

**Comment by stephditroia** [comment]
Which delimiter should I use for families with multiple external datatypes? Comma didn't work. 
![image](https://github.com/user-attachments/assets/ab988da1-71e4-4ee9-b479-265803e41dc9)

**Comment by stephditroia** [comment]
There are only a handful of families with more than one data type. I can fix these manually if needed.

**Comment by hanars** [comment]
semicolon should work as the delimiter
