### ISSUE TITLE
MME searches taking >15 mins

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4225]
**Is your feature request related to a problem? Please describe.**
A search for new MME hits spins for >15 minutes before returning matches. 

**Describe the solution you'd like**
As its taking far longer than usual, can you look into potential issues/ ways to speed it up?

**Additional context**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F019668_rgp_95/matchmaker_exchange
I ran into this in RGP_95 and a collaborator also reached out thinking it was not working.

**Comment by hanars** [comment]
GeneMatcher has been having performance issues this week. Theres nothing we can do about it. If you want to reach out and try to get them to fix their reliability issues, be my guest but I have tried several times with no luck
