### ISSUE TITLE
Training cases are not working

### ISSUE THREAD

**Issue by PamRobertson** [broadinstitute/seqr#4227]
**Describe the bug**
A clear and concise description of what the bug is, and what you instead expect to be happening
I've clicked on a few training cases from GREGoR Training Project C (GT9, GT10) and when I press variant search >> select a saved search >> search >> the page is very slow to load and then instead of seeing variants I get an error message.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/a3ee242b2adf6be61a7b7e2f217a2d64?page=1&sort=xpos

**Scope of the bug**
Bug is affecting the training cases.

**Screenshots**
 
![Screenshot 2024-07-11 at 11 14 27 AM](https://github.com/broadinstitute/seqr/assets/144047666/7d255a2b-f361-40e9-afd8-07f19c9a2bf6)
![Screenshot 2024-07-11 at 11 14 47 AM](https://github.com/broadinstitute/seqr/assets/144047666/0aa111e2-6644-490b-a482-baddd7ab5c43)

**Comment by lynnpais** [comment]
@PamRobertson these cases are no longer functional as we are creating new projects for training purposes. Can I ask what you'll be using it for, i.e. to train people TGG staff, students or someone else?

**Comment by PamRobertson** [comment]
Hi @lynnpais - the training is for myself. I've had chats with Chrissy in getting trained up in seqr and helping the team with some RGP analysis.

**Comment by lynnpais** [comment]
Of course! You can use the new project - https://seqr.broadinstitute.org/project/R0801_gregor_training_project_/project_page
