### ISSUE TITLE
AirTable/Seqr Loading: cannot load families with member(s) in Historic PDO 

### ISSUE THREAD

**Issue by matren395** [broadinstitute/seqr#4236]
**Describe the bug**
The current Seqr Loading Pipeline/AirTable Behavior does not work when existing family members of the new samples are in 'Historic' or 'Available in seqr' -tagged PDOs in the AirTable. Since the new loading pipeline requires full families to be loaded, we'd like to have these family members included in loading , but they're not included in the subset (and throw an error when loading from Seqr's data management page). 

**Link to page(s) where bug is occurring**
Documented: https://the-tgg.slack.com/archives/CMM4R47LH/p1720712515717939 
Seqr page: https://seqr.broadinstitute.org/data_management/load_data
AirTable: https://airtable.com/app3Y97xtbbaOopVR/tblG1k2YLBu4bw2XY/viwW0oZeRVcbgTduD?blocks=hide

**Scope of the bug**
Only with families with old members. We do not have this problem when we are loading entirely new families. 

**Screenshots**
![image](https://github.com/user-attachments/assets/9d40aec2-788a-410a-b58e-900e34ae3cba)

... when the samples are not absent, just in Historic or non-Methods DAGs

**Comment by hanars** [comment]
This hasnow been fixed and families where some samples are in the PDOs to load and others are already loaded will no longer throw an error and will instead load the whole family
