### ISSUE TITLE
Seqr family page loading very slowly

### ISSUE THREAD

**Issue by msingerb** [broadinstitute/seqr#4238]
**Describe the bug**
It is taking a long time to load the family pages when using the searchbar. Once I get to a saved variants page it quickly loads when I return to the family page. I am using chrome so not sure if there's something going on.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/family_page/F027305_rgp_770

**Scope of the bug**
This is happening in all RGP projects at least.

**Comment by hanars** [comment]
Developer note: Family detail api endpoint takes ~50s for this family, very unacceptable performance

**Comment by hanars** [comment]
this is now fixed
