### ISSUE TITLE
Saved variants page not loading

### ISSUE THREAD

**Issue by msingerb** [broadinstitute/seqr#4239]
**Describe the bug**
For this specific family I am unable to load the saved variants page. It starts loading and then goes to a blank screen. This has been tested with multiple users and they have the same problem.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F027123_rgp_749

**Scope of the bug**
I have only had this problem with this family.

**Screenshots**
![image](https://github.com/user-attachments/assets/4d909efe-720a-4d17-beb3-8635fd68e160)

**Comment by hanars** [comment]
this page is now working again
