### ISSUE TITLE
Project page goes blank when scrolling 

### ISSUE THREAD

**Issue by stephditroia** [broadinstitute/seqr#4240]
**Describe the bug**
The [TGG_Shimamura_WGS](https://seqr.broadinstitute.org/project/R0649_tgg_shimamura_wgs/project_page) project page consistently goes blank when you scroll through cases. Hitting refresh fixes it temporarily but the page goes blank again if you scroll down.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0649_tgg_shimamura_wgs/project_page

**Scope of the bug**
This is happening across several users. This does not happen with any other project.

**Comment by hanars** [comment]
this is now fixed!
