### ISSUE TITLE
Add browser info to FAQ

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4243]
**Is your feature request related to a problem? Please describe.**
Some individuals run into issues using unsupported browsers, hence would be good to specify which browser is recommended.

**Describe the solution you'd like**
To the seqr FAQ, add the following:

Q: Which browser works best for seqr?
seqr is designed to work best in Google Chrome. While it may function with other browsers, certain features might not be supported.

**Comment by hanars** [comment]
I am not comfortable with this wording, @lynnpais how does the following sound:

Q: Which browsers are supported for seqr?
seqr is only supported in Google Chrome. While it may sometimes function in other browsers, to ensure reliable behavior you should only use seqr in Chrome

**Comment by lynnpais** [comment]
Yes, that is fine.

**Comment by hanars** [comment]
Blocked on getting Spanish language copy

**Comment by hanars** [comment]
Added
