### ISSUE TITLE
Move location of Sort By feature

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4244]
**Is your feature request related to a problem? Please describe.**
Currently, users need to re-run a search if they would like to change how variants are sorted.

**Describe the solution you'd like**
Move the Sort By feature prior to the Search option, so users can adjust this if required before running their search.

**Describe alternatives you've considered**
NA

**Additional context**
Discussed earlier this week.

**Comment by hanars** [comment]
This is now done
