### ISSUE TITLE
Families disappeared

### ISSUE THREAD

**Issue by jin0008** [broadinstitute/seqr#4252]
**Describe the bug**
A family cohort disappeared after uploading additional data.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0715_seqr_highmyopia_exomes/project_page

**Scope of the bug**
This issue is only in this project. I could not see entire family in google chrome. Interestingly, I was able to see families in other browser like safari and Firefox. However, I could not perform variant search using safari or Firefox.

**Screenshots**
![seqr_open_in_chrome](https://github.com/user-attachments/assets/ff64d727-6bf9-4217-97b2-0fb4f15948c2)

**Comment by hanars** [comment]
You have an "Analysed By" filter applied. Clear the filter to view all the families
