### ISSUE TITLE
Update MT constraint metrics display

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4264]
**Is your feature request related to a problem? Please describe.**
We need to update the constraint metrics display for mt variants. Ben has completed the pipeline work #561 - https://github.com/broadinstitute/seqr-loading-pipelines/issues/561

**Describe the solution you'd like**
Display the mitochondrial local constraint score (MLC) in a traffic light system like we do for the in silico tools
High constraint is >=0.75 - red; 0.50-0.74 is yellow; <0.50 is green. Include the thresholds in the hover over and mention, "Based on [Lake et al., 2023](https://www.biorxiv.org/content/10.1101/2022.12.16.520778v2)". There's no PMID yet.

**Comment by bpblanken** [comment]
@hanars 

Yep!  https://github.com/broadinstitute/seqr-loading-pipelines/issues/561#issuecomment-2251177994

**Comment by hanars** [comment]
We do not as a general rule provide citations for in silico scores, we only currently cite the 2022 ClinGen recommendations or nothing at all. I will not add the citation as part of this ticket, if we want to more broadly have citations for score thresholds we should have a separate ticket for adding them for the dozen or so remaining scores

**Comment by hanars** [comment]
This score has now been added
