### ISSUE TITLE
Update variant display in the UI to show multiple genotypes (WES and WGS) for a single variant

### ISSUE THREAD

**Issue by jklugherz** [broadinstitute/seqr#4269]

**Comment by jklugherz** [comment]
<img width="526" alt="Screenshot 2024-10-01 at 2 22 08 PM" src="https://github.com/user-attachments/assets/c52cb308-3e29-4206-b531-d41e44029a08">
@hanars would stacking the genotypes like this be sufficient for displaying genotypes for both sample types on one variant?

**Comment by hanars** [comment]
@lynnpais I thought we agreed on a UI in the meeting we had with the analysts, can you please update the ticket with that decision?

**Comment by lynnpais** [comment]
@hanars is it in the slides you put together and reviewed with the analyst team?

**Comment by hanars** [comment]
:shrug: I was not taking notes during that meeting, I thought you were

**Comment by hanars** [comment]
@lynnpais no one on the engineering team has notes of what the ultimate decision was for the UI. If you do not have notes either than please make a decision in consultation with Chrissy or whoever else you thin needs to be involved, but at this point this work is blocked on a product decision.

As best Julia and I can remember, we had agreed that we would show the genotype (i.e. A/**C**) once per individual, and underneath where we currently show GQ and AB we would show the GQ/AB for each sample type on its own row i.e.
A/**C**
_WES: 99, 0.45
WGS: 86, 0.37_

What we can't remember is how we wanted to show cases where the genotype itself differed between sample types - did we want to always show the genotype for one sample type like WGS and then if the other sample type is different show a big red warning icon next to it? Or would we want to show the full genotype for each sample type stacked above each other?

**Comment by lynnpais** [comment]
The previous message got buried in my email. Will get a response to this asap.

**Comment by lynnpais** [comment]
Found the notes :)

Variant display: Show WGS genotype. Below genotype, stack GQ and AB, WGS first followed by WES. Flag if genotypes don't match.

Can we go with the yellow flag currently used for SV discrepancies or is there a reason you suggest going with red?

**Comment by hanars** [comment]
For SNV_INDEL data yellow is already used for "Potential UPD/ Hemizygosity" and for "Variant absent in parents" for comp hets, so I thought it might be confusing for it to also be this/ maybe it would be missed. But if you think using the same yellow for this as for everything else makes sense then that works too!

**Comment by lynnpais** [comment]
yellow flag is fine!

**Comment by jklugherz** [comment]
Here's an example of an individual with differing genotypes across sample types. Please let me know your feedback @lynnpais and @hanars 

I made changes to the genotype details hover over, the quality and filters, and added a warning for differing genotypes.

![Screenshot 2024-10-16 at 4 30 23 PM](https://github.com/user-attachments/assets/a0c885a7-d5e9-4e0b-b4f1-a5d4278ad4b2)

![Screenshot 2024-10-16 at 4 37 52 PM](https://github.com/user-attachments/assets/d12800f3-a312-4c74-af8a-6ee9dd538a8b)

**Comment by hanars** [comment]
My concern with this UI is its not super clear which sample type has which genotype when they are different. I think showing the full alleles in the hover over for both sample types would be more explicit. I realize it might be hard to do in the code using the existing yellow triangle, so if that doesn't work then you should just a different warning icon for this (maybe like in orange)

**Comment by lynnpais** [comment]
Yes, would be good to show the full allele in the hover over for both sample types. Otherwise, it's looking nice!

**Comment by jklugherz** [comment]
<img width="326" alt="Screenshot 2024-10-17 at 11 26 44 AM" src="https://github.com/user-attachments/assets/d6b6c927-2697-4a9a-a304-ec0e2f313eb7">

how's this? it's not hard to keep them in the same warning popup, but it might be to style the alleles

**Comment by hanars** [comment]
I think we should do the allele styling - its okay like this for indels but a plain text C/G vs C/C is pretty hard to differentiate without bolding. While its a small amount of extra work up front its worth it (popups can take react nodes instead of text for the content so it shouldn't be too hard)

**Comment by jklugherz** [comment]
![Screenshot 2024-10-21 at 5 37 17 PM](https://github.com/user-attachments/assets/cc809f76-bfef-4b4c-b953-6e34698cf015)

how's this for alleles in the popup with styling?
