### ISSUE TITLE
Study Status Changes

### ISSUE THREAD

**Issue by evamar22** [broadinstitute/seqr#4279]
Hello, I’m doing some status changes to GRU families in seqr right now and it’s saying Melanie O'Leary is the one doing these changes rather than me. I looped Lynn on this and she confirmed this is not normal behavior. A list of the affected RGP families are below:
1124 (https://seqr.broadinstitute.org/project/R0594_rare_genomes_project_gen/case_review)
3522
3527
3529
3531
3537
3540
3541

There's multiple families I’m changing to Not Accept. I experimented the status change with the others and it seems if I toggle the "Not Accepted" one first, it will always say Mel did the change. But if I do any other one first, for example "Inactive", it will say I made the change. Clicking back to "Not Accepted" will show I made the change only if I toggled any other status change first. Examples of the ones I fixed using this method are the following: 3544, 3550, 3557, and 3558. I've also provided a screenshot below of the "Not Accepted" change I made but it shows Mel did it. Melanie has never logged into my computer nor used her credentials.

[Screenshot 2024-08-08 at 12 17 54 PM](https://github.com/user-attachments/assets/b72109bc-a406-4ebd-8228-558f4c5e4ea1)

**Comment by hanars** [comment]
So looking through the logs, it looks like Melanie updated the case review status for these families around 11:20AM on August 8. For the ones you say you fixed, I see you updating them around 12:15 that same day. Is there any chance at all that Melanie actually did go through and update the case review status an hour before you did?

**Comment by hanars** [comment]
A couple notes on seqr behavior:
1) If you have seqr open for a while and are not fully refreshing the page, seqr will not necessarily sync what its showing you with the latest values form its database. So say you have the case review page open for a few hours - any families you edit will sync with whats in the database when you edit them, but any families you do *not* actively edit will just show you what was true whenever you first loaded the page and will not change to reflect changes anyone else was making
2) If you go to edit something in seqr and you are not actually making any changes, seqr will not update anything. So if Melanie had already changed the case review status and then you tried to change it to the same thing as her seqr would see that the value was not actually changing and not update anything

**Comment by lynnpais** [comment]
Eva and Mel agreed with the above reasoning.
