### ISSUE TITLE
PrimateAI color ranges differ across variants

### ISSUE THREAD

**Issue by bw2** [broadinstitute/seqr#4280]
PrimateAI color ranges displayed in the mouse-over help dialog are not consistent across different variants on this page:
https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/family/F018960_rgp_8

The cited paper https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9748256/  lists the thresholds as 
<img width="825" alt="image" src="https://github.com/user-attachments/assets/e845f938-47cd-44d4-9ab2-348e469fdd0d">

which matches the constants defined @
https://github.com/broadinstitute/seqr/blob/master/ui/shared/utils/constants.js#L1434

and some of the dialogs are as expected
<img width="208" alt="image" src="https://github.com/user-attachments/assets/2f8b823c-f990-4087-aa9b-f36df5bfb226">

but some of the dialogs on that variants page look like
<img width="212" alt="image" src="https://github.com/user-attachments/assets/540b4730-dea7-400e-b420-9d2aad985934">
<img width="197" alt="image" src="https://github.com/user-attachments/assets/ec5bf86d-b5bc-4c41-a534-2876e96a5a1b">

**Comment by hanars** [comment]
For Primate AI we show gene-specific thresholds so we expect the thresholds to be different for different variants

**Comment by bw2** [comment]
Would be helpful for the help dialog to have a description of this.

**Comment by hanars** [comment]
@lynnpais please feel free to submit a feature request if you agree
