### ISSUE TITLE
Update APOGEE scores to APOGEE 2 scores for mtDNA missense variants

### ISSUE THREAD

**Issue by slstenton** [broadinstitute/seqr#4284]
**Is your feature request related to a problem? Please describe.**
APOGEE in silico scores have recently been updated to APOGEE 2 scores

**Describe the solution you'd like**
Update APOGEE to APOGEE 2

**Additional context**
APOGEE 2 probabilities/classes of pathogenicity can be freely downloaded from MitImpact [http://mitimpact.css-mendel.it/]

**Comment by jklugherz** [comment]
@lynnpais Do the analysts want both apogee scores, or should the apogee2 score be displayed in place of the current apogee1 score?

**Comment by lynnpais** [comment]
APOGEE 2 can replace the older ones, thanks.

**Comment by jklugherz** [comment]
APOGEE 2 scores are available in seqr.
