### ISSUE TITLE
Updates to saved searches

### ISSUE THREAD

**Issue by Caustint** [broadinstitute/seqr#4286]
**Is your feature request related to a problem? Please describe.**
Some important variants are currently being missed by our saved searches: a few categories of SVs (including intragenic exon duplications, which can lead to LOF) and exonic variants in noncoding transcripts. We'd like to make changes to the 4 core saved searches (de/novo dominant restrictive and permissive, recessive restrictive and permissive) to correct this issue. We'd also like to implement Hemi/Hom cutoffs for the recessive restrictive search to reduce the number of benign variants returned.

**Describe the solution you'd like**
I have created the 4 updated saved searches in my account. We'd like to update the existing saved searches with these new search parameters as follows:
De novo/Dominant Restrictive - De novo/Dominant Restrictive Aug 2024 Update
De novo/Dominant Permissve - De novo/Dominant Permissive Aug 2024 Update
Recessive Restrictive - Recessive Restrictive Aug 2024 Update
Recessive Permissive - Recessive Permissive Aug 2024 Update
(I'm not looking to change the names of the saved searches, just wanted to label them clearly)

**Describe alternatives you've considered**
The analyst team and I have done quite a bit of testing on the proposed changes to confirm they return known candidate variants without adding too many additional variants. We are intentionally adding noncoding transcript exon variant (canonical) to the de novo/dominant restrictive but NOT permissive saved search, as it returns far too many variants in the permissive search. I have not added noncoding transcript exon variant (canonical) to the recessive restrictive search since allowing biallelic noncoding variants adds way too many variants in my opinion.

**Additional context**

**Comment by hanars** [comment]
@lynnpais per our discussion the other day we need to change how these requests are defined, if you could update the ticket to instead clarify the exact changes that are being made to search that would be great

**Comment by lynnpais** [comment]
Changes -

**De novo/ Dom Restrictive**
Remove: 
Structural consequence - Inversion Span
Add:
Structural consequence - Intragenic Exon Duplication
Noncoding transcript exon variant (canonical)

**De novo/ Dom Permissive**
Add:
Structural consequence - Intragenic Exon Duplication
Structural consequence - Partial Exon Duplication
Structural consequence - Breakend Exonic

**Recessive Restrictive**
Annotations (first hit)
Remove: 
Structural consequence - Inversion Span
Add:
Structural consequence - Intragenic Exon Duplication

Annotations (second-hit)
Remove: 
Structural consequence - Inversion Span
Add:
Structural consequence - Intragenic Exon Duplication

Frequency: set H/H to 5 for gnomAD exomes and genomes

**Recessive Permissive**
Annotations (first hit)
Add:
Structural consequence - Inversion Span
Structural consequence - Breakend Exonic
Annotations (second-hit)
Add:
Structural consequence - Inversion Span
Structural consequence - Breakend Exonic

Frequency: set H/H to 5 for gnomAD exomes and genomes

**Comment by hanars** [comment]
Saved searches have been updated
