### ISSUE TITLE
Change SV GQ buckets

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4287]
**Is your feature request related to a problem? Please describe.**
We'd like to set the SV GQ to 5, but are currently unable to do so because the bucket is 0-10. 

**Describe the solution you'd like**
Update the bucket range to 5, making it 0, 5, 10, 15, etc.

**Describe alternatives you've considered**
Discussed with the analyst team.

**Additional context**
<img width="1520" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFpPQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fb7c9fb341ab894f77dc08c1b995104b24961ecd/Screenshot%202024-08-12%20at%201.04.45%E2%80%AFPM.png" alt="Screenshot 2024-08-12 at 1.04.45 PM.png" />

**Comment by hanars** [comment]
This has been changed
