### ISSUE TITLE
Variant Lookup error

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4302]
**Describe the bug**
There seems to be an issue with the Variant Lookup. I tried it for the example (4-88047328-C-T) cited in the Variant Lookup page, as well as a variant tagged in an RGP case (details below) and used the seqr link to identify other variants in seqr. 

**Link to page(s) where bug is occurring**
Variant page - https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/variant/SV0114109_1155293337_f032092_r

seqr look up link - https://seqr.broadinstitute.org/summary_data/variant_lookup?variantId=1-155293337-G-A&genomeVersion=38&sampleType=WGS

Page with error - https://seqr.broadinstitute.org/summary_data/variant_lookup?variantId=1-155293337-G-A&genomeVersion=38&sampleType=WGS

**Scope of the bug**
Likely affecting all projects.

**Screenshots**
<img width="1475" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0plQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--69305b04a5ca3c776a157261ce16473c6617e976/Screenshot%202024-08-15%20at%208.29.52%E2%80%AFAM.png" alt="Screenshot 2024-08-15 at 8.29.52 AM.png" />

**Comment by hanars** [comment]
This is now fixed!
