### ISSUE TITLE
Seqr Internal Server Error (variant search feature)

### ISSUE THREAD

**Issue by mcampbell2851** [broadinstitute/seqr#4317]
Hi all,

Wondering if anyone is receiving (or has received in the past) an "Internal Server Error" when conducting variant search queries within a project/cohort? I have attached a picture of the error message for your review... I first began to experience this issue on Saturday, and it has yet to dissipate. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/

Best,

Mark Campbell
Research Technologist
Reproductive Endocrine Unit
Massachusetts General Hospital
Email: mcampbell32@mgh.harvard.edu
![Seqr_Internal_Server_Error](https://github.com/user-attachments/assets/f7677470-d198-4ec6-a07b-b820126cf059)

**Comment by hanars** [comment]
Hello, can you please link the full URL of the page with the bug, not the partial URL

**Comment by mcampbell2851** [comment]
Hi there!

Thank you so much for your response! I have attached two links. Link #1 pertains to the specific project/cohort for which I wish to conduct gene variant queries. Link #2 pertains to one example of the resulting "Internal Server Error" page after I conduct such a query (I.e., for a specific gene(s)).

Link #1: https://seqr.broadinstitute.org/variant_search/project/R0731_seqr_reu_wes_2022

Link #2:
https://seqr.broadinstitute.org/variant_search/results/1c9451825305b0baeda96cf90beabf9d?page=1&sort=xpos

Please let me know if there is anything else I can provide to help!

Best,

Mark Campbell
Research Technologist
Reproductive Endocrine Unit
Massachusetts General Hospital
Email: mcampbell32@mgh.harvard.edu

**Comment by hanars** [comment]
There is a bug in seqr causing this issue - as a workaround while we get this fixed if you provide the ENSEMBL ID for that gene instead of the gene name, search will work:
https://seqr.broadinstitute.org/variant_search/results/98ab7ca5bd7e784f6d2685e13eafc4d7?page=1&sort=xpos

**Comment by mcampbell2851** [comment]
Thank you so much!!

**Comment by hanars** [comment]
This bug is now fixed. Thanks for reporting!
