### ISSUE TITLE
Variant search results with multiple pages not loading beyond page 1

### ISSUE THREAD

**Issue by eoheir** [broadinstitute/seqr#4323]
**Describe the bug**
For searches that return multiple pages of variants, I am not able to see the variants beyond page 1 of the results. When I clicked to move to the next page of variants, I got a spinning loading wheel for >10 minutes until I gave up. 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/cd3ed053c9b615098a6482df2124ce37?page=1&sort=xpos 

**Scope of the bug**
I tried this in a few different cases in the TGG_Gazda_Yu_WGS project as well as an RGP GRU case and haven't been able to get page 2 to load in any of them.

**Screenshots**
<img width="1503" alt="Screenshot 2024-08-22 at 2 19 35 PM" src="https://github.com/user-attachments/assets/55150ec2-eb2f-49bd-a237-0d69cd635609">

**Comment by hanars** [comment]
Debugging note: this is an error with the seqr javascript, not the search backend

**Comment by hanars** [comment]
This is fixed now
