### ISSUE TITLE
Add columns to "Bulk Edit Individual Metadata" table

### ISSUE THREAD

**Issue by apham98** [broadinstitute/seqr#4328]
**Is your feature request related to a problem? Please describe.**
I am trying to see if the "Tissue Affected Status" is all up to date in a project and it would be helpful to download it from the “Bulk Edit Individual metadata” section in seqr for all current individuals in a project.

**Describe the solution you'd like**
It would be helpful to add MONDO ID, analyte type, primary biosample, and tissue affected status as columns in the "Bulk Edit Individual metadata" table while we’re at it so we can easily download that for current individuals and bulk edit those fields going forward.

**Describe alternatives you've considered**
Manually looking through seqr project page.

**Additional context**
NA

**Comment by hanars** [comment]
These values are now included on the "Bulk Edit Individuals" downloads and can be updated there
