### ISSUE TITLE
Rename environment variables in hail search service.

### ISSUE THREAD

**Issue by bpblanken** [broadinstitute/seqr#4359]
- rename `SSD_DATASETS_DIR` to `HAIL_SEARCH_DATA_DIR` and default to `/seqr/seqr-hail-search-data`
- add `REFERENCE_DATASETS_DIR` and default to `/seqr/seqr-reference-data` and use the env var for the prefilter tables (I'm going to close [this pr](https://github.com/broadinstitute/seqr/pull/4354/files) in favor of doing it with this ticket).  
- `DATASETS_DIR` does not need to change and can stay as a reference to the in memory file system used by us but not by external users.

**Comment by hanars** [comment]
I am opting to change `DATASETS_DIR` to `IN_MEMORY_DIR` to be more explicit. Since it is only used by us I do not think there is any harm there
