### ISSUE TITLE
Allow only new samples to be loaded to an AnVIL project

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4379]
**Describe the solution you'd like**
Allow only new joint-called samples to be loaded to an existing AnVIL project

**Comment by hanars** [comment]
@lynnpais this is now live in seqr. This means that if users wish to load more data to a seqr project it does not *have* to be joint called with all previous data. I defer to you on how you would like to communicate this out to users (although I'm happy to proofread any drafts)
