### ISSUE TITLE
Show luigi UI in seqr

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4402]
Show luigi UI in seqr

**Comment by hanars** [comment]
@bpblanken can you add instructions for how to have luigi running locally?

**Comment by bpblanken** [comment]
I _think_ the easiest approach is to run it through the docker container:

```
mkdir -p ./data/luigi-state #directory needs to exist before startup :/
docker run -p 8082:8082 -it -v /.data:/seqr gcr.io/seqr-project/seqr-pipeline-runner luigid
```

Let me know if that doesn't work!
