### ISSUE TITLE
Add known sex aneuploidy info to seqr

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4404]
Add known sex aneuploidy info to seqr. In database keep detailed info, In UI show with appropriate square or circle icon based on presence of Y chromosome. Update loading pedigree to match what we are delivered in metrics file

**Comment by bpblanken** [comment]
The message I have is:
```
It looks like 10 samples have different predicted sex values than we would expect.
I was told 2 samples are XXX,
3 samples are XYY,
4 samples are XO,
1 sample is XXY
```

@matren395 would you mind confirming that this is the exhaustive list?

**Comment by hanars** [comment]
Do we know how those are formatted in the metrics file?

**Comment by bpblanken** [comment]
Yep, I think it's just those plain text values.  Here's the screenshot of the initial investigation after the pipeline failed: 

![image](https://github.com/user-attachments/assets/a82c10e5-651d-491b-ad14-f4171b53673a)

**Comment by lynnpais** [comment]
Would be good to have a yellow warning flag on sex chromosome variants in these cases (as a warning that there is an aneuploidy in case you didn’t see the info on the family page)

**Comment by hanars** [comment]
This is now live!
