### ISSUE TITLE
Blank page when selecting saved variants bar

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4407]
**Describe the bug**
Blank page when selecting saved variants bar.

**Link to page(s) where bug is occurring**
Saved variants page - 
https://seqr.broadinstitute.org/project/R0594_rare_genomes_project_gen/saved_variants/family/F032178_rgp_2045

Blank page - https://seqr.broadinstitute.org/project/R0594_rare_genomes_project_gen/saved_variants/family/F032178_rgp_2045/Review

**Scope of the bug**
Currently in RGP_2045 only

**Comment by hanars** [comment]
This is now fixed
