### ISSUE TITLE
Variants being returned that don't meet search criteria (Missense, VUS)

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4409]
**Describe the bug**
In this search, I did not select Missense nor VUS. But a missense VUS in ZNFR3 is returned. Any other reason this is being returned? 

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/variant_search/results/eaf6542f39ac37a0e2b1c513dc4ef092?page=1&sort=in_omim

Another example where I did not select VUS or missense variant but they were returned - 
https://seqr.broadinstitute.org/variant_search/results/e8a25cef354bd5542ab7698187454ac1?page=1&sort=in_omim
The variants in missense WNK1, missense ACAN, missense PPFIA3

**Scope of the bug**
Currently in the RGP project

**Screenshots**
<img width="1544" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW92Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6eb19cc8d74a7113d021fade27d213bbab821c7a/Screenshot%202024-10-08%20at%2010.21.07%E2%80%AFAM.png" alt="Screenshot 2024-10-08 at 10.21.07 AM.png" />

**Comment by hanars** [comment]
VEP will annotate multiple consequences for the same transcript, but we currently only show one transcript consequence per transcript, but in this case the variant's transcripts are all annotated as both missense and splice region. I will put up a fix to show additional consequences when available to make it clear

**Comment by hanars** [comment]
I have updated the seqr UI to show when VEP annotates more than one consequence per transcript, and now the missense variants that are not clinvar path and not high splice AI are showing "Additonal VEP consequences:  splice region variant" on them, to make it clear why they are being returned
