### ISSUE TITLE
Blank page when trying to access MME submissions in a project

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4438]
**Describe the bug**
Blank page when trying to access MME submissions in a project

**Link to page(s) where bug is occurring**
Project page where I selected tagged variants "MME Submissions: - https://seqr.broadinstitute.org/project/R0528_cmg_engle_wes/project_page

Blank page - https://seqr.broadinstitute.org/project/R0528_cmg_engle_wes/saved_variants/MME%20Submission

**Scope of the bug**
Project specific at the moment

**Comment by hanars** [comment]
this is now fixed
