### ISSUE TITLE
Refresh saved searches 

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4450]
**Is your feature request related to a problem? Please describe.**
As discussed, remnants of prior annotations exist in our saved searches. As a result, variants are returned even if the annotation is not selected.

Here's an example of a de novo/dominant search returning variants (SVs, missense, synonymous) that were not selected. Note: I did modify the search to only include nonsense variants. Also set the inheritance to ? for the parents so that we have more variants as examples. 

**Describe the solution you'd like**
Update/refresh our four saved searches: de novo/dominant restrictive and permissive + recessive restrictive and permissive. 

**Describe alternatives you've considered**
NA

**Additional context**
Discussed earlier this week.

**Comment by hanars** [comment]
In the body of the ticket you say "heres an example" but theres no link - I think you forgot to add it

**Comment by lynnpais** [comment]
Whoops! Here's the link to a dominant permissive search - https://seqr.broadinstitute.org/variant_search/results/f940e1c926462b46b992a144fd171c02?page=1&sort=in_omim

It was modified as described above.
