### ISSUE TITLE
Blank page when trying to open specific cases

### ISSUE THREAD

**Issue by eoheir** [broadinstitute/seqr#4452]
**Describe the bug**
I cannot open cases YUDBA_504 or YUDBA_500. I'm brought to a blank page when I click on these family IDs from the project page. I've also tried navigating directly to these cases using the search bar, but still get a blank page. My collaborators are having the same issue as well.

**Link to page(s) where bug is occurring**
Project page: https://seqr.broadinstitute.org/project/R0737_tgg_gazda_yu_wgs/project_page
YUDBA_504 blank page: https://seqr.broadinstitute.org/project/R0737_tgg_gazda_yu_wgs/family_page/F050403_yudba_504
YUDBA_500 blank page: https://seqr.broadinstitute.org/project/R0737_tgg_gazda_yu_wgs/family_page/F050378_yudba_500

**Scope of the bug**
Seems to be specific families - I was able to open several other cases in this project without any issues. 

**Screenshots**
<img width="1493" alt="Screenshot 2024-10-25 at 3 53 38 PM" src="https://github.com/user-attachments/assets/7f524ac2-f8ae-4f58-af9b-d889c915c97c">

**Comment by hanars** [comment]
Related to https://github.com/broadinstitute/seqr/issues/4447

**Comment by hanars** [comment]
this is now fixed
