### ISSUE TITLE
Local installs can view internal fields

### ISSUE THREAD

**Issue by anjalijain22** [broadinstitute/seqr#4484]
**Describe the bug**
Local installations by default to not have "Analyst" and "Project Manager" permissions available. However, there are multiple locations on the UI where I can see remnants of these roles. 
1. In any project: Under "Edit Families & Individuals" > "Edit Individuals" > "proband relationship": Gives a permission denied if I try to edit it.
![Screenshot 2024-11-18 at 1 01 26 PM](https://github.com/user-attachments/assets/94575bc8-32e5-4c8a-b4d8-456aafec81d9)

2. Can view the Reports Tab at the top of the seqr webpage - not sure if the highlighted tabs are useful for local installations not affiliated with the Broad Institute.
![Screenshot 2024-11-18 at 1 02 26 PM](https://github.com/user-attachments/assets/f7baa998-83e0-4d50-a5fd-8b7bddfa9070)

3. Under Data Management > Users: In the users table, can view columns for Analyst and PM.
![Screenshot 2024-11-18 at 1 03 21 PM](https://github.com/user-attachments/assets/31bdd2b8-c023-4fe7-8879-43a950b55d45)

**Link to page(s) where bug is occurring**
Local installation so no direct links

**Scope of the bug**
Experiencing this issue in all projects when a user has superuser permission.

**Link to the relevant discussion post**
https://github.com/broadinstitute/seqr/discussions/2853#discussioncomment-3986304

**Comment by hanars** [comment]
Thanks so much for reporting, this is very helpful!

**Comment by hanars** [comment]
#2 should have been addressed 6 months ago - can you confirm that you are running a version of seqr that has been updated in that time period and that you have not, in fact, enabled an analyst role for yourself?

**Comment by hanars** [comment]
1 and 3 have been fixed in that latest seqr release

**Comment by anjalijain22** [comment]
Hi Hana, thank you for promptly fixing this! Regarding 2: I can confirm that we are using a version of seqr that was updated in mid Sept 2024 (commit hash: 8d474f75af06a9e3beed052c7d8068dbfb79b66b) and we don't have the analyst role enabled in our local instance. As a superuser, I am able to see the "reports" tab.

**Comment by hanars** [comment]
Yes, you should see the reports tab without the AnVIL or Grgeor reports. The other reports are considered broadly useful and 6 months ago we made them available to local installations by default

**Comment by anjalijain22** [comment]
I actually do see the reports tab with AnVIL and Gregor reports as a superuser. Is there anything else that could explain this behaviour?

**Comment by hanars** [comment]
Ah, so it appears we disbaled those reports themselves, if you click on them you should get a 404 error, but left them in the header. I can fix that!

**Comment by hanars** [comment]
these tabs have been removed in the latest seqr release. Thanks again for reporting these issues!
