### ISSUE TITLE
Sex & Relatedness PDOs automatically labelled "available in Seqr"

### ISSUE THREAD

**Issue by matren395** [broadinstitute/seqr#4490]
**Describe the bug**

For the new feature to write out samples that fail Sex & Relatedness Checks to their own PDO , I believe they were previously being given the PDOStatus 'Methods (Loading)'. For the most recent callset, they were written out with the PDOStatus 'Available in Seqr'. That is i) untrue and ii) would prevent them from being actually loaded in successive runs. 

**Link to page(s) where bug is occurring**
https://airtable.com/app3Y97xtbbaOopVR/tblG1k2YLBu4bw2XY/viwW0oZeRVcbgTduD?blocks=hide

**Scope of the bug**
Only just happened with the most recent callset - I believe it was staying in 'Methods (Loading)' before but I don't have any documentation. 

**Screenshots**
<img width="1085" alt="image" src="https://github.com/user-attachments/assets/2e72e1c5-bc3f-485e-9db2-f0fe5b9d9ad2">

<img width="1085" alt="image" src="https://github.com/user-attachments/assets/af81caca-14a1-43a8-aa5c-22ac3e11ccc8">

**Comment by hanars** [comment]
this should be fixed going forward
