### ISSUE TITLE
Missing OMIM gene association and genCC from variant pages

### ISSUE THREAD

**Issue by msingerb** [broadinstitute/seqr#4502]
**Describe the bug**
The OMIM gene association and genCC tags are missing from the variant pages.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0351_cmg_bonnemann_exomes/saved_variants/family/F023814_bon_b18_16/Known%20gene%20for%20phenotype

**Scope of the bug**
Are you experiencing this issue in all projects? Within specific families within one project?
I am seeing this in multiple projects, even when its been tagged as a known gene for phenotype.

**Screenshots**
![image (19)](https://github.com/user-attachments/assets/f1ef670f-f5ca-4c57-92af-33d43e5a9414)
![image (20)](https://github.com/user-attachments/assets/67e78659-76ee-4313-b8ed-5dd5c3f33724)

**Comment by hanars** [comment]
This is fixed now
