### ISSUE TITLE
Update seqr VLM text to include prompts

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4520]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when ... researchers do not list details about their case when they reach out using seqr's Variant Lookup . 

**Describe the solution you'd like**
Update text to include phenotype and question prompts. Draft here - https://docs.google.com/document/d/1AKFBnbwzPkYhyxmYF_pv1_G2f_bbbY6eaED4S6UJB2s/edit?usp=sharing

**Comment by hanars** [comment]
this is now live
