### ISSUE TITLE
Issue with Matchmaker Submission in Seqr

### ISSUE THREAD

**Issue by hectormendezr** [broadinstitute/seqr#4533]
**Describe the bug**
It seems there is a bug in Seqr when using Matchmaker. When I attempt to submit a case, the window turns completely blank.

**Link to page(s) where bug is occurring**
https://seqr.broadinstitute.org/project/R0780_gss_anvil_seqr/family_page/F058890_gss1672/matchmaker_exchange

**Scope of the bug**
![Screen Shot 2024-12-10 at 10 09 42 AM](https://github.com/user-attachments/assets/3fa1c268-b22f-4280-a1f3-b289de120441)
![Screen Shot 2024-12-10 at 10 09 07 AM](https://github.com/user-attachments/assets/e920b1c2-0c16-4c77-ac64-2f4fdac0ba88) the bug in some other cases.

**Comment by hanars** [comment]
This has been fixed, thanks for reporting!
