### ISSUE TITLE
Iranome lookup link not responding

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#4541]
**Describe the bug**
Iranome lookup is not responding. It's possible the link changed and this is not a true bug.

**Link to page(s) where bug is occurring**
Iranome link for the TT missense variant - https://seqr.broadinstitute.org/project/R0384_rare_genomes_project_gen/saved_variants/variant/SV0114915_2178702065_f032092_r

Iranome page with error- [[http://www.iranome.ir/variant/1-155293337-G-A](http://www.iranome.ir/variant/2-178702065-T-A)](http://www.iranome.ir/variant/2-178702065-T-A)

Page should actually go to - https://www.iranome.com/variant/2-178702065-T-A

**Scope of the bug**
Iranome look up only

**Screenshots**
<img width="1222" alt="Screenshot 2024-12-13 at 9 59 33 AM" src="https://github.com/user-attachments/assets/3bfaa88b-842c-4e8c-b701-24c5e0e1a611" />

<img width="1347" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzhsQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2abc8aea8fd00b45cc9268f4c05610154a7c5b54/Screenshot%202024-12-13%20at%209.58.02%E2%80%AFAM.png" alt="Screenshot 2024-12-13 at 9.58.02 AM.png" />

**Comment by hanars** [comment]
link has been fixed!
