### ISSUE TITLE
Saved search gives error "Invalid gq_sv filter 5"

### ISSUE THREAD

**Issue by AunErki** [broadinstitute/seqr#4547]
Hello!

I use seqr local docker install and my project is based on DRAGEN generated WGS data.

While I try to conduct a search using "Select a Saved Search (Recommended)" option "De Novo/Dominant Restrictive" or "Recessive restrictive" I always get an error "Invalid gq_sv filter 5". Custom search seems to work fine.

I wonder what is causing this issue?

**Comment by hanars** [comment]
this is a bug and has been fixed in the latest seqr release

**Comment by AunErki** [comment]
Thank you! I pulled the latest release and confirm that the error is gone now! :)
