### ISSUE TITLE
Sex And Relatedness failure messages print all _sr PDOs for each message

### ISSUE THREAD

**Issue by matren395** [broadinstitute/seqr#4551]
**Describe the bug**
When the loading pipeline posts in the Slack channel #seqr_loading_notifications, for each individual message, it prints all alternate PDO's (i.e. PDO-XYZ123_sr) associated with a given project. This can be misleading, when an individual message contains only one failed family but for a project linked to over a dozen PDOs (expected for very large projects), giving the false impression that one family is split into a dozen PDOs. 

I would expect to see only the PDOs associated with the given failed family or families per message. 

**Link to page(s) where bug is occurring**

https://the-tgg.slack.com/archives/CMM4R47LH/p1734206473279229

**Scope of the bug**

Seeing this for large projects - specifically both RGP projects (R0384 & R0594)

**Comment by matren395** [comment]
Screenshot of issue: 

<img width="886" alt="Screenshot 2024-12-18 at 1 13 33 PM" src="https://github.com/user-attachments/assets/191b4874-1cc0-45fc-8b17-f53aa4eb99fd" />

**Comment by hanars** [comment]
Updated the message to be clearer
