### ISSUE TITLE
Alert on failed airtable updates

### ISSUE THREAD

**Issue by matren395** [broadinstitute/seqr#4552]
**Describe the bug**

Users frequently submit duplicate Anvil Data Loading requests, due to misunderstandings or impatience, which then wastes our time and resources. Seqr has a way of logging this, but the message does not get posted directly to slack. 

Posting a message of this to a Slack channel (#anvil-data-loading perhaps) so everybody can see and the relevant ACBs can update the Anvil Data Loading AirTable accurately could be a good idea. 

**Link to page(s) where bug is occurring**

Example, note row 260: https://airtable.com/appUelDNM3BnWaR7M/tbljif5De7AKysdbi/viwxCMYX7wPmBhwEg?blocks=hide 

**Scope of the bug**

Just for duplicate Anvil requests

**Screenshots**

Modestly relevant example, of users requesting loading of the same samples again , even after the first pass succeeded 

<img width="1032" alt="image" src="https://github.com/user-attachments/assets/06c0d04a-f506-4099-a78a-fe3fd3d3f6ec" />

**Comment by hanars** [comment]
I am not sure exactly what this ticket is referring to, seqr does not have a way of knowing if duplicate requests have come through. I think maybe this is referring to what I was saying about if Airtable fails to update I get notified and I could send that notification in slack so you could know that sirtable did not update?

**Comment by matren395** [comment]
sorry oops : 

<img width="863" alt="image" src="https://github.com/user-attachments/assets/4abe6ee9-7b6b-43e7-81ae-be4cfa59b7d2" />
 
was trying to make a ticket for this exchange, sorry if I got something misinterpreted

**Comment by hanars** [comment]
Okay thanks, I can work with that!

**Comment by hanars** [comment]
This has been done!
