### ISSUE TITLE
Slow loading of cases and saving tags

### ISSUE THREAD

**Issue by lynnpais** [broadinstitute/seqr#530]
Hi, 

The Gleeson_exomes project and individual cases are taking ~10secs or so to load. Notes and tags take 5-10 seconds to save after hitting submit. 

https://seqr.broadinstitute.org/project/gleeson_cmg-samples_exomes_v1/family/5609/mendelian-variant-search#search/3586c6b8/results

**Comment by hanars** [comment]
closing this out for staleness. If this is still an issue, please feel free to let me know
