### ISSUE TITLE
Add reason for excluded

### ISSUE THREAD

**Issue by englandeleina** [broadinstitute/seqr#584]
It would be nice to have an **optional** pop-up when you click excluded in Seqr with a multiple choice selection for comments, including something like /too common/poor phenotypic fit/poor functional fit/poorly conserved ... etc, plus one free text option. The same could be done for clicking review with a free text pop up. This would encourage individuals to remember to explain rationale for tagging a variant, but since this is **optional** should not interfere with anyone's workflow/time spent on cases!

**Comment by hanars** [comment]
Implement this by prompting after successfully adding an "excluded" tag to add a note. The modal header for that note should say "Reason for Excluded" and there should be placeholder text of 'Variant excluded because..."
