### ISSUE TITLE
Display Refseq transcript IDs / MANE select

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr#742]
Display Refseq transcript IDs in seqr next to the Ensembl transcripts (ZV, AKL)

**Comment by hanars** [comment]
for MVP, will show Refseq transcripts that have a 1-to-1 mapping with ensembl transcripts, will do this at display time in seqr. @lynnpais to add the data source for the mapping

**Comment by lynnpais** [comment]
We need the information from row 1 in the table. Here's an example for the gene MEGF6 - http://useast.ensembl.org/Homo_sapiens/Transcript/Summary?g=ENSG00000162591;r=1:3487951-3611508;t=ENST00000356575

It maps Ensemble, RefSeq and Mane transcripts.

**Comment by hanars** [comment]
@lynnpais should the refseq ID link anywhere? Or should we just show it?

**Comment by lynnpais** [comment]
It can be shown besides the Ensembl transcript, when for example you select
'missense variant' on the 'variant page'.

Can it also be tagged as 'MANE Select' and can this show in the hover over?

This would only be for transcript where there is 1:1 matching as seen in
the first row in the table here -
http://useast.ensembl.org/Homo_sapiens/Transcript/Summary?g=ENSG00000142627;r=1:16124337-16156069;t=ENST00000358432

**Comment by hanars** [comment]
when we show the refseq ID, should that link anywhere, the way it does on the ensembl page? Or should we just show the ID as plain text

And yes, we can shw MANE select

**Comment by hanars** [comment]
these have been added
