### ISSUE TITLE
Free text search for variant notes regardless of pagination

### ISSUE THREAD

**Issue by hanars** [broadinstitute/seqr#748]
dd searching of variant notes if the deprecated pages will eventually be removed (due to pagination in the new layout we need to go to the deprecated saved variant page and use the browser search) We have to make sure both in-seqr search (the search box) and browser search (command+F) are supported(ZV)

**Comment by lynnpais** [comment]
Decided not to implement as it's a fair amount of work and may not be used much by the analyst.
