### ISSUE TITLE
Callset annotation across callsets

### ISSUE THREAD

**Issue by anneodonnell** [broadinstitute/seqr#936]
It would be great to have the AC from the internal exome callset also noted in seqr on the genome callset (and vice versa) so we recognize additional hits (or poor matches) across seqr data.

**Comment by hanars** [comment]
https://github.com/broadinstitute/seqr/issues/936 for tracking pipeline work

**Comment by hanars** [comment]
@lynnpais confirming that based on our last meeting with Anne we are okay with not completing this before the hail backend MVP, with the idea that we can always add it later if it turns out we need it

**Comment by lynnpais** [comment]
Yes, fine to proceed for now with the MVP. This is generally good to have so we should revisit this later.

**Comment by hanars** [comment]
opted not to do this for now, can reopen/ create new ticket if we decide to do in the future
